// Package python is the Python throughput backend (PLAN §6.4): it emits
// dataclasses with serialize (Encoder) and, per class, a FLAT decode visitor
// against corelib-py -- whose pull API is gone, CORELIB_PLAN §5.3.1 making the
// visitor the only decode surface. See visitor.go for the decode half. Plus JSON
// helpers for the conformance harness.
package python

import (
	"fmt"
	"sort"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for Python.
type Backend struct{}

func (*Backend) Lang() string { return "python" }

// Generate emits a single module (all enums/bitfields/dataclasses + messages).
// In project mode it adds a harness and pyproject.toml.
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	g := &gen{
		schema:  s,
		banner:  cfgString(cfg, "tool_banner", "sofabgen"),
		license: generator.LicenseID(cfg),
		limits:  resolveLimits(s, cfg),
		size:    generator.NewSizePolicy(cfg),
	}
	module := g.module(s)
	files := []generator.File{{Path: "message.py", Content: module}}
	if cfgString(cfg, "emit", "sources") == "project" {
		files = append(files, g.projectFiles(s, cfg)...)
	}
	if g.sizeErr != nil {
		return nil, g.sizeErr
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	banner  string
	license string // SPDX id, "" to omit the header line
	limits  limitSet
	// size is the max_message_size policy; sizeErr carries a violation out of
	// the emit path, which has no error channel of its own.
	size    generator.SizePolicy
	sizeErr error
}

// messageSize resolves a class's worst-case encoded size via the shared walk
// (ir.MaxWireSize), falling back to the configured max_message_size ceiling when
// a field is unbounded. The emit path has no error channel, so a violation of an
// explicitly configured ceiling is recorded here and surfaced by Generate.
func (g *gen) messageSize(name string, fields []*ir.Field) generator.MessageSize {
	ms, err := g.size.Resolve(name, fields)
	if err != nil && g.sizeErr == nil {
		g.sizeErr = err
	}
	return ms
}

// limitSet is the receiver-side decode-limit configuration (generator#102),
// resolved against the schema. Every cap is always set -- the target carries a
// finite default that the config key only overrides (§9.5, generator#385) -- so
// an entry is active exactly when the schema actually has an unbounded field of
// that kind; otherwise the cap would be inert and no plumbing is emitted.
//
// The configured value is emitted AS CONFIGURED. It used to be raised to the
// largest schema bound of its kind, because corelib-py applies its caps per
// Decoder and would otherwise reject a schema-bounded field larger than the cap
// -- which §6.2.1 forbids, since there the schema bound governs. That raise kept
// such messages decodable by loosening the cap for the UNBOUNDED fields too,
// which is exactly the protection §6.2.1 wants kept tight. Generated code now
// declares each bounded field with d.schema_bounded() instead, so the cap binds
// only what the schema left open and can stay at the number the deployment
// chose (generator#325).
type limitSet struct {
	arrayCount, stringLen, blobLen int64
	arrayHas, stringHas, blobHas   bool
}

func (l limitSet) any() bool { return l.arrayHas || l.stringHas || l.blobHas }

// resolveLimits resolves the max_dyn_* caps over the target's finite defaults
// and against the schema's bounds (see limitSet).
func resolveLimits(s *ir.Schema, cfg map[string]any) limitSet {
	var all []*ir.Field
	for _, m := range s.Messages {
		all = append(all, m.Fields...)
	}
	b := ir.Bounds(all)
	d := generator.ServerDynLimits.Resolve(cfg)
	var l limitSet
	if b.HasDynArray {
		l.arrayCount, l.arrayHas = d.ArrayCount, true
	}
	if b.HasDynString {
		l.stringLen, l.stringHas = d.StringLen, true
	}
	if b.HasDynBlob {
		l.blobLen, l.blobHas = d.BlobLen, true
	}
	return l
}

type pyfile struct{ b strings.Builder }

func (f *pyfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *pyfile) blank()        { f.b.WriteByte('\n') }
func (f *pyfile) bytes() []byte { return []byte(f.b.String()) }

func (g *gen) module(s *ir.Schema) []byte {
	f := &pyfile{}
	f.line("# Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("# SPDX-License-Identifier: %s", g.license)
	}
	f.line("from __future__ import annotations")
	f.line("from dataclasses import dataclass, field")
	f.line("from enum import IntEnum")
	// The decode section is emitted FIRST, into a buffer, so the import line can
	// be read off what it actually references (visitorNeeds) instead of a second
	// walk over the schema that has to agree with the emitter by hand.
	decodeSection := g.decodeSection(s)
	// SofaDecodeError and SofaIncompleteError are unconditional: every class's
	// decode() surfaces the three-valued outcome through them (MESSAGE_SPEC §7).
	names := []string{
		"Decoder", "Encoder", "SofaDecodeError", "SofaIncompleteError",
		"Status", "Visitor",
	}
	if g.limits.any() {
		names = append(names, "SofaLimitError")
	}
	// Field is the on_field argument, and WireType / FixlenSubtype are the tags
	// its §7.3 tests compare against; each appears only where a bound exists.
	needField, needWire, needFixlen := visitorNeeds(decodeSection)
	if needField {
		names = append(names, "Field")
	}
	if needFixlen {
		names = append(names, "FixlenSubtype")
	}
	if needWire {
		names = append(names, "WireType")
	}
	sort.Strings(names)
	f.line("from sofab import %s", strings.Join(names, ", "))
	f.blank()

	if g.limits.any() {
		f.line("# Receiver-side decode limits, baked from the sofabgen config")
		f.line("# (max_dyn_array_count / max_dyn_string_len / max_dyn_blob_len). They govern")
		f.line("# only fields the schema left unbounded -- a cap must never bind a field")
		f.line("# the schema already bounds -- so they are applied in on_field,")
		f.line("# in the else of the schema-bound chain, rather than handed to the Decoder,")
		f.line("# which knows no schema and would cap every field alike. Exceeding one")
		f.line("# raises sofab.SofaLimitError at the count/length header, before any")
		f.line("# allocation.")
		if g.limits.arrayHas {
			f.line("MAX_DYN_ARRAY_COUNT = %d", g.limits.arrayCount)
		}
		if g.limits.stringHas {
			f.line("MAX_DYN_STRING_LEN = %d", g.limits.stringLen)
		}
		if g.limits.blobHas {
			f.line("MAX_DYN_BLOB_LEN = %d", g.limits.blobLen)
		}
		f.blank()
	}

	// enums + bitfield constants first
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfieldConsts(f, nt)
		}
	}
	// struct/union dataclasses, then messages
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitDataclass(f, g.typeName(key), nt.Summary, nt.Fields)
		}
	}
	for _, m := range s.Messages {
		g.emitDataclass(f, exported(m.Name), m.Summary, m.Fields)
	}
	// Decode last: an array scope gap-fills with an element CONSTRUCTOR, so every
	// dataclass a visitor can name must already be defined.
	f.b.WriteString(decodeSection)
	return f.bytes()
}

// decodeSection renders the module's decode half -- the streaming reader plus
// one flat visitor per generated class -- as text, so module() can size its
// import line from it.
func (g *gen) decodeSection(s *ir.Schema) string {
	f := &pyfile{}
	f.line("# --- decode ---------------------------------------------------------------")
	f.blank()
	g.emitStreamDecoder(f)
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitVisitor(f, g.typeName(key), nt.Fields)
		}
	}
	for _, m := range s.Messages {
		g.emitVisitor(f, exported(m.Name), m.Fields)
	}
	return f.b.String()
}

// emitStreamDecoder writes the generated reader §6.1.1 requires: the streaming
// half of the decode pair, obtained from a class's decoder() and fed chunks of
// any size. There is deliberately no finish()/end() — the status each feed
// returns IS the outcome so far, and whether an INCOMPLETE at end-of-input is
// acceptable is the caller's framing decision (CORELIB_PLAN §5.2.4).
func (g *gen) emitStreamDecoder(f *pyfile) {
	f.line("class _StreamDecoder:")
	f.line("    \"\"\"Streaming reader: feed chunks, read the message when it is COMPLETE.")
	f.line("")
	f.line("    Every feed() returns the outcome for the bytes so far --")
	f.line("    COMPLETE / INCOMPLETE / INVALID. There is no finalize step: an")
	f.line("    INCOMPLETE tail is retained and continued by the next chunk, and only")
	f.line("    the caller's framing knows whether more can still come.")
	f.line(`    """`)
	f.line("")
	f.line("    __slots__ = (\"message\", \"_d\")")
	f.line("")
	f.line("    def __init__(self, msg_cls, vis_cls) -> None:")
	f.line("        self.message = msg_cls()")
	f.line("        self._d = Decoder(visitor=vis_cls(self.message))")
	f.line("")
	f.line("    def feed(self, chunk) -> Status:")
	f.line("        return self._d.feed(chunk)")
	f.line("")
	f.line("    @property")
	f.line("    def status(self) -> Status:")
	f.line("        return self._d.status")
	f.line("")
	f.line("    @property")
	f.line("    def error(self):")
	f.line("        return self._d.error")
	f.blank()
}

// schemaHasCountedNativeArray reports whether any field (recursively through
// nested-array element items) is a native scalar array with a schema `count` —
// the arrays whose decode emits the over-count SofaDecodeError guard
// (generator#100). The recursion is what keeps this in lockstep with the
// emitter: a nested native ROW carries its own capacity and is bounded at its
// own count header, so a schema whose ONLY counted native array is such a row
// (a count-less outer array of counted u32 rows) still needs the import — a
// top-level-only scan would leave the raise NameError at decode time.
func schemaHasCountedNativeArray(s *ir.Schema) bool {
	var arrHas func(elem ir.Kind, items *ir.ArrayElem, hasCount bool) bool
	arrHas = func(elem ir.Kind, items *ir.ArrayElem, hasCount bool) bool {
		if hasCount && isNativeArrayElem(elem) {
			return true
		}
		if elem == ir.KindArray && items != nil {
			return arrHas(items.Elem, items.ElemItems, items.HasCount)
		}
		return false
	}
	return schemaHasField(s, func(fld *ir.Field) bool {
		return fld.Kind == ir.KindArray && arrHas(fld.Elem, fld.ElemItems, fld.HasCount)
	})
}

// schemaHasCountedWrapperArray reports whether any field (recursively through
// nested-array element items) is a fixed-count wrapper-sequence array —
// string/blob/struct/union/nested-array elements with a schema `count` — the
// fields whose decode emits the over-index SofaDecodeError guard (generator#142).
func schemaHasCountedWrapperArray(s *ir.Schema) bool {
	var arrHas func(elem ir.Kind, items *ir.ArrayElem, hasCount bool) bool
	arrHas = func(elem ir.Kind, items *ir.ArrayElem, hasCount bool) bool {
		if hasCount && !isNativeArrayElem(elem) {
			return true
		}
		if elem == ir.KindArray && items != nil {
			return arrHas(items.Elem, items.ElemItems, items.HasCount)
		}
		return false
	}
	return schemaHasField(s, func(fld *ir.Field) bool {
		return fld.Kind == ir.KindArray && arrHas(fld.Elem, fld.ElemItems, fld.HasCount)
	})
}

// schemaHasMaxlenStringBlob reports whether any field (recursively through
// nested-array element items) is a bounded (maxlen) string/blob — a scalar
// string/blob carrying a schema `maxlen`, or a string/blob array element
// carrying an element maxlen — the fields whose decode emits the over-length
// SofaDecodeError guard (MESSAGE_SPEC §7.1). Kept in lockstep with the import
// condition: a schema that rejects only on a bounded string/blob still needs
// SofaDecodeError imported.
func schemaHasMaxlenStringBlob(s *ir.Schema) bool {
	var arrHas func(elem ir.Kind, items *ir.ArrayElem, elemMaxHas bool) bool
	arrHas = func(elem ir.Kind, items *ir.ArrayElem, elemMaxHas bool) bool {
		if elemMaxHas && (elem == ir.KindString || elem == ir.KindBlob) {
			return true
		}
		if elem == ir.KindArray && items != nil {
			return arrHas(items.Elem, items.ElemItems, items.ElemMaxHas)
		}
		return false
	}
	return schemaHasField(s, func(fld *ir.Field) bool {
		if (fld.Kind == ir.KindString || fld.Kind == ir.KindBlob) && fld.HasMaxlen {
			return true
		}
		return fld.Kind == ir.KindArray && arrHas(fld.Elem, fld.ElemItems, fld.ElemMaxHas)
	})
}

// pyFixlenSubtype returns the FixlenSubtype member a fixlen kind must carry, or
// "" for a kind that is not fixlen-framed.
func pyFixlenSubtype(k ir.Kind) string {
	switch k {
	case ir.KindFP32:
		return "FixlenSubtype.FP32"
	case ir.KindFP64:
		return "FixlenSubtype.FP64"
	case ir.KindString:
		return "FixlenSubtype.STRING"
	case ir.KindBlob:
		return "FixlenSubtype.BLOB"
	}
	return ""
}

// pyExpectedWire returns the WireType member a field's header must carry for its
// schema-typed reader to be the right one, mirroring the encode side
// (emitMarshal / marshalArray): unsigned integers, bool and bitfield ->
// UNSIGNED; signed integers and enum -> SIGNED; fp32/fp64, string and blob ->
// FIXLEN; nested messages and composite (wrapper) arrays -> SEQUENCE_START;
// native scalar arrays -> the matching ARRAY_* wire type.
func pyExpectedWire(fld *ir.Field) string {
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBool, ir.KindBitfield:
		return "WireType.UNSIGNED"
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		return "WireType.SIGNED"
	case ir.KindFP32, ir.KindFP64, ir.KindString, ir.KindBlob:
		return "WireType.FIXLEN"
	case ir.KindStruct, ir.KindUnion:
		return "WireType.SEQUENCE_START"
	case ir.KindArray:
		if !isNativeArrayElem(fld.Elem) {
			return "WireType.SEQUENCE_START"
		}
		switch fld.Elem {
		case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
			return "WireType.ARRAY_SIGNED"
		case ir.KindFP32, ir.KindFP64:
			return "WireType.ARRAY_FIXLEN"
		default: // u8/u16/u32/u64, bool, bitfield
			return "WireType.ARRAY_UNSIGNED"
		}
	}
	return "WireType.SEQUENCE_START" // unreachable: keeps the switch total
}

// schemaHasField reports whether any message or named-type field satisfies pred.
func schemaHasField(s *ir.Schema, pred func(*ir.Field) bool) bool {
	any := func(fields []*ir.Field) bool {
		for _, fld := range fields {
			if pred(fld) {
				return true
			}
		}
		return false
	}
	for _, key := range s.NamedOrder {
		if any(s.Named[key].Fields) {
			return true
		}
	}
	for _, m := range s.Messages {
		if any(m.Fields) {
			return true
		}
	}
	return false
}

func (g *gen) emitEnum(f *pyfile, nt *ir.NamedType) {
	f.line("class %s(IntEnum):", g.typeName(nt.Key))
	for _, c := range nt.Consts {
		// Sphinx attribute comment(s) carrying the constant's description, above
		// the member so pydoc/Sphinx attaches it to the enum value.
		if c.Description != "" {
			for _, dl := range strings.Split(c.Description, "\n") {
				f.line("    #: %s", dl)
			}
		}
		f.line("    %s = %d", strings.ToUpper(c.Name), c.Value)
	}
	f.blank()
}

func (g *gen) emitBitfieldConsts(f *pyfile, nt *ir.NamedType) {
	f.line("class %s(IntEnum):", g.typeName(nt.Key))
	for _, fl := range nt.Flags {
		// Sphinx attribute comment(s): the flag description, with the schema
		// default appended as "(default: true/false)" when the flag has one.
		for _, dl := range bitfieldFlagDocLines(fl) {
			f.line("    #: %s", dl)
		}
		f.line("    %s = 1 << %d", strings.ToUpper(fl.Name), fl.Pos)
	}
	f.blank()
}

// bitfieldFlagDocLines builds the Sphinx attribute-comment text (without the
// leading "#: ") for a bitfield flag: its Description, plus a trailing
// "(default: true)" / "(default: false)" note appended to the last line when
// the flag declares a default. Returns nil when there is nothing to document.
func bitfieldFlagDocLines(fl *ir.BitfieldFlag) []string {
	var lines []string
	if fl.Description != "" {
		lines = strings.Split(fl.Description, "\n")
	}
	if fl.HasDefault {
		note := "(default: false)"
		if fl.Default {
			note = "(default: true)"
		}
		if len(lines) == 0 {
			lines = []string{note}
		} else {
			lines[len(lines)-1] = lines[len(lines)-1] + " " + note
		}
	}
	return lines
}

// emitClassDoc writes a triple-quoted class docstring as the first statement of
// the class body when the summary is non-empty. A single-line summary becomes
// """<summary>"""; a multi-line summary opens with """ on the first line and
// closes with """ on its own line. UTF-8 passes through byte-for-byte.
func emitClassDoc(f *pyfile, summary string) {
	if summary == "" {
		return
	}
	lines := strings.Split(summary, "\n")
	if len(lines) == 1 {
		f.line(`    """%s"""`, lines[0])
		return
	}
	f.line(`    """%s`, lines[0])
	for _, ln := range lines[1:] {
		f.line("    %s", ln)
	}
	f.line(`    """`)
}

// pyFieldDocLines builds the Sphinx attribute-comment text (without the leading
// "#: ") from a field's Description and Unit. A multi-line description yields one
// line per source line; a non-empty Unit is appended as " (unit: <Unit>)" to the
// last line. A deprecated field gets a trailing ".. deprecated::" directive so
// Sphinx renders the deprecation and pydoc surfaces the note. Returns nil when
// there is nothing to document.
func pyFieldDocLines(fld *ir.Field) []string {
	var lines []string
	if fld.Description != "" {
		lines = strings.Split(fld.Description, "\n")
	}
	if fld.Unit != "" {
		if len(lines) == 0 {
			lines = []string{fmt.Sprintf("(unit: %s)", fld.Unit)}
		} else {
			lines[len(lines)-1] = fmt.Sprintf("%s (unit: %s)", lines[len(lines)-1], fld.Unit)
		}
	}
	if note := generator.BoundNote(fld, generator.StorageDynamic); note != "" {
		lines = append(lines, note)
	}
	if fld.Deprecated {
		lines = append(lines,
			".. deprecated::",
			"   Deprecated and retained only for backward compatibility; do not use in new code.")
	}
	return lines
}

func (g *gen) emitDataclass(f *pyfile, name, summary string, fields []*ir.Field) {
	f.line("@dataclass")
	f.line("class %s:", name)
	// Class docstring (pydoc/Sphinx) as the first statement in the body, when the
	// summary is non-empty. It also satisfies the body for a field-less class.
	emitClassDoc(f, summary)
	if len(fields) == 0 && summary == "" {
		f.line("    pass")
	}
	for _, fld := range fields {
		// Sphinx attribute comment(s) immediately before the declaration.
		for _, dl := range pyFieldDocLines(fld) {
			f.line("    #: %s", dl)
		}
		f.line("    %s: %s = %s", pyIdent(fld.Name), g.pyAnnot(fld), g.pyDefault(fld))
	}
	f.blank()

	// Worst-case encoded size. It is what sizes the buffer encode() hands the
	// encoder: the corelib is given storage and never grows or reallocates it
	// (CORELIB_PLAN §5.1), so the number has to come from the schema, here.
	//
	// Deliberately unannotated: an annotated class attribute in a @dataclass
	// becomes a FIELD, which would put MAX_SIZE on the wire and in __init__.
	ms := g.messageSize(name, fields)
	if ms.Bounded {
		f.line("    # Worst-case encoded size, derived from the schema: no value of this")
		f.line("    # class can encode to more, which is why encode() can size one exact")
		f.line("    # buffer from it.")
		f.line("    MAX_SIZE = %d", ms.Size)
	} else {
		f.line("    # Configured ceiling (max_message_size), NOT a size this class cannot")
		f.line("    # exceed: a field of it is unbounded, so the schema supplies no worst")
		f.line("    # case and encode() must not size a buffer from this number.")
		f.line("    MAX_SIZE_LIMIT = %d", ms.Size)
		f.line("    MAX_SIZE = MAX_SIZE_LIMIT")
	}
	f.blank()

	g.emitIsDefault(f, fields)

	// _marshal
	f.line("    def serialize(self, e: Encoder) -> None:")
	if len(fields) == 0 {
		f.line("        pass")
	}
	for _, fld := range fields {
		g.emitMarshal(f, fld)
	}
	f.blank()

	// Decode lives in the flat visitor emitted for this class (visitor.go);
	// §7.3's "skip a contradicting field" needs no code at all there, because a
	// field whose wire type contradicts the schema is delivered to a DIFFERENT
	// typed hook, where its (location, id) matches no arm and it falls through.

	// JSON helpers + encode/decode
	g.emitJSON(f, name, fields, ms)
}

// emitIsDefault emits the object's all-default predicate. It is the exact
// negation of what _marshal writes: the object is default iff _marshal would
// emit no child at all, evaluated per field and recursively (MESSAGE_SPEC §2).
// Keep this in lockstep with emitMarshal -- both are generated from
// fieldIsDefaultExpr's per-field expressions for exactly that reason. A predicate
// that disagrees with the writer omits a field that is on the wire, or keeps one
// that is not.
func (g *gen) emitIsDefault(f *pyfile, fields []*ir.Field) {
	f.line("    def _is_default(self) -> bool:")
	if len(fields) == 0 {
		f.line("        return True")
		f.blank()
		return
	}
	for _, fld := range fields {
		f.line("        if not (%s):", g.fieldIsDefaultExpr(fld))
		f.line("            return False")
	}
	f.line("        return True")
	f.blank()
}

// fieldIsDefaultExpr is the boolean expression "this field equals its default",
// i.e. the negation of emitMarshal's write guard for the same field.
func (g *gen) fieldIsDefaultExpr(fld *ir.Field) string {
	acc := "self." + pyIdent(fld.Name)
	switch fld.Kind {
	case ir.KindBlob:
		// emitMarshal compares bytes(acc) so a bytearray/memoryview value still
		// matches the literal default.
		return fmt.Sprintf("bytes(%s) == %s", acc, g.pyDefault(fld))
	case ir.KindStruct, ir.KindUnion:
		// Lazily framed: the frame survives iff the nested _marshal wrote a child,
		// which is exactly "the nested object is not default".
		return fmt.Sprintf("%s._is_default()", acc)
	case ir.KindArray:
		return g.arrayIsDefaultExpr(fld, acc)
	}
	return fmt.Sprintf("%s == %s", acc, g.pyDefault(fld))
}

// arrayIsDefaultExpr mirrors emitMarshalArray. An array's declared `count: N` is
// a CAPACITY, never a length (MESSAGE_SPEC §3), so it takes no part in this test:
// the value is compared against the declared default exactly as written, with no
// padding to N on either side, and against the empty collection when none is
// declared. A count:N array is therefore default only when it is EMPTY -- an
// all-zero N-element value is a length-N array, which differs from the empty one
// and stays on the wire.
func (g *gen) arrayIsDefaultExpr(fld *ir.Field, acc string) string {
	if isNativeArrayElem(fld.Elem) {
		if lit, ok := g.pyNativeArrayDefault(fld); ok {
			return fmt.Sprintf("%s == %s", acc, lit)
		}
		return fmt.Sprintf("len(%s) == 0", acc)
	}
	// Wrapper array: the writer emits a child for every element it holds, because
	// the LAST element is written whatever its value (§2) -- so "no child is
	// written" is exactly "the array is empty", and the two cannot drift apart.
	return fmt.Sprintf("len(%s) == 0", acc)
}

func (g *gen) emitMarshal(f *pyfile, fld *ir.Field) {
	acc := "self." + pyIdent(fld.Name)
	var write string
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		write = fmt.Sprintf("e.write_unsigned(%d, int(%s))", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		write = fmt.Sprintf("e.write_signed(%d, int(%s))", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("e.write_bool(%d, %s)", fld.ID, acc)
	case ir.KindFP32:
		write = fmt.Sprintf("e.write_float32(%d, %s)", fld.ID, acc)
	case ir.KindFP64:
		write = fmt.Sprintf("e.write_float64(%d, %s)", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("e.write_string(%d, %s)", fld.ID, acc)
	case ir.KindBlob:
		// blob is a leaf: omit when equal to its default (empty if none).
		f.line("        if bytes(%s) != %s:", acc, g.pyDefault(fld))
		f.line("            e.write_bytes(%d, bytes(%s))", fld.ID, acc)
		return
	case ir.KindStruct, ir.KindUnion:
		// MESSAGE_SPEC S2: the != default test is per field and a sequence is no
		// exception, so the frame is opened LAZILY -- the corelib holds the header
		// back until a child field appears. The nested marshal omits each child that
		// equals its default, so "no child was written" IS "the object equals its
		// declared default", evaluated per field and recursively. An all-default
		// nested object is therefore dropped, not emitted as an empty wrapper.
		f.line("        e.write_sequence_begin_lazy(%d)", fld.ID)
		f.line("        %s.serialize(e)", acc)
		f.line("        e.write_sequence_end()")
		return
	case ir.KindArray:
		g.emitMarshalArray(f, fld, acc)
		return
	}
	// Scalar/string/enum/bitfield leaf: always omit when equal to the default;
	// sparse encoding is canonical (MESSAGE_SPEC S2) and the decoder reconstructs
	// the omitted field from its default.
	f.line("        if %s != %s:", acc, g.pyDefault(fld))
	f.line("            %s", write)
}

func (g *gen) emitMarshalArray(f *pyfile, fld *ir.Field, acc string) {
	// A native scalar array is a leaf field: omit it when equal to its default
	// (materialized in the dataclass), else when empty. A composite/dynamic-element
	// array is a wrapper sequence, opened lazily and closed by the dropping end
	// (see marshalArray) -- an empty one vanishes instead of being framed empty.
	//
	// A declared `count: N` takes no part in either test. `count` is a CAPACITY,
	// never a length (§3): it never reaches the wire, so the value is compared
	// against the declared default exactly as written -- neither side padded to N
	// -- and against the empty collection when no default is declared.
	if isNativeArrayElem(fld.Elem) {
		if lit, ok := g.pyNativeArrayDefault(fld); ok {
			f.line("        if %s != %s:", acc, lit)
		} else {
			f.line("        if len(%s) != 0:", acc)
		}
		g.marshalArray(f, "            ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0, "")
		return
	}
	// The field-level wrapper frame is dropped when no element is written, and
	// absence then reconstructs the field's default. That is correct because a
	// wrapper array's declared `default` is not materialized today -- the dataclass
	// default is the empty list -- so absent and explicitly-empty denote the same
	// value. If that gap is ever closed, this call needs a guard --
	// `if value != default: ... e.write_sequence_end_keep()` -- so that a value
	// differing from a non-empty default still reaches the wire as the empty
	// wrapper, the only encoding of "explicitly empty" (MESSAGE_SPEC §2, §3).
	g.marshalArray(f, "        ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0, "")
}

// lastElemExpr is the "this element is the array's last" test, at loop position
// iv over the value val.
//
// It is the whole of the positional half of MESSAGE_SPEC §2's element rule. A
// wrapper array carries no length field: its decoded length is *highest present
// id + 1* (§5.1), so the element at the highest index is the only one whose
// PRESENCE carries the length, and nothing that carries the length may be elided.
// Everything before it may be: an interior element equal to the element default
// is indistinguishable from an absent one, because the decoder restores an absent
// id from that same default. Hence: interior sparse, last always written.
//
// A declared `count: N` changes nothing here. N is a capacity, not a length (§3),
// so it can never restore an elided tail -- the same test applies with or without
// one.
func lastElemExpr(iv, val string) string {
	return fmt.Sprintf("%s == len(%s) - 1", iv, val)
}

// emitSeqEnd closes the wrapper sequence opened at ind, choosing between the two
// closers the corelib offers. Every sequence is opened LAZILY (the corelib holds
// the header back until a child is written), so the closer alone decides whether
// a contentless one survives: write_sequence_end drops it, write_sequence_end_keep
// forces the empty frame out.
//
// keepIf is the condition under which an empty frame must survive:
//   - "" -- never. A sequence-typed FIELD (a struct/union field, an array
//     wrapper): an all-default one is omitted and absence reconstructs it (§2).
//   - a lastElemExpr -- a sequence-form array ELEMENT, kept only at the array's
//     last index. In the interior it is dropped and leaves an id GAP, which is
//     what makes an all-default element sparse like any other default value.
//     Note this is decided from the position in the VALUE, at run time; the
//     schema cannot answer it.
func emitSeqEnd(f *pyfile, ind, keepIf string) {
	if keepIf == "" {
		f.line("%se.write_sequence_end()", ind)
		return
	}
	f.line("%sif %s:", ind, keepIf)
	f.line("%s    e.write_sequence_end_keep()", ind)
	f.line("%selse:", ind)
	f.line("%s    e.write_sequence_end()", ind)
}

// marshalArray writes the array `val` as field `idExpr`. Numeric/enum/boolean/
// bitfield elements use the native array wire type (enum->signed, bool/bitfield->
// unsigned); string/blob/struct/union/array elements lower to a wrapper sequence
// whose child ids are the 0-based index (per MESSAGE_SPEC). Recurses for nested
// arrays.
//
// Every element the value holds is written -- no trailing run is elided, of
// either element kind, because the wire count IS the array's length (§3) and the
// highest wrapper id IS its last index (§5.1). What the interior may drop is a
// value that is indistinguishable from absence, and only that.
//
// keepIf is the closer this call's own wrapper takes (see emitSeqEnd); the native
// element kinds open no sequence and ignore it.
func (g *gen) marshalArray(f *pyfile, ind, idExpr, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int, keepIf string) {
	iv := fmt.Sprintf("_i%d", depth)
	ev := fmt.Sprintf("_e%d", depth)
	switch elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64:
		f.line("%se.write_unsigned_array(%s, %s)", ind, idExpr, val)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("%se.write_signed_array(%s, %s)", ind, idExpr, val)
	case ir.KindEnum:
		f.line("%se.write_signed_array(%s, [int(_v) for _v in %s])", ind, idExpr, val)
	case ir.KindBool:
		f.line("%se.write_unsigned_array(%s, [1 if _v else 0 for _v in %s])", ind, idExpr, val)
	case ir.KindBitfield:
		f.line("%se.write_unsigned_array(%s, [int(_v) for _v in %s])", ind, idExpr, val)
	case ir.KindFP32:
		f.line("%se.write_float32_array(%s, %s)", ind, idExpr, val)
	case ir.KindFP64:
		f.line("%se.write_float64_array(%s, %s)", ind, idExpr, val)
	case ir.KindString:
		// A string element is a leaf: in the array's INTERIOR it is omitted when it
		// equals the element default (empty), leaving an id gap the decoder restores
		// from that same default -- the ordinary sparse-field rule of MESSAGE_SPEC
		// §2, applied to an element. At the LAST index it is written whatever its
		// value: see lastElemExpr.
		f.line("%se.write_sequence_begin_lazy(%s)", ind, idExpr)
		f.line("%sfor %s, %s in enumerate(%s):", ind, iv, ev, val)
		f.line(`%s    if %s != "" or %s:`, ind, ev, lastElemExpr(iv, val))
		f.line("%s        e.write_string(%s, %s)", ind, iv, ev)
		emitSeqEnd(f, ind, keepIf)
	case ir.KindBlob:
		// A blob element is a leaf, exactly like the string element above.
		f.line("%se.write_sequence_begin_lazy(%s)", ind, idExpr)
		f.line("%sfor %s, %s in enumerate(%s):", ind, iv, ev, val)
		f.line("%s    if len(%s) != 0 or %s:", ind, ev, lastElemExpr(iv, val))
		f.line("%s        e.write_bytes(%s, bytes(%s))", ind, iv, ev)
		emitSeqEnd(f, ind, keepIf)
	case ir.KindStruct, ir.KindUnion:
		// A sequence-form element obeys the SAME rule as the leaf elements above --
		// one rule for both kinds -- and the lazily-held frame is where it is
		// applied. The nested _marshal writes no child exactly when the element
		// equals its declared default, so the CLOSER alone decides: the dropping one
		// in the interior, where an all-default element vanishes into an id gap; the
		// keeping one at the last index, where it survives as an empty frame because
		// that presence is what fixes the array's length.
		f.line("%se.write_sequence_begin_lazy(%s)", ind, idExpr)
		f.line("%sfor %s, %s in enumerate(%s):", ind, iv, ev, val)
		f.line("%s    e.write_sequence_begin_lazy(%s)", ind, iv)
		f.line("%s    %s.serialize(e)", ind, ev)
		emitSeqEnd(f, ind+"    ", lastElemExpr(iv, val))
		emitSeqEnd(f, ind, keepIf)
	case ir.KindArray:
		f.line("%se.write_sequence_begin_lazy(%s)", ind, idExpr)
		f.line("%sfor %s, %s in enumerate(%s):", ind, iv, ev, val)
		if isNativeArrayElem(items.Elem) {
			// A native row is a single count-prefixed value with no frame of its own,
			// so the rule lands on the WRITE rather than on a closer: an interior row
			// equal to the element default (the empty row) is not written at all, and
			// the last row always is.
			f.line("%s    if len(%s) != 0 or %s:", ind, ev, lastElemExpr(iv, val))
			g.marshalArray(f, ind+"        ", iv, ev, items.Elem, items.ElemRef, items.ElemItems, depth+1, "")
		} else {
			// A wrapper row has its own frame, so it takes the closer instead -- the
			// same interior/last choice, expressed the same way as for a struct
			// element above.
			g.marshalArray(f, ind+"    ", iv, ev, items.Elem, items.ElemRef, items.ElemItems, depth+1, lastElemExpr(iv, val))
		}
		emitSeqEnd(f, ind, keepIf)
	}
}

// capOf maps a schema fixed-count bound to a wrapper array's cap: N when the
// array declares a count, -1 (dynamic/unbounded) otherwise.
func capOf(hasCount bool, count int64) int64 {
	if hasCount {
		return count
	}
	return -1
}
