// Package python is the Python throughput backend (PLAN §6.4): it emits
// dataclasses with _marshal (Encoder) and a pull-parser _unmarshal
// (Decoder.next/skip + typed readers) against corelib-py, plus JSON helpers for
// the conformance harness.
package python

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for Python.
type Backend struct{}

func (*Backend) Lang() string { return "python" }

// Generate emits a single module (all enums/bitfields/dataclasses + messages).
// In project mode it adds a harness and pyproject.toml.
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	g := &gen{schema: s, banner: cfgString(cfg, "tool_banner", "sofabgen"), license: generator.LicenseID(cfg), omit: cfgBool(cfg, "omit_defaults")}
	module := g.module(s)
	files := []generator.File{{Path: "messages.py", Content: module}}
	if cfgString(cfg, "emit", "sources") == "project" {
		files = append(files, g.projectFiles(s, cfg)...)
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	banner  string
	license string // SPDX id, "" to omit the header line
	omit    bool
}

type pyfile struct{ b strings.Builder }

func (f *pyfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *pyfile) blank()        { f.b.WriteByte('\n') }
func (f *pyfile) bytes() []byte { return []byte(f.b.String()) }

func (g *gen) module(s *ir.Schema) []byte {
	f := &pyfile{}
	f.line("# Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("# SPDX-License-Identifier: %s", g.license)
	}
	f.line("from __future__ import annotations")
	f.line("import io")
	f.line("from dataclasses import dataclass, field")
	f.line("from enum import IntEnum")
	f.line("from sofab import Encoder, Decoder, WireType")
	f.blank()

	// enums + bitfield constants first
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfieldConsts(f, nt)
		}
	}
	// struct/union dataclasses, then messages
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitDataclass(f, g.typeName(key), nt.Fields)
		}
	}
	for _, m := range s.Messages {
		g.emitDataclass(f, exported(m.Name), m.Fields)
	}
	return f.bytes()
}

func (g *gen) emitEnum(f *pyfile, nt *ir.NamedType) {
	f.line("class %s(IntEnum):", g.typeName(nt.Key))
	for _, c := range nt.Consts {
		f.line("    %s = %d", strings.ToUpper(c.Name), c.Value)
	}
	f.blank()
}

func (g *gen) emitBitfieldConsts(f *pyfile, nt *ir.NamedType) {
	f.line("class %s(IntEnum):", g.typeName(nt.Key))
	for _, fl := range nt.Flags {
		f.line("    %s = 1 << %d", strings.ToUpper(fl.Name), fl.Pos)
	}
	f.blank()
}

func (g *gen) emitDataclass(f *pyfile, name string, fields []*ir.Field) {
	f.line("@dataclass")
	f.line("class %s:", name)
	if len(fields) == 0 {
		f.line("    pass")
	}
	for _, fld := range fields {
		f.line("    %s: %s = %s", pyIdent(fld.Name), g.pyAnnot(fld), g.pyDefault(fld))
	}
	f.blank()

	// _marshal
	f.line("    def _marshal(self, e: Encoder) -> None:")
	if len(fields) == 0 {
		f.line("        pass")
	}
	for _, fld := range fields {
		g.emitMarshal(f, fld)
	}
	f.blank()

	// _unmarshal (pull-parser)
	f.line("    def _unmarshal(self, d: Decoder) -> None:")
	f.line("        while True:")
	f.line("            fld = d.next()")
	f.line("            if fld is None or fld.type == WireType.SEQUENCE_END:")
	f.line("                return")
	for i, fld := range fields {
		kw := "elif"
		if i == 0 {
			kw = "if"
		}
		f.line("            %s fld.id == %d:", kw, fld.ID)
		g.emitUnmarshal(f, fld)
	}
	if len(fields) > 0 {
		f.line("            else:")
		f.line("                d.skip()")
	} else {
		f.line("            d.skip()")
	}
	f.blank()

	// JSON helpers + encode/decode
	g.emitJSON(f, name, fields)
}

func (g *gen) emitMarshal(f *pyfile, fld *ir.Field) {
	acc := "self." + pyIdent(fld.Name)
	var write string
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		write = fmt.Sprintf("e.write_unsigned(%d, int(%s))", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		write = fmt.Sprintf("e.write_signed(%d, int(%s))", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("e.write_bool(%d, %s)", fld.ID, acc)
	case ir.KindFP32:
		write = fmt.Sprintf("e.write_float32(%d, %s)", fld.ID, acc)
	case ir.KindFP64:
		write = fmt.Sprintf("e.write_float64(%d, %s)", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("e.write_string(%d, %s)", fld.ID, acc)
	case ir.KindBlob:
		f.line("        e.write_bytes(%d, bytes(%s))", fld.ID, acc)
		return
	case ir.KindStruct, ir.KindUnion:
		f.line("        e.write_sequence_begin(%d)", fld.ID)
		f.line("        %s._marshal(e)", acc)
		f.line("        e.write_sequence_end()")
		return
	case ir.KindArray:
		g.emitMarshalArray(f, fld, acc)
		return
	}
	if g.omit {
		f.line("        if %s != %s:", acc, g.pyDefault(fld))
		f.line("            %s", write)
	} else {
		f.line("        %s", write)
	}
}

func (g *gen) emitMarshalArray(f *pyfile, fld *ir.Field, acc string) {
	switch fld.Elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64:
		f.line("        e.write_unsigned_array(%d, %s)", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("        e.write_signed_array(%d, %s)", fld.ID, acc)
	case ir.KindFP32:
		f.line("        e.write_float32_array(%d, %s)", fld.ID, acc)
	case ir.KindFP64:
		f.line("        e.write_float64_array(%d, %s)", fld.ID, acc)
	case ir.KindString:
		f.line("        e.write_sequence_begin(%d)", fld.ID)
		f.line("        for _i, _s in enumerate(%s):", acc)
		f.line("            e.write_string(_i, _s)")
		f.line("        e.write_sequence_end()")
	case ir.KindBlob:
		f.line("        e.write_sequence_begin(%d)", fld.ID)
		f.line("        for _i, _b in enumerate(%s):", acc)
		f.line("            e.write_bytes(_i, bytes(_b))")
		f.line("        e.write_sequence_end()")
	}
}

func (g *gen) emitUnmarshal(f *pyfile, fld *ir.Field) {
	acc := "self." + pyIdent(fld.Name)
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		f.line("                %s = d.unsigned()", acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		f.line("                %s = d.signed()", acc)
	case ir.KindBool:
		f.line("                %s = d.bool()", acc)
	case ir.KindFP32:
		f.line("                %s = d.float32()", acc)
	case ir.KindFP64:
		f.line("                %s = d.float64()", acc)
	case ir.KindString:
		f.line("                %s = d.string()", acc)
	case ir.KindBlob:
		f.line("                %s = d.bytes()", acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("                %s._unmarshal(d)", acc)
	case ir.KindArray:
		g.emitUnmarshalArray(f, fld, acc)
	}
}

func (g *gen) emitUnmarshalArray(f *pyfile, fld *ir.Field, acc string) {
	switch fld.Elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64:
		f.line("                %s = d.read_unsigned_array()", acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("                %s = d.read_signed_array()", acc)
	case ir.KindFP32:
		f.line("                %s = d.read_float32_array()", acc)
	case ir.KindFP64:
		f.line("                %s = d.read_float64_array()", acc)
	case ir.KindString:
		f.line("                %s = []", acc)
		f.line("                while True:")
		f.line("                    _ef = d.next()")
		f.line("                    if _ef is None or _ef.type == WireType.SEQUENCE_END:")
		f.line("                        break")
		f.line("                    %s.append(d.string())", acc)
	case ir.KindBlob:
		f.line("                %s = []", acc)
		f.line("                while True:")
		f.line("                    _ef = d.next()")
		f.line("                    if _ef is None or _ef.type == WireType.SEQUENCE_END:")
		f.line("                        break")
		f.line("                    %s.append(d.bytes())", acc)
	}
}
