package python

import (
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// projectFiles scaffolds a runnable Python project: an encode/decode JSON
// harness over the generated module + a pyproject.toml (PLAN §9.1).
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any) []generator.File {
	return []generator.File{
		{Path: "harness.py", Content: g.harness(s)},
		{Path: "pyproject.toml", Content: []byte(pyproject)},
		{Path: "README.md", Content: []byte(readme)},
	}
}

const pyproject = `# @generated by sofabgen
[project]
name = "sofabuffers-generated"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = ["sofa-buffers-corelib"]
`

const readme = "# Generated SofaBuffers Python module\n\n" +
	"`@generated by sofabgen`. Encode/decode harness over `corelib-py`.\n\n" +
	"```sh\n# with corelib-py on PYTHONPATH:\n" +
	"echo '{...}' | python harness.py encode <Message>   # JSON -> bytes\n" +
	"python harness.py decode <Message> < bytes.bin       # bytes -> JSON\n```\n"

func (g *gen) harness(s *ir.Schema) []byte {
	f := &pyfile{}
	f.line("# Code generated by %s; DO NOT EDIT.", g.banner)
	f.line("import sys, json")
	f.line("import messages")
	f.blank()
	f.line("MESSAGES = {")
	for _, m := range s.Messages {
		f.line("    %q: messages.%s,", m.Name, exported(m.Name))
	}
	f.line("}")
	f.blank()
	f.line("def main() -> int:")
	f.line("    if len(sys.argv) < 2:")
	f.line("        sys.stderr.write('usage: harness.py <encode|decode> [Message]\\n')")
	f.line("        return 2")
	f.line("    mode = sys.argv[1]")
	f.line("    name = sys.argv[2] if len(sys.argv) > 2 else %q", defaultMessage(s))
	f.line("    cls = MESSAGES.get(name)")
	f.line("    if cls is None:")
	f.line("        sys.stderr.write('unknown message\\n')")
	f.line("        return 2")
	f.line("    data = sys.stdin.buffer.read()")
	f.line("    if mode == 'encode':")
	f.line("        obj = cls.from_jsonable(json.loads(data))")
	f.line("        sys.stdout.buffer.write(obj.encode())")
	f.line("    elif mode == 'decode':")
	f.line("        obj = cls.decode(data)")
	f.line("        sys.stdout.write(json.dumps(obj.to_jsonable()))")
	f.line("        sys.stdout.write('\\n')")
	f.line("    else:")
	f.line("        sys.stderr.write('unknown mode\\n')")
	f.line("        return 2")
	f.line("    return 0")
	f.blank()
	f.line("if __name__ == '__main__':")
	f.line("    sys.exit(main())")
	return f.bytes()
}

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

var _ = strings.TrimSpace
