// Package dart is the Dart throughput backend (PLAN §6.4): plain classes with a
// streaming `marshal` over the corelib Encoder and a push child-visitor decode
// against corelib-dart.
//
// corelib-dart's decode model is the push child-visitor (like Go): a
// `MessageVisitor` whose `onSequenceStart(id)` returns a child visitor for a
// nested scope, and whose native arrays arrive whole through a distinct
// `on*Array` callback. So the MESSAGE_SPEC §7.3/§7.4 wire-type dispatch is
// settled structurally — a contradictory header (including an integer array at a
// scalar id, or a fixlen subtype mismatch) lands in a different, unhandled
// callback and evaporates; a re-opened struct scope descends into the existing
// member (merge), while an array wrapper clears its list in `onSequenceStart`
// (replace). No `askip` guard is needed.
//
// The corelib's visitor callbacks return void, so a generated visitor cannot
// signal INVALID mid-decode. The over-count (#100), over-index (#142) and
// over-maxlen (S7.1) verdicts therefore ride a sticky `_inv` flag the visitor
// sets and the generated `decode`/`tryDecode` converts to a terminal INVALID
// after the corelib returns — the Rust/Zig "generated guard, sticky flag" model.
// The receiver-side decode limits (#102) are enforced by the corelib itself,
// passed in as a `DecoderLimits` (the Go/Python/TS family).
package dart

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for Dart.
type Backend struct{}

func (*Backend) Lang() string { return "dart" }

// Generate emits a single library file (message.dart) with every enum/bitfield
// constant class and object class, plus — when emit==project — a buildable
// package (pubspec.yaml + a JSON encode/decode harness) against corelib-dart.
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	g := &gen{
		schema:  s,
		banner:  cfgString(cfg, "tool_banner", "sofabgen"),
		license: generator.LicenseID(cfg),
		limits:  resolveLimits(s, cfg),
	}
	project := cfgString(cfg, "emit", "sources") == "project"
	prefix := ""
	if project {
		prefix = "lib/"
	}
	files := []generator.File{{Path: prefix + "message.dart", Content: g.module(s)}}
	if project {
		files = append(files, g.projectFiles(s, cfg)...)
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	banner  string
	license string // SPDX id, "" to omit the header line
	limits  limitSet
}

// limitSet is the receiver-side decode-limit configuration (generator#102),
// resolved against the schema like the Go/Python/TS backends: corelib-dart
// enforces the limits globally per decode (a DecoderLimits passed to the
// decoder), so each active cap is the configured value raised to the largest
// schema bound of its kind, and an entry is active only when its key is set AND
// the schema actually has an unbounded field of that kind.
type limitSet struct {
	arrayCount, stringLen, blobLen int64
	arrayHas, stringHas, blobHas   bool
}

func (l limitSet) any() bool { return l.arrayHas || l.stringHas || l.blobHas }

func resolveLimits(s *ir.Schema, cfg map[string]any) limitSet {
	var all []*ir.Field
	for _, m := range s.Messages {
		all = append(all, m.Fields...)
	}
	b := ir.Bounds(all)
	var l limitSet
	if v, ok := cfgLimit(cfg, "max_dyn_array_count"); ok && b.HasDynArray {
		l.arrayCount, l.arrayHas = max(v, b.MaxCount), true
	}
	if v, ok := cfgLimit(cfg, "max_dyn_string_len"); ok && b.HasDynString {
		l.stringLen, l.stringHas = max(v, b.MaxStringLen), true
	}
	if v, ok := cfgLimit(cfg, "max_dyn_blob_len"); ok && b.HasDynBlob {
		l.blobLen, l.blobHas = max(v, b.MaxBlobLen), true
	}
	return l
}

// ---- source file builder --------------------------------------------------

type dfile struct{ b strings.Builder }

func (f *dfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *dfile) blank()        { f.b.WriteByte('\n') }
func (f *dfile) bytes() []byte { return []byte(f.b.String()) }

// ---- module ---------------------------------------------------------------

func (g *gen) module(s *ir.Schema) []byte {
	f := &dfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("// SPDX-License-Identifier: %s", g.license)
	}
	f.line("// ignore_for_file: unused_field, unused_element, deprecated_member_use_from_same_package")
	f.line("import 'dart:typed_data';")
	f.line("import 'package:sofabuffers/sofabuffers.dart' as sofab;")
	f.blank()

	g.emitLimits(f)
	g.emitPrelude(f, s)

	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfield(f, nt)
		}
	}
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitClass(f, g.typeName(key), nt.Summary, nt.Fields, false)
		}
	}
	for _, m := range s.Messages {
		g.emitClass(f, exported(m.Name), m.Summary, m.Fields, true)
	}
	return f.bytes()
}

func (g *gen) emitLimits(f *dfile) {
	if !g.limits.any() {
		return
	}
	f.line("// Receiver-side decode limits baked from the sofabgen config")
	f.line("// (max_dyn_array_count / max_dyn_string_len / max_dyn_blob_len). They govern")
	f.line("// only fields the schema left unbounded; each cap is raised to the largest")
	f.line("// schema bound of its kind. Exceeding a cap fails decode with limitExceeded.")
	if g.limits.arrayHas {
		f.line("const int maxDynArrayCount = %d;", g.limits.arrayCount)
	}
	if g.limits.stringHas {
		f.line("const int maxDynStringLen = %d;", g.limits.stringLen)
	}
	if g.limits.blobHas {
		f.line("const int maxDynBlobLen = %d;", g.limits.blobLen)
	}
	var parts []string
	if g.limits.arrayHas {
		parts = append(parts, "maxArrayCount: maxDynArrayCount")
	}
	if g.limits.stringHas {
		parts = append(parts, "maxStringLen: maxDynStringLen")
	}
	if g.limits.blobHas {
		parts = append(parts, "maxBlobLen: maxDynBlobLen")
	}
	f.line("const sofab.DecoderLimits _limits = sofab.DecoderLimits(%s);", strings.Join(parts, ", "))
	f.blank()
}

// limitsArg is the trailing ", limits: _limits" appended to Decoder.decode when
// any receiver-side cap is active, else "".
func (g *gen) limitsArg() string {
	if g.limits.any() {
		return ", limits: _limits"
	}
	return ""
}

// ---- enum / bitfield ------------------------------------------------------

// emitEnum lowers an enum to a Dart namespace of `static const int` values (the
// field itself stays a raw `int`, signed on the wire). This matches the Zig
// backend's integer namespaces and admits negative values, which a plain Dart
// enum cannot.
func (g *gen) emitEnum(f *dfile, nt *ir.NamedType) {
	emitDoc(f, "", nt.Summary)
	f.line("abstract final class %s {", g.typeName(nt.Key))
	f.line("  %s._();", g.typeName(nt.Key))
	for _, c := range nt.Consts {
		emitDoc(f, "  ", c.Description)
		f.line("  static const int %s = %d;", dartIdent(c.Name), c.Value)
	}
	f.line("}")
	f.blank()
}

func (g *gen) emitBitfield(f *dfile, nt *ir.NamedType) {
	emitDoc(f, "", nt.Summary)
	f.line("abstract final class %s {", g.typeName(nt.Key))
	f.line("  %s._();", g.typeName(nt.Key))
	for _, fl := range nt.Flags {
		emitDoc(f, "  ", flagDoc(fl))
		f.line("  static const int %s = 1 << %d;", dartIdent(fl.Name), fl.Pos)
	}
	f.line("}")
	f.blank()
}

// ---- object class ---------------------------------------------------------

func (g *gen) emitClass(f *dfile, name, summary string, fields []*ir.Field, isMessage bool) {
	emitDoc(f, "", summary)
	f.line("class %s {", name)
	for _, fld := range fields {
		emitDoc(f, "  ", fieldDoc(fld))
		if fld.Deprecated {
			f.line("  @Deprecated('retained for backward compatibility only')")
		}
		f.line("  %s %s%s;", g.dartType(fld), dartIdent(fld.Name), g.dartInit(fld))
		if fld.Kind == ir.KindFP32 {
			// Companion raw-bits slot: a Dart `double` cannot carry an fp32 NaN's
			// payload/signaling bits (§4.6), so when decode delivers a NaN we keep the
			// exact 32 wire bits here and re-emit them via writeFp32Bits. null == "no
			// captured bits; derive the wire image from the double".
			f.line("  int? %s;", fp32BitsField(fld.Name))
		}
	}
	f.blank()

	// marshal: sparse-canonical field writes in ascending id order.
	f.line("  void marshal(sofab.Encoder e) {")
	for _, fld := range fields {
		g.emitMarshal(f, fld)
	}
	f.line("  }")

	if isMessage {
		f.blank()
		f.line("  /// Worst-case serialized size (schema-bounded fields; a cap for")
		f.line("  /// unbounded ones).")
		f.line("  static const int maxSize = %d;", g.maxSize(fields))
		f.line("  /// Serializes this message to a fresh byte buffer.")
		f.line("  Uint8List encode() => sofab.Encoder.encodeToBytes(marshal);")
		f.blank()
		f.line("  /// Status-surfacing one-shot decode (MESSAGE_SPEC S7): fills [out] and")
		f.line("  /// returns the terminal decode outcome. `invalid` covers both malformed")
		f.line("  /// bytes and a schema-bound violation (over-count/over-index/over-maxlen);")
		f.line("  /// `incomplete` means the bytes end inside a field or an open sequence.")
		f.line("  static sofab.DecodeStatus tryDecode(Uint8List data, %s out) {", name)
		f.line("    final e = _Dec();")
		f.line("    final st = sofab.Decoder.decode(data, %s(out, e)%s);", visitorName(name), g.limitsArg())
		f.line("    return e.inv ? sofab.DecodeStatus.invalid : st;")
		f.line("  }")
		f.blank()
		f.line("  /// Best-effort one-shot decode (the 90 %% case): returns the message with")
		f.line("  /// every field decoded so far, discarding the status. Prefer [tryDecode]")
		f.line("  /// when a truncated or malformed message must be distinguished.")
		f.line("  static %s decode(Uint8List data) {", name)
		f.line("    final m = %s();", name)
		f.line("    tryDecode(data, m);")
		f.line("    return m;")
		f.line("  }")
	}
	f.line("}")
	f.blank()

	g.emitVisitor(f, name, fields)
}

func visitorName(typeName string) string { return "_" + typeName + "Visitor" }

// ---- marshal --------------------------------------------------------------

func (g *gen) emitMarshal(f *dfile, fld *ir.Field) {
	acc := dartIdent(fld.Name)
	var write string
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		write = fmt.Sprintf("e.writeUnsigned(%d, %s);", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		write = fmt.Sprintf("e.writeSigned(%d, %s);", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("e.writeBool(%d, %s);", fld.ID, acc)
	case ir.KindFP32:
		// A NaN with captured bits re-emits bit-for-bit (writeFp32Bits); any other
		// value (incl. a user-set NaN with no captured bits) goes through writeFp32.
		// `acc != default` still gates omission: a NaN never equals the default.
		bits := fp32BitsField(fld.Name)
		f.line("    if (%s != %s) {", acc, g.dartDefaultValue(fld))
		f.line("      if (%s.isNaN && %s != null) { e.writeFp32Bits(%d, %s!); } else { e.writeFp32(%d, %s); }", acc, bits, fld.ID, bits, fld.ID, acc)
		f.line("    }")
		return
	case ir.KindFP64:
		write = fmt.Sprintf("e.writeFp64(%d, %s);", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("e.writeString(%d, %s);", fld.ID, acc)
	case ir.KindBlob:
		// A blob is a leaf: omit when equal to its default (empty if none).
		if def, ok := g.blobDefaultLit(fld); ok {
			f.line("    if (!_bytesEq(%s, %s)) { e.writeBlob(%d, %s); }", acc, def, fld.ID, acc)
		} else {
			f.line("    if (%s.isNotEmpty) { e.writeBlob(%d, %s); }", acc, fld.ID, acc)
		}
		return
	case ir.KindStruct, ir.KindUnion:
		// A sequence is always framed; its children are omitted per-field by the
		// nested marshal (MESSAGE_SPEC S2).
		f.line("    e.beginSequence(%d); %s.marshal(e); e.endSequence();", fld.ID, acc)
		return
	case ir.KindArray:
		g.emitMarshalArray(f, fld, acc)
		return
	}
	// Scalar/string/enum/bitfield/bool leaf: omit when equal to the default.
	f.line("    if (%s != %s) { %s }", acc, g.dartDefaultValue(fld), write)
}

// blobDefaultLit is the Uint8List literal a blob field is compared against for
// omission when it has a non-empty schema default; ("", false) otherwise.
func (g *gen) blobDefaultLit(f *ir.Field) (string, bool) {
	init := g.dartInit(f)
	rhs := strings.TrimPrefix(init, " = ")
	if rhs == "Uint8List(0)" {
		return "", false
	}
	return rhs, true
}

func (g *gen) emitMarshalArray(f *dfile, fld *ir.Field, acc string) {
	// A native scalar array is a leaf field: omit when equal to its (trimmed)
	// default, else when empty. A composite/dynamic-element array is a wrapper
	// sequence and is always framed.
	if nativeArrayElem(fld.Elem) {
		val := acc
		if fld.Elem == ir.KindBool {
			val = fmt.Sprintf("[for (final _b in %s) _b ? 1 : 0]", acc)
		}
		trimmed := g.trimExpr(val, fld.Elem, fld.HasCount)
		if fld.HasCount {
			if def, ok := g.trimmedDefaultLit(fld); ok {
				f.line("    { final _t = %s; if (!_listEq(_t, %s)) { %s } }", trimmed, def, g.writeArrayStmt(fld, "_t"))
			} else {
				f.line("    { final _t = %s; if (_t.isNotEmpty) { %s } }", trimmed, g.writeArrayStmt(fld, "_t"))
			}
		} else {
			if def, ok := g.arrayDefaultLit(fld); ok {
				f.line("    if (!_listEq(%s, %s)) { %s }", val, def, g.writeArrayStmt(fld, val))
			} else {
				f.line("    if (%s.isNotEmpty) { %s }", acc, g.writeArrayStmt(fld, val))
			}
		}
		return
	}
	// Wrapper sequence (string/blob/struct/union/nested array).
	g.marshalWrapperArray(f, "    ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
}

// writeArrayStmt is the corelib call writing native-array expression `val` as
// field fld.ID (enum→signed, bool/bitfield→unsigned).
func (g *gen) writeArrayStmt(fld *ir.Field, val string) string {
	switch {
	case unsignedArrayElem(fld.Elem):
		return fmt.Sprintf("e.writeUnsignedArray(%d, %s);", fld.ID, val)
	case signedArrayElem(fld.Elem):
		return fmt.Sprintf("e.writeSignedArray(%d, %s);", fld.ID, val)
	case fld.Elem == ir.KindFP32:
		return fmt.Sprintf("e.writeFp32Array(%d, %s);", fld.ID, val)
	default: // fp64
		return fmt.Sprintf("e.writeFp64Array(%d, %s);", fld.ID, val)
	}
}

// trimExpr wraps a native-array expression in the trailing-default-run trim a
// fixed-count array's canonical encoding requires (MESSAGE_SPEC S3). Elements
// compare by BIT PATTERN for floats. A dynamic array has no N to refill from, so
// it is not trimmed.
func (g *gen) trimExpr(val string, elem ir.Kind, fixed bool) string {
	if !fixed {
		return val
	}
	switch elem {
	case ir.KindFP32:
		return fmt.Sprintf("_trimF32(%s)", val)
	case ir.KindFP64:
		return fmt.Sprintf("_trimF64(%s)", val)
	default:
		return fmt.Sprintf("_trimInt(%s)", val)
	}
}

// trimmedDefaultLit is the trimmed default list literal a fixed-count native
// array's value is compared against for whole-field omission; ("", false) when
// the field has no schema default (so the trimmed default is empty).
func (g *gen) trimmedDefaultLit(f *ir.Field) (string, bool) {
	vals, ok := f.Default.([]any)
	if !ok {
		return "", false
	}
	// Trim the trailing element-default run by bit pattern.
	n := len(vals)
	for n > 0 && g.isElemZero(f.Elem, vals[n-1]) {
		n--
	}
	if n == 0 {
		return "", false
	}
	parts := make([]string, n)
	for i := 0; i < n; i++ {
		parts[i] = g.marshalElemLit(f.Elem, vals[i])
	}
	return fmt.Sprintf("<%s>[%s]", g.marshalArrayElemType(f.Elem), strings.Join(parts, ", ")), true
}

// marshalArrayElemType is the Dart element type of a native array's MARSHAL wire
// image, against which the omit-compare runs: a bool array is compared as its
// 0/1 integer image, so its compare list is <int>, not <bool>.
func (g *gen) marshalArrayElemType(elem ir.Kind) string {
	if elem == ir.KindBool {
		return "int"
	}
	return g.dartArrayElemType(elem, nil, nil)
}

// arrayDefaultLit is the full (untrimmed) default list literal a dynamic native
// array's value is compared against for omission; ("", false) when no default.
func (g *gen) arrayDefaultLit(f *ir.Field) (string, bool) {
	vals, ok := f.Default.([]any)
	if !ok {
		return "", false
	}
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = g.marshalElemLit(f.Elem, v)
	}
	return fmt.Sprintf("<%s>[%s]", g.marshalArrayElemType(f.Elem), strings.Join(parts, ", ")), true
}

// marshalElemLit renders a native-array default element as it appears in the
// MARSHAL wire image (bool → 0/1 int), matching the trimmed/omit compare.
func (g *gen) marshalElemLit(elem ir.Kind, v any) string {
	if elem == ir.KindBool {
		if b, ok := v.(bool); ok && b {
			return "1"
		}
		return "0"
	}
	return g.elemLit(elem, v)
}

func (g *gen) isElemZero(elem ir.Kind, v any) bool {
	switch elem {
	case ir.KindBool:
		b, _ := v.(bool)
		return !b
	case ir.KindFP32, ir.KindFP64:
		switch x := v.(type) {
		case float64:
			return x == 0 // note: +0.0 only; -0.0 has non-zero bits but == 0 here
		case int:
			return x == 0
		case int64:
			return x == 0
		}
		return false
	default:
		switch x := v.(type) {
		case int:
			return x == 0
		case int64:
			return x == 0
		case string:
			return x == "0"
		case float64:
			return x == 0
		}
		return false
	}
}

// marshalWrapperArray writes a wrapper-sequence array (string/blob/struct/union
// or nested array). Elements are keyed by 0-based index; string/blob leaves are
// omitted when equal to the element default (empty).
func (g *gen) marshalWrapperArray(f *dfile, ind, idExpr, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	switch elem {
	case ir.KindString:
		f.line("%se.beginSequence(%s);", ind, idExpr)
		f.line("%sfor (var %s = 0; %s < %s.length; %s++) { if (%s[%s].isNotEmpty) e.writeString(%s, %s[%s]); }", ind, iv, iv, val, iv, val, iv, iv, val, iv)
		f.line("%se.endSequence();", ind)
	case ir.KindBlob:
		f.line("%se.beginSequence(%s);", ind, idExpr)
		f.line("%sfor (var %s = 0; %s < %s.length; %s++) { if (%s[%s].isNotEmpty) e.writeBlob(%s, %s[%s]); }", ind, iv, iv, val, iv, val, iv, iv, val, iv)
		f.line("%se.endSequence();", ind)
	case ir.KindStruct, ir.KindUnion:
		f.line("%se.beginSequence(%s);", ind, idExpr)
		f.line("%sfor (var %s = 0; %s < %s.length; %s++) {", ind, iv, iv, val, iv)
		f.line("%s  e.beginSequence(%s); %s[%s].marshal(e); e.endSequence();", ind, iv, val, iv)
		f.line("%s}", ind)
		f.line("%se.endSequence();", ind)
	case ir.KindArray:
		// A nested row is a wrapper-sequence element, not a `count: N` field, so it
		// is never trimmed (MESSAGE_SPEC S3).
		f.line("%se.beginSequence(%s);", ind, idExpr)
		f.line("%sfor (var %s = 0; %s < %s.length; %s++) {", ind, iv, iv, val, iv)
		if nativeArrayElem(items.Elem) {
			row := fmt.Sprintf("%s[%s]", val, iv)
			if items.Elem == ir.KindBool {
				row = fmt.Sprintf("[for (final _b in %s[%s]) _b ? 1 : 0]", val, iv)
			}
			f.line("%s  %s", ind, g.writeRowStmt(items.Elem, iv, row))
		} else {
			g.marshalWrapperArray(f, ind+"  ", iv, fmt.Sprintf("%s[%s]", val, iv), items.Elem, items.ElemRef, items.ElemItems, depth+1)
		}
		f.line("%s}", ind)
		f.line("%se.endSequence();", ind)
	}
}

// writeRowStmt writes one native-array row of a matrix as element `idExpr`.
func (g *gen) writeRowStmt(elem ir.Kind, idExpr, val string) string {
	switch {
	case unsignedArrayElem(elem):
		return fmt.Sprintf("e.writeUnsignedArray(%s, %s);", idExpr, val)
	case signedArrayElem(elem):
		return fmt.Sprintf("e.writeSignedArray(%s, %s);", idExpr, val)
	case elem == ir.KindFP32:
		return fmt.Sprintf("e.writeFp32Array(%s, %s);", idExpr, val)
	default:
		return fmt.Sprintf("e.writeFp64Array(%s, %s);", idExpr, val)
	}
}
