package dart

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/analysis"
	"github.com/sofa-buffers/generator/internal/ir"
	"github.com/sofa-buffers/generator/internal/model"
	"github.com/sofa-buffers/generator/internal/naming"
	"github.com/sofa-buffers/generator/internal/parser"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/dart/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every name on the Dart member lists, sorted, split into two
// scopes: a name whose fold an earlier name already has (`enum` after `Enum`,
// `null` after `Null`) goes to the second, since one scope may not hold both
// (the validator's second naming rule).
func reservedNames() (first, twins []string) {
	var names []string
	for _, set := range []map[string]bool{dartKeywords, dartMembers, dartObjectMembers, dartOuterNames, unionFixed} {
		for n := range set {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	seen := map[string]bool{}
	for _, n := range names {
		if seen[naming.Fold(n)] {
			twins = append(twins, n)
			continue
		}
		seen[naming.Fold(n)] = true
		first = append(first, n)
	}
	return first, twins
}

// reservedTypeNames is every name a type identifier is escaped away from
// (isTypeReserved), sorted.
func reservedTypeNames() []string {
	var names []string
	for _, set := range []map[string]bool{dartKeywords, dartOuterNames} {
		for n := range set {
			if isTypeReserved(n) {
				names = append(names, n)
			}
		}
	}
	for n := range dartTopLevelNames {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// unreachableTypeNames are names of dart:io, dart:convert and dart:typed_data
// that no list holds: the harness imports those libraries under a prefix, so a
// message spelled like one needs no escape. Probed as messages all the same.
var unreachableTypeNames = []string{"ByteBuffer", "Codec", "File", "Int32List", "JsonCodec", "Platform", "Stdin", "Utf8Codec"}

// reservedYAML is the collision schema: every member-reserved name as a field of
// a message, of a nested struct and as a union option (case twins in a scope of
// their own); every type-reserved name, and the unreachable probes, as a
// message; and the member collisions the contract resolves by escaping instead
// of refusing -- a field beside its neighbour's fp32 companion, a field and a
// union option spelled like a class, a union option beside another's `<opt>Id`
// and `has<Opt>`, a bool-array option whose slot would hide `_bools01`, and enum
// constants spelled like a keyword and like their own class. Names are quoted:
// `true`, `false` and `null` are YAML scalars.
func reservedYAML() string {
	first, twins := reservedNames()
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/dart/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/dart -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field and as a type must analyze\n")
	b.WriteString("# clean and round-trip.\n")
	fields := func(names []string, ind string) string {
		var f strings.Builder
		for i, n := range names {
			fmt.Fprintf(&f, "%s%q: { id: %d, type: u8 }\n", ind, n, i)
		}
		return f.String()
	}
	opts := func(names []string) []string {
		var o []string
		for i, n := range names {
			o = append(o, fmt.Sprintf("%q: { id: %d, type: u8 }", n, i))
		}
		return o
	}
	k := len(first)
	uopts := append(opts(first),
		fmt.Sprintf(`a: { id: %d, type: u8 }`, k),
		fmt.Sprintf(`aId: { id: %d, type: u8 }`, k+1),
		fmt.Sprintf(`x: { id: %d, type: u8 }`, k+2),
		fmt.Sprintf(`hasX: { id: %d, type: u8 }`, k+3),
		fmt.Sprintf(`Inner: { id: %d, type: u8 }`, k+4),
		fmt.Sprintf(`bools01: { id: %d, type: array, items: { type: boolean, count: 4 } }`, k+5),
	)
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner:
%s    Twins:
%s    P:
      x: { id: 0, type: u8 }
  enum:
    E: { "class": 0, "E": 1, "int": 2 }
messages:
  m:
    payload:
%s      inner: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      twins: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Twins' } }
      u: { id: %d, type: union, oneof: { %s } }
      ut: { id: %d, type: union, oneof: { %s } }
      f: { id: %d, type: fp32 }
      fFp32Bits: { id: %d, type: u8 }
      M: { id: %d, type: u8 }
      P: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/P' } }
      ev: { id: %d, type: enum, enum: { $ref: '#/$defs/enum/E' } }
`, fields(first, "      "), fields(twins, "      "), fields(first, "      "),
		k, k+1, k+2, strings.Join(uopts, ", "), k+3, strings.Join(opts(twins), ", "),
		k+4, k+5, k+6, k+7, k+8)
	types := append(reservedTypeNames(), unreachableTypeNames...)
	sort.Strings(types)
	for _, n := range types {
		fmt.Fprintf(&b, "  %q: { payload: { x: { id: 0, type: u8 } } }\n", n)
	}
	return b.String()
}

// reservedJSON is the harness input for m: every field under its schema name at
// a non-default value, and each union holding a non-default option.
func reservedJSON() string {
	first, twins := reservedNames()
	top := map[string]any{}
	inner := map[string]any{}
	tw := map[string]any{}
	for i, n := range first {
		top[n] = i + 1
		inner[n] = i + 2
	}
	for i, n := range twins {
		tw[n] = i + 3
	}
	top["inner"] = inner
	top["twins"] = tw
	top["u"] = map[string]any{"bools01": []bool{true, false, true}}
	top["ut"] = map[string]any{twins[len(twins)-1]: 4}
	top["f"] = 1.5
	top["fFp32Bits"] = 7
	top["M"] = 8
	top["P"] = map[string]any{"x": 9}
	top["ev"] = 2
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite analyzes that file with
// --fatal-infos, compiles and round-trips it (tests/conformance/dart/run.sh), so
// a name added to reserved.go is covered once the file is regenerated -- and
// this test fails until it is.
func TestReservedSchemaFile(t *testing.T) {
	for path, want := range map[string]string{
		"../../tests/conformance/dart/reserved.yaml": reservedYAML(),
		"../../tests/conformance/dart/reserved.json": reservedJSON(),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// loadSchema runs load->resolve->IR over a definition file (Load, so a
// cross-file $ref resolves), stopping short of generation.
func loadSchema(t *testing.T, def string) *ir.Schema {
	t.Helper()
	doc, err := parser.Load(def)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := doc.Resolve(); err != nil {
		t.Fatal(err)
	}
	s, err := model.Build(doc)
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.Analyze(s); err != nil {
		t.Fatal(err)
	}
	return s
}

// TestReservedNamesAreMangled: every name on the list is a member with a
// trailing underscore -- except the members only a union has -- in the message
// and in the nested struct; a case twin, in the struct of its own scope. A
// capitalised one may need more than one: `String_` is also the class of the
// message `String`.
func TestReservedNamesAreMangled(t *testing.T) {
	first, twins := reservedNames()
	out := genFor(t, writeDef(t, reservedYAML()), map[string]any{})
	check := func(names []string, classes int) {
		for _, n := range names {
			re := `(?m)^  int ` + regexp.QuoteMeta(n) + `_+ = 0;$`
			if unionFixed[n] {
				re = `(?m)^  int ` + regexp.QuoteMeta(n) + ` = 0;$`
			}
			if got := len(regexp.MustCompile(re).FindAllString(out, -1)); got != classes {
				t.Errorf("field %q is an escaped member in %d of the %d classes", n, got, classes)
			}
		}
	}
	check(first, 2)
	check(twins, 1)
}

// TestTypeNamesAreEscaped: a message spelled like a name the library or its
// harness uses unqualified is that name plus `_`, with its roles built from the
// unescaped name; one spelled like a name of a prefixed import keeps its name.
func TestTypeNamesAreEscaped(t *testing.T) {
	out := genFor(t, writeDef(t, reservedYAML()), map[string]any{"emit": "project", "timestamp": false})
	for _, n := range reservedTypeNames() {
		for _, want := range []string{"class " + n + "_ {", "class " + n + "__Decoder {", "class _" + n + "__Visitor "} {
			if !strings.Contains(out, want) {
				t.Errorf("message %s: want %q", n, want)
			}
		}
	}
	for _, n := range unreachableTypeNames {
		if !strings.Contains(out, "class "+n+" {") {
			t.Errorf("message %s: want its own name, unescaped", n)
		}
	}
	for _, imp := range []string{"import 'dart:io' as io;", "import 'dart:convert' as convert;", "import 'dart:typed_data' as typed;"} {
		if !strings.Contains(out, imp) {
			t.Errorf("harness: want %q", imp)
		}
	}
}

// TestMemberCollisionsAreEscaped: what used to be refused generates, and the
// schema's own names keep their spelling -- the derived member, or the one that
// would hide a class, takes the `_`.
func TestMemberCollisionsAreEscaped(t *testing.T) {
	out := genFor(t, writeDef(t, reservedYAML()), map[string]any{})
	for _, want := range []string{
		"  int fFp32Bits = 0;",           // the field keeps its name ...
		"  int? fFp32Bits_;",             // ... and f's companion yields
		"  int M_ = 0;",                  // a field spelled like the class M
		"  P P_ = P();",                  // ... and like the struct it holds
		"  static const int class_ = 0;", // an enum constant spelled like a keyword
		"  static const int E_ = 1;",     // ... and like its own class
		"  static const int int_ = 2;",
		"  static const int aId_ = ", // `a`'s id constant beside an option aId
		"  static const int aIdId = ",
		"  bool get hasX_ => ", // `x`'s has<X> beside an option hasX
		"  int get hasX => ",
		"  int get Inner_ => ", // an option spelled like a class
		"_bools01_",            // a slot that would hide the library's _bools01
	} {
		if !strings.Contains(out, want) {
			t.Errorf("want %q", want)
		}
	}
}

var (
	dartBlank    = regexp.MustCompile(`(?s)/\*.*?\*/|//[^\n]*|'''.*?'''|'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"`)
	dartClass    = regexp.MustCompile(`(?m)^class ([A-Z]\w*)[^{\n]*\{`)
	dartMember   = regexp.MustCompile(`^\s*(?:@\w+\s+)*(?:(?:static|final|const|late|external|factory|covariant)\s+)*(?:[\w<>?,\[\] .]+?\s+)?(?:get\s+|set\s+)?(\w+)\s*(?:\(|=>|=|;|\{)`)
	dartTok      = regexp.MustCompile(`(?:^|[^\w.$])([A-Za-z_]\w*)`)
	dartConst    = regexp.MustCompile(`(?m)^const \w+ (\w+)`)
	dartTopLevel = regexp.MustCompile(`(?m)^(?:abstract final class|class|const \w+|[\w<>?,.][\w<>?, .]*?) (_?\w+)\s*(?:<[^>]*>)?\s*(?:\(|=|\{|extends)`)
)

// namesInTable is every member name the member table hands out.
func namesInTable(t *memberTable) map[string]bool {
	out := map[string]bool{}
	for _, n := range t.fields {
		out[n.member], out[n.bits], out[n.def] = true, true, true
	}
	for _, u := range t.unions {
		for _, o := range u.opts {
			for _, n := range []string{o.prop, o.has, o.mutable, o.slot, o.bits, o.bitSlot, o.idConst} {
				out[n] = true
			}
		}
	}
	for _, n := range t.consts {
		out[n] = true
	}
	for _, n := range t.flags {
		out[n] = true
	}
	delete(out, "")
	return out
}

// TestDartNamesInScope is the drift guard: over the corpus, realworld set,
// example, names schema and collision schema,
//
//   - every member a generated class declares beyond the schema's own must be
//     on dartMembers (or a union's own member, or private);
//   - every OUTER name a class body uses -- an upper-case name, the `sofab`
//     prefix, a top-level constant -- must be on the list or be a generated
//     class, which members() keeps every member off;
//   - every upper-case name the library or the harness uses unqualified must be
//     a generated class or one typeEscape escapes a type away from.
//
// A class body that starts to use `Int32List`, or a harness that starts to use
// `Uri`, fails here until the name is reserved.
func TestDartNamesInScope(t *testing.T) {
	defs, _ := filepath.Glob("../../tests/matrix/corpus/defs/*.yaml")
	rw, _ := filepath.Glob("../../examples/messages/realworld/*.yaml")
	defs = append(append(defs, rw...), "../../examples/messages/example.yaml",
		"../../tests/conformance/lib/names.yaml", "../../tests/conformance/dart/reserved.yaml")
	for _, def := range defs {
		s := loadSchema(t, def)
		g := &gen{schema: s}
		classes := g.moduleClasses()
		fields := namesInTable(g.members())
		files, err := (&Backend{}).Generate(s, map[string]any{"emit": "project", "timestamp": false})
		if err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		var lib, harness string
		for _, f := range files {
			switch f.Path {
			case "lib/message.dart":
				lib = dartBlank.ReplaceAllString(string(f.Content), `''`)
			case "bin/harness.dart":
				harness = dartBlank.ReplaceAllString(string(f.Content), `''`)
			}
		}
		consts := map[string]bool{}
		for _, m := range dartConst.FindAllStringSubmatch(lib, -1) {
			consts[m[1]] = true
		}
		for _, loc := range dartClass.FindAllStringSubmatchIndex(lib, -1) {
			// A message's decoder keeps its own state; no schema field is in
			// scope there.
			if strings.HasSuffix(lib[loc[2]:loc[3]], "__Decoder") {
				continue
			}
			depth := 1
			var body strings.Builder
			for _, line := range strings.Split(lib[loc[1]:], "\n") {
				if depth == 0 {
					break
				}
				if depth == 1 {
					if m := dartMember.FindStringSubmatch(line); m != nil {
						n := m[1]
						if !(fields[n] || classes[n] || strings.HasPrefix(n, "_") || dartMembers[n] || dartObjectMembers[n] || unionFixed[n] || dartKeywords[n]) {
							t.Errorf("%s: member %s is not on dartMembers", filepath.Base(def), n)
						}
					}
				}
				depth += strings.Count(line, "{") - strings.Count(line, "}")
				body.WriteString(line + "\n")
			}
			for _, m := range dartTok.FindAllStringSubmatch(body.String(), -1) {
				n := m[1]
				outer := n[0] >= 'A' && n[0] <= 'Z' || n == "sofab" || consts[n]
				if outer && !(dartKeywords[n] || dartOuterNames[n] || classes[n] || fields[n]) {
					t.Errorf("%s: outer name %s is not on the list", filepath.Base(def), n)
				}
			}
		}
		for what, src := range map[string]string{"library": lib, "harness": harness} {
			for _, m := range dartTok.FindAllStringSubmatch(src, -1) {
				n := m[1]
				// A declared member (an enum constant `LOW`) and the type
				// parameter of the library's _prefixEq<T> are not outer names:
				// both are declared where they are used.
				if n[0] >= 'A' && n[0] <= 'Z' && !classes[n] && !fields[n] && n != "T" && !isTypeReserved(n) {
					t.Errorf("%s: the %s uses %s unqualified, and no type is escaped away from it", filepath.Base(def), what, n)
				}
			}
		}
	}
}

// TestNamesSchemaDeclaresEachNameOnce generates the shared name-collision
// schema (tests/conformance/lib/names.yaml) and checks, without a toolchain,
// that every top-level declaration of the library and the harness -- which
// imports the library unprefixed, so the two share one namespace -- appears
// exactly once, and that every message has its class, decoder and visitor.
func TestNamesSchemaDeclaresEachNameOnce(t *testing.T) {
	s := loadSchema(t, "../../tests/conformance/lib/names.yaml")
	files, err := (&Backend{}).Generate(s, map[string]any{"emit": "project", "timestamp": false})
	if err != nil {
		t.Fatalf("names.yaml must generate: %v", err)
	}
	decl := map[string]int{}
	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".dart") {
			continue
		}
		src := dartBlank.ReplaceAllString(string(f.Content), `''`)
		for _, m := range dartTopLevel.FindAllStringSubmatch(src, -1) {
			decl[m[1]]++
		}
	}
	for n, c := range decl {
		if c != 1 {
			t.Errorf("%s is declared %d times", n, c)
		}
	}
	for _, m := range s.Messages {
		raw := messageRaw(m.Name)
		for _, n := range []string{messageClass(m.Name), decoderName(raw), visitorName(raw), toJSONName(raw), fromJSONName(raw), benchOpName(raw)} {
			if decl[n] != 1 {
				t.Errorf("message %s: %s is declared %d times, want once", m.Name, n, decl[n])
			}
		}
	}
	for _, key := range s.NamedOrder {
		if decl[(&gen{schema: s}).typeName(key)] != 1 {
			t.Errorf("type %s: its class is not declared exactly once", key)
		}
	}
}
