package golang

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// projectFiles scaffolds a buildable Go module with an encode/decode JSON
// harness (PLAN §9.1). The harness uses stdlib encoding/json — the generated
// structs carry json tags with the canonical schema field names — so no JSON
// codegen is needed beyond the struct tags.
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any) []generator.File {
	modPath := cfgString(cfg, "module_path", "example.com/generated")
	goVersion := cfgString(cfg, "go_version", "1.21")
	return []generator.File{
		{Path: "go.mod", Content: []byte(g.goMod(modPath, goVersion))},
		{Path: "harness/main.go", Content: g.harness(s, modPath)},
		{Path: "README.md", Content: []byte(g.readme(s))},
	}
}

func (g *gen) goMod(modPath, goVersion string) string {
	return fmt.Sprintf(`// @generated by sofabgen
module %s

go %s

require %s v0.0.0

replace %s => %s
`, modPath, goVersion, corelibImport, corelibImport, "${SOFAB_GO_CORELIB}")
}

func (g *gen) readme(s *ir.Schema) string {
	var b strings.Builder
	b.WriteString("# Generated SofaBuffers Go module\n\n")
	b.WriteString("`@generated by sofabgen`. Encode/decode harness over `corelib-go`.\n\n")
	b.WriteString("```sh\n# point the replace at a corelib-go checkout, then:\n")
	b.WriteString("go run ./harness encode <Message> < in.json   # JSON -> bytes\n")
	b.WriteString("go run ./harness decode <Message> < bytes.bin # bytes -> JSON\n```\n")
	return b.String()
}

// emitBench emits the Callgrind workload entry points (tests/bench, ARCHITECTURE
// §15). Each run_<workload> performs EXACTLY ONE op and is //go:noinline, so
//
//	valgrind --tool=callgrind --collect-atstart=no --toggle-collect=main.run_<workload>
//
// collects that single op and nothing else — process start, JSON parsing and the
// decode input's pre-encode all happen before collection is toggled on. Same shape
// as corelib-go/bench/run_callgrind.sh, which toggles on the same mangled name.
//
// noinline is on the wrapper only, so Encode/Decode and the corelib inline into it
// as usual — that inlining is the cost being measured.
//
// Each op is preceded by an uncollected warmup_<workload>, and that is not
// optional. Go is AOT-compiled, so there is no JIT to tier up — but the runtime
// still builds interface tables and resolves type/name offsets LAZILY on first
// use, and the allocator touches each size class for the first time. `toggle`
// collects exactly one op, which is the first one, so without a warmup all of
// that one-time cost is charged to the op. Measured on the bench schema, it was
// 18k Ir (32%) of decode and 5.5k Ir (22%) of encode — enough that making codegen
// more interface-heavy read as a 44% decode regression while steady-state per-op
// work had actually got cheaper. One warmup op was believed to suffice: every one
// of those costs is a global cache filled on first touch, never a per-op cost that
// decays — checked at 1/2/3/5/10 warmups, which landed within 95 Ir (0.25%) of each
// other with no trend, i.e. below the 0.3% at which results.txt calls a value moved.
//
// That belief did not survive being measured properly, and no warmup COUNT fixes
// what it missed. 53 runs of the `go` row on an unchanged tree read encode as either
// 18625 or 20468 — 9.1% apart, the low value on ~13% of runs (#494). The 1843 Ir
// between the two modes is, function for function, one Go allocator slow path:
// mcache.refill -> mcentral.cacheSpan -> mheap.allocSpan/initSpan and their
// bookkeeping. Nothing else moves at all.
//
// It is the buffer Encode() allocates. That buffer is one size class (1037 bytes ->
// class 1152 on the bench schema) and a span of that class holds seven objects, so
// one allocation in seven exhausts the mcache span and the next one refills it.
// Which of the seven the COLLECTED op gets is decided by how many objects of that
// class the process allocated before it, and that is not a constant: probed with
// runtime.MemStats it was 6 on 38 of 40 runs and 8 on the other 2 — a property of the
// runtime's own start-up, not of anything the harness does. At 6 the single warmup
// takes the span's last slot and the op pays the refill; at 8 the op is the third
// object of a fresh span and does not. The addresses say the same thing: the op's
// buffer comes back 1152 bytes after the warmup's (fast) or 533760 bytes away (a
// brand-new span).
//
// A warmup count therefore cannot fix it. The op refills whenever prior+warmups is a
// multiple of seven, and prior takes two values two apart, so whatever the count,
// one of them is unlucky. Measured, by padding that size class before the op to
// stand in for a differently-behaved start-up: at one warmup the slow mode appears
// at pad 0 and 7 (prior 6) and pad 5 (prior 8); at two warmups it does not go away,
// it moves to pad 4 and 6.
//
// benchAlignSpan removes the phase rather than guessing it, and that is the fix: it
// allocates the same size until the allocator hands back an object that is NOT
// adjacent to its predecessor — the first object of a fresh span — so the collected
// op always takes the second slot of one. Over the same pad sweep the reading is
// then 18604 on 27 of 27 runs, and 300 of 300 unpadded runs agree at 18625.
//
// That pins the op to a slot that never pays a refill, so the number is a chosen
// phase, not an average: a steady-state encoder pays one refill per seven ops
// (~1843/7 = ~263 Ir), so the row reads ~1.4% under what encoding in a loop costs.
// Deliberate — results.txt is a diff tool, and a stable baseline is worth more here
// than an amortised one. Recorded in tests/bench/README.md.
//
// Only the encode half is aligned, because only it was measured to need it — and
// only encode is fixed by it. Sampled 300 deep, BOTH go rows still jitter on decode:
// four outliers in 300 on each (~1.3%), unchanged by this code, which never runs in
// the decode branch. An earlier reading of 60100 on 20 of 20 recorded that as zero
// spread; at a 1.3% rate twenty draws miss it 77% of the time, so that was sampling
// depth, not a property of the row.
//
// The alignment is emitted for every message, so `go-unbounded` gets it too — but it
// does not make that row safe, only unchanged. A message with an unbounded field has
// no worst-case size to allocate, so its Encode() grows an output buffer through a
// separate scratch buffer, in a DIFFERENT size class from the one cap(wire) names:
// padding that scratch class still flips the row by 13.9%, aligned or not. It reads
// exactly today (13314 on 300 of 300) because that class happens to sit far from a
// boundary in this runtime, which is luck, not immunity. Worth a follow-up if it ever
// moves; not fixed here, because it is not what was measured to be broken.
//
// The warmup is a separate symbol so --toggle-collect cannot see it, and so is the
// alignment.
func (g *gen) emitBench(f *gofile, s *ir.Schema, pkgAlias string) {
	f.line("// benchAlignSink holds the buffer benchAlignSpan allocated last, so the")
	f.line("// compiler cannot decide the allocation is dead and drop it.")
	f.line("var benchAlignSink []byte")
	f.blank()
	f.line("// benchAlignSpan pins the allocator to a known point in the size class the")
	f.line("// measured op allocates its output from, so that op costs the same in every")
	f.line("// process. Without it a bench row reading one op is bimodal by ~9%%, at random.")
	f.line("//")
	f.line("// Go hands out small objects from a per-P span of one size class, and a span")
	f.line("// holds a handful of them -- seven, say, in the 1152-byte class a 1037-byte")
	f.line("// buffer falls in. Whichever allocation lands on the last slot of a span")
	f.line("// makes the NEXT one refill the span from mcentral -- ~1843 Ir of allocator")
	f.line("// slow path. Which slot the collected op gets depends on how many objects of")
	f.line("// that class the runtime's own start-up already took, which varies per")
	f.line("// process, so a fixed number of warmups cannot settle it: it only moves the")
	f.line("// unlucky phase somewhere else.")
	f.line("//")
	f.line("// So this does not guess the phase, it removes it. Allocating the same size")
	f.line("// repeatedly walks the span one object at a time -- successive addresses are")
	f.line("// exactly one size class apart -- until the allocator hands back one that is")
	f.line("// NOT adjacent, which is the first object of a fresh span. Returning there")
	f.line("// leaves the collected op holding the second slot of that span, in every")
	f.line("// process. sample is the warmup's own output, so the size class is the one")
	f.line("// the op actually uses and no message constant has to be threaded in here.")
	f.line("//")
	f.line("// noinline and a separate symbol, like the warmups: --toggle-collect keys on")
	f.line("// entering a symbol, so anything the measured op must not be charged for has")
	f.line("// to happen outside run_*.")
	f.line("//go:noinline")
	f.line("func benchAlignSpan(sample []byte) {")
	f.line("\tn := cap(sample)")
	f.line("\tif n == 0 {")
	f.line("\t\treturn")
	f.line("\t}")
	f.line("\tat := func() uintptr {")
	f.line("\t\tb := make([]byte, n)")
	f.line("\t\tbenchAlignSink = b")
	f.line("\t\treturn reflect.ValueOf(b).Pointer()")
	f.line("\t}")
	f.line("\t// The stride is the size class, which is not n and is not exported by the")
	f.line("\t// runtime -- so learn it: inside a span every step is the stride, so the")
	f.line("\t// most common step over a short run is it, whatever the class turns out")
	f.line("\t// to be and whichever probe straddled a span boundary.")
	f.line("\tconst probes = 32")
	f.line("\tsteps := make(map[uintptr]int, probes)")
	f.line("\tprev := at()")
	f.line("\tstride, seen := uintptr(0), 0")
	f.line("\tfor i := 0; i < probes; i++ {")
	f.line("\t\tp := at()")
	f.line("\t\td := p - prev")
	f.line("\t\tprev = p")
	f.line("\t\tsteps[d]++")
	f.line("\t\tif steps[d] > seen {")
	f.line("\t\t\tstride, seen = d, steps[d]")
	f.line("\t\t}")
	f.line("\t}")
	f.line("\t// Bounded: a span cannot hold more objects than it has bytes, and a run")
	f.line("\t// that somehow never sees a boundary must still end.")
	f.line("\tfor i := 0; i < 1<<12; i++ {")
	f.line("\t\tp := at()")
	f.line("\t\tif p-prev != stride {")
	f.line("\t\t\treturn")
	f.line("\t\t}")
	f.line("\t\tprev = p")
	f.line("\t}")
	f.line("\t// Falling out means no span boundary was found, so the op runs at an")
	f.line("\t// arbitrary phase and the row is bimodal again. Say so rather than")
	f.line("\t// returning quietly: a silent no-op here is invisible in results.txt.")
	f.line("\tfmt.Fprintln(os.Stderr, \"benchAlignSpan: no span boundary in 4096 allocations; this reading is not phase-pinned\")")
	f.line("}")
	f.blank()
	f.line("// Bench state at package scope: the results outlive the measured call so")
	f.line("// main can observe them after collection stops, which is what keeps the op")
	f.line("// from being optimized away. See tests/bench/README.md.")
	for _, m := range s.Messages {
		typeName, base, low := msgIdent(m), msgBase(m), workload(m)
		f.line("var bench%sIn *%s.%s", base, pkgAlias, typeName)
		f.line("var bench%sWire []byte", base)
		f.line("var bench%sOut *%s.%s", base, pkgAlias, typeName)
		f.blank()
		f.line("//go:noinline")
		f.line("func run_encode_%s() {", low)
		f.line("\tb, err := bench%sIn.Encode()", base)
		f.line("\tif err != nil {")
		f.line("\t\tfail(err)")
		f.line("\t}")
		f.line("\tbench%sWire = b", base)
		f.line("}")
		f.blank()
		f.line("//go:noinline")
		f.line("func run_decode_%s() {", low)
		f.line("\tobj, err := %s.%s__Decode(bench%sWire)", pkgAlias, base, base)
		f.line("\tif err != nil {")
		f.line("\t\tfail(err)")
		f.line("\t}")
		f.line("\tbench%sOut = obj", base)
		f.line("}")
		f.blank()
		f.line("// warmup_* pay the runtime's one-time costs (lazy itabs, type/name")
		f.line("// offsets, first-touch allocator spans) so the collected op does not.")
		f.line("// The body is DUPLICATED rather than delegating to run_*: toggling is")
		f.line("// keyed on entering the symbol, whoever the caller is, so a warmup that")
		f.line("// called run_* would be collected right along with the real op.")
		f.line("//go:noinline")
		f.line("func warmup_encode_%s() {", low)
		f.line("\tb, err := bench%sIn.Encode()", base)
		f.line("\tif err != nil {")
		f.line("\t\tfail(err)")
		f.line("\t}")
		f.line("\tbench%sWire = b", base)
		f.line("}")
		f.blank()
		f.line("//go:noinline")
		f.line("func warmup_decode_%s() {", low)
		f.line("\tobj, err := %s.%s__Decode(bench%sWire)", pkgAlias, base, base)
		f.line("\tif err != nil {")
		f.line("\t\tfail(err)")
		f.line("\t}")
		f.line("\tbench%sOut = obj", base)
		f.line("}")
		f.blank()
	}

	f.line("// benchMain runs one op of <workload>. Everything here is setup, warmup and")
	f.line("// observation; only the run_* call is collected.")
	f.line("func benchMain(w string, in []byte) int {")
	for _, m := range s.Messages {
		base, low := msgBase(m), workload(m)
		f.line("\tif w == \"encode_%s\" || w == \"decode_%s\" {", low, low)
		f.line("\t\tbench%sIn = %s.%s__New()", base, pkgAlias, base)
		f.line("\t\tif err := json.Unmarshal(in, bench%sIn); err != nil {", base)
		f.line("\t\t\tfail(err)")
		f.line("\t\t}")
		f.line("\t\tif w == \"encode_%s\" {", low)
		f.line("\t\t\twarmup_encode_%s() // one-time runtime costs (not collected)", low)
		f.line("\t\t\tbenchAlignSpan(bench%sWire) // known allocator phase (not collected)", base)
		f.line("\t\t\trun_encode_%s()", low)
		f.line("\t\t} else {")
		f.line("\t\t\twarmup_encode_%s() // setup: the decode input (not collected)", low)
		f.line("\t\t\twarmup_decode_%s() // one-time runtime costs (not collected)", low)
		f.line("\t\t\trun_decode_%s()", low)
		f.line("\t\t}")
		f.line("\t\tvar sink uint64")
		f.line("\t\tfor _, c := range bench%sWire {", base)
		f.line("\t\t\tsink = sink*31 + uint64(c)")
		f.line("\t\t}")
		f.line("\t\tif bench%sOut != nil {", base)
		f.line("\t\t\tj, _ := json.Marshal(bench%sOut)", base)
		f.line("\t\t\tsink += uint64(len(j))")
		f.line("\t\t}")
		f.line("\t\tfmt.Fprintf(os.Stderr, \"sink=%%d BYTES=%%d\\n\", sink, len(bench%sWire))", base)
		f.line("\t\tfmt.Fprintf(os.Stderr, \"wire_hex=%%s\\n\", hex.EncodeToString(bench%sWire))", base)
		f.line("\t\treturn 0")
		f.line("\t}")
	}
	f.line("\tfmt.Fprintf(os.Stderr, \"unknown workload: %%s\\n\", w)")
	f.line("\treturn 2")
	f.line("}")
	f.blank()
}

// harness emits the uniform encode/decode JSON CLI for the Go module.
func (g *gen) harness(s *ir.Schema, modPath string) []byte {
	f := newGoFile("main")
	// A schema of shared types alone ($defs, no message) has no message to
	// encode, decode or bench: the harness then reads none of the generated
	// package, JSON or hex, and Go refuses an unused import outright.
	hasMsg := len(s.Messages) > 0
	if hasMsg {
		f.imp("bytes")
		f.imp("encoding/hex")
		f.imp("encoding/json")
		f.imp("errors")
		f.imp(corelibImport)
		f.imp("math")
		f.imp("strings")
	}
	f.imp("fmt")
	f.imp("io")
	f.imp("os")
	f.imp("reflect")
	f.imp("strconv")
	if hasMsg {
		f.imp(modPath + "/" + g.pkg)
	}

	pkgAlias := g.pkg
	g.emitBench(f, s, pkgAlias)
	f.line("func main() {")
	f.line("\tif len(os.Args) < 2 {")
	f.line("\t\tfmt.Fprintln(os.Stderr, \"usage: harness <encode|decode|streamdecode|streamencode|bench> [Message|workload]\")")
	f.line("\t\tos.Exit(2)")
	f.line("\t}")
	f.line("\tmode := os.Args[1]")
	f.line("\tmsg := %q", defaultMessage(s))
	f.line("\tif len(os.Args) > 2 {")
	f.line("\t\tmsg = os.Args[2]")
	f.line("\t}")
	f.line("\tin, _ := io.ReadAll(os.Stdin)")
	f.line("\t// `bench <workload>` takes a workload, not a message name.")
	f.line("\tif mode == \"bench\" {")
	f.line("\t\tw := \"\"")
	f.line("\t\tif len(os.Args) > 2 {")
	f.line("\t\t\tw = os.Args[2]")
	f.line("\t\t}")
	f.line("\t\tos.Exit(benchMain(w, in))")
	f.line("\t}")
	f.line("\tswitch msg {")
	for _, m := range s.Messages {
		base := msgBase(m)
		f.line("\tcase %q:", m.Name)
		f.line("\t\tif mode == \"encode\" {")
		f.line("\t\t\tobj := %s.%s__New()", pkgAlias, base)
		f.line("\t\t\tif err := unmarshalJSON(in, obj); err != nil {")
		f.line("\t\t\t\tfail(err)")
		f.line("\t\t\t}")
		f.line("\t\t\tb, err := obj.Encode()")
		f.line("\t\t\tif err != nil {")
		f.line("\t\t\t\tfail(err)")
		f.line("\t\t\t}")
		f.line("\t\t\tos.Stdout.Write(b)")
		f.line("\t\t} else if mode == \"decode\" {")
		f.line("\t\t\tobj, err := %s.%s__Decode(in)", pkgAlias, base)
		f.line("\t\t\tif err != nil {")
		f.line("\t\t\t\tfail(err)")
		f.line("\t\t\t}")
		f.line("\t\t\tout, _ := marshalJSON(obj)")
		f.line("\t\t\tos.Stdout.Write(out)")
		f.line("\t\t\tfmt.Fprintln(os.Stdout)")
		// The same bytes through the reader-driven entry point (§5.6). Fed a byte
		// at a time on purpose: a reader that hands over the whole message in one
		// Read would exercise AcceptStream without ever making it suspend and
		// resume, which is the half that can actually be wrong.
		// The chunk size is an argument, default 1; 0 hands over the whole
		// message in one Read. tests/conformance/lib/check_chunk_invariance.py
		// sweeps it.
		f.line("\t\t} else if mode == \"streamdecode\" {")
		f.line("\t\t\tobj, err := %s.%s__DecodeFrom(&dripReader{b: in, n: chunkArg()})", pkgAlias, base)
		f.line("\t\t\tif err != nil {")
		// A refusal is terminal (CORELIB_PLAN §5.2, §6.3), and Go has no finish():
		// asking again is an empty Feed on the same decoder. The refused decode is
		// replayed on a decoder this harness owns, because DecodeFrom does not hand
		// its decoder back, and the second answer is printed as `[finish=X]` for
		// tests/conformance/lib/check_terminal_refusal.py.
		f.line("\t\t\t\td := sofab.NewDecoder(%s.%s__New())", pkgAlias, base)
		f.line("\t\t\t\td.FeedFrom(&dripReader{b: in, n: chunkArg()}, make([]byte, 4096))")
		f.line("\t\t\t\t_, again := d.Feed(nil)")
		f.line("\t\t\t\tfail(fmt.Errorf(\"%%v [finish=%%s]\", err, verdictName(again)))")
		f.line("\t\t\t}")
		f.line("\t\t\tout, _ := marshalJSON(obj)")
		f.line("\t\t\tos.Stdout.Write(out)")
		f.line("\t\t\tfmt.Fprintln(os.Stdout)")
		// The encode twin of streamdecode: the same message through a sink, drained
		// into a buffer the harness owns. Window 0 is the generated EncodeTo with its
		// own scratch; any other window is a scratch of that size (raised to the
		// corelib's floor) driven through Serialize, so a drain lands on every kind of
		// boundary. tests/conformance/lib/check_stream_encode.py sweeps it.
		f.line("\t\t} else if mode == \"streamencode\" {")
		f.line("\t\t\tobj := %s.%s__New()", pkgAlias, base)
		f.line("\t\t\tif err := unmarshalJSON(in, obj); err != nil {")
		f.line("\t\t\t\tfail(err)")
		f.line("\t\t\t}")
		f.line("\t\t\tvar out bytes.Buffer")
		f.line("\t\t\tif w := windowArg(); w == 0 {")
		f.line("\t\t\t\tif err := obj.EncodeTo(&out); err != nil {")
		f.line("\t\t\t\t\tfail(err)")
		f.line("\t\t\t\t}")
		f.line("\t\t\t} else {")
		f.line("\t\t\t\tif w < sofab.MinOutputBuffer {")
		f.line("\t\t\t\t\tw = sofab.MinOutputBuffer")
		f.line("\t\t\t\t}")
		f.line("\t\t\t\te, err := sofab.NewEncoderSink(make([]byte, w), 0, func(_ *sofab.Encoder, b []byte) error {")
		f.line("\t\t\t\t\tout.Write(b)")
		f.line("\t\t\t\t\treturn nil")
		f.line("\t\t\t\t})")
		f.line("\t\t\t\tif err != nil {")
		f.line("\t\t\t\t\tfail(err)")
		f.line("\t\t\t\t}")
		f.line("\t\t\t\tobj.Serialize(e)")
		f.line("\t\t\t\tif err := e.Flush(); err != nil {")
		f.line("\t\t\t\t\tfail(err)")
		f.line("\t\t\t\t}")
		f.line("\t\t\t}")
		f.line("\t\t\tos.Stdout.Write(out.Bytes())")
		f.line("\t\t} else {")
		f.line("\t\t\tfail(fmt.Errorf(\"unknown mode %%q\", mode))")
		f.line("\t\t}")
	}
	f.line("\tdefault:")
	f.line("\t\tfail(fmt.Errorf(\"unknown message %%q\", msg))")
	f.line("\t}")
	f.line("}")
	f.blank()
	if hasMsg {
		f.line("// verdictName names the category a decoder answered with, `none` when it")
		f.line("// answered nothing -- which, after a refusal, is itself the failure.")
		f.line("func verdictName(err error) string {")
		f.line("\tswitch {")
		f.line("\tcase err == nil:")
		f.line("\t\treturn \"none\"")
		f.line("\tcase errors.Is(err, sofab.ErrLimitExceeded):")
		f.line("\t\treturn \"LimitExceeded\"")
		f.line("\tcase errors.Is(err, sofab.ErrInvalidMsg):")
		f.line("\t\treturn \"InvalidMessage\"")
		f.line("\t}")
		f.line("\treturn err.Error()")
		f.line("}")
		f.blank()
	}
	if hasMsg {
		g.emitInfSpelling(f)
	}
	f.line("func fail(err error) {")
	f.line("\tfmt.Fprintln(os.Stderr, \"error:\", err)")
	f.line("\tos.Exit(1)")
	f.line("}")
	f.blank()
	f.line("// chunkArg is `streamdecode`'s optional third argument: the bytes per Read,")
	f.line("// 1 by default, 0 for the whole message in one Read.")
	f.line("func chunkArg() int {")
	f.line("\tif len(os.Args) > 3 {")
	f.line("\t\tn, err := strconv.Atoi(os.Args[3])")
	f.line("\t\tif err != nil || n < 0 {")
	f.line("\t\t\tfail(fmt.Errorf(\"bad chunk size %%q\", os.Args[3]))")
	f.line("\t\t}")
	f.line("\t\treturn n")
	f.line("\t}")
	f.line("\treturn 1")
	f.line("}")
	f.blank()
	f.line("// windowArg is `streamencode`'s third argument: the encode buffer size in")
	f.line("// bytes, 0 for the generated EncodeTo with its own scratch.")
	f.line("func windowArg() int {")
	f.line("\tif len(os.Args) > 3 {")
	f.line("\t\tn, err := strconv.Atoi(os.Args[3])")
	f.line("\t\tif err != nil || n < 0 {")
	f.line("\t\t\tfail(fmt.Errorf(\"bad window size %%q\", os.Args[3]))")
	f.line("\t\t}")
	f.line("\t\treturn n")
	f.line("\t}")
	f.line("\treturn 0")
	f.line("}")
	f.blank()
	f.line("// dripReader delivers at most n bytes per Read (one by default), so")
	f.line("// `streamdecode` drives the decoder across a boundary at every single")
	f.line("// position in the message. A bytes.Reader would hand the whole thing over")
	f.line("// in one Read and prove only that the signature compiles. n == 0 delivers")
	f.line("// everything at once.")
	f.line("type dripReader struct {")
	f.line("\tb []byte")
	f.line("\ti int")
	f.line("\tn int")
	f.line("}")
	f.blank()
	f.line("func (r *dripReader) Read(p []byte) (int, error) {")
	f.line("\tif r.i >= len(r.b) {")
	f.line("\t\treturn 0, io.EOF")
	f.line("\t}")
	f.line("\tif len(p) == 0 {")
	f.line("\t\treturn 0, nil")
	f.line("\t}")
	f.line("\tn := r.n")
	f.line("\tif n == 0 {")
	f.line("\t\tn = len(r.b)")
	f.line("\t}")
	f.line("\tif n > len(p) {")
	f.line("\t\tn = len(p)")
	f.line("\t}")
	f.line("\tn = copy(p[:n], r.b[r.i:])")
	f.line("\tr.i += n")
	f.line("\treturn n, nil")
	f.line("}")
	return g.render(f, "harness/main.go")
}

// workload is a message's part of its bench workload names (encode_<w>,
// decode_<w>) and of the harness functions run_encode_<w>, warmup_decode_<w>,
// ...: the name lower-cased, which is what tests/bench/rows.json spells. It is
// injective: two names that lower-case alike fold alike, and messages have
// distinct folds (the naming rules). The bench variables are
// bench<M>In/Wire/Out over the message's Pascal name, equally distinct.
func workload(m *ir.Message) string { return strings.ToLower(m.Name) }

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

// emitInfSpelling emits marshalJSON and unmarshalJSON, the harness's JSON front door (harness-only
// scaffolding, never part of emit: sources; see ARCHITECTURE §8 emit modes). It is
// json.Unmarshal plus the one spelling encoding/json has no number for: the
// strings "inf" and "-inf" at a float position, which is how the shared vector
// file writes an infinite float and how the encode driver passes it on
// (tests/conformance/lib/check_vectors_encode.py). The strings are located by
// walking the parsed tree against the destination's type, so a string FIELD
// holding the text "inf" is left alone, and the infinities are set after the
// rest of the message has been unmarshalled.
func (g *gen) emitInfSpelling(f *gofile) {
	for _, l := range []string{
		"// infAt is a position the input spelled in a way encoding/json cannot carry: a float",
		"// written \"inf\" or \"-inf\", or a string written with \\xNN escapes for bytes that",
		"// are not UTF-8 (raw is then those bytes).",
		"type infAt struct {",
		"\tpath []any // map keys (string) and slice indexes (int) from the root",
		"\tneg  bool",
		"\traw  *string",
		"}",
		"",
		"func jsonName(sf reflect.StructField) string {",
		"\tname, _, _ := strings.Cut(sf.Tag.Get(\"json\"), \",\")",
		"\treturn name",
		"}",
		"",
		"// scrubInf replaces each infinity spelling at a float position of type t with",
		"// 0 and records where it was.",
		"func scrubInf(v any, t reflect.Type, path []any, out *[]infAt) any {",
		"\tfor t.Kind() == reflect.Pointer {",
		"\t\tt = t.Elem()",
		"\t}",
		"\tswitch x := v.(type) {",
		"\tcase map[string]any:",
		"\t\tif t.Kind() != reflect.Struct {",
		"\t\t\treturn v",
		"\t\t}",
		"\t\tfor i := 0; i < t.NumField(); i++ {",
		"\t\t\tname := jsonName(t.Field(i))",
		"\t\t\tif e, ok := x[name]; ok && name != \"\" {",
		"\t\t\t\tx[name] = scrubInf(e, t.Field(i).Type, append(append([]any{}, path...), name), out)",
		"\t\t\t}",
		"\t\t}",
		"\tcase []any:",
		"\t\tif t.Kind() != reflect.Slice && t.Kind() != reflect.Array {",
		"\t\t\treturn v",
		"\t\t}",
		"\t\tfor i, e := range x {",
		"\t\t\tx[i] = scrubInf(e, t.Elem(), append(append([]any{}, path...), i), out)",
		"\t\t}",
		"\tcase string:",
		"\t\tif t.Kind() == reflect.String {",
		"\t\t\tvar raw strings.Builder",
		"\t\t\thas := false",
		"\t\t\tfor _, r := range x {",
		"\t\t\t\tif r >= 0xF700 && r <= 0xF7FF {",
		"\t\t\t\t\traw.WriteByte(byte(r - 0xF700))",
		"\t\t\t\t\thas = true",
		"\t\t\t\t} else {",
		"\t\t\t\t\traw.WriteRune(r)",
		"\t\t\t\t}",
		"\t\t\t}",
		"\t\t\tif has {",
		"\t\t\t\ts := raw.String()",
		"\t\t\t\t*out = append(*out, infAt{path: path, raw: &s})",
		"\t\t\t\treturn \"\"",
		"\t\t\t}",
		"\t\t}",
		"\t\tif (x == \"inf\" || x == \"-inf\") && (t.Kind() == reflect.Float32 || t.Kind() == reflect.Float64) {",
		"\t\t\t*out = append(*out, infAt{path: path, neg: x == \"-inf\"})",
		"\t\t\treturn json.Number(\"0\")",
		"\t\t}",
		"\t}",
		"\treturn v",
		"}",
		"",
		"// jsonTree is the value as encoding/json would render it, except that a float",
		"// with no JSON number (an infinity, a NaN) becomes the string \"inf\", \"-inf\"",
		"// or \"nan\". Only marshalJSON uses it, when json.Marshal has refused.",
		"func jsonTree(v reflect.Value) any {",
		"\tswitch v.Kind() {",
		"\tcase reflect.Pointer, reflect.Interface:",
		"\t\tif v.IsNil() {",
		"\t\t\treturn nil",
		"\t\t}",
		"\t\treturn jsonTree(v.Elem())",
		"\tcase reflect.Struct:",
		"\t\tm := map[string]any{}",
		"\t\tfor i := 0; i < v.NumField(); i++ {",
		"\t\t\tif name := jsonName(v.Type().Field(i)); name != \"\" && name != \"-\" {",
		"\t\t\t\tm[name] = jsonTree(v.Field(i))",
		"\t\t\t}",
		"\t\t}",
		"\t\treturn m",
		"\tcase reflect.Slice, reflect.Array:",
		"\t\tif v.Kind() == reflect.Slice && v.IsNil() {",
		"\t\t\treturn nil",
		"\t\t}",
		"\t\tif v.Type().Elem().Kind() == reflect.Uint8 {",
		"\t\t\treturn v.Interface()",
		"\t\t}",
		"\t\tout := make([]any, v.Len())",
		"\t\tfor i := range out {",
		"\t\t\tout[i] = jsonTree(v.Index(i))",
		"\t\t}",
		"\t\treturn out",
		"\tcase reflect.Float32, reflect.Float64:",
		"\t\tf := v.Float()",
		"\t\tswitch {",
		"\t\tcase math.IsNaN(f):",
		"\t\t\treturn \"nan\"",
		"\t\tcase math.IsInf(f, 1):",
		"\t\t\treturn \"inf\"",
		"\t\tcase math.IsInf(f, -1):",
		"\t\t\treturn \"-inf\"",
		"\t\t}",
		"\t\tbits := 64",
		"\t\tif v.Kind() == reflect.Float32 {",
		"\t\t\tbits = 32",
		"\t\t}",
		"\t\treturn json.Number(strconv.FormatFloat(f, 'g', -1, bits))",
		"\t}",
		"\treturn v.Interface()",
		"}",
		"",
		"// marshalJSON is json.Marshal plus the output half of the infinity spelling:",
		"// the same strings unmarshalJSON reads, so a decoded +-inf can be printed.",
		"func marshalJSON(obj any) ([]byte, error) {",
		"\tout, err := json.Marshal(obj)",
		"\tif err == nil {",
		"\t\treturn out, nil",
		"\t}",
		"\treturn json.Marshal(jsonTree(reflect.ValueOf(obj)))",
		"}",
		"",
		"// byteEscapes rewrites each \\xNN in the input, which JSON has no such escape for, to",
		"// \\uF7NN so the text still parses; scrubInf turns those back into the bytes.",
		"func byteEscapes(in []byte) []byte {",
		"\tvar out []byte",
		"\tfor i := 0; i < len(in); i++ {",
		"\t\tswitch {",
		"\t\tcase in[i] == '\\\\' && i+1 < len(in) && in[i+1] == '\\\\':",
		"\t\t\tout = append(out, '\\\\', '\\\\')",
		"\t\t\ti++",
		"\t\tcase in[i] == '\\\\' && i+3 < len(in) && in[i+1] == 'x':",
		"\t\t\tout = append(out, '\\\\', 'u', 'F', '7', in[i+2], in[i+3])",
		"\t\t\ti += 3",
		"\t\tdefault:",
		"\t\t\tout = append(out, in[i])",
		"\t\t}",
		"\t}",
		"\treturn out",
		"}",
		"",
		"func unmarshalJSON(in []byte, obj any) error {",
		"\tin = byteEscapes(in)",
		"\tdec := json.NewDecoder(bytes.NewReader(in))",
		"\tdec.UseNumber() // keeps a 64-bit integer exact while the tree is rewritten",
		"\tvar tree any",
		"\tif err := dec.Decode(&tree); err != nil {",
		"\t\treturn json.Unmarshal(in, obj)",
		"\t}",
		"\tvar infs []infAt",
		"\ttree = scrubInf(tree, reflect.TypeOf(obj), nil, &infs)",
		"\tclean, err := json.Marshal(tree)",
		"\tif err != nil {",
		"\t\treturn err",
		"\t}",
		"\tif err := json.Unmarshal(clean, obj); err != nil {",
		"\t\treturn err",
		"\t}",
		"\tfor _, at := range infs {",
		"\t\trv := reflect.ValueOf(obj)",
		"\t\tfor _, p := range at.path {",
		"\t\t\tfor rv.Kind() == reflect.Pointer {",
		"\t\t\t\trv = rv.Elem()",
		"\t\t\t}",
		"\t\t\tswitch k := p.(type) {",
		"\t\t\tcase string:",
		"\t\t\t\tfor i := 0; i < rv.NumField(); i++ {",
		"\t\t\t\t\tif jsonName(rv.Type().Field(i)) == k {",
		"\t\t\t\t\t\trv = rv.Field(i)",
		"\t\t\t\t\t\tbreak",
		"\t\t\t\t\t}",
		"\t\t\t\t}",
		"\t\t\tcase int:",
		"\t\t\t\trv = rv.Index(k)",
		"\t\t\t}",
		"\t\t}",
		"\t\tif at.raw != nil {",
		"\t\t\trv.SetString(*at.raw)",
		"\t\t\tcontinue",
		"\t\t}",
		"\t\tsign := 1",
		"\t\tif at.neg {",
		"\t\t\tsign = -1",
		"\t\t}",
		"\t\trv.SetFloat(math.Inf(sign))",
		"\t}",
		"\treturn nil",
		"}",
		"",
	} {
		f.line("%s", l)
	}
}
