// Code generated by sofabgen; DO NOT EDIT.
#![allow(dead_code, unused_variables, unused_imports, non_camel_case_types, clippy::all)]
use sofab::{OStream, IStream, Visitor, Id, Unsigned, Signed};
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Scalars {
    pub u8min: u8,
    pub u8max: u8,
    pub u64max: u64,
    pub i8min: i8,
    pub i64min: i64,
    pub f32: f32,
    pub f64: f64,
    pub flag: bool,
}

impl Default for Scalars {
    fn default() -> Self {
        Self {
            u8min: 0,
            u8max: 255,
            u64max: 18446744073709551615,
            i8min: -128,
            i64min: i64::MIN,
            f32: 3.14,
            f64: -2.5,
            flag: true,
        }
    }
}

impl Scalars {
    pub const MAX_SIZE: usize = 82;
    pub fn marshal(&self, os: &mut OStream) {
        if self.u8min != 0 { let _ = os.write_unsigned(0, self.u8min as Unsigned); }
        if self.u8max != 255 { let _ = os.write_unsigned(1, self.u8max as Unsigned); }
        if self.u64max != 18446744073709551615 { let _ = os.write_unsigned(2, self.u64max as Unsigned); }
        if self.i8min != -128 { let _ = os.write_signed(3, self.i8min as Signed); }
        if self.i64min != i64::MIN { let _ = os.write_signed(4, self.i64min as Signed); }
        if self.f32 != 3.14 { let _ = os.write_fp32(5, self.f32); }
        if self.f64 != -2.5 { let _ = os.write_fp64(6, self.f64); }
        if self.flag != true { let _ = os.write_boolean(7, self.flag); }
    }
    pub fn encode(&self) -> Vec<u8> {
        let mut buf = vec![0u8; Self::MAX_SIZE];
        let used = { let mut os = OStream::new(&mut buf); self.marshal(&mut os); os.bytes_used() };
        buf.truncate(used);
        buf
    }
    pub fn decode(data: &[u8]) -> Self {
        scalars_dec::decode(data)
    }
    pub fn try_decode(data: &[u8]) -> Result<Self, sofab::Error> {
        scalars_dec::try_decode(data)
    }
}

mod scalars_dec {
    use super::*;
    use sofab::{IStream, Visitor, Id, Unsigned, Signed};

    pub fn decode(data: &[u8]) -> Scalars {
        let mut m = Scalars::default();
        {
            let mut v = V { m: &mut m, stack: Vec::new(), cur: _Loc::Root, acc: Vec::new(), ai: 0 };
            let mut is = IStream::new();
            let _ = is.feed(data, &mut v);
        }
        m
    }

    pub fn try_decode(data: &[u8]) -> Result<Scalars, sofab::Error> {
        let mut m = Scalars::default();
        {
            let mut v = V { m: &mut m, stack: Vec::new(), cur: _Loc::Root, acc: Vec::new(), ai: 0 };
            let mut is = IStream::new();
            is.feed(data, &mut v)?;
        }
        Ok(m)
    }

#[derive(Clone, Copy, PartialEq)]
enum _Loc {
    Root,
}

struct V<'a> {
    m: &'a mut Scalars,
    stack: Vec<_Loc>,
    cur: _Loc,
    acc: Vec<u8>,
    ai: usize, // index into the fixed native array currently being filled
}

impl<'a> Visitor for V<'a> {
    fn unsigned(&mut self, id: Id, value: Unsigned) {
        match (self.cur, id) {
            (_Loc::Root, 0) => self.m.u8min = value as u8,
            (_Loc::Root, 1) => self.m.u8max = value as u8,
            (_Loc::Root, 2) => self.m.u64max = value as u64,
            (_Loc::Root, 7) => self.m.flag = value != 0,
            _ => {}
        }
    }
    fn signed(&mut self, id: Id, value: Signed) {
        match (self.cur, id) {
            (_Loc::Root, 3) => self.m.i8min = value as i8,
            (_Loc::Root, 4) => self.m.i64min = value as i64,
            _ => {}
        }
    }
    fn fp32(&mut self, id: Id, value: f32) {
        match (self.cur, id) {
            (_Loc::Root, 5) => self.m.f32 = value,
            _ => {}
        }
    }
    fn fp64(&mut self, id: Id, value: f64) {
        match (self.cur, id) {
            (_Loc::Root, 6) => self.m.f64 = value,
            _ => {}
        }
    }
}
}

