// Code generated by sofabgen; DO NOT EDIT.
#![allow(dead_code, unused_variables, unused_imports, non_camel_case_types, clippy::all)]
use sofab::{OStream, IStream, Visitor, Id, Unsigned, Signed};
use serde::{Serialize, Deserialize};

/// Why a whole-buffer decode was refused: the error half of a message's
/// `try_decode` and of `Decoder::finish`.
///
/// `sofab::Error` has no INCOMPLETE variant on purpose: running out of
/// bytes mid-field is an outcome rather than a failure, so `IStream::feed`
/// hands it back as `Ok(Status::Incomplete)` -- only the caller's framing
/// can say whether more bytes are still coming. The two entry points above
/// ARE that framing, so for them a trailing INCOMPLETE is truncation. It
/// stays distinct from `InvalidMsg`: a truncated message is unfinished,
/// not malformed, and more bytes would complete it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecodeError {
    /// The bytes ended inside a field, or with a sequence still open, and
    /// there are no more: `Status::Incomplete` where that is final.
    Incomplete,
    /// Whatever the decode itself refused, in the corelib's own vocabulary:
    /// malformed bytes, a receiver-side cap (S6.2.1/S6.3), an overflowed
    /// fixed-capacity field.
    Sofab(sofab::Error),
}

impl From<sofab::Error> for DecodeError {
    fn from(e: sofab::Error) -> Self { DecodeError::Sofab(e) }
}

impl core::fmt::Display for DecodeError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            DecodeError::Incomplete => f.write_str("incomplete message"),
            DecodeError::Sofab(e) => write!(f, "{:?}", e),
        }
    }
}

impl std::error::Error for DecodeError {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct Scalars {
    pub u8min: u8,
    pub u8max: u8,
    pub u64max: u64,
    pub i8min: i8,
    pub i64min: i64,
    pub f32: f32,
    pub f64: f64,
    pub flag: bool,
}

impl Default for Scalars {
    fn default() -> Self {
        Self {
            u8min: 0,
            u8max: 255,
            u64max: 18446744073709551615,
            i8min: -128,
            i64min: i64::MIN,
            f32: 3.14,
            f64: -2.5,
            flag: true,
        }
    }
}

impl Scalars {
    /// Worst-case encoded size of this message, derived from the schema.
    pub const MAX_SIZE: usize = 49;
    pub fn serialize<_F: sofab::Flush>(&self, os: &mut OStream<'_, _F>) {
        if self.u8min != 0 { let _ = os.write_unsigned(0, self.u8min as Unsigned); }
        if self.u8max != 255 { let _ = os.write_unsigned(1, self.u8max as Unsigned); }
        if self.u64max != 18446744073709551615 { let _ = os.write_unsigned(2, self.u64max as Unsigned); }
        if self.i8min != -128 { let _ = os.write_signed(3, self.i8min as Signed); }
        if self.i64min != i64::MIN { let _ = os.write_signed(4, self.i64min as Signed); }
        if self.f32 != 3.14 { let _ = os.write_fp32(5, self.f32); }
        if self.f64 != -2.5 { let _ = os.write_fp64(6, self.f64); }
        if self.flag != true { let _ = os.write_boolean(7, self.flag); }
    }
    pub fn encode(&self) -> Vec<u8> {
        let mut buf = vec![0u8; Self::MAX_SIZE];
        let used = { let mut os = OStream::new(&mut buf); self.serialize(&mut os); os.bytes_used() };
        buf.truncate(used);
        buf
    }
    pub fn decode(data: &[u8]) -> Self {
        scalars_dec::decode(data)
    }
    /// Decode a whole buffer, surfacing the accept/reject verdict --
    /// a truncated tail included, which is `DecodeError::Incomplete` and
    /// not a half-filled value.
    pub fn try_decode(data: &[u8]) -> Result<Self, DecodeError> {
        scalars_dec::try_decode(data)
    }
    /// An incremental decoder for this message: hold it and feed chunks as
    /// they arrive, instead of buffering the whole message first.
    pub fn decoder() -> ScalarsDecoder {
        ScalarsDecoder::new()
    }
}

pub use scalars_dec::Decoder as ScalarsDecoder;
mod scalars_dec {
    use super::*;
    use sofab::{IStream, Visitor, Id, Unsigned, Signed, ArrayKind};

    pub fn decode(data: &[u8]) -> Scalars {
        let mut m = Scalars::default();
        {
            let mut v = V { m: &mut m, stack: Vec::new(), cur: _Loc::Root, dead: 0, err: false, inv: false, askip: 0 };
            let mut is = IStream::new();
            let _ = is.feed(data, &mut v);
        }
        m
    }

    pub fn try_decode(data: &[u8]) -> Result<Scalars, DecodeError> {
        let mut m = Scalars::default();
        let overflow;
        let invalid;
        let fed;
        {
            let mut v = V { m: &mut m, stack: Vec::new(), cur: _Loc::Root, dead: 0, err: false, inv: false, askip: 0 };
            let mut is = IStream::new();
            fed = is.feed(data, &mut v);
            overflow = v.err;
            invalid = v.inv;
        }
        // A scalar array carried more elements than its schema `count`, an
        // invalid-UTF-8 string, an over-length string/blob, or an over-index
        // wrapper element: INVALID, and it dominates a truncated tail (S5.2).
        if invalid { return Err(DecodeError::Sofab(sofab::Error::InvalidMsg)); }
        // Nothing refused above: now surface feed's own verdict. A structural
        // InvalidMsg rides `?`; Status::Incomplete does NOT -- the corelib leaves
        // the end-of-input judgement to the caller (S5.2.4) because only the
        // caller's framing knows whether more bytes come, and this entry point IS
        // that framing: it was handed the whole buffer, so an Incomplete here is
        // a truncated message and is rejected, not returned half-filled (S7).
        if fed? == sofab::Status::Incomplete { return Err(DecodeError::Incomplete); }
        // A fixed-capacity field overflowed during the fill:
        // report it rather than return a silently-truncated value.
        if overflow { return Err(DecodeError::Sofab(sofab::Error::BufferFull)); }
        Ok(m)
    }

    /// Incremental decoder: hold one and feed the message as bytes arrive.
    ///
    /// The wire format has no end marker at the top level -- a message ends
    /// where its bytes end -- so `feed` cannot tell you the message is
    /// complete, and does not try to. Its verdict is about the bytes handed
    /// in, and it is a `Status`, not an error: `Status::Complete` means they
    /// ended on a clean field boundary (the message COULD end here),
    /// `Status::Incomplete` means they ended mid-field. Neither is a failure
    /// mid-stream, which is why both live in the success arm (S5.2.1). The
    /// caller's own framing -- a length prefix, a datagram boundary, a closed
    /// socket -- decides when to stop; `finish` then gives the verdict for the
    /// message as a whole, and is the only place a trailing `Status::Incomplete`
    /// becomes the rejection `DecodeError::Incomplete`.
    ///
    /// Every `Err` from `feed` is terminal: discard the decoder.
    pub struct Decoder {
        m: Scalars,
        is: IStream,
        stack: Vec<_Loc>,
        cur: _Loc,
        dead: u16,
        err: bool,
        inv: bool,
        askip: usize,
    }

    impl Decoder {
        pub fn new() -> Self {
            Self { m: Scalars::default(), is: IStream::new(), stack: Vec::new(), cur: _Loc::Root, dead: 0, err: false, inv: false, askip: 0 }
        }

        /// Feed the next chunk. `Ok(Status::Complete)` if it ended on a field
        /// boundary, `Ok(Status::Incomplete)` if it ended mid-field -- see the
        /// type docs: neither answers whether the MESSAGE is done, only whether
        /// these bytes were. `Err` is a refusal, and it is terminal.
        pub fn feed(&mut self, chunk: &[u8]) -> Result<sofab::Status, sofab::Error> {
            let fed = {
                let mut v = V { m: &mut self.m, stack: core::mem::take(&mut self.stack), cur: self.cur, dead: self.dead, err: self.err, inv: self.inv, askip: self.askip };
                let r = self.is.feed(chunk, &mut v);
                // `..` covers `m`, ending its borrow before the write-back.
                let V { stack, cur, dead, err, inv, askip, .. } = v;
                self.stack = stack;
                self.cur = cur;
                self.dead = dead;
                self.err = err;
                self.inv = inv;
                self.askip = askip;
                r
            };
            // INVALID dominates a truncated tail (S5.2), so it is reported
            // ahead of feed's own Incomplete verdict.
            if self.inv { return Err(sofab::Error::InvalidMsg); }
            fed
        }

        /// Take the decoded message once the caller's framing says the input
        /// is over. Applies the same checks as try_decode, including that the
        /// stream actually ended at a clean boundary -- a truncated message
        /// must be rejected, not returned half-filled.
        pub fn finish(mut self) -> Result<Scalars, DecodeError> {
            if self.inv { return Err(DecodeError::Sofab(sofab::Error::InvalidMsg)); }
            // An empty chunk probes end-of-input without supplying any: Complete
            // only when nothing is half-read. The caller's framing has said the
            // input is over, so an Incomplete here is truncation -- rejected,
            // never handed back as a silently partial value (S7).
            if self.feed(&[])? == sofab::Status::Incomplete {
                return Err(DecodeError::Incomplete);
            }
            if self.err { return Err(DecodeError::Sofab(sofab::Error::BufferFull)); }
            Ok(self.m)
        }
    }

    impl Default for Decoder {
        fn default() -> Self { Self::new() }
    }

#[derive(Clone, Copy, PartialEq)]
enum _Loc {
    Root,
    Dead,
}

struct V<'a> {
    m: &'a mut Scalars,
    stack: Vec<_Loc>,
    cur: _Loc,
    dead: u16, // depth of the skipped subtree cur sits in (see sequence_begin)
    err: bool,
    inv: bool,
    askip: usize, // elements left to discard from a wire-type-contradictory array
}

impl<'a> Visitor for V<'a> {
    fn unsigned(&mut self, id: Id, value: Unsigned) {
        if self.askip > 0 { self.askip -= 1; return; } // array delivered at a scalar id
        match (self.cur, id) {
            (_Loc::Root, 0) => { if value > 255 { self.inv = true; return; } self.m.u8min = value as u8 },
            (_Loc::Root, 1) => { if value > 255 { self.inv = true; return; } self.m.u8max = value as u8 },
            (_Loc::Root, 2) => { self.m.u64max = value as u64 },
            (_Loc::Root, 7) => self.m.flag = value != 0,
            _ => {}
        }
    }
    fn signed(&mut self, id: Id, value: Signed) {
        if self.askip > 0 { self.askip -= 1; return; } // array delivered at a scalar id
        match (self.cur, id) {
            (_Loc::Root, 3) => { if value < -128 || value > 127 { self.inv = true; return; } self.m.i8min = value as i8 },
            (_Loc::Root, 4) => { self.m.i64min = value as i64 },
            _ => {}
        }
    }
    fn fp32(&mut self, id: Id, value: f32) {
        if self.askip > 0 { self.askip -= 1; return; } // array delivered at a scalar id
        match (self.cur, id) {
            (_Loc::Root, 5) => self.m.f32 = value,
            _ => {}
        }
    }
    fn fp64(&mut self, id: Id, value: f64) {
        if self.askip > 0 { self.askip -= 1; return; } // array delivered at a scalar id
        match (self.cur, id) {
            (_Loc::Root, 6) => self.m.f64 = value,
            _ => {}
        }
    }
    fn array_begin(&mut self, id: Id, kind: ArrayKind, count: usize) {
        self.askip = match kind {
            ArrayKind::Unsigned => match (self.cur, id) {
                _ => count,
            },
            ArrayKind::Signed => match (self.cur, id) {
                _ => count,
            },
            _ => count,
        };
        match (kind, self.cur, id) {
            _ => {}
        }
    }
    fn sequence_begin(&mut self, _id: Id) {
        // Inside a skipped subtree: count the level and stay Dead.
        if self.cur == _Loc::Dead { self.dead = self.dead.saturating_add(1); return; }
        self.stack.push(self.cur);
        self.cur = _Loc::Dead;
    }
    fn sequence_end(&mut self) {
        // Closing a level of a skipped subtree: nothing was stacked for it.
        if self.dead > 0 { self.dead -= 1; return; }
        self.cur = self.stack.pop().unwrap_or(_Loc::Root);
    }
}
}

