// Code generated by sofabgen; DO NOT EDIT.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <span>
#include <cstring>
#include <cstddef>
#include "sofab/sofab.hpp"

static_assert(sofab::API_VERSION == 1,
    "SofaBuffers: generated against C++ API v1, but the linked corelib differs.");

namespace message {

#ifndef SOFABUFFERS_GEN_PRELUDE
#define SOFABUFFERS_GEN_PRELUDE
struct _StrSeq : sofab::IStreamMessage {
    std::vector<std::string> &out;
    long _cap;
    explicit _StrSeq(std::vector<std::string> &o, long cap = -1) : out(o), _cap(cap) {}
    void deserialize(sofab::IStreamImpl &is, sofab::id id, std::size_t, std::size_t) noexcept override {
        if (_cap >= 0 && static_cast<std::size_t>(id) >= static_cast<std::size_t>(_cap)) { is.invalidate(); return; }
        std::string _s; is.read(_s);
        while (out.size() <= static_cast<std::size_t>(id)) out.emplace_back();
        out[id] = std::move(_s);
    }
};
struct _BlobSeq : sofab::IStreamMessage {
    std::vector<std::vector<std::uint8_t>> &out;
    long _cap;
    explicit _BlobSeq(std::vector<std::vector<std::uint8_t>> &o, long cap = -1) : out(o), _cap(cap) {}
    void deserialize(sofab::IStreamImpl &is, sofab::id id, std::size_t, std::size_t) noexcept override {
        if (_cap >= 0 && static_cast<std::size_t>(id) >= static_cast<std::size_t>(_cap)) { is.invalidate(); return; }
        std::string _s; is.read(_s);
        while (out.size() <= static_cast<std::size_t>(id)) out.emplace_back();
        out[id].assign(_s.begin(), _s.end());
    }
};
template <typename T>
struct _MsgSeq : sofab::IStreamMessage {
    std::vector<T> *out = nullptr;
    // Schema fixed-count bound N (-1 == dynamic/unbounded). An element id >= N is
    // a schema-bound violation (MESSAGE_SPEC S5.1/S7: an index at or past the
    // fixed count is INVALID, never grown-into) - reject before emplacing, which
    // also bounds the allocation against an over-index heap-amplification DoS.
    long cap = -1;
    void deserialize(sofab::IStreamImpl &is, sofab::id id, std::size_t, std::size_t _count) noexcept override {
        if (cap >= 0 && static_cast<std::size_t>(id) >= static_cast<std::size_t>(cap)) { is.invalidate(); return; }
        T &row = out->emplace_back();
        // A count-less native-array row (matrix with dynamic rows) is a std::vector
        // that the corelib's span read fills only up to its current size, so size it
        // to the row's wire count first. Struct/union rows are IStreamMessage
        // (no resize) and fixed std::array rows have no resize(), so both skip this.
        if constexpr (requires { row.resize(_count); } && !std::is_base_of_v<sofab::IStreamMessage, T>) {
            row.resize(_count);
        }
        is.read(row);
    }
};
template <typename C>
std::span<const typename C::value_type> _trimTail(const C &_a) noexcept {
    using _T = typename C::value_type;
    const _T _z{};
    std::size_t _n = _a.size();
    while (_n > 0 && std::memcmp(&_a[_n - 1], &_z, sizeof(_T)) == 0) --_n;
    return std::span<const _T>(_a.data(), _n);
}
#endif

struct Scalars : sofab::OStreamMessage, sofab::IStreamMessage {
    std::uint64_t u64max = 18446744073709551615ULL;
    std::int64_t i64min = -9223372036854775808LL;
    double f64 = -2.5;
    float f32 = 3.14f;
    std::uint8_t u8min = 0;
    std::uint8_t u8max = 255;
    std::int8_t i8min = -128;
    bool flag = true;
    static constexpr std::size_t _maxSize = 82;

    std::vector<std::uint8_t> encode() const {
        sofab::OStreamInline<_maxSize> os;
        serialize(os);
        return std::vector<std::uint8_t>(os.data(), os.data() + os.bytesUsed());
    }
    static Scalars decode(const std::uint8_t *data, std::size_t len) {
        sofab::IStreamObject<Scalars> in;
        in.feed(data, len);
        return *in;
    }

    static sofab::IStreamImpl::Result try_decode(const std::uint8_t *data, std::size_t len, Scalars &out) {
        sofab::IStreamObject<Scalars> in;
        sofab::IStreamImpl::Result r = in.feed(data, len);
        if (r.ok()) { out = *in; }
        return r;
    }

    sofab::OStreamImpl::Result serialize(sofab::OStreamImpl &os) const noexcept override {
        if (u8min != 0) { (void)os.write(0, u8min); }
        if (u8max != 255) { (void)os.write(1, u8max); }
        if (u64max != 18446744073709551615ULL) { (void)os.write(2, u64max); }
        if (i8min != -128) { (void)os.write(3, i8min); }
        if (i64min != -9223372036854775808LL) { (void)os.write(4, i64min); }
        if (f32 != 3.14f) { (void)os.write(5, f32); }
        if (f64 != -2.5) { (void)os.write(6, f64); }
        if (flag != true) { (void)os.write(7, flag); }
        return os.writeIf(0, false, false);
    }

    void deserialize(sofab::IStreamImpl &is, sofab::id id, std::size_t, std::size_t) noexcept override {
        switch (id) {
        case 0:
            is.read(u8min);
            break;
        case 1:
            is.read(u8max);
            break;
        case 2:
            is.read(u64max);
            break;
        case 3:
            is.read(i8min);
            break;
        case 4:
            is.read(i64min);
            break;
        case 5:
            is.read(f32);
            break;
        case 6:
            is.read(f64);
            break;
        case 7:
            is.read(flag);
            break;
        default: break;
        }
    }
};

} // namespace message
