package java

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// projectFiles scaffolds a Maven project with a Gson-based encode/decode JSON
// harness over corelib-java. JSON is parsed with Gson and emitted by hand so
// u64 round-trips exactly (Long.toUnsignedString / parseUnsignedLong).
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any, dir string) []generator.File {
	return []generator.File{
		{Path: "pom.xml", Content: []byte(g.pom())},
		{Path: dir + "Json.java", Content: g.jsonHelper(s)},
		{Path: dir + "Main.java", Content: g.mainHarness(s)},
		{Path: "README.md", Content: []byte("# Generated SofaBuffers Java project\n\n`@generated by sofabgen`. `mvn -q compile exec:java`.\n")},
	}
}

func (g *gen) pom() string {
	return `<!-- @generated by sofabgen -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.sofabuffers</groupId>
  <artifactId>generated</artifactId>
  <version>0.0.0</version>
  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <exec.mainClass>` + g.pkg + `.Main</exec.mainClass>
  </properties>
  <dependencies>
    <dependency><groupId>org.sofabuffers</groupId><artifactId>corelib</artifactId><version>${sofab.version}</version></dependency>
    <dependency><groupId>com.google.code.gson</groupId><artifactId>gson</artifactId><version>2.11.0</version></dependency>
  </dependencies>
  <build>
    <finalName>harness</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <archive><manifest><mainClass>` + g.pkg + `.Main</mainClass></manifest></archive>
          <descriptorRefs><descriptorRef>jar-with-dependencies</descriptorRef></descriptorRefs>
          <appendAssemblyId>false</appendAssemblyId>
        </configuration>
        <executions><execution><phase>package</phase><goals><goal>single</goal></goals></execution></executions>
      </plugin>
    </plugins>
  </build>
</project>
`
}

func (g *gen) mainHarness(s *ir.Schema) []byte {
	f := &jfile{}
	g.header(f)
	f.line("package %s;", g.pkg)
	f.line("import com.google.gson.*;")
	f.line("import java.io.*;")
	f.line("import java.nio.charset.StandardCharsets;")
	f.blank()
	f.line("public class Main {")
	f.line("    public static void main(String[] args) throws Exception {")
	f.line("        String mode = args.length > 0 ? args[0] : \"\";")
	f.line("        String name = args.length > 1 ? args[1] : %q;", defaultMessage(s))
	f.line("        ByteArrayOutputStream bos = new ByteArrayOutputStream();")
	f.line("        byte[] tmp = new byte[8192]; int n; while ((n = System.in.read(tmp)) > 0) bos.write(tmp, 0, n);")
	f.line("        byte[] input = bos.toByteArray();")
	f.line("        switch (name) {")
	for _, m := range s.Messages {
		mt := exported(m.Name)
		f.line("        case %q: {", m.Name)
		f.line("            if (mode.equals(\"encode\")) {")
		f.line("                JsonObject j = JsonParser.parseString(new String(input, StandardCharsets.UTF_8)).getAsJsonObject();")
		f.line("                %s obj = new %s(); Json.from(j, obj);", mt, mt)
		f.line("                System.out.write(obj.encode());")
		f.line("            } else if (mode.equals(\"decode\")) {")
		f.line("                %s obj = %s.decode(input);", mt, mt)
		f.line("                StringBuilder sb = new StringBuilder(); Json.to(obj, sb);")
		f.line("                System.out.write(sb.toString().getBytes(StandardCharsets.UTF_8)); System.out.write('\\n');")
		f.line("            } else { System.err.println(\"unknown mode\"); System.exit(2); }")
		f.line("            break;")
		f.line("        }")
	}
	f.line("        default: System.err.println(\"unknown message\"); System.exit(2);")
	f.line("        }")
	f.line("        System.out.flush();")
	f.line("    }")
	f.line("}")
	return f.bytes()
}

// jsonHelper emits to/from JSON for every object (Gson tree in, hand-written
// out). u64 fields are exact via unsigned string handling.
func (g *gen) jsonHelper(s *ir.Schema) []byte {
	f := &jfile{}
	g.header(f)
	f.line("package %s;", g.pkg)
	f.line("import com.google.gson.*;")
	f.line("import java.util.*;")
	f.blank()
	f.line("final class Json {")

	emitted := map[string]bool{}
	for _, m := range s.Messages {
		for _, key := range g.reachable(m) {
			nt := s.Named[key]
			if (nt.Category == ir.CatStruct || nt.Category == ir.CatUnion) && !emitted[key] {
				emitted[key] = true
				g.emitJSONFns(f, g.typeName(key), nt.Fields)
			}
		}
		g.emitJSONFns(f, exported(m.Name), m.Fields)
	}

	f.line("    static void str(StringBuilder b, String s) {")
	f.line("        b.append('\"');")
	f.line("        for (int i = 0; i < s.length(); i++) { char c = s.charAt(i);")
	f.line("            if (c == '\"' || c == '\\\\') b.append('\\\\').append(c);")
	f.line("            else if (c == '\\n') b.append(\"\\\\n\"); else if (c == '\\t') b.append(\"\\\\t\");")
	f.line("            else if (c < 0x20) b.append(String.format(\"\\\\u%%04x\", (int)c)); else b.append(c); }")
	f.line("        b.append('\"');")
	f.line("    }")
	f.line("    static void bytes(StringBuilder b, byte[] a) {")
	f.line("        b.append('['); for (int i = 0; i < a.length; i++) { if (i>0) b.append(','); b.append(a[i] & 0xFF); } b.append(']');")
	f.line("    }")
	f.line("    static byte[] toBytes(JsonArray a) { byte[] r = new byte[a.size()]; for (int i=0;i<r.length;i++) r[i]=(byte)a.get(i).getAsInt(); return r; }")
	f.line("}")
	return f.bytes()
}

func (g *gen) emitJSONFns(f *jfile, typeName string, fields []*ir.Field) {
	// to
	f.line("    static void to(%s o, StringBuilder b) {", typeName)
	f.line("        b.append('{');")
	for i, fld := range fields {
		if i > 0 {
			f.line("        b.append(',');")
		}
		f.line("        b.append(\"\\\"%s\\\":\");", fld.Name)
		g.emitTo(f, fld)
	}
	f.line("        b.append('}');")
	f.line("    }")
	// from
	f.line("    static void from(JsonObject j, %s o) {", typeName)
	f.line("        JsonElement e;")
	for _, fld := range fields {
		f.line("        e = j.get(%q); if (e != null && !e.isJsonNull()) {", fld.Name)
		g.emitFrom(f, fld)
		f.line("        }")
	}
	f.line("    }")
}

func (g *gen) emitTo(f *jfile, fld *ir.Field) {
	acc := "o." + javaIdent(fld.Name)
	switch fld.Kind {
	case ir.KindU64:
		f.line("        b.append(Long.toUnsignedString(%s));", acc)
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum, ir.KindBitfield:
		f.line("        b.append(%s);", acc)
	case ir.KindBool:
		f.line("        b.append(%s);", acc)
	case ir.KindFP32, ir.KindFP64:
		f.line("        b.append(%s);", acc)
	case ir.KindString:
		f.line("        Json.str(b, %s == null ? \"\" : %s);", acc, acc)
	case ir.KindBlob:
		f.line("        Json.bytes(b, %s == null ? new byte[0] : %s);", acc, acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("        to(%s, b);", acc)
	case ir.KindArray:
		g.emitToArray(f, fld, acc)
	}
}

func (g *gen) emitToArray(f *jfile, fld *ir.Field, acc string) {
	g.jsonToArray(f, "        ", acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0, primitiveArrayElem(fld.Elem))
}

// jsonToArray writes val as a JSON array. u* elements print unsigned; struct/union
// recurse via to(); nested arrays recurse; the rest print via append. Loop vars
// are depth-suffixed to nest safely. prim: val is a primitive array (index via
// [i]/length) rather than a boxed List (get(i)/size()).
func (g *gen) jsonToArray(f *jfile, ind, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int, prim bool) {
	iv := fmt.Sprintf("_i%d", depth)
	el := fmt.Sprintf("%s.get(%s)", val, iv)
	bound := val + ".size()"
	if prim {
		el = fmt.Sprintf("%s[%s]", val, iv)
		bound = val + ".length"
	}
	f.line("%s{ b.append('['); for (int %s = 0; %s < %s; %s++) { if (%s>0) b.append(',');", ind, iv, iv, bound, iv, iv)
	switch elem {
	case ir.KindString:
		f.line("%s    Json.str(b, %s);", ind, el)
	case ir.KindBlob:
		f.line("%s    Json.bytes(b, %s);", ind, el)
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64:
		f.line("%s    b.append(Long.toUnsignedString(%s));", ind, el)
	case ir.KindStruct, ir.KindUnion:
		f.line("%s    to(%s, b);", ind, el)
	case ir.KindArray:
		g.jsonToArray(f, ind+"    ", el, items.Elem, items.ElemRef, items.ElemItems, depth+1, false)
	default: // i*, enum, bitfield, boolean, fp
		f.line("%s    b.append(%s);", ind, el)
	}
	f.line("%s} b.append(']'); }", ind)
}

func (g *gen) emitFrom(f *jfile, fld *ir.Field) {
	acc := "o." + javaIdent(fld.Name)
	switch fld.Kind {
	case ir.KindU64:
		f.line("            %s = Long.parseUnsignedLong(e.getAsString());", acc)
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum, ir.KindBitfield:
		f.line("            %s = e.getAsLong();", acc)
	case ir.KindBool:
		f.line("            %s = e.getAsBoolean();", acc)
	case ir.KindFP32:
		f.line("            %s = e.getAsFloat();", acc)
	case ir.KindFP64:
		f.line("            %s = e.getAsDouble();", acc)
	case ir.KindString:
		f.line("            %s = e.getAsString();", acc)
	case ir.KindBlob:
		f.line("            %s = Json.toBytes(e.getAsJsonArray());", acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("            from(e.getAsJsonObject(), %s);", acc)
	case ir.KindArray:
		g.emitFromArray(f, fld, acc)
	}
}

func (g *gen) emitFromArray(f *jfile, fld *ir.Field, acc string) {
	g.jsonFromArray(f, "            ", acc, "e.getAsJsonArray()", fld.Elem, fld.ElemRef, fld.ElemItems, 0, primitiveArrayElem(fld.Elem))
}

// jsonFromArray rebuilds target from the JsonArray src, mirroring jsonToArray:
// u64 parses from string, struct/union recurse via from(), nested arrays recurse
// into a fresh List; the rest map to the matching Gson accessor. Loop/temporary
// vars are depth-suffixed to nest safely.
func (g *gen) jsonFromArray(f *jfile, ind, target, src string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int, prim bool) {
	if prim {
		// Primitive array: allocate to the JSON array size and fill by index.
		av := fmt.Sprintf("_a%d", depth)
		kv := fmt.Sprintf("_k%d", depth)
		var getter string
		switch elem {
		case ir.KindU64:
			getter = fmt.Sprintf("Long.parseUnsignedLong(%s.get(%s).getAsString())", av, kv)
		case ir.KindFP32:
			getter = fmt.Sprintf("%s.get(%s).getAsFloat()", av, kv)
		case ir.KindFP64:
			getter = fmt.Sprintf("%s.get(%s).getAsDouble()", av, kv)
		default: // u8/u16/u32, i8..i64, enum, bitfield
			getter = fmt.Sprintf("%s.get(%s).getAsLong()", av, kv)
		}
		f.line("%sJsonArray %s = %s; %s = new %s[%s.size()];", ind, av, src, target, primArrayBase(elem), av)
		f.line("%sfor (int %s = 0; %s < %s.length; %s++) %s[%s] = %s;", ind, kv, kv, target, kv, target, kv, getter)
		return
	}
	ev := fmt.Sprintf("_e%d", depth)
	f.line("%s%s.clear(); for (JsonElement %s : %s) {", ind, target, ev, src)
	switch elem {
	case ir.KindString:
		f.line("%s    %s.add(%s.getAsString());", ind, target, ev)
	case ir.KindBlob:
		f.line("%s    %s.add(Json.toBytes(%s.getAsJsonArray()));", ind, target, ev)
	case ir.KindU64:
		f.line("%s    %s.add(Long.parseUnsignedLong(%s.getAsString()));", ind, target, ev)
	case ir.KindBool:
		f.line("%s    %s.add(%s.getAsBoolean());", ind, target, ev)
	case ir.KindFP32:
		f.line("%s    %s.add(%s.getAsFloat());", ind, target, ev)
	case ir.KindFP64:
		f.line("%s    %s.add(%s.getAsDouble());", ind, target, ev)
	case ir.KindStruct, ir.KindUnion:
		v := fmt.Sprintf("_v%d", depth)
		f.line("%s    %s %s = new %s(); from(%s.getAsJsonObject(), %s); %s.add(%s);", ind, g.typeName(ref.Key), v, g.typeName(ref.Key), ev, v, target, v)
	case ir.KindArray:
		v := fmt.Sprintf("_v%d", depth)
		vt := "List<" + g.javaArrayElemType(items.Elem, items.ElemRef, items.ElemItems) + ">"
		f.line("%s    %s %s = new ArrayList<>();", ind, vt, v)
		g.jsonFromArray(f, ind+"    ", v, ev+".getAsJsonArray()", items.Elem, items.ElemRef, items.ElemItems, depth+1, false)
		f.line("%s    %s.add(%s);", ind, target, v)
	default: // u8/u16/u32, i8..i64, enum, bitfield
		f.line("%s    %s.add(%s.getAsLong());", ind, target, ev)
	}
	f.line("%s}", ind)
}

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

var _ = strings.TrimSpace
