package java

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/analysis"
	"github.com/sofa-buffers/generator/internal/ir"
	"github.com/sofa-buffers/generator/internal/model"
	"github.com/sofa-buffers/generator/internal/naming"
	"github.com/sofa-buffers/generator/internal/parser"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/java/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every name on the Java list, sorted.
func reservedNames() []string {
	var names []string
	for _, set := range []map[string]bool{javaKeywords, javaStatics, javaQualifiers} {
		for n := range set {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	return names
}

// reservedTypeNames is every type identifier on javaTypeNames, sorted.
func reservedTypeNames() []string {
	var names []string
	for n := range javaTypeNames {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// reservedYAML is a schema that uses every reserved name as a field of a message,
// of a nested struct, and as an option of a union -- plus the union's own tag
// name `which`, `v`, the parameter name of every union setter, and the one path
// clash a decoder frame name can hit: inner.inner2 beside a field inner_inner2.
// Every type-level name (javaTypeNames) is a message of its own: its class is
// escaped, and its file, visitor and decoder must still build.
func reservedYAML(names []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/java/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/java -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field must compile warning-free and round-trip.\n")
	var fields strings.Builder
	var opts []string
	for i, n := range names {
		fmt.Fprintf(&fields, "      %q: { id: %d, type: u8 }\n", n, i)
		opts = append(opts, fmt.Sprintf("%q: { id: %d, type: u8 }", n, i))
	}
	k := len(names)
	opts = append(opts, fmt.Sprintf("which: { id: %d, type: u8 }", k), fmt.Sprintf("v: { id: %d, type: u8 }", k+1))
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
messages:
  m:
    payload:
%s      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      u:            { id: %d, type: union, oneof: { %s } }
`, fields.String(), k, fields.String(), k, k+1, k+2, strings.Join(opts, ", "))
	for _, n := range reservedTypeNames() {
		fmt.Fprintf(&b, "  %s: { payload: { x: { id: 0, type: u8 } } }\n", n)
	}
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field and nested one
// at a non-default value, and the union holding option `v` -- the one a setter
// without `this.` would assign to its own parameter.
func reservedJSON(names []string) string {
	top := map[string]any{}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	for i, n := range names {
		top[n] = i + 1
		inner[n] = i + 2
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{"v": 9}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite compiles that file warning-free and
// round-trips it (tests/conformance/java/run.sh), so a name added to reserved.go
// is covered once the file is regenerated -- and this test fails until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := reservedNames()
	for path, want := range map[string]string{
		"../../tests/conformance/java/reserved.yaml": reservedYAML(names),
		"../../tests/conformance/java/reserved.json": reservedJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// TestReservedNamesAreMangled: every name on the list is a field with a trailing
// underscore, in the message and the nested struct; a union setter assigns its
// slot through `this.`.
func TestReservedNamesAreMangled(t *testing.T) {
	names := reservedNames()
	files := genJavaFromYAML(t, reservedYAML(names), map[string]any{})
	var all strings.Builder
	for _, c := range files {
		all.WriteString(c)
	}
	for _, n := range names {
		if got := len(regexp.MustCompile(`(?m)^    public long `+regexp.QuoteMeta(n)+`_;$`).FindAllString(all.String(), -1)); got != 2 {
			t.Errorf("field %q is the field %s_ in %d of the 2 classes", n, n, got)
		}
	}
	if !strings.Contains(all.String(), "public void setV(long v) { which = V_ID; this._v = v; }") {
		t.Error("the setter of option `v` does not assign through this._v")
	}
}

// TestReservedTypeNamesAreEscaped: a message spelled like a name on
// javaTypeNames is the class <Name>_ in <Name>_.java, and its visitor is built
// from the unescaped identifier.
func TestReservedTypeNamesAreEscaped(t *testing.T) {
	files := genJavaFromYAML(t, reservedYAML(reservedNames()), map[string]any{})
	for _, n := range reservedTypeNames() {
		src, ok := files["src/main/java/message/"+n+"_.java"]
		if !ok {
			t.Errorf("message %s: no file %s_.java", n, n)
			continue
		}
		for _, want := range []string{"public class " + n + "_ {", "class _" + n + "__Visitor implements Visitor {"} {
			if !strings.Contains(src, want) {
				t.Errorf("%s_.java lacks %q", n, want)
			}
		}
	}
}

// TestMangledFieldCannotMeetAField: the collision checkFieldNames used to
// refuse (`int` mangled onto a field `int_`) is a validator error now -- a name
// never ends with `_` -- so the backend needs no refusal of its own.
func TestMangledFieldCannotMeetAField(t *testing.T) {
	src := "version: 1\nmessages:\n  m:\n    payload:\n      int: { id: 0, type: u8 }\n      int_: { id: 1, type: u8 }\n"
	doc, err := parser.Parse([]byte(src), "c.yaml")
	if err != nil {
		t.Fatal(err)
	}
	resolved, _ := doc.Resolve()
	if errs := parser.Validate(resolved); errs == nil {
		t.Error("a field name ending in `_` must be a validation error")
	}
}

// publicClassBody is the body of a Java file's public top-level class -- the
// region where that class's fields are in scope (its nested classes included,
// a second top-level class in the same file not). Comments and string literals
// are blanked first so their braces and dots do not count.
func publicClassBody(src string) string {
	src = regexp.MustCompile(`(?s)/\*.*?\*/|//[^\n]*|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'`).ReplaceAllString(src, `""`)
	loc := regexp.MustCompile(`(?m)^public (?:final )?class \w+[^{]*\{`).FindStringIndex(src)
	if loc == nil {
		return ""
	}
	depth := 1
	for i := loc[1]; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return src[loc[1]:i]
			}
		}
	}
	return src[loc[1]:]
}

// TestJavaNamesInScope is the drift guard for javaStatics and javaQualifiers:
// over the whole corpus, realworld set and example, every static field a public
// generated class declares and every name its body uses as an expression
// qualifier must be on the list (union option ids `<OPT>_ID` and `_`-prefixed
// names aside, which no schema field can spell). A backend that
// starts writing `Math.max(...)` or declares another static fails here until the
// name is reserved -- instead of shipping a class a field named `Math` breaks.
// Lower-case qualifiers other than package roots are locals and parameters,
// which shadow a field anyway.
func TestJavaNamesInScope(t *testing.T) {
	defs, _ := filepath.Glob("../../tests/matrix/corpus/defs/*.yaml")
	rw, _ := filepath.Glob("../../examples/messages/realworld/*.yaml")
	defs = append(append(defs, rw...), "../../examples/messages/example.yaml",
		"../../tests/conformance/lib/names.yaml", "../../tests/conformance/java/reserved.yaml")
	used := map[string]bool{}
	staticRe := regexp.MustCompile(`\bstatic final [\w<>\[\], ]+? (\w+)\s*[=;]`)
	qualRe := regexp.MustCompile(`(?:^|[^\w.])([A-Za-z_]\w*)\.[A-Za-z_]`)
	optID := regexp.MustCompile(`^[A-Z0-9_]+_ID$`)
	for _, def := range defs {
		doc, err := parser.Load(def) // Load, not Parse: cross_file.yaml refers to ../shared
		if err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		if _, err := doc.Resolve(); err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		s, err := model.Build(doc)
		if err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		if err := analysis.Analyze(s); err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		files, err := (&Backend{}).Generate(s, map[string]any{"emit": "project"})
		if err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		pkgFiles := map[string]string{}
		for _, f := range files {
			// The generated package only: the harness is its own package
			// (message/harness/), where no schema name is in scope.
			rel, ok := strings.CutPrefix(f.Path, "src/main/java/message/")
			if !ok || !strings.HasSuffix(rel, ".java") || strings.Contains(rel, "/") {
				continue
			}
			pkgFiles[f.Path] = string(f.Content)
		}
		checkTypeNames(t, filepath.Base(def), s, pkgFiles, used)
		for path, content := range pkgFiles {
			f := struct{ Path string }{path}
			body := publicClassBody(content)
			for _, m := range staticRe.FindAllStringSubmatch(body, -1) {
				n := m[1]
				if strings.HasPrefix(n, "_") || optID.MatchString(n) || javaStatics[n] {
					continue
				}
				t.Errorf("%s (%s): static field %s is not on javaStatics", f.Path, filepath.Base(def), n)
			}
			for _, m := range qualRe.FindAllStringSubmatch(body, -1) {
				n := m[1]
				if n == "this" || !(n[0] >= 'A' && n[0] <= 'Z' || n == "java" || n == "javax" || n == "org") {
					continue
				}
				if !javaQualifiers[n] {
					t.Errorf("%s (%s): qualifier %s is not on javaQualifiers", f.Path, filepath.Base(def), n)
				}
			}
		}
	}
	// And the other way round: a list entry the backend no longer emits is stale.
	var src strings.Builder
	for _, name := range []string{"backend.go", "helpers.go", "union.go", "visitor.go"} {
		b, err := os.ReadFile(name)
		if err != nil {
			t.Fatal(err)
		}
		src.Write(b)
	}
	for n := range javaTypeNames {
		if !used[n] && !regexp.MustCompile(`\b`+n+`\b`).MatchString(src.String()) {
			t.Errorf("javaTypeNames lists %s, which the backend no longer emits", n)
		}
	}
}

// checkTypeNames is the type-level drift guard: every simple capitalised name a
// generated file of the package uses -- as a type, an annotation, a qualifier,
// a nested class -- is either a class the schema generated or on javaTypeNames.
// A name that is neither is one a schema type could take and so shadow (a class
// of the package hides java.lang and the on-demand imports alike), and a nested
// class hides a schema type of its name inside the message. Constants
// (ALL_CAPS), `_`-led generated names, and the schema's own field names are not
// type names.
func checkTypeNames(t *testing.T, def string, s *ir.Schema, files map[string]string, used map[string]bool) {
	t.Helper()
	blank := regexp.MustCompile(`(?s)/\*.*?\*/|//[^\n]*|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'`)
	header := regexp.MustCompile(`(?m)^(?:package|import) [^;]*;`)
	topClass := regexp.MustCompile(`(?m)^(?:public |final |abstract )*class (\w+)`)
	nestedClass := regexp.MustCompile(`(?m)^[ \t]+(?:public |private |static |final )*class (\w+)`)
	token := regexp.MustCompile(`(?:^|[^\w.])([A-Z]\w*)`)
	allCaps := regexp.MustCompile(`^[A-Z][A-Z0-9_]*$`)
	fieldNames := map[string]bool{}
	addFields := func(fs []*ir.Field) {
		for _, f := range fs {
			fieldNames[javaIdent(f.Name)] = true
		}
	}
	for _, m := range s.Messages {
		addFields(m.Fields)
	}
	for _, nt := range s.Named {
		addFields(nt.Fields)
	}
	generated := map[string]bool{}
	bodies := map[string]string{}
	for path, content := range files {
		body := header.ReplaceAllString(blank.ReplaceAllString(content, `""`), "")
		bodies[path] = body
		for _, m := range topClass.FindAllStringSubmatch(body, -1) {
			generated[m[1]] = true
		}
	}
	for path, body := range bodies {
		for _, m := range nestedClass.FindAllStringSubmatch(body, -1) {
			used[m[1]] = true
			if _, ok := javaTypeNames[m[1]]; !ok {
				t.Errorf("%s (%s): nested class %s is not on javaTypeNames", path, def, m[1])
			}
		}
		for _, m := range token.FindAllStringSubmatch(body, -1) {
			n := m[1]
			if generated[n] || allCaps.MatchString(n) || fieldNames[n] {
				continue
			}
			used[n] = true
			if _, ok := javaTypeNames[n]; !ok {
				t.Errorf("%s (%s): the generated code uses %s unqualified, which is not on javaTypeNames", path, def, n)
			}
		}
	}
}

// TestFrameNamesAreDistinct: decoder frames are named by the schema path joined
// with `_` and looked up by name, so the path inner.inner2 and a field
// inner_inner2 must be two frames -- sharing one, the decoder stored the field
// inner_inner2 into inner.inner2 without an error.
func TestFrameNamesAreDistinct(t *testing.T) {
	src := "version: 1\n$defs:\n  struct:\n    B: { x: { id: 0, type: u8 } }\n    A: { b: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/B' } } }\n" +
		"messages:\n  m:\n    payload:\n      a: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/A' } }\n      a_b: { id: 1, type: struct, fields: { $ref: '#/$defs/struct/B' } }\n"
	doc, err := parser.Parse([]byte(src), "f.yaml")
	if err != nil {
		t.Fatal(err)
	}
	s, err := model.Build(doc)
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.Analyze(s); err != nil {
		t.Fatal(err)
	}
	g := &gen{schema: s}
	seen := map[string]bool{}
	for _, fr := range g.frames(s.Messages[0]) {
		if seen[fr.loc] {
			t.Errorf("two decoder frames are both named %s", fr.loc)
		}
		seen[fr.loc] = true
	}
	if !seen["Root_a_b"] || !seen["Root_a__b"] {
		t.Errorf("want frames Root_a_b and Root_a__b, got %v", seen)
	}
}

// TestNamesSchemaDeclaresEachClassOnce generates the shared name-collision
// schema (tests/conformance/lib/names.yaml, ARCHITECTURE §8 "Naming") and checks
// the guarantee without a toolchain: every top-level class -- message, $defs
// type, inline and split-variant type, visitor, harness -- is declared exactly
// once in its package, every public class sits in the file of its own name, and
// no two files are one on a case-insensitive filesystem.
func TestNamesSchemaDeclaresEachClassOnce(t *testing.T) {
	src, err := os.ReadFile("../../tests/conformance/lib/names.yaml")
	if err != nil {
		t.Fatal(err)
	}
	decl := regexp.MustCompile(`(?m)^((?:public )?)(?:final )?class (\w+)`)
	for _, emit := range []string{"sources", "project"} {
		files := genJavaFromYAML(t, string(src), map[string]any{"emit": emit})
		seen := map[string]string{}
		folded := map[string]string{}
		for path, content := range files {
			k := strings.ToLower(path)
			if prev, dup := folded[k]; dup {
				t.Errorf("%s: %s and %s are one file on a case-insensitive filesystem", emit, prev, path)
			}
			folded[k] = path
			if !strings.HasSuffix(path, ".java") {
				continue
			}
			for _, m := range decl.FindAllStringSubmatch(content, -1) {
				q := filepath.Dir(path) + "." + m[2]
				if prev, dup := seen[q]; dup {
					t.Errorf("%s: class %s is declared in %s and %s", emit, q, prev, path)
				}
				seen[q] = path
				if m[1] != "" && filepath.Base(path) != m[2]+".java" {
					t.Errorf("%s: public class %s is in %s", emit, m[2], path)
				}
			}
		}
		// The spelling of each channel, one example each.
		for _, c := range []struct{ file, want string }{
			{"M_A.java", "public class M_A {"},                    // inline struct m.a
			{"MA.java", "public class MA {"},                      // message m_a
			{"M_Decoder.java", "public class M_Decoder {"},        // inline path spelled like a role
			{"M_Arr.java", "public class M_Arr {"},                // array element: the field's own path
			{"M_ArrElem.java", "public class M_ArrElem {"},        // the old suffix, now a plain path
			{"Shape__DefaultPt.java", "class Shape__DefaultPt {"}, // split variant
			{"Shape__DefaultNum.java", "class Shape__DefaultNum {"},
			{"ShapeDefault_Pt.java", "class ShapeDefault_Pt {"},
			{"ShapeDefaultPt.java", "class ShapeDefaultPt {"},
			{"Point.java", "class Point {"},                      // $defs struct: no category prefix
			{"StructPoint.java", "class StructPoint {"},          // message struct_point
			{"M.java", "class _M__Visitor implements Visitor {"}, // private visitor
			{"MVisitor.java", "public class MVisitor {"},         // message m_visitor
			{"Decoder_.java", "public class Decoder_ {"},         // escaped: the nested Decoder
			{"String_.java", "public class String_ {"},           // escaped: java.lang
			{"Seq_.java", "public class Seq_ {"},                 // escaped: corelib
			{"Con_.java", "public class Con_ {"},                 // escaped: Windows device names
			{"Nul_.java", "public class Nul_ {"},
			{"Com1_.java", "public class Com1_ {"},
			{"Json.java", "public class Json {"}, // no longer the harness's
			{"Main.java", "public class Main {"},
			{"harness/Json.java", "final class Json {"},
			{"harness/Main.java", "public class Main {"},
		} {
			if emit == "sources" && strings.HasPrefix(c.file, "harness/") {
				continue
			}
			if got := files["src/main/java/message/"+c.file]; !strings.Contains(got, c.want) {
				t.Errorf("%s: %s lacks %q", emit, c.file, c.want)
			}
		}
	}
}

// deviceYAML has messages and a $defs type spelled like Windows device names
// (naming.IsDeviceStem), one referring to another, so both the declaring and
// the referring side of the escape are seen.
const deviceYAML = `version: 1
$defs:
  struct:
    nul: { x: { id: 0, type: u8 } }
messages:
  con:
    payload:
      a: { id: 0, type: struct, fields: { b: { id: 0, type: u8 } } }
      n: { id: 1, type: struct, fields: { $ref: '#/$defs/struct/nul' } }
  aux: { payload: { x: { id: 0, type: u8 } } }
  com_1: { payload: { x: { id: 0, type: u8 } } }
  LPT9: { payload: { x: { id: 0, type: u8 } } }
  console: { payload: { x: { id: 0, type: u8 } } }
`

// TestDeviceTypeNamesAreEscaped: a type spelled like a Windows device name is
// the class <Name>_ in <Name>_.java -- Con.java, Nul.java, Com1.java cannot
// exist there -- while a longer name (Console) and a path below an escaped type
// (Con_A) are kept, and the visitor is built from the unescaped identifier.
func TestDeviceTypeNamesAreEscaped(t *testing.T) {
	for _, emit := range []string{"sources", "project"} {
		files := genJavaFromYAML(t, deviceYAML, map[string]any{"emit": emit})
		const dir = "src/main/java/message/"
		for _, c := range []struct{ file, want string }{
			{"Con_.java", "public class Con_ {"},
			{"Con_.java", "class _Con__Visitor implements Visitor {"},
			{"Con_.java", "public Nul_ n"},
			{"Aux_.java", "public class Aux_ {"},
			{"Com1_.java", "public class Com1_ {"},
			{"LPT9_.java", "public class LPT9_ {"},
			{"Nul_.java", "public class Nul_ {"},
			{"Con_A.java", "public class Con_A {"},
			{"Console.java", "public class Console {"},
		} {
			src, ok := files[dir+c.file]
			if !ok {
				t.Errorf("%s: no file %s", emit, c.file)
				continue
			}
			if !strings.Contains(src, c.want) {
				t.Errorf("%s: %s lacks %q", emit, c.file, c.want)
			}
		}
		for path := range files {
			if stem, _, _ := strings.Cut(filepath.Base(path), "."); naming.IsDeviceStem(stem) {
				t.Errorf("%s: %s cannot exist on Windows", emit, path)
			}
		}
	}
}
