// Code generated by sofabgen; DO NOT EDIT.
import { OStream, Cursor, WireType } from "@sofa-buffers/corelib";

export class Scalars {
  u8min: number = 0;
  u8max: number = 255;
  u64max: bigint = 18446744073709551615n;
  i8min: number = -128;
  i64min: bigint = -9223372036854775808n;
  f32: number = 3.14;
  f64: number = -2.5;
  flag: boolean = true;

  marshal(os: OStream): void {
    if (this.u8min !== 0) {
      os.writeUnsigned(0, this.u8min);
    }
    if (this.u8max !== 255) {
      os.writeUnsigned(1, this.u8max);
    }
    if (this.u64max !== 18446744073709551615n) {
      os.writeUnsigned(2, this.u64max);
    }
    if (this.i8min !== -128) {
      os.writeSigned(3, this.i8min);
    }
    if (this.i64min !== -9223372036854775808n) {
      os.writeSigned(4, this.i64min);
    }
    if (this.f32 !== 3.14) {
      os.writeFp32(5, this.f32);
    }
    if (this.f64 !== -2.5) {
      os.writeFp64(6, this.f64);
    }
    if (this.flag !== true) {
      os.writeBoolean(7, this.flag);
    }
  }

  toJSON(): Record<string, unknown> {
    return {
      "u8min": this.u8min,
      "u8max": this.u8max,
      "u64max": this.u64max.toString(),
      "i8min": this.i8min,
      "i64min": this.i64min.toString(),
      "f32": this.f32,
      "f64": this.f64,
      "flag": this.flag,
    };
  }

  static fromJSON(d: Record<string, unknown>): Scalars {
    const o = new Scalars();
    if ("u8min" in d) o.u8min = d["u8min"] as number;
    if ("u8max" in d) o.u8max = d["u8max"] as number;
    if ("u64max" in d) o.u64max = BigInt(d["u64max"] as string | number);
    if ("i8min" in d) o.i8min = d["i8min"] as number;
    if ("i64min" in d) o.i64min = BigInt(d["i64min"] as string | number);
    if ("f32" in d) o.f32 = d["f32"] as number;
    if ("f64" in d) o.f64 = d["f64"] as number;
    if ("flag" in d) o.flag = d["flag"] as boolean;
    return o;
  }

  static decode(bytes: Uint8Array): Scalars {
    return Scalars.decodeFrom(new Cursor(bytes));
  }

  static decodeFrom(c: Cursor): Scalars {
    return Scalars.decodeInto(c, new Scalars());
  }

  // Monomorphic pull decode: one switch(id) reads straight into this type's fields.
  // Decodes into `o` so a re-opened sequence continues its scope.
  static decodeInto(c: Cursor, o: Scalars): Scalars {
    while (c.readHeader()) {
      switch (c.id) {
      case 0: if (c.wire !== WireType.Unsigned) { c.skip(c.wire); break; } o.u8min = Number(c.readUnsigned()); break;
      case 1: if (c.wire !== WireType.Unsigned) { c.skip(c.wire); break; } o.u8max = Number(c.readUnsigned()); break;
      case 2: if (c.wire !== WireType.Unsigned) { c.skip(c.wire); break; } o.u64max = c.readUnsigned() as bigint; break;
      case 3: if (c.wire !== WireType.Signed) { c.skip(c.wire); break; } o.i8min = Number(c.readSigned()); break;
      case 4: if (c.wire !== WireType.Signed) { c.skip(c.wire); break; } o.i64min = c.readSigned() as bigint; break;
      case 5: if (c.wire !== WireType.Fixlen) { c.skip(c.wire); break; } o.f32 = c.readFp32(); break;
      case 6: if (c.wire !== WireType.Fixlen) { c.skip(c.wire); break; } o.f64 = c.readFp64(); break;
      case 7: if (c.wire !== WireType.Unsigned) { c.skip(c.wire); break; } o.flag = Boolean(c.readUnsigned()); break;
      default: c.skip(c.wire); break;
      }
    }
    return o;
  }
}

