// Package cpp is the max-speed C++ backend (PLAN §6.3): header-only output
// against corelib-cpp. Each object is a struct deriving OStreamMessage +
// IStreamMessage with serialize()/deserialize(); nested struct/union decode via
// is.read(child), encode via os.write(id, child). 64-bit-safe; no heap on the
// hot path (OStreamInline<_maxSize>).
//
// The `corelib` config key selects the C++ corelib: "cpp" (default, pure
// corelib-cpp) or "c-cpp" (the C++ wrapper over the C library in corelib-c-cpp).
// Both expose the same sofab:: interface and identical encode output. They
// differ on decode of variable-length fields: corelib-cpp resizes targets for
// you, while the corelib-c-cpp wrapper binds a target by address and fills it
// after the field callback. The "c-cpp" path therefore pre-sizes strings/blobs
// from the field length, reads blobs/sequences via the wrapper's native
// read() overloads, and reads enums into their underlying-typed storage (a
// local temp would dangle under the deferred decoder). The project Makefile for
// "c-cpp" compiles and links corelib-c-cpp's C sources.
package cpp

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for max-speed C++.
type Backend struct{}

func (*Backend) Lang() string { return "cpp" }

// Generate emits one header-only .hpp per message (with its reachable types).
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	clib := cfgString(cfg, "corelib", "cpp") == "c-cpp"
	fixed := cfgString(cfg, "containers", "dynamic") == "fixed"
	// The fixed-capacity (embedded) profile layers on the corelib-c-cpp wrapper:
	// its inline containers rely on the wrapper's deferred, address-stable decode
	// model. It is meaningless (and unsupported) against the pure corelib-cpp.
	if fixed && !clib {
		return nil, fmt.Errorf("cpp: containers: fixed requires corelib: c-cpp (the fixed-capacity embedded profile targets the corelib-c-cpp wrapper)")
	}
	g := &gen{schema: s, ns: cfgString(cfg, "namespace", "message"), banner: cfgString(cfg, "tool_banner", "sofabgen"), license: generator.LicenseID(cfg), clib: clib, fixed: fixed, allowDynamic: cfgBool(cfg, "allow_dynamic", false)}
	if fixed {
		if err := g.checkBounded(s); err != nil {
			return nil, err
		}
	}
	var files []generator.File
	for _, m := range s.Messages {
		files = append(files, generator.File{Path: strings.ToLower(m.Name) + ".hpp", Content: g.header(m)})
	}
	if cfgString(cfg, "emit", "sources") == "project" {
		files = append(files, g.projectFiles(s, cfg)...)
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	ns      string
	banner  string
	license string // SPDX id, "" to omit the header line
	// clib selects the corelib-c-cpp C++ wrapper (corelib: c-cpp) instead of the
	// pure corelib-cpp. The wrapper's read(std::string&) fills the string's
	// existing buffer rather than resizing it, so generated decode must pre-size
	// variable-length fields from the field length the deserialize callback gets.
	clib bool
	// fixed selects the fixed-capacity (embedded) profile (containers: fixed),
	// layered on clib. Blobs become FixedBytes<N> and struct/union/matrix/blob
	// sequence arrays become InlineVector<T,N>, sized from the schema — no heap on
	// the message path. Strings remain std::string (a fixed-string decode overload
	// is blocked on a corelib-c-cpp addition).
	fixed bool
	// allowDynamic keeps a std::vector/std::string fallback for genuinely
	// unbounded fields (string/blob without maxlen, array without count) under the
	// fixed profile; without it such a field is a hard generate-time error.
	allowDynamic bool
}

type hfile struct{ b strings.Builder }

func (f *hfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *hfile) blank()        { f.b.WriteByte('\n') }
func (f *hfile) bytes() []byte { return []byte(f.b.String()) }

func (g *gen) header(m *ir.Message) []byte {
	// reachable named types in post-order (children before parents)
	order := g.reachable(m)

	f := &hfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("// SPDX-License-Identifier: %s", g.license)
	}
	f.line("#pragma once")
	f.line("#include <cstdint>")
	f.line("#include <string>")
	f.line("#include <vector>")
	f.line("#include <array>")
	f.line("#include %q", "sofab/sofab.hpp")
	f.blank()
	f.line("static_assert(sofab::API_VERSION == 1,")
	f.line("    \"SofaBuffers: generated against C++ API v1, but the linked corelib differs.\");")
	f.blank()
	f.line("namespace %s {", g.ns)
	f.blank()
	// Guard the shared decode helpers so multiple generated headers (multi-message
	// builds) can be included in one TU without redefining them.
	// The _MsgSeq struct/union/nested-array sequence decoder is shared by both
	// corelibs. The pure-corelib-cpp path additionally needs the _StrSeq/_BlobSeq
	// string/blob sequence helpers; the corelib-c-cpp wrapper decodes those via
	// native read() overloads instead.
	f.line("#ifndef SOFABUFFERS_GEN_PRELUDE")
	f.line("#define SOFABUFFERS_GEN_PRELUDE")
	if !g.clib {
		f.line("%s", cppPrelude)
	}
	if g.fixed {
		f.line("%s", cppFixedPrelude)
	}
	f.line("%s", cppMsgSeqPrelude)
	f.line("#endif")
	f.blank()

	for _, key := range order {
		nt := g.schema.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfield(f, nt)
		}
	}
	for _, key := range order {
		nt := g.schema.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitStruct(f, g.typeName(key), nt.Summary, nt.Fields, false)
		}
	}
	g.emitStruct(f, exported(m.Name), m.Summary, m.Fields, true)
	f.line("} // namespace %s", g.ns)
	return f.bytes()
}

func (g *gen) emitEnum(f *hfile, nt *ir.NamedType) {
	f.line("enum class %s : %s {", g.typeName(nt.Key), enumBacking(nt))
	for _, c := range nt.Consts {
		f.line("    %s = %d,", exported(c.Name), c.Value)
	}
	f.line("};")
	f.blank()
}

func (g *gen) emitBitfield(f *hfile, nt *ir.NamedType) {
	f.line("enum %s : %s {", g.typeName(nt.Key), bitfieldBacking(nt))
	for _, fl := range nt.Flags {
		f.line("    %s%s = %d,", g.typeName(nt.Key), exported(fl.Name), uint64(1)<<uint(fl.Pos))
	}
	f.line("};")
	f.blank()
}

func (g *gen) emitStruct(f *hfile, name, summary string, fields []*ir.Field, isMessage bool) {
	emitStructDoc(f, summary)
	f.line("struct %s : sofab::OStreamMessage, sofab::IStreamMessage {", name)
	// Declare members widest-first to minimise padding; encode/decode below stay
	// in schema/id order, so the wire bytes are unchanged.
	for _, fld := range ir.SortedForLayout(fields) {
		if doc := fieldDoc(fld); doc != "" {
			f.line("    %s %s = %s;  ///< %s", g.cppType(fld), cppIdent(fld.Name), g.cppDefault(fld), doc)
		} else {
			f.line("    %s %s = %s;", g.cppType(fld), cppIdent(fld.Name), g.cppDefault(fld))
		}
	}
	if isMessage {
		size, _ := g.maxSize(fields)
		f.line("    static constexpr std::size_t _maxSize = %d;", size)
	}
	f.blank()

	// per-message encode()/decode() (members so multiple messages don't clash).
	if isMessage {
		f.line("    std::vector<std::uint8_t> encode() const {")
		f.line("        sofab::OStreamInline<_maxSize> os;")
		f.line("        serialize(os);")
		f.line("        return std::vector<std::uint8_t>(os.data(), os.data() + os.bytesUsed());")
		f.line("    }")
		if g.fixed {
			// Heap-free encode for the embedded profile: serialize into an inline
			// buffer and copy into caller storage. Returns the byte count, or 0 if
			// the output does not fit in cap (bytes are otherwise unchanged).
			f.line("    std::size_t encodeTo(std::uint8_t *dst, std::size_t cap) const noexcept {")
			f.line("        sofab::OStreamInline<_maxSize> os;")
			f.line("        serialize(os);")
			f.line("        std::size_t n = os.bytesUsed();")
			f.line("        if (n > cap) { return 0; }")
			f.line("        for (std::size_t i = 0; i < n; ++i) { dst[i] = os.data()[i]; }")
			f.line("        return n;")
			f.line("    }")
		}
		f.line("    static %s decode(const std::uint8_t *data, std::size_t len) {", name)
		f.line("        sofab::IStreamObject<%s> in;", name)
		f.line("        in.feed(data, len);")
		f.line("        return *in;")
		f.line("    }")
		f.blank()
	}

	// serialize: each write is a statement (Result is non-assignable, used only
	// for chaining); return a no-op writeIf so the signature is satisfied.
	f.line("    sofab::OStreamImpl::Result serialize(sofab::OStreamImpl &os) const noexcept override {")
	for _, fld := range fields {
		g.emitSerialize(f, fld)
	}
	// No-op write purely to return a Result; bool is never feature-gated (avoid a
	// 64-bit literal so the body compiles under SOFAB_DISABLE_INT64_SUPPORT).
	f.line("        return os.writeIf(0, false, false);")
	f.line("    }")
	f.blank()

	// deserialize: unhandled ids are auto-skipped by the driver (no-op default).
	// In clib mode the field length (_size) pre-sizes variable-length targets.
	sizeParam := "std::size_t"
	if g.clib {
		sizeParam = "std::size_t _size"
	}
	f.line("    void deserialize(sofab::IStreamImpl &is, sofab::id id, %s, std::size_t) noexcept override {", sizeParam)
	f.line("        switch (id) {")
	for _, fld := range fields {
		f.line("        case %d:", fld.ID)
		g.emitDeserialize(f, fld)
		f.line("            break;")
	}
	f.line("        default: break;")
	f.line("        }")
	f.line("    }")
	f.line("};")
	f.blank()
}

// emitStructDoc writes a Doxygen @brief block before a struct, when the summary
// is non-empty. Single-line summaries become a one-line /** @brief ... */;
// multi-line summaries expand to a starred block, one comment line per source
// line. UTF-8 passes through byte-for-byte.
func emitStructDoc(f *hfile, summary string) {
	if summary == "" {
		return
	}
	// Neutralise a comment terminator so a summary containing "*/" cannot close
	// the /** ... */ block early (the trailing member ///< form is a line comment
	// and needs no such guard).
	summary = strings.ReplaceAll(summary, "*/", "* /")
	lines := strings.Split(summary, "\n")
	if len(lines) == 1 {
		f.line("/** @brief %s */", lines[0])
		return
	}
	f.line("/**")
	f.line(" * @brief %s", lines[0])
	for _, ln := range lines[1:] {
		f.line(" * %s", ln)
	}
	f.line(" */")
}

// fieldDoc builds the trailing member-doc text from a field's Description and
// Unit. Multi-line descriptions collapse to one line (joined with spaces) since
// a trailing ///< comment cannot span lines. Returns "" when both are empty.
func fieldDoc(fld *ir.Field) string {
	desc := strings.Join(strings.Split(fld.Description, "\n"), " ")
	switch {
	case desc != "" && fld.Unit != "":
		return fmt.Sprintf("%s (unit: %s)", desc, fld.Unit)
	case desc != "":
		return desc
	case fld.Unit != "":
		return fmt.Sprintf("(unit: %s)", fld.Unit)
	default:
		return ""
	}
}

func (g *gen) emitSerialize(f *hfile, fld *ir.Field) {
	acc := cppIdent(fld.Name)
	var write string
	switch fld.Kind {
	// Write each integer at its natural width (not a forced 64-bit cast): the
	// varint output is value-based so the bytes are identical, and it lets the
	// corelib-c-cpp wrapper compile with SOFAB_DISABLE_INT64_SUPPORT for messages
	// that have no u64/i64 field (a u64/i64 field still requires INT64, correctly).
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64,
		ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		write = fmt.Sprintf("(void)os.write(%d, %s);", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("(void)os.write(%d, %s);", fld.ID, acc)
	case ir.KindFP32, ir.KindFP64:
		write = fmt.Sprintf("(void)os.write(%d, %s);", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("(void)os.write(%d, %s);", fld.ID, acc)
	case ir.KindEnum:
		write = fmt.Sprintf("(void)os.write(%d, static_cast<%s>(%s));", fld.ID, enumBacking(fld.Ref.Target), acc)
	case ir.KindBitfield:
		write = fmt.Sprintf("(void)os.write(%d, %s);", fld.ID, acc)
	case ir.KindBlob:
		// A blob is a leaf: sparse-canonical encoding (MESSAGE_SPEC S2) omits it
		// when it equals its default (empty if none). The decoder reconstructs the
		// omitted blob from the member's construction default.
		f.line("        if (%s != %s%s) { (void)os.write(%d, %s.data(), static_cast<std::int32_t>(%s.size())); }", acc, g.cppType(fld), g.cppDefault(fld), fld.ID, acc, acc)
		return
	case ir.KindStruct, ir.KindUnion:
		// A sequence is ALWAYS framed; its child fields are omitted per-field by the
		// nested serialize. An all-default nested object thus encodes to an empty
		// wrapper sequence, not a dropped field.
		f.line("        (void)os.write(%d, %s);", fld.ID, acc)
		return
	case ir.KindArray:
		g.emitSerializeArray(f, fld, acc)
		return
	}
	// Scalar/string/enum/bitfield leaf: always omit when equal to the default.
	// Sparse encoding is canonical (MESSAGE_SPEC S2); the decoder reconstructs the
	// omitted field from its member construction default.
	f.line("        if (%s != %s) { %s }", acc, g.cppDefault(fld), write)
}

func (g *gen) emitSerializeArray(f *hfile, fld *ir.Field, acc string) {
	// A native scalar array is a leaf: omit the whole field when it equals its
	// default (materialized at construction). A composite/dynamic-element array is
	// a wrapper sequence and is ALWAYS framed (never whole-omitted, no per-element
	// omission).
	if isNativeArrayElem(fld.Elem) {
		def := g.cppArrayContainer(fld.Elem, fld.ElemRef, fld.ElemItems, fld.Count, fld.ElemMaxHas, fld.ElemMax) + g.cppDefault(fld)
		f.line("        if (%s != %s) {", acc, def)
		g.serializeArray(f, "            ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, fld.Count, 0)
		f.line("        }")
		return
	}
	g.serializeArray(f, "        ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, fld.Count, 0)
}

// serializeArray writes an array value as field idExpr, mirroring the Go/Python
// backends: numeric/bitfield elements use the native array wire type directly;
// enum (->signed) and boolean (->0/1 unsigned) are value-converted through a
// temporary native array; string/blob/struct/union/nested-array elements lower
// to a wrapper sequence whose child ids are the 0-based index. Recurses for
// nested arrays, depth-suffixing loop vars to avoid collisions.
func (g *gen) serializeArray(f *hfile, ind, idExpr, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, count int64, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	ev := fmt.Sprintf("_e%d", depth)
	tv := fmt.Sprintf("_t%d", depth)
	switch elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64,
		ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64,
		ir.KindFP32, ir.KindFP64, ir.KindBitfield:
		f.line("%s(void)os.write(%s, %s);", ind, idExpr, val)
	case ir.KindEnum:
		bk := enumBacking(ref.Target)
		f.line("%s{ std::array<%s, %d> %s{}; for (std::size_t %s = 0; %s < %d; ++%s) %s[%s] = static_cast<%s>(%s[%s]); (void)os.write(%s, %s); }",
			ind, bk, count, tv, iv, iv, count, iv, tv, iv, bk, val, iv, idExpr, tv)
	case ir.KindBool:
		f.line("%s{ std::array<std::uint8_t, %d> %s{}; for (std::size_t %s = 0; %s < %d; ++%s) %s[%s] = %s[%s] ? 1 : 0; (void)os.write(%s, %s); }",
			ind, count, tv, iv, iv, count, iv, tv, iv, val, iv, idExpr, tv)
	case ir.KindBlob:
		f.line("%s(void)os.sequenceBegin(%s);", ind, idExpr)
		f.line("%s{ sofab::id %s = 0; for (const auto &%s : %s) { (void)os.write(%s++, %s.data(), static_cast<std::int32_t>(%s.size())); } }", ind, iv, ev, val, iv, ev, ev)
		f.line("%s(void)os.sequenceEnd();", ind)
	case ir.KindString, ir.KindStruct, ir.KindUnion:
		// os.write(index, element): a string writes a fixlen field; a struct/union
		// writes sequenceBegin(index)/serialize/sequenceEnd (per MESSAGE_SPEC).
		f.line("%s(void)os.sequenceBegin(%s);", ind, idExpr)
		f.line("%s{ sofab::id %s = 0; for (const auto &%s : %s) { (void)os.write(%s++, %s); } }", ind, iv, ev, val, iv, ev)
		f.line("%s(void)os.sequenceEnd();", ind)
	case ir.KindArray:
		f.line("%s(void)os.sequenceBegin(%s);", ind, idExpr)
		f.line("%s{ sofab::id %s = 0; for (const auto &%s : %s) {", ind, iv, ev, val)
		g.serializeArray(f, ind+"    ", fmt.Sprintf("%s++", iv), ev, items.Elem, items.ElemRef, items.ElemItems, items.Count, depth+1)
		f.line("%s} }", ind)
		f.line("%s(void)os.sequenceEnd();", ind)
	}
}

func (g *gen) emitDeserialize(f *hfile, fld *ir.Field) {
	acc := cppIdent(fld.Name)
	switch fld.Kind {
	case ir.KindString:
		// corelib-c-cpp's read() fills the existing buffer, so pre-size from the
		// field length; a zero-length string binds no target (read_field asserts
		// varlen > 0), so skip the read and leave it empty. corelib-cpp resizes
		// for us, so an empty string is fine there.
		if g.clib {
			f.line("            %s.assign(_size, '\\0'); if (_size) is.read(%s);", acc, acc)
		} else {
			f.line("            is.read(%s);", acc)
		}
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64,
		ir.KindBool, ir.KindFP32, ir.KindFP64, ir.KindStruct, ir.KindUnion:
		f.line("            is.read(%s);", acc)
	case ir.KindBlob:
		// corelib-c-cpp binds blobs with the BLOB tag via its read(void*, size_t)
		// overload into the address-stable vector buffer; corelib-cpp reads a
		// length-prefixed blob into a std::string.
		if g.fixed && fld.HasMaxlen {
			// FixedBytes: bound the inline buffer's logical length, then bind the
			// stable buffer via the wrapper's read(void*,size_t) blob overload.
			f.line("            %s.set_len(_size); is.read(%s.data(), _size);", acc, acc)
		} else if g.clib {
			f.line("            %s.resize(_size); is.read(%s.data(), _size);", acc, acc)
		} else {
			f.line("            { std::string _t; is.read(_t); %s.assign(_t.begin(), _t.end()); }", acc)
		}
	case ir.KindEnum:
		// corelib-c-cpp's read binds a target by address and fills it after the
		// callback, so a local temp would dangle; read straight into the enum's
		// underlying-typed storage instead. corelib-cpp copies in place, so the
		// temp is safe there.
		if g.clib {
			f.line("            is.read(reinterpret_cast<%s &>(%s));", enumBacking(fld.Ref.Target), acc)
		} else {
			f.line("            { std::int64_t _v = 0; is.read(_v); %s = static_cast<%s>(_v); }", acc, g.typeName(fld.Ref.Key))
		}
	case ir.KindBitfield:
		// The bitfield member is an integral type, so corelib-c-cpp can fill it
		// directly (no dangling temp).
		if g.clib {
			f.line("            is.read(%s);", acc)
		} else {
			f.line("            { std::uint64_t _v = 0; is.read(_v); %s = static_cast<%s>(_v); }", acc, g.cppType(fld))
		}
	case ir.KindArray:
		g.deserializeArray(f, "            ", acc, fld.Elem, fld.ElemRef, fld.ElemItems, fld.Count, fld.ElemMaxHas, fld.ElemMax, 0)
	}
}

// deserializeArray reads an array into target, mirroring serializeArray. Native
// numeric/bitfield arrays read directly; enum/boolean arrays value-convert;
// string/blob use the native/_StrSeq helpers; struct/union and nested arrays use
// the _MsgSeq sequence visitor. The corelib-c-cpp wrapper binds targets by
// address for a deferred pass, so its enum/boolean arrays read in place (a temp
// would dangle) and the target vector is reserved so an emplace never moves a
// still-unfilled bound element.
func (g *gen) deserializeArray(f *hfile, ind, target string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, count int64, elemMaxHas bool, elemMax int64, depth int) {
	tv := fmt.Sprintf("_t%d", depth)
	iv := fmt.Sprintf("_i%d", depth)
	rv := fmt.Sprintf("_r%d", depth)
	switch elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64,
		ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64,
		ir.KindFP32, ir.KindFP64, ir.KindBitfield:
		f.line("%sis.read(%s);", ind, target)
	case ir.KindEnum:
		bk := enumBacking(ref.Target)
		if g.clib {
			f.line("%sis.read(reinterpret_cast<std::array<%s, %d> &>(%s));", ind, bk, count, target)
		} else {
			f.line("%s{ std::array<%s, %d> %s{}; is.read(%s); for (std::size_t %s = 0; %s < %d; ++%s) %s[%s] = static_cast<%s>(%s[%s]); }",
				ind, bk, count, tv, tv, iv, iv, count, iv, target, iv, g.cppArrayElem(elem, ref, items, elemMaxHas, elemMax), tv, iv)
		}
	case ir.KindBool:
		if g.clib {
			f.line("%sis.read(reinterpret_cast<std::array<std::uint8_t, %d> &>(%s));", ind, count, target)
		} else {
			f.line("%s{ std::array<std::uint8_t, %d> %s{}; is.read(%s); for (std::size_t %s = 0; %s < %d; ++%s) %s[%s] = %s[%s] != 0; }",
				ind, count, tv, tv, iv, iv, count, iv, target, iv, tv, iv)
		}
	case ir.KindString:
		if g.clib {
			f.line("%sis.read(%s);", ind, target)
		} else {
			f.line("%s{ _StrSeq %s{%s}; is.read(%s); }", ind, rv, target, rv)
		}
	case ir.KindBlob:
		cont := g.cppArrayContainer(elem, ref, items, count, elemMaxHas, elemMax)
		if strings.HasPrefix(cont, "InlineVector") {
			// Fixed blob sequence: fill fixed inline slots by the element size (the
			// read(void*,size_t) blob overload), no heap. The collector is static
			// because the corelib-c-cpp decoder dereferences it after this returns.
			f.line("%s{ static _FixedBlobSeq<%s> %s; %s.out = &%s; is.read(%s); }", ind, cont, rv, rv, target, rv)
		} else if g.clib {
			f.line("%sis.read(%s);", ind, target)
		} else {
			f.line("%s{ _BlobSeq %s{%s}; is.read(%s); }", ind, rv, target, rv)
		}
	case ir.KindStruct, ir.KindUnion:
		cont := g.cppArrayContainer(elem, ref, items, count, elemMaxHas, elemMax)
		g.deserializeSeqInto(f, ind, target, g.typeName(ref.Key), count, rv, cont)
	case ir.KindArray:
		inner := g.cppArrayContainer(items.Elem, items.ElemRef, items.ElemItems, items.Count, items.ElemMaxHas, items.ElemMax)
		cont := g.cppArrayContainer(elem, ref, items, count, elemMaxHas, elemMax)
		g.deserializeSeqInto(f, ind, target, inner, count, rv, cont)
	}
}

// deserializeSeqInto reads a wrapper sequence of elemType into target via the
// _MsgSeq visitor. corelib-cpp decodes synchronously, so a plain stack-local
// visitor is fine. The corelib-c-cpp wrapper is a deferred decoder that uses the
// visitor after this call returns, so its visitor gets static storage; a fixed
// count also reserves the target up front so an emplace never reallocates a
// still-bound element (a dynamic sequence cannot be pre-sized this way).
func (g *gen) deserializeSeqInto(f *hfile, ind, target, elemType string, count int64, rv, container string) {
	if strings.HasPrefix(container, "InlineVector") {
		// Fixed inline sequence: the visitor emplaces into the next inline slot
		// (address-stable, no reserve/reallocation). Static for the same deferred
		// reason as the dynamic clib path.
		f.line("%s{ static _MsgSeqFixed<%s> %s; %s.out = &%s; is.read(%s); }", ind, container, rv, rv, target, rv)
		return
	}
	if g.clib {
		reserve := ""
		if count > 0 {
			reserve = fmt.Sprintf(" %s.reserve(%d);", target, count)
		}
		f.line("%s{ static _MsgSeq<%s> %s; %s.out = &%s;%s is.read(%s); }", ind, elemType, rv, rv, target, reserve, rv)
		return
	}
	f.line("%s{ _MsgSeq<%s> %s; %s.out = &%s; is.read(%s); }", ind, elemType, rv, rv, target, rv)
}

// checkBounded enforces the fixed-capacity (embedded) profile's unbounded-field
// policy (plan §9): every field that the profile lowers to fixed storage must be
// sized by the schema. A blob needs a maxlen; a struct/union/nested-array/blob
// sequence needs a count (and a blob element needs an element maxlen). An
// unbounded such field is a hard error unless allow_dynamic keeps a std::vector/
// std::string fallback for it. Strings are exempt: they stay std::string in this
// profile regardless (a fixed-string decode overload is blocked on corelib-c-cpp).
func (g *gen) checkBounded(s *ir.Schema) error {
	if g.allowDynamic {
		return nil
	}
	seen := map[string]bool{}
	var walkFields func(owner string, fields []*ir.Field) error
	var walkArray func(owner, path string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, count int64, elemMaxHas bool) error
	walkArray = func(owner, path string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, count int64, elemMaxHas bool) error {
		switch elem {
		case ir.KindString:
			return nil // deferred to std::vector<std::string>
		case ir.KindBlob:
			if count <= 0 {
				return unboundedErr(owner, path, "count")
			}
			if !elemMaxHas {
				return unboundedErr(owner, path, "element maxlen")
			}
		case ir.KindStruct, ir.KindUnion:
			if count <= 0 {
				return unboundedErr(owner, path, "count")
			}
			return walkFields(g.typeName(ref.Key), ref.Target.Fields)
		case ir.KindArray:
			if count <= 0 {
				return unboundedErr(owner, path, "count")
			}
			return walkArray(owner, path+"[]", items.Elem, items.ElemRef, items.ElemItems, items.Count, items.ElemMaxHas)
		}
		return nil
	}
	walkFields = func(owner string, fields []*ir.Field) error {
		if seen[owner] {
			return nil
		}
		seen[owner] = true
		for _, fld := range fields {
			switch fld.Kind {
			case ir.KindBlob:
				if !fld.HasMaxlen {
					return unboundedErr(owner, fld.Name, "maxlen")
				}
			case ir.KindStruct, ir.KindUnion:
				if err := walkFields(g.typeName(fld.Ref.Key), fld.Ref.Target.Fields); err != nil {
					return err
				}
			case ir.KindArray:
				if err := walkArray(owner, fld.Name, fld.Elem, fld.ElemRef, fld.ElemItems, fld.Count, fld.ElemMaxHas); err != nil {
					return err
				}
			}
		}
		return nil
	}
	for _, m := range s.Messages {
		if err := walkFields(exported(m.Name), m.Fields); err != nil {
			return err
		}
	}
	return nil
}

func unboundedErr(owner, path, missing string) error {
	return fmt.Errorf("cpp: field %q in %q has no %s; the fixed-capacity (embedded) profile requires count on every array and maxlen on every blob (set allow_dynamic: true to keep a std::vector/std::string fallback for unbounded fields)", path, owner, missing)
}

// reachable returns named-type keys used by m in post-order (children first).
// Composite array elements (enum/bitfield/struct/union) and nested-array element
// composites are collected too, so an array-of-struct element type is emitted.
func (g *gen) reachable(m *ir.Message) []string {
	var order []string
	seen := map[string]bool{}
	var visit func(fields []*ir.Field)
	var addRef func(ref *ir.TypeRef)
	var visitArray func(elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem)
	addRef = func(ref *ir.TypeRef) {
		if ref == nil {
			return
		}
		key := ref.Key
		if seen[key] {
			return
		}
		seen[key] = true
		t := ref.Target
		if t.Category == ir.CatStruct || t.Category == ir.CatUnion {
			visit(t.Fields)
		}
		order = append(order, key)
	}
	visitArray = func(elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem) {
		switch elem {
		case ir.KindEnum, ir.KindBitfield, ir.KindStruct, ir.KindUnion:
			addRef(ref)
		case ir.KindArray:
			visitArray(items.Elem, items.ElemRef, items.ElemItems)
		}
	}
	visit = func(fields []*ir.Field) {
		for _, f := range fields {
			if f.Kind == ir.KindArray {
				visitArray(f.Elem, f.ElemRef, f.ElemItems)
				continue
			}
			addRef(f.Ref)
		}
	}
	visit(m.Fields)
	return order
}
