package cpp

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// emitBench emits the Callgrind workload entry points (tests/bench, ARCHITECTURE
// §15). Each run_<workload> performs EXACTLY ONE op and is noinline with external
// linkage, so
//
//	valgrind --tool=callgrind --collect-atstart=no --toggle-collect=run_<workload>
//
// collects that single op and nothing else — process start, JSON parsing and the
// decode input's pre-encode all happen in bench_main, before collection is toggled
// on. Same shape as corelib-c-cpp/bench/cpp/bench.cpp.
//
// extern "C" keeps the symbol unmangled so --toggle-collect can name it without a
// C++ mangling pattern. The barrier is on the wrapper only: encode/try_decode and
// the corelib still inline into it, which is the cost being measured.
func (g *gen) emitBench(f *hfile, s *ir.Schema) {
	for _, m := range s.Messages {
		mt := exported(m.Name)
		low := strings.ToLower(m.Name)
		f.line("static %s _bench_%s_in;", mt, low)
		f.line("static %s _bench_%s_out;", mt, low)
		f.line("static std::vector<std::uint8_t> _bench_%s_wire;", low)
		f.blank()
		f.line("extern \"C\" __attribute__((noinline)) void run_encode_%s() {", low)
		f.line("    _bench_%s_wire = _bench_%s_in.encode();", low, low)
		f.line("}")
		f.blank()
		f.line("extern \"C\" __attribute__((noinline)) void run_decode_%s() {", low)
		f.line("    (void)%s::try_decode(_bench_%s_wire.data(), _bench_%s_wire.size(), _bench_%s_out);", mt, low, low, low)
		f.line("}")
		f.blank()
	}

	f.line("// bench_main runs one op of <workload>. Everything here is setup and")
	f.line("// observation; only the run_* call is collected.")
	f.line("static int bench_main(const std::string &w, const std::string &in) {")
	f.line("    char err[128];")
	f.line("    sofab_json_t *root = sofab_json_parse(in.data(), in.size(), err, sizeof(err));")
	f.line("    if (!root) { std::cerr << \"json: \" << err << \"\\n\"; return 1; }")
	f.line("    unsigned long long sink = 0;")
	for _, m := range s.Messages {
		low := strings.ToLower(m.Name)
		f.line("    if (w == \"encode_%s\" || w == \"decode_%s\") {", low, low)
		f.line("        from_json(root, _bench_%s_in); sofab_json_free(root);", low)
		f.line("        if (w == \"encode_%s\") {", low)
		f.line("            run_encode_%s();", low)
		f.line("        } else {")
		f.line("            run_encode_%s();  // setup: the decode input (not collected)", low)
		f.line("            run_decode_%s();", low)
		f.line("        }")
		f.line("        // Observe both results after collection stops, so neither op can be")
		f.line("        // optimized away but the folding costs no measured instructions.")
		f.line("        for (auto b : _bench_%s_wire) sink = sink * 31u + b;", low)
		f.line("        { std::ostringstream o; to_json(_bench_%s_out, o); sink += o.str().size(); }", low)
		f.line("        std::cerr << \"sink=\" << sink << \" BYTES=\" << _bench_%s_wire.size() << \"\\n\";", low)
		f.line("        std::cerr << \"wire_hex=\";")
		f.line("        for (auto b : _bench_%s_wire) { char h[3]; std::snprintf(h, sizeof(h), \"%%02x\", b); std::cerr << h; }", low)
		f.line("        std::cerr << \"\\n\";")
		f.line("        return 0;")
		f.line("    }")
	}
	f.line("    sofab_json_free(root);")
	f.line("    std::cerr << \"unknown workload: \" << w << \"\\n\";")
	f.line("    return 2;")
	f.line("}")
	f.blank()
}

// projectFiles scaffolds a buildable C++ project: an encode/decode JSON harness
// (json.hpp keeps the JSON dependency out of the message headers) + a Makefile.
// The harness reuses corelib-c-cpp's vendored sofab_test_json reader for input
// and emits canonical JSON by hand (blob as number[], to match the C harness).
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any) []generator.File {
	return []generator.File{
		{Path: "harness/json.hpp", Content: g.jsonHeader(s)},
		{Path: "harness/main.cpp", Content: g.harnessMain(s)},
		{Path: "Makefile", Content: []byte(g.makefile(s))},
		{Path: "README.md", Content: []byte(cppReadme)},
	}
}

const cppReadme = "# Generated SofaBuffers C++ project\n\n" +
	"`@generated by sofabgen`. Encode/decode harness over a C++ corelib.\n\n" +
	"Default build, against the pure-C++20 `corelib-cpp`:\n\n" +
	"```sh\nmake SOFAB_CPP_DIR=/path/to/corelib-cpp SOFAB_C_DIR=/path/to/corelib-c-cpp\n```\n\n" +
	"When generated with `corelib: c-cpp`, the code targets the C++ wrapper of the\n" +
	"C library and only needs `corelib-c-cpp` (its C sources are compiled + linked):\n\n" +
	"```sh\nmake SOFAB_C_DIR=/path/to/corelib-c-cpp\n```\n\n" +
	"```sh\necho '{...}' | ./harness/harness encode <Message>\n" +
	"./harness/harness decode <Message> < bytes.bin\n```\n"

func (g *gen) makefile(s *ir.Schema) string {
	if g.clib {
		return cppClibMakefile
	}
	return `# @generated by sofabgen
SOFAB_CPP_DIR ?= /opt/corelib-cpp
SOFAB_C_DIR   ?= /opt/corelib-c-cpp
CXX ?= g++
# The C++ standard is kept separate from CXXFLAGS so it is always applied even if
# a caller overrides CXXFLAGS. corelib-cpp requires C++20 (concepts, std::span).
CXXSTD ?= -std=c++20
CXXFLAGS ?= -O2 -Wall
INCLUDES := -I. -I$(SOFAB_CPP_DIR)/include -I$(SOFAB_C_DIR)/test/shared

harness/harness: harness/main.cpp $(SOFAB_C_DIR)/test/shared/sofab_test_json.c
	$(CXX) $(CXXSTD) $(CXXFLAGS) $(INCLUDES) harness/main.cpp -x c $(SOFAB_C_DIR)/test/shared/sofab_test_json.c -o $@

.PHONY: clean
clean:
	rm -f harness/harness
`
}

// cppClibMakefile builds against corelib-c-cpp's C++ wrapper (corelib: c-cpp).
// The wrapper sits on the C library, whose sources rely on C enum arithmetic and
// do not compile as C++, so they are compiled as C objects with $(CC) and linked
// with the C++ harness. Only SOFAB_C_DIR is needed.
const cppClibMakefile = `# @generated by sofabgen
SOFAB_C_DIR ?= /opt/corelib-c-cpp
CXX ?= g++
CC  ?= gcc
# The language standards are kept separate from C/CXXFLAGS so they are always
# applied even if a caller overrides those: C99 for the corelib's C sources,
# C++20 for the wrapper + harness.
CSTD   ?= -std=c99
CXXSTD ?= -std=c++20
# Embedded-friendly defaults: optimise for size and let the linker garbage-collect
# unused sections. All generated + corelib code is noexcept and uses no RTTI
# (typeid/dynamic_cast), so exceptions and RTTI tables can be dropped outright.
# These are safe for every corelib-c-cpp build and cut .text with zero wire/API
# impact; override C/CXXFLAGS to change them.
CFLAGS   ?= -Os -ffunction-sections -fdata-sections
CXXFLAGS ?= -Os -Wall -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti
LDFLAGS  ?= -Wl,--gc-sections
INCLUDES := -I. -I$(SOFAB_C_DIR)/src/include -I$(SOFAB_C_DIR)/test/shared

COBJS = object.o ostream.o istream.o sofab_test_json.o

.PHONY: all
all: harness/harness

object.o ostream.o istream.o: %.o: $(SOFAB_C_DIR)/src/%.c
	$(CC) $(CSTD) $(CFLAGS) -I$(SOFAB_C_DIR)/src/include -c $< -o $@
sofab_test_json.o: $(SOFAB_C_DIR)/test/shared/sofab_test_json.c
	$(CC) $(CSTD) $(CFLAGS) -I$(SOFAB_C_DIR)/src/include -I$(SOFAB_C_DIR)/test/shared -c $< -o $@

harness/harness: harness/main.cpp $(COBJS)
	$(CXX) $(CXXSTD) $(CXXFLAGS) $(INCLUDES) harness/main.cpp $(COBJS) $(LDFLAGS) -o $@

.PHONY: clean
clean:
	rm -f harness/harness $(COBJS)
`

// jsonHeader emits to_json/from_json free functions for every object, in
// post-order (children before parents, so overload resolution sees them).
func (g *gen) jsonHeader(s *ir.Schema) []byte {
	f := &hfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	f.line("#pragma once")
	for _, m := range s.Messages {
		f.line("#include %q", strings.ToLower(m.Name)+".hpp")
	}
	f.line("#include %q", "sofab_test_json.h")
	f.line("#include <ostream>")
	f.line("#include <cstdint>")
	f.line("#include <cstdio>")
	f.blank()
	f.line("namespace %s {", g.ns)
	f.line("%s", jsonHelpers)
	f.blank()

	emitted := map[string]bool{}
	for _, m := range s.Messages {
		for _, key := range g.reachable(m) {
			nt := s.Named[key]
			if (nt.Category == ir.CatStruct || nt.Category == ir.CatUnion) && !emitted[key] {
				emitted[key] = true
				g.emitJSONFns(f, g.typeName(key), nt.Fields)
			}
		}
		g.emitJSONFns(f, exported(m.Name), m.Fields)
	}
	f.line("} // namespace %s", g.ns)
	return f.bytes()
}

func (g *gen) emitJSONFns(f *hfile, typeName string, fields []*ir.Field) {
	// to_json
	f.line("inline void to_json(const %s &o, std::ostream &out) {", typeName)
	f.line("    out << '{';")
	for i, fld := range fields {
		if i > 0 {
			f.line("    out << ',';")
		}
		f.line("    out << \"\\\"%s\\\":\";", fld.Name)
		g.emitToJSON(f, fld)
	}
	f.line("    out << '}';")
	f.line("}")
	// from_json
	f.line("inline void from_json(const sofab_json_t *j, %s &o) {", typeName)
	f.line("    const sofab_json_t *c;")
	f.line("    (void)c; (void)j; (void)o;")
	for _, fld := range fields {
		g.emitFromJSON(f, fld)
	}
	f.line("}")
	f.blank()
}

func (g *gen) emitToJSON(f *hfile, fld *ir.Field) {
	acc := "o." + cppIdent(fld.Name)
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		f.line("    out << static_cast<unsigned long long>(%s);", acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		f.line("    out << static_cast<long long>(%s);", acc)
	case ir.KindBool:
		f.line("    out << (%s ? \"true\" : \"false\");", acc)
	case ir.KindFP32, ir.KindFP64:
		f.line("    json_num(out, %s);", acc)
	case ir.KindString:
		f.line("    json_str(out, %s);", acc)
	case ir.KindBlob:
		f.line("    json_bytes(out, %s);", acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("    to_json(%s, out);", acc)
	case ir.KindArray:
		g.emitToJSONArray(f, fld, acc)
	}
}

func (g *gen) emitToJSONArray(f *hfile, fld *ir.Field, acc string) {
	g.toJSONArray(f, "    ", acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
}

// toJSONArray renders an array expr as a JSON array, recursing for nested arrays.
// Enum/signed integers print as long long; unsigned/bitfield as unsigned long
// long; struct/union delegate to to_json; blob stays a number[] (C canonical).
func (g *gen) toJSONArray(f *hfile, ind, expr string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	ev := fmt.Sprintf("_e%d", depth)
	ff := fmt.Sprintf("_f%d", depth)
	f.line("%s{ out << '['; bool %s = true; for (const auto &%s : %s) { if (!%s) out << ','; %s = false;", ind, ff, ev, expr, ff, ff)
	inner := ind + "    "
	switch elem {
	case ir.KindString:
		f.line("%sjson_str(out, %s);", inner, ev)
	case ir.KindBlob:
		f.line("%sjson_bytes(out, %s);", inner, ev)
	case ir.KindFP32, ir.KindFP64:
		f.line("%sjson_num(out, %s);", inner, ev)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		f.line("%sout << static_cast<long long>(%s);", inner, ev)
	case ir.KindBool:
		f.line("%sout << (%s ? \"true\" : \"false\");", inner, ev)
	case ir.KindStruct, ir.KindUnion:
		f.line("%sto_json(%s, out);", inner, ev)
	case ir.KindArray:
		g.toJSONArray(f, inner, ev, items.Elem, items.ElemRef, items.ElemItems, depth+1)
	default: // unsigned / bitfield
		f.line("%sout << static_cast<unsigned long long>(%s);", inner, ev)
	}
	f.line("%s} out << ']'; }", ind)
}

func (g *gen) emitFromJSON(f *hfile, fld *ir.Field) {
	acc := "o." + cppIdent(fld.Name)
	f.line("    c = sofab_json_get(j, %q);", fld.Name)
	f.line("    if (c) {")
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		f.line("        %s = static_cast<%s>(sofab_json_u64(c));", acc, g.cppType(fld))
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("        %s = static_cast<%s>(sofab_json_i64(c));", acc, g.cppType(fld))
	case ir.KindBool:
		f.line("        %s = sofab_json_bool(c) != 0;", acc)
	case ir.KindFP32:
		f.line("        %s = static_cast<float>(sofab_json_double(c));", acc)
	case ir.KindFP64:
		f.line("        %s = sofab_json_double(c);", acc)
	case ir.KindString:
		// assign(string_view) works for both std::string and sofab::FixedString.
		f.line("        { size_t _l; const char *_s = sofab_json_string(c, &_l); %s.assign(std::string_view{_s, _l}); }", acc)
	case ir.KindBlob:
		f.line("        %s.clear(); json_to_bytes(c, %s);", acc, acc)
	case ir.KindEnum:
		f.line("        %s = static_cast<%s>(sofab_json_i64(c));", acc, g.typeName(fld.Ref.Key))
	case ir.KindStruct, ir.KindUnion:
		f.line("        from_json(c, %s);", acc)
	case ir.KindArray:
		g.emitFromJSONArray(f, fld, acc)
	}
	f.line("    }")
}

func (g *gen) emitFromJSONArray(f *hfile, fld *ir.Field, acc string) {
	g.fromJSONArray(f, "        ", "c", acc, fld.Elem, fld.ElemRef, fld.ElemItems, fld.Count, fld.ElemMaxHas, fld.ElemMax, 0)
}

// fromJSONArray parses a JSON array node into target, recursing for nested
// arrays. Native elements (numeric/enum/boolean/bitfield) overwrite a fixed
// std::array by index; string/blob/struct/union/nested-array elements append to
// a std::vector.
func (g *gen) fromJSONArray(f *hfile, ind, node, target string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, count int64, elemMaxHas bool, elemMax int64, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	ev := fmt.Sprintf("_e%d", depth)
	vv := fmt.Sprintf("_v%d", depth)
	inner := ind + "    "
	if isNativeArrayElem(elem) {
		f.line("%sfor (size_t %s = 0; %s < sofab_json_array_size(%s); %s++) {", ind, iv, iv, node, iv)
		f.line("%sconst sofab_json_t *%s = sofab_json_array_at(%s, %s);", inner, ev, node, iv)
		switch elem {
		case ir.KindFP32, ir.KindFP64:
			f.line("%sif (%s < %s.size()) %s[%s] = static_cast<%s>(sofab_json_double(%s));", inner, iv, target, target, iv, numCppType(elem), ev)
		case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
			f.line("%sif (%s < %s.size()) %s[%s] = static_cast<%s>(sofab_json_i64(%s));", inner, iv, target, target, iv, numCppType(elem), ev)
		case ir.KindEnum:
			f.line("%sif (%s < %s.size()) %s[%s] = static_cast<%s>(sofab_json_i64(%s));", inner, iv, target, target, iv, g.typeName(ref.Key), ev)
		case ir.KindBool:
			f.line("%sif (%s < %s.size()) %s[%s] = sofab_json_bool(%s) != 0;", inner, iv, target, target, iv, ev)
		case ir.KindBitfield:
			f.line("%sif (%s < %s.size()) %s[%s] = static_cast<%s>(sofab_json_u64(%s));", inner, iv, target, target, iv, bitfieldBacking(ref.Target), ev)
		default: // unsigned
			f.line("%sif (%s < %s.size()) %s[%s] = static_cast<%s>(sofab_json_u64(%s));", inner, iv, target, target, iv, numCppType(elem), ev)
		}
		f.line("%s}", ind)
		return
	}
	// std::vector element: clear then append.
	f.line("%s%s.clear();", ind, target)
	f.line("%sfor (size_t %s = 0; %s < sofab_json_array_size(%s); %s++) {", ind, iv, iv, node, iv)
	f.line("%sconst sofab_json_t *%s = sofab_json_array_at(%s, %s);", inner, ev, node, iv)
	switch elem {
	case ir.KindString:
		if strings.HasPrefix(g.cppArrayContainer(elem, ref, items, count, elemMaxHas, elemMax), "sofab::InlineVector") {
			// InlineVector<FixedString>: default-construct a slot, then assign.
			f.line("%s{ size_t _l; const char *_s = sofab_json_string(%s, &_l); %s.emplace_back().assign(std::string_view{_s, _l}); }", inner, ev, target)
		} else {
			f.line("%s{ size_t _l; const char *_s = sofab_json_string(%s, &_l); %s.emplace_back(_s, _l); }", inner, ev, target)
		}
	case ir.KindBlob:
		f.line("%s{ %s _b{}; json_to_bytes(%s, _b); %s.push_back(std::move(_b)); }", inner, g.cppArrayElem(elem, ref, items, elemMaxHas, elemMax), ev, target)
	case ir.KindStruct, ir.KindUnion:
		f.line("%s{ %s %s; from_json(%s, %s); %s.push_back(std::move(%s)); }", inner, g.typeName(ref.Key), vv, ev, vv, target, vv)
	case ir.KindArray:
		icont := g.cppArrayContainer(items.Elem, items.ElemRef, items.ElemItems, items.Count, items.ElemMaxHas, items.ElemMax)
		f.line("%s{ %s %s{};", inner, icont, vv)
		g.fromJSONArray(f, inner+"    ", ev, vv, items.Elem, items.ElemRef, items.ElemItems, items.Count, items.ElemMaxHas, items.ElemMax, depth+1)
		f.line("%s%s.push_back(std::move(%s)); }", inner+"    ", target, vv)
	}
	f.line("%s}", ind)
}

func (g *gen) harnessMain(s *ir.Schema) []byte {
	f := &hfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	f.line("#include \"json.hpp\"")
	f.line("#include <iostream>")
	f.line("#include <sstream>")
	f.line("#include <string>")
	f.line("#include <cstring>")
	f.line("#include <cstdio>")
	f.line("#include <vector>")
	f.blank()
	f.line("using namespace %s;", g.ns)
	f.blank()
	g.emitBench(f, s)
	f.line("int main(int argc, char **argv) {")
	f.line("    if (argc < 2) { std::cerr << \"usage: harness <encode|decode|bench> [Message|workload]\\n\"; return 2; }")
	f.line("    std::string mode = argv[1];")
	f.line("    std::string msg = argc > 2 ? argv[2] : %q;", defaultMessage(s))
	f.line("    std::ostringstream _in; _in << std::cin.rdbuf(); std::string in = _in.str();")
	f.line("    // `bench <workload>` takes a workload, not a message name.")
	f.line("    if (mode == \"bench\") { return bench_main(argc > 2 ? argv[2] : \"\", in); }")
	for i, m := range s.Messages {
		kw := "if"
		if i > 0 {
			kw = "else if"
		}
		mt := exported(m.Name)
		f.line("    %s (msg == %q) {", kw, m.Name)
		f.line("        if (mode == \"encode\") {")
		f.line("            char err[128];")
		f.line("            sofab_json_t *root = sofab_json_parse(in.data(), in.size(), err, sizeof(err));")
		f.line("            if (!root) { std::cerr << \"json: \" << err << \"\\n\"; return 1; }")
		f.line("            %s obj; from_json(root, obj); sofab_json_free(root);", mt)
		f.line("            auto bytes = obj.encode();")
		f.line("            std::cout.write(reinterpret_cast<const char *>(bytes.data()), bytes.size());")
		f.line("        } else if (mode == \"decode\") {")
		// try_decode, not the best-effort decode: the harness must surface the
		// accept/reject verdict (a malformed input exits non-zero) so the
		// conformance run can assert rejects, e.g. over-count arrays (#100).
		f.line("            %s obj;", mt)
		f.line("            auto r = %s::try_decode(reinterpret_cast<const std::uint8_t *>(in.data()), in.size(), obj);", mt)
		f.line("            if (!r.ok()) { std::cerr << \"decode error\\n\"; return 1; }")
		f.line("            to_json(obj, std::cout); std::cout << \"\\n\";")
		if !g.clib {
			// Surface the §7 decode outcome so a conformance run can assert the
			// INVALID-vs-INCOMPLETE distinction that a bare non-zero exit hides — e.g.
			// a field that is both over-bound and truncated must be INVALID, not
			// INCOMPLETE (generator#216 / §5.2). Pure corelib-cpp only: its Result
			// carries the invalid()/incomplete()/limitExceeded() predicates (the c-cpp
			// wrapper's Result does not, and has no measure phase to test anyway).
			f.line("        } else if (mode == \"status\") {")
			f.line("            %s obj;", mt)
			f.line("            auto r = %s::try_decode(reinterpret_cast<const std::uint8_t *>(in.data()), in.size(), obj);", mt)
			f.line("            std::cout << (r.invalid() ? \"INVALID\" : r.incomplete() ? \"INCOMPLETE\" : r.limitExceeded() ? \"LIMIT_EXCEEDED\" : \"COMPLETE\") << \"\\n\";")
		}
		f.line("        } else { std::cerr << \"unknown mode\\n\"; return 2; }")
		f.line("    }")
	}
	f.line("    else { std::cerr << \"unknown message\\n\"; return 2; }")
	f.line("    return 0;")
	f.line("}")
	return f.bytes()
}

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

var jsonHelpers = `inline void json_str(std::ostream &out, std::string_view s) {
    out << '"';
    for (unsigned char c : s) {
        if (c == '"' || c == '\\') { out << '\\' << c; }
        else if (c == '\n') out << "\\n";
        else if (c == '\t') out << "\\t";
        else if (c == '\r') out << "\\r";
        else if (c < 0x20) { char b[8]; std::snprintf(b, sizeof(b), "\\u%04x", c); out << b; }
        else out << c;
    }
    out << '"';
}
template <class Bytes>
inline void json_bytes(std::ostream &out, const Bytes &b) {
    out << '['; bool f = true; for (std::size_t i = 0; i < b.size(); i++) { if (!f) out << ','; f = false; out << static_cast<unsigned>(b.data()[i]); } out << ']';
}
inline void json_num(std::ostream &out, double v) { char b[32]; std::snprintf(b, sizeof(b), "%.17g", v); out << b; }
template <class Bytes>
inline void json_to_bytes(const sofab_json_t *c, Bytes &dst) {
    size_t n = sofab_json_array_size(c);
    for (size_t i = 0; i < n; i++) dst.push_back(static_cast<std::uint8_t>(sofab_json_u64(sofab_json_array_at(c, i))));
}`

var _ = fmt.Sprintf
