package cpp

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// projectFiles scaffolds a buildable C++ project: an encode/decode JSON harness
// (json.hpp keeps the JSON dependency out of the message headers) + a Makefile.
// The harness reuses corelib-c-cpp's vendored sofab_test_json reader for input
// and emits canonical JSON by hand (blob as number[], to match the C harness).
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any) []generator.File {
	return []generator.File{
		{Path: "harness/json.hpp", Content: g.jsonHeader(s)},
		{Path: "harness/main.cpp", Content: g.harnessMain(s)},
		{Path: "Makefile", Content: []byte(g.makefile(s))},
		{Path: "README.md", Content: []byte(cppReadme)},
	}
}

const cppReadme = "# Generated SofaBuffers C++ project\n\n" +
	"`@generated by sofabgen`. Encode/decode harness over a C++ corelib.\n\n" +
	"Default build, against the pure-C++20 `corelib-cpp`:\n\n" +
	"```sh\nmake SOFAB_CPP_DIR=/path/to/corelib-cpp SOFAB_C_DIR=/path/to/corelib-c-cpp\n```\n\n" +
	"When generated with `corelib: c-cpp`, the code targets the C++ wrapper of the\n" +
	"C library and only needs `corelib-c-cpp` (its C sources are compiled + linked):\n\n" +
	"```sh\nmake SOFAB_C_DIR=/path/to/corelib-c-cpp\n```\n\n" +
	"```sh\necho '{...}' | ./harness/harness encode <Message>\n" +
	"./harness/harness decode <Message> < bytes.bin\n```\n"

func (g *gen) makefile(s *ir.Schema) string {
	if g.clib {
		return cppClibMakefile
	}
	return `# @generated by sofabgen
SOFAB_CPP_DIR ?= /opt/corelib-cpp
SOFAB_C_DIR   ?= /opt/corelib-c-cpp
CXX ?= g++
CXXFLAGS ?= -std=c++20 -O2 -Wall -I. -I$(SOFAB_CPP_DIR)/include -I$(SOFAB_C_DIR)/test/shared

harness/harness: harness/main.cpp $(SOFAB_C_DIR)/test/shared/sofab_test_json.c
	$(CXX) $(CXXFLAGS) harness/main.cpp -x c $(SOFAB_C_DIR)/test/shared/sofab_test_json.c -o $@

.PHONY: clean
clean:
	rm -f harness/harness
`
}

// cppClibMakefile builds against corelib-c-cpp's C++ wrapper (corelib: c-cpp).
// The wrapper sits on the C library, whose sources rely on C enum arithmetic and
// do not compile as C++, so they are compiled as C objects with $(CC) and linked
// with the C++ harness. Only SOFAB_C_DIR is needed.
const cppClibMakefile = `# @generated by sofabgen
SOFAB_C_DIR ?= /opt/corelib-c-cpp
CXX ?= g++
CC  ?= gcc
CFLAGS   ?= -std=c99 -O2 -I$(SOFAB_C_DIR)/src/include
CXXFLAGS ?= -std=c++20 -O2 -Wall -I. -I$(SOFAB_C_DIR)/src/include -I$(SOFAB_C_DIR)/test/shared

COBJS = object.o ostream.o istream.o sofab_test_json.o

.PHONY: all
all: harness/harness

object.o ostream.o istream.o: %.o: $(SOFAB_C_DIR)/src/%.c
	$(CC) $(CFLAGS) -c $< -o $@
sofab_test_json.o: $(SOFAB_C_DIR)/test/shared/sofab_test_json.c
	$(CC) $(CFLAGS) -I$(SOFAB_C_DIR)/test/shared -c $< -o $@

harness/harness: harness/main.cpp $(COBJS)
	$(CXX) $(CXXFLAGS) harness/main.cpp $(COBJS) -o $@

.PHONY: clean
clean:
	rm -f harness/harness $(COBJS)
`

// jsonHeader emits to_json/from_json free functions for every object, in
// post-order (children before parents, so overload resolution sees them).
func (g *gen) jsonHeader(s *ir.Schema) []byte {
	f := &hfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	f.line("#pragma once")
	for _, m := range s.Messages {
		f.line("#include %q", strings.ToLower(m.Name)+".hpp")
	}
	f.line("#include %q", "sofab_test_json.h")
	f.line("#include <ostream>")
	f.line("#include <cstdint>")
	f.line("#include <cstdio>")
	f.blank()
	f.line("namespace %s {", g.ns)
	f.line("%s", jsonHelpers)
	f.blank()

	emitted := map[string]bool{}
	for _, m := range s.Messages {
		for _, key := range g.reachable(m) {
			nt := s.Named[key]
			if (nt.Category == ir.CatStruct || nt.Category == ir.CatUnion) && !emitted[key] {
				emitted[key] = true
				g.emitJSONFns(f, g.typeName(key), nt.Fields)
			}
		}
		g.emitJSONFns(f, exported(m.Name), m.Fields)
	}
	f.line("} // namespace %s", g.ns)
	return f.bytes()
}

func (g *gen) emitJSONFns(f *hfile, typeName string, fields []*ir.Field) {
	// to_json
	f.line("inline void to_json(const %s &o, std::ostream &out) {", typeName)
	f.line("    out << '{';")
	for i, fld := range fields {
		if i > 0 {
			f.line("    out << ',';")
		}
		f.line("    out << \"\\\"%s\\\":\";", fld.Name)
		g.emitToJSON(f, fld)
	}
	f.line("    out << '}';")
	f.line("}")
	// from_json
	f.line("inline void from_json(const sofab_json_t *j, %s &o) {", typeName)
	f.line("    const sofab_json_t *c;")
	f.line("    (void)c; (void)j; (void)o;")
	for _, fld := range fields {
		g.emitFromJSON(f, fld)
	}
	f.line("}")
	f.blank()
}

func (g *gen) emitToJSON(f *hfile, fld *ir.Field) {
	acc := "o." + fld.Name
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		f.line("    out << static_cast<unsigned long long>(%s);", acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		f.line("    out << static_cast<long long>(%s);", acc)
	case ir.KindBool:
		f.line("    out << (%s ? \"true\" : \"false\");", acc)
	case ir.KindFP32, ir.KindFP64:
		f.line("    json_num(out, %s);", acc)
	case ir.KindString:
		f.line("    json_str(out, %s);", acc)
	case ir.KindBlob:
		f.line("    json_bytes(out, %s);", acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("    to_json(%s, out);", acc)
	case ir.KindArray:
		g.emitToJSONArray(f, fld, acc)
	}
}

func (g *gen) emitToJSONArray(f *hfile, fld *ir.Field, acc string) {
	f.line("    { out << '['; bool _f = true; for (const auto &_e : %s) { if (!_f) out << ','; _f = false;", acc)
	switch fld.Elem {
	case ir.KindString:
		f.line("        json_str(out, _e); } out << ']'; }")
	case ir.KindBlob:
		f.line("        json_bytes(out, _e); } out << ']'; }")
	case ir.KindFP32, ir.KindFP64:
		f.line("        json_num(out, _e); } out << ']'; }")
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("        out << static_cast<long long>(_e); } out << ']'; }")
	default:
		f.line("        out << static_cast<unsigned long long>(_e); } out << ']'; }")
	}
}

func (g *gen) emitFromJSON(f *hfile, fld *ir.Field) {
	acc := "o." + fld.Name
	f.line("    c = sofab_json_get(j, %q);", fld.Name)
	f.line("    if (c) {")
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		f.line("        %s = static_cast<%s>(sofab_json_u64(c));", acc, g.cppType(fld))
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("        %s = static_cast<%s>(sofab_json_i64(c));", acc, g.cppType(fld))
	case ir.KindBool:
		f.line("        %s = sofab_json_bool(c) != 0;", acc)
	case ir.KindFP32:
		f.line("        %s = static_cast<float>(sofab_json_double(c));", acc)
	case ir.KindFP64:
		f.line("        %s = sofab_json_double(c);", acc)
	case ir.KindString:
		f.line("        { size_t _l; const char *_s = sofab_json_string(c, &_l); %s.assign(_s, _l); }", acc)
	case ir.KindBlob:
		f.line("        %s.clear(); json_to_bytes(c, %s);", acc, acc)
	case ir.KindEnum:
		f.line("        %s = static_cast<%s>(sofab_json_i64(c));", acc, g.typeName(fld.Ref.Key))
	case ir.KindStruct, ir.KindUnion:
		f.line("        from_json(c, %s);", acc)
	case ir.KindArray:
		g.emitFromJSONArray(f, fld, acc)
	}
	f.line("    }")
}

func (g *gen) emitFromJSONArray(f *hfile, fld *ir.Field, acc string) {
	if fld.Elem == ir.KindString || fld.Elem == ir.KindBlob {
		f.line("        %s.clear();", acc) // vectors append; fixed arrays overwrite by index
	}
	f.line("        for (size_t _i = 0; _i < sofab_json_array_size(c); _i++) {")
	f.line("            const sofab_json_t *_e = sofab_json_array_at(c, _i);")
	switch fld.Elem {
	case ir.KindString:
		f.line("            { size_t _l; const char *_s = sofab_json_string(_e, &_l); %s.emplace_back(_s, _l); }", acc)
	case ir.KindBlob:
		f.line("            { std::vector<std::uint8_t> _b; json_to_bytes(_e, _b); %s.push_back(std::move(_b)); }", acc)
	case ir.KindFP32, ir.KindFP64:
		f.line("            if (_i < %s.size()) %s[_i] = static_cast<%s>(sofab_json_double(_e));", acc, acc, numCppType(fld.Elem))
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("            if (_i < %s.size()) %s[_i] = static_cast<%s>(sofab_json_i64(_e));", acc, acc, numCppType(fld.Elem))
	default:
		f.line("            if (_i < %s.size()) %s[_i] = static_cast<%s>(sofab_json_u64(_e));", acc, acc, numCppType(fld.Elem))
	}
	f.line("        }")
}

func (g *gen) harnessMain(s *ir.Schema) []byte {
	f := &hfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	f.line("#include \"json.hpp\"")
	f.line("#include <iostream>")
	f.line("#include <sstream>")
	f.line("#include <string>")
	f.line("#include <cstring>")
	f.blank()
	f.line("using namespace %s;", g.ns)
	f.blank()
	f.line("int main(int argc, char **argv) {")
	f.line("    if (argc < 2) { std::cerr << \"usage: harness <encode|decode> [Message]\\n\"; return 2; }")
	f.line("    std::string mode = argv[1];")
	f.line("    std::string msg = argc > 2 ? argv[2] : %q;", defaultMessage(s))
	f.line("    std::ostringstream _in; _in << std::cin.rdbuf(); std::string in = _in.str();")
	for i, m := range s.Messages {
		kw := "if"
		if i > 0 {
			kw = "else if"
		}
		mt := exported(m.Name)
		f.line("    %s (msg == %q) {", kw, m.Name)
		f.line("        if (mode == \"encode\") {")
		f.line("            char err[128];")
		f.line("            sofab_json_t *root = sofab_json_parse(in.data(), in.size(), err, sizeof(err));")
		f.line("            if (!root) { std::cerr << \"json: \" << err << \"\\n\"; return 1; }")
		f.line("            %s obj; from_json(root, obj); sofab_json_free(root);", mt)
		f.line("            auto bytes = obj.encode();")
		f.line("            std::cout.write(reinterpret_cast<const char *>(bytes.data()), bytes.size());")
		f.line("        } else if (mode == \"decode\") {")
		f.line("            auto obj = %s::decode(reinterpret_cast<const std::uint8_t *>(in.data()), in.size());", mt)
		f.line("            to_json(obj, std::cout); std::cout << \"\\n\";")
		f.line("        } else { std::cerr << \"unknown mode\\n\"; return 2; }")
		f.line("    }")
	}
	f.line("    else { std::cerr << \"unknown message\\n\"; return 2; }")
	f.line("    return 0;")
	f.line("}")
	return f.bytes()
}

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

var jsonHelpers = `inline void json_str(std::ostream &out, const std::string &s) {
    out << '"';
    for (unsigned char c : s) {
        if (c == '"' || c == '\\') { out << '\\' << c; }
        else if (c == '\n') out << "\\n";
        else if (c == '\t') out << "\\t";
        else if (c == '\r') out << "\\r";
        else if (c < 0x20) { char b[8]; std::snprintf(b, sizeof(b), "\\u%04x", c); out << b; }
        else out << c;
    }
    out << '"';
}
inline void json_bytes(std::ostream &out, const std::vector<std::uint8_t> &b) {
    out << '['; bool f = true; for (auto x : b) { if (!f) out << ','; f = false; out << static_cast<unsigned>(x); } out << ']';
}
inline void json_num(std::ostream &out, double v) { char b[32]; std::snprintf(b, sizeof(b), "%.17g", v); out << b; }
inline void json_to_bytes(const sofab_json_t *c, std::vector<std::uint8_t> &dst) {
    size_t n = sofab_json_array_size(c);
    for (size_t i = 0; i < n; i++) dst.push_back(static_cast<std::uint8_t>(sofab_json_u64(sofab_json_array_at(c, i))));
}`

var _ = fmt.Sprintf
