package cpp

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/naming"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/cpp/reserved.{yaml,json} from the reserved-name list")

// paramNames are the spellings the generated member functions used for their
// parameters and locals before they all took a leading underscore -- a field of
// one of these names would have been shadowed by (or would have shadowed) the
// parameter, and a decode assigned the parameter instead of the member.
var paramNames = []string{"os", "is", "id", "out", "data", "len", "in", "dst",
	"r", "o", "v", "n", "scratch", "chunk", "size", "count"}

// roleNames are option names whose union accessors used to collide: the getter
// of `set_a` and the setter of `a`, and so on for every role.
var roleNames = []string{"a", "set_a", "has_a", "mutable_a"}

// macroSample is the part of the macro list a union takes as options: a
// std::variant of all of it would be a thousand alternatives.
var macroSample = []string{"NULL", "EOF", "BUFSIZ", "INT8_MAX", "SIZE_MAX", "errno",
	"stdin", "stdout", "linux", "unix", "offsetof", "SOFAB_ID_MAX", "SOFAB_HPP"}

// distinctFolds keeps the first name of each fold: the validator refuses two
// names of one scope that differ only in case or underscores.
func distinctFolds(lists ...[]string) []string {
	seen := map[string]bool{}
	var out []string
	for _, l := range lists {
		for _, n := range l {
			if f := naming.Fold(n); !seen[f] {
				seen[f] = true
				out = append(out, n)
			}
		}
	}
	return out
}

func sortedKeys(sets ...map[string]bool) []string {
	var names []string
	for _, set := range sets {
		for n := range set {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	return names
}

// memberNames is every name a field is tested under: every name on the member
// list (keywords, generated members, header macros, a SOFAB_ macro), the
// parameter names, and the role-prefixed names. `Which` and `which` fold alike,
// so only the union's lower-case accessor is a field.
func memberNames() []string {
	return distinctFolds(sortedKeys(cppKeywords, cppMembers, corelibProbes), []string{"which", "SOFAB_ID_MAX"},
		paramNames, roleNames, sortedKeys(cppHeaderMacros))
}

// optionNames is every name a union option is tested under.
func optionNames() []string {
	return distinctFolds(sortedKeys(cppKeywords, cppMembers, corelibProbes), []string{"which"}, paramNames, roleNames, macroSample)
}

// reservedYAML is the collision schema: every member name as a field of a
// message and of a nested struct, every option name as an option of a union;
// a field named like its own message (`M`) and like the type it holds
// (`Point`); an enum whose constants and a bitfield whose flags are macros;
// and every type-level name on the list as a message or $defs name -- the
// names a class body sees unqualified (cppTypeReserved), a macro as a type
// (`NULL`, and SIZE_MAX / SOFAB_HPP as inline paths), and `FILE`, which the
// harness would otherwise find twice.
func reservedYAML() string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/cpp/reserved.go and macros.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/cpp -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name, as a field, an option or a type, must\n")
	b.WriteString("# compile warning-free and round-trip (tests/conformance/cpp/run.sh).\n")
	var fields strings.Builder
	names := memberNames()
	for i, n := range names {
		fmt.Fprintf(&fields, "      %q: { id: %d, type: u8 }\n", n, i)
	}
	var opts []string
	for i, n := range optionNames() {
		opts = append(opts, fmt.Sprintf("%q: { id: %d, type: u8 }", n, i))
	}
	k := len(names)
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    inner:
%s    point:
      x: { id: 0, type: u8 }
    context:
      x: { id: 0, type: u8 }
  enum:
    e: { "NULL": 0, EOF: 1, BUFSIZ: 2 }
  bitfield:
    INT8:
      MAX: { pos: 0 }
      MIN: { pos: 1 }
messages:
  m:
    payload:
%s      inner:  { id: %d, type: struct, fields: { $ref: '#/$defs/struct/inner' } }
      u:      { id: %d, type: union, oneof: { %s } }
      M:      { id: %d, type: u8 }
      Point:  { id: %d, type: struct, fields: { $ref: '#/$defs/struct/point' } }
      e_val:  { id: %d, type: enum, enum: { $ref: '#/$defs/enum/e' } }
      bits:   { id: %d, type: bitfield, bits: { $ref: '#/$defs/bitfield/INT8' } }
      ctx:    { id: %d, type: struct, fields: { $ref: '#/$defs/struct/context' } }
  which: { payload: { x: { id: 0, type: u8 } } }
  message: { payload: { x: { id: 0, type: u8 } } }
  o_stream_message: { payload: { x: { id: 0, type: u8 } } }
  i_stream_message: { payload: { x: { id: 0, type: u8 } } }
  "NULL": { payload: { x: { id: 0, type: u8 } } }
  FILE: { payload: { x: { id: 0, type: u8 } } }
  SIZE: { payload: { MAX: { id: 0, type: struct, fields: { x: { id: 0, type: u8 } } } } }
  SOFAB: { payload: { HPP: { id: 0, type: struct, fields: { x: { id: 0, type: u8 } } } } }
`, fields.String(), fields.String(), k, k+1, strings.Join(opts, ", "), k+2, k+3, k+4, k+5, k+6)
	return b.String()
}

// reservedJSON is the harness input for m: every field and nested one at a
// non-default value, and the union holding option `id` -- the one the decode
// used to read its tag from when it was spelled like the parameter.
func reservedJSON() string {
	top := map[string]any{}
	inner := map[string]any{}
	for i, n := range memberNames() {
		top[n] = i%250 + 1
		inner[n] = (i+7)%250 + 1
	}
	top["inner"] = inner
	top["u"] = map[string]any{"id": 9}
	top["M"] = 11
	top["Point"] = map[string]any{"x": 12}
	top["e_val"] = 2
	top["bits"] = 3
	top["ctx"] = map[string]any{"x": 13}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite compiles that file warning-free on
// all four profiles and round-trips it, so a name added to reserved.go or
// macros.go is covered once the file is regenerated -- and this test fails
// until it is.
func TestReservedSchemaFile(t *testing.T) {
	for path, want := range map[string]string{
		"../../tests/conformance/cpp/reserved.yaml": reservedYAML(),
		"../../tests/conformance/cpp/reserved.json": reservedJSON(),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// TestReservedNamesAreMangled: every name on the member list comes out with a
// trailing underscore as a member of the message and of the nested struct; the
// parameter names and the role names, which are not on it, stay as they are;
// and the type-level names take the escape.
func TestReservedNamesAreMangled(t *testing.T) {
	files := unionFiles(t, reservedYAML(), nil)
	h := files["m.hpp"] + files["sofab-defs.hpp"]
	for _, n := range memberNames() {
		want := n + "_"
		for _, p := range append(append([]string{"which"}, paramNames...), roleNames...) {
			if n == p {
				want = n
			}
		}
		if got := strings.Count(h, "    std::uint8_t "+want+" = 0;\n"); got != 2 {
			t.Errorf("field %q is the member %s in %d of the 2 structs", n, want, got)
		}
	}
	for _, want := range []string{
		"std::uint8_t M_ = 0;",         // own class name
		"Point Point_ = {};",           // the type it holds
		"enum class E : std::int8_t {", // constants escaped below
		"    NULL_ = 0,", "    EOF_ = 1,", "    BUFSIZ_ = 2,",
		"    INT8_MAX_ = 1ULL,", // flag spelled like a macro
		"    INT8_MIN_ = 2ULL,",
		"Context_ ctx = {};", // corelib-c-cpp's private nested type
		"switch (_id) {",     // the parameter, never a member
	} {
		if !strings.Contains(h, want) {
			t.Errorf("m.hpp: missing %q", want)
		}
	}
	for file, want := range map[string]string{
		"which.hpp":            "struct Which_ : sofab::Message {",
		"message.hpp":          "struct Message_ : sofab::Message {",
		"o_stream_message.hpp": "struct OStreamMessage_ : sofab::Message {",
		"i_stream_message.hpp": "struct IStreamMessage_ : sofab::Message {",
		"null.hpp":             "struct NULL_ : sofab::Message {",
		"size.hpp":             "struct SIZE_MAX_ : sofab::Message {",
		"sofab.hpp":            "struct SOFAB_HPP_ : sofab::Message {",
		"file.hpp":             "struct FILE : sofab::Message {",
	} {
		if !strings.Contains(files[file], want) {
			t.Errorf("%s: missing %q", file, want)
		}
	}
	if !strings.Contains(files["harness/main.cpp"], "::sofabuffers::FILE obj;") {
		t.Error("the harness does not qualify the message type it names")
	}
}

// TestNamespaceConfig: a configured namespace the generated code cannot live
// in is a configuration error, raised before any schema name is looked at. A
// component sofab puts the types into the corelib's namespace (a message
// `OStream` redefines sofab::OStream); sofabgen meets the RawArray helper's;
// std, or either of them further down, makes the qualified `std::` /
// `sofab::` references find the configured namespace. Any other namespace is
// accepted.
func TestNamespaceConfig(t *testing.T) {
	src := "version: 1\nmessages:\n  OStream:\n    payload:\n" +
		"      e: { id: 0, type: array, items: { type: enum, count: 2, enum: { a: 0, b: 1 } } }\n"
	for _, ns := range []string{
		"sofab", "sofabgen", "std", "a::sofab", "sofab::a", "a::std", "a::sofabgen",
		"class", "NULL", "SOFAB_X", "a.b", "a::", "::a", "1a", "a__b", "_X",
	} {
		_, err := genHeader(t, src, "ostream.hpp", map[string]any{"namespace": ns})
		if err == nil {
			t.Errorf("namespace %q: accepted", ns)
		} else if !strings.Contains(err.Error(), fmt.Sprintf("config namespace %q", ns)) {
			t.Errorf("namespace %q: the error does not name the config: %v", ns, err)
		}
	}
	for _, ns := range []string{"message", "sofabuffers", "myproj::msg", "Message", "Sofab", "sofab_x", "a::OStream"} {
		if _, err := genHeader(t, src, "ostream.hpp", map[string]any{"namespace": ns}); err != nil {
			t.Errorf("namespace %q: refused: %v", ns, err)
		}
	}
}

// TestUnionRoleAccessorsAreDistinct: options `a` and `set_a` (and has_a,
// mutable_a) derive six accessors each; the getter of a role-prefixed option
// takes the escape, so every accessor is spelled once.
func TestUnionRoleAccessorsAreDistinct(t *testing.T) {
	src := "version: 1\nmessages:\n  m:\n    payload:\n      u: { id: 0, type: union, oneof: { a: { id: 0, type: u8 }, set_a: { id: 1, type: u8 }, has_a: { id: 2, type: u8 }, mutable_a: { id: 3, type: u8 } } }\n"
	for _, p := range unionProfiles {
		h := unionFiles(t, src, p.cfg)["m.hpp"]
		decl := regexp.MustCompile(`(?m)^    (?:[\w:<>]+ &?)(\w+)\((?:const )?[\w:<>]* ?&?_?v?\) (?:const )?noexcept`)
		seen := map[string]int{}
		for _, m := range decl.FindAllStringSubmatch(h, -1) {
			seen[m[1]]++
		}
		for _, want := range []string{"a", "set_a", "has_a", "mutable_a", "set_a_", "has_a_", "mutable_a_",
			"set_set_a", "has_set_a", "mutable_set_a", "set_mutable_a"} {
			if seen[want] != 1 {
				t.Errorf("%s: accessor %s declared %d times, want 1", p.name, want, seen[want])
			}
		}
	}
}

// TestBitfieldFlagsAcrossTypesAreDistinct: flags are namespace-level, spelled
// <Type>_<Flag>, so `F.a_b` and `FA.b` -- one name under the old <Type><Flag>
// spelling -- are F_AB and FA_B.
func TestBitfieldFlagsAcrossTypesAreDistinct(t *testing.T) {
	src := "version: 1\n$defs:\n  bitfield:\n    F: { a_b: { pos: 0 } }\n    FA: { b: { pos: 0 } }\nmessages:\n  m:\n    payload:\n      f: { id: 0, type: bitfield, bits: { $ref: '#/$defs/bitfield/F' } }\n      g: { id: 1, type: bitfield, bits: { $ref: '#/$defs/bitfield/FA' } }\n"
	h := unionFiles(t, src, nil)["sofab-defs.hpp"]
	for _, want := range []string{"    F_AB = 1ULL,", "    FA_B = 1ULL,"} {
		if !strings.Contains(h, want) {
			t.Errorf("missing %q in:\n%s", want, h)
		}
	}
}

// TestReservedNamesCompile: the collision schema must give code that compiles
// -- types and project harness -- under -Wall -Wextra -Werror on all four
// profiles. The generator exits 0 on code that does not compile, so only
// compiling it catches a missing entry. Gated on the corelib checkouts
// (SOFAB_CPP_DIR, SOFAB_C_DIR), like the union compile gate; run.sh also builds
// and round-trips the same file.
func TestReservedNamesCompile(t *testing.T) {
	cpp, cc := os.Getenv("SOFAB_CPP_DIR"), os.Getenv("SOFAB_C_DIR")
	if cpp == "" || cc == "" {
		t.Skip("set SOFAB_CPP_DIR and SOFAB_C_DIR to corelib checkouts to run the compile gate")
	}
	gxx, err := exec.LookPath("g++")
	if err != nil {
		t.Skip("g++ not found")
	}
	src := reservedYAML()
	for _, p := range unionProfiles {
		dir := t.TempDir()
		for path, content := range unionFiles(t, src, p.cfg) {
			full := filepath.Join(dir, path)
			if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		inc := "-I" + filepath.Join(cpp, "include")
		if p.cfg["corelib"] == "c-cpp" {
			inc = "-I" + filepath.Join(cc, "src", "include")
		}
		for _, std := range []string{"-std=c++20", "-std=gnu++20"} {
			args := []string{std, "-Wall", "-Wextra", "-Werror", "-fsyntax-only", inc,
				"-I" + filepath.Join(cc, "test", "shared"), "-I" + dir, filepath.Join(dir, "harness", "main.cpp")}
			if out, err := exec.Command(gxx, args...).CombinedOutput(); err != nil {
				t.Fatalf("%s %s: the collision schema does not compile:\n%s", p.name, std, out)
			}
		}
	}
}
