// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"github.com/sofa-buffers/corelib-go"
)

// _visitorBase supplies no-op defaults for every sofab.Visitor method, so a
// generated object overrides only the callbacks its fields actually use.
type _visitorBase struct{}

func (_visitorBase) Unsigned(sofab.ID, uint64) error               { return nil }
func (_visitorBase) Signed(sofab.ID, int64) error                  { return nil }
func (_visitorBase) Float32(sofab.ID, float32) error               { return nil }
func (_visitorBase) Float64(sofab.ID, float64) error               { return nil }
func (_visitorBase) String(sofab.ID, string) error                 { return nil }
func (_visitorBase) Bytes(sofab.ID, []byte) error                  { return nil }
func (_visitorBase) UnsignedArray(sofab.ID, []uint64) error        { return nil }
func (_visitorBase) SignedArray(sofab.ID, []int64) error           { return nil }
func (_visitorBase) Float32Array(sofab.ID, []float32) error        { return nil }
func (_visitorBase) Float64Array(sofab.ID, []float64) error        { return nil }
func (_visitorBase) BeginSequence(sofab.ID) (sofab.Visitor, error) { return _visitorBase{}, nil }
func (_visitorBase) EndSequence() error                            { return nil }

// _strSeq / _bytesSeq collect the elements of a string / blob array. Elements are
// keyed by index id: an INTERIOR element equal to the element default is omitted
// on the wire, so we place each value at its id and fill any gap with the element
// default ("" / nil). The array's LAST element is always on the wire, so the
// decoded length -- highest present id + 1 -- is exact. Blob copies (the corelib
// value aliases the decode buffer).
// cap is the schema count bound N (-1 == dynamic/unbounded). N is a CAPACITY, not
// a length: it never reaches the wire and never adds elements the wire did not
// carry. All it does here is bound the array -- an element id >= N is a
// schema-bound violation (INVALID, never grown-into) -- rejected before the slice
// grows, which also bounds the id-keyed fill against an over-index amplification
// DoS.
// emax is the schema element maxlen bound (-1 == unbounded): an element whose
// wire byte length exceeds emax is malformed input,
// rejected as INVALID before the slice grows - never silently truncated.
type _strSeq struct {
	_visitorBase
	out  *[]string
	cap  int
	emax int
}

// The element's schema bounds are decided at the LENGTH WORD, before a byte of
// payload is taken. S5.2 makes INVALID dominate INCOMPLETE, so a message
// truncated right after the word carrying the violating number must still be
// INVALID -- deciding it in String(), which never runs for such a message,
// reported INCOMPLETE instead.
//
// Both bounds sit inside the declared-subtype test: FixlenHeader fires for ANY
// fixlen subtype at this id, and an element whose subtype contradicts the
// declaration was never this array's value (S7.3), so neither its id nor its
// length may be measured against this array's bounds.
//
// ArrayBegin comes along because sofab.HeaderVisitor declares both and the cursor
// reaches them through ONE type assertion -- implementing only one leaves the
// assertion failing and silently disables the other hook.
func (s *_strSeq) ArrayBegin(sofab.ID, sofab.ArrayKind, int) error { return nil }

func (s *_strSeq) FixlenHeader(id sofab.ID, subtype, length int) error {
	if subtype != 2 {
		return nil
	}
	if s.cap >= 0 && int(id) >= s.cap {
		return sofab.ErrInvalidMsg
	}
	if s.emax >= 0 && length > s.emax {
		return sofab.ErrInvalidMsg
	}
	return nil
}

func (s *_strSeq) String(id sofab.ID, v string) error {
	if s.cap >= 0 && int(id) >= s.cap {
		return sofab.ErrInvalidMsg
	}
	if s.emax >= 0 && len(v) > s.emax {
		return sofab.ErrInvalidMsg
	}
	// The element is being materialized, so this is where its UTF-8 is checked.
	// A payload the decoder skips never reaches a collector at all, which is
	// exactly the point: validation follows the destination, not the wire.
	if !sofab.Utf8Valid([]byte(v)) {
		return sofab.ErrInvalidMsg
	}
	for len(*s.out) <= int(id) {
		*s.out = append(*s.out, "")
	}
	(*s.out)[id] = v
	return nil
}

type _bytesSeq struct {
	_visitorBase
	out  *[][]byte
	cap  int
	emax int
}

// The blob twin of the string collector above: bounds latched at the length word,
// gated on the declared subtype, with ArrayBegin alongside for the one assertion.
func (s *_bytesSeq) ArrayBegin(sofab.ID, sofab.ArrayKind, int) error { return nil }

func (s *_bytesSeq) FixlenHeader(id sofab.ID, subtype, length int) error {
	if subtype != 3 {
		return nil
	}
	if s.cap >= 0 && int(id) >= s.cap {
		return sofab.ErrInvalidMsg
	}
	if s.emax >= 0 && length > s.emax {
		return sofab.ErrInvalidMsg
	}
	return nil
}

func (s *_bytesSeq) Bytes(id sofab.ID, v []byte) error {
	if s.cap >= 0 && int(id) >= s.cap {
		return sofab.ErrInvalidMsg
	}
	if s.emax >= 0 && len(v) > s.emax {
		return sofab.ErrInvalidMsg
	}
	for len(*s.out) <= int(id) {
		*s.out = append(*s.out, nil)
	}
	(*s.out)[id] = append([]byte(nil), v...)
	return nil
}

// _objSeq collects the elements of a struct/union array: each element is a nested
// sequence decoded into the element the child id names (PT is *T and a Visitor).
// The element id IS the array index (S5.1), exactly as for the _strSeq/_bytesSeq
// leaf paths above, so the element is PLACED at out[id] after gap-filling with
// default elements -- never appended. Appending would shorten the array by the
// size of any interior id gap -- and an omitted all-default interior element is
// exactly such a gap -- and would decode a REOPENED id as a second element
// instead of merging into the first (S7.4). An element id >= cap (schema count N)
// is rejected as INVALID (S5.1/S7), which also bounds the gap-fill.
type _objSeq[T any, PT interface {
	*T
	sofab.Visitor
}] struct {
	_visitorBase
	out *[]T
	cap int
}

func (s *_objSeq[T, PT]) BeginSequence(id sofab.ID) (sofab.Visitor, error) {
	if s.cap >= 0 && int(id) >= s.cap {
		return nil, sofab.ErrInvalidMsg
	}
	var zero T
	for len(*s.out) <= int(id) {
		*s.out = append(*s.out, zero)
	}
	return PT(&(*s.out)[id]), nil
}

// _isDefaulter is implemented by every generated struct/union type: isDefault
// reports whether the object equals its declared default, compared per child
// field and recursively (S2) -- never as a byte image. It is the explicit form of
// the predicate lazy framing applies implicitly ("not one child was written"),
// generated from the very same per-field expressions the writer uses so the two
// cannot drift apart.
type _isDefaulter interface{ isDefault() bool }

// _placeRow stores a decoded row of a matrix (an array whose elements are native
// arrays) at the index its element id names, growing the outer slice with empty
// rows so an id GAP decodes as an empty row instead of shifting every later row
// down by one. Gaps are ordinary here: an interior row equal to the element
// default (the empty row) is omitted by a conformant encoder (S2), and only the
// LAST row is guaranteed present -- which is what makes the decoded length,
// highest present id + 1, exact.
//
// cap is the outer array's schema count bound N (-1 == unbounded). N is a
// capacity: it bounds the array (a row id >= N is INVALID, S5.1/S7) but never
// adds rows. Rejecting before the grow also bounds the id-keyed fill against an
// over-index amplification DoS.
func _placeRow[T any](out *[][]T, cap int, id sofab.ID, row []T) error {
	if cap >= 0 && int(id) >= cap {
		return sofab.ErrInvalidMsg
	}
	for len(*out) <= int(id) {
		*out = append(*out, nil)
	}
	(*out)[id] = row
	return nil
}

// _uMatSeq / _sMatSeq / _f32MatSeq / _f64MatSeq / _boolMatSeq collect the rows of
// a matrix (array whose elements are native arrays); each row arrives widened.
// hi/lo are the width the schema declares for a row's elements. The conversion
// below only masks, so an element outside that width has to be rejected here or
// it would be stored as a different value than the wire carried.
//
// A zero bound means the element type spans the whole range this callback can
// deliver, so nothing can fall outside it and the scan is skipped.
type _uMatSeq[T ~uint8 | ~uint16 | ~uint32 | ~uint64] struct {
	_visitorBase
	out *[][]T
	cap int
	hi  uint64
}

func (s *_uMatSeq[T]) UnsignedArray(id sofab.ID, v []uint64) error {
	if s.hi != 0 {
		for _, _x := range v {
			if _x > s.hi {
				return sofab.ErrInvalidMsg
			}
		}
	}
	return _placeRow(s.out, s.cap, id, sofab.NarrowUnsigned[T](v))
}

type _sMatSeq[T ~int8 | ~int16 | ~int32 | ~int64] struct {
	_visitorBase
	out *[][]T
	cap int
	lo  int64
	hi  int64
}

func (s *_sMatSeq[T]) SignedArray(id sofab.ID, v []int64) error {
	if s.lo != 0 {
		for _, _x := range v {
			if _x < s.lo || _x > s.hi {
				return sofab.ErrInvalidMsg
			}
		}
	}
	return _placeRow(s.out, s.cap, id, sofab.NarrowSigned[T](v))
}

type _f32MatSeq struct {
	_visitorBase
	out *[][]float32
	cap int
}

func (s *_f32MatSeq) Float32Array(id sofab.ID, v []float32) error {
	return _placeRow(s.out, s.cap, id, v)
}

type _f64MatSeq struct {
	_visitorBase
	out *[][]float64
	cap int
}

func (s *_f64MatSeq) Float64Array(id sofab.ID, v []float64) error {
	return _placeRow(s.out, s.cap, id, v)
}

type _boolMatSeq struct {
	_visitorBase
	out *[][]bool
	cap int
}

func (s *_boolMatSeq) UnsignedArray(id sofab.ID, v []uint64) error {
	row := make([]bool, len(v))
	for i, x := range v {
		row[i] = x != 0
	}
	return _placeRow(s.out, s.cap, id, row)
}

// _seqSeq collects an array whose elements are themselves wrapper-sequence arrays:
// each element opens a sequence collected into the inner slice its element id
// names, by mk. Placed at out[id], never appended, for the same reason as
// _placeRow above: an omitted all-default interior row leaves an id gap.
type _seqSeq[T any] struct {
	_visitorBase
	out *[][]T
	cap int
	mk  func(*[]T) sofab.Visitor
}

func (s *_seqSeq[T]) BeginSequence(id sofab.ID) (sofab.Visitor, error) {
	if s.cap >= 0 && int(id) >= s.cap {
		return nil, sofab.ErrInvalidMsg
	}
	for len(*s.out) <= int(id) {
		*s.out = append(*s.out, nil)
	}
	return s.mk(&(*s.out)[id]), nil
}
