// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"github.com/sofa-buffers/corelib-go"
	"math"
)

// _visitorBase supplies no-op defaults for every sofab.Visitor method, so a
// generated object overrides only the callbacks its fields actually use.
type _visitorBase struct{}

func (_visitorBase) Unsigned(sofab.ID, uint64) error               { return nil }
func (_visitorBase) Signed(sofab.ID, int64) error                  { return nil }
func (_visitorBase) Float32(sofab.ID, float32) error               { return nil }
func (_visitorBase) Float64(sofab.ID, float64) error               { return nil }
func (_visitorBase) String(sofab.ID, string) error                 { return nil }
func (_visitorBase) Bytes(sofab.ID, []byte) error                  { return nil }
func (_visitorBase) UnsignedArray(sofab.ID, []uint64) error        { return nil }
func (_visitorBase) SignedArray(sofab.ID, []int64) error           { return nil }
func (_visitorBase) Float32Array(sofab.ID, []float32) error        { return nil }
func (_visitorBase) Float64Array(sofab.ID, []float64) error        { return nil }
func (_visitorBase) BeginSequence(sofab.ID) (sofab.Visitor, error) { return _visitorBase{}, nil }
func (_visitorBase) EndSequence() error                            { return nil }

// _narrowU / _narrowS copy a 64-bit-widened native array down to its declared
// element width.
func _narrowU[T ~uint8 | ~uint16 | ~uint32 | ~uint64](v []uint64) []T {
	out := make([]T, len(v))
	for i, x := range v {
		out[i] = T(x)
	}
	return out
}

func _narrowS[T ~int8 | ~int16 | ~int32 | ~int64](v []int64) []T {
	out := make([]T, len(v))
	for i, x := range v {
		out[i] = T(x)
	}
	return out
}

// _trimTail / _trimTailF32 / _trimTailF64 return a[:M'], where M' is one past the
// last element that differs from the element default (0 if every element is the
// default). A fixed-count array's canonical wire carries exactly those M'
// elements; the decoder rebuilds the trailing default run from the schema count
// (MESSAGE_SPEC S3). Elements compare by BIT PATTERN, not by ==, so a trailing
// -0.0 (which == 0.0) survives the round-trip instead of being silently trimmed
// to +0.0.
func _trimTail[T comparable](a []T, zero T) []T {
	n := len(a)
	for n > 0 && a[n-1] == zero {
		n--
	}
	return a[:n]
}

func _trimTailF32(a []float32) []float32 {
	n := len(a)
	for n > 0 && math.Float32bits(a[n-1]) == 0 {
		n--
	}
	return a[:n]
}

func _trimTailF64(a []float64) []float64 {
	n := len(a)
	for n > 0 && math.Float64bits(a[n-1]) == 0 {
		n--
	}
	return a[:n]
}

// _padTo grows a to exactly n elements with the element default. A fixed-count
// array decodes to exactly its schema count regardless of the wire count, so a
// growable container must materialize the trailing default run the encoder
// elided (MESSAGE_SPEC S3).
func _padTo[T any](a []T, n int, zero T) []T {
	for len(a) < n {
		a = append(a, zero)
	}
	return a
}

// _strSeq / _bytesSeq collect the elements of a string / blob array. Elements are
// keyed by index id: a default (empty) element is omitted on the
// wire, so we place each value at its id and fill any gap with the element default
// ("" / nil). Blob copies (the corelib value aliases the decode buffer).
type _strSeq struct {
	_visitorBase
	out *[]string
}

func (s *_strSeq) String(id sofab.ID, v string) error {
	for len(*s.out) <= int(id) {
		*s.out = append(*s.out, "")
	}
	(*s.out)[id] = v
	return nil
}

type _bytesSeq struct {
	_visitorBase
	out *[][]byte
}

func (s *_bytesSeq) Bytes(id sofab.ID, v []byte) error {
	for len(*s.out) <= int(id) {
		*s.out = append(*s.out, nil)
	}
	(*s.out)[id] = append([]byte(nil), v...)
	return nil
}

// _objSeq collects the elements of a struct/union array: each element is a nested
// sequence decoded into a freshly appended T (PT is *T and a Visitor).
type _objSeq[T any, PT interface {
	*T
	sofab.Visitor
}] struct {
	_visitorBase
	out *[]T
}

func (s *_objSeq[T, PT]) BeginSequence(_ sofab.ID) (sofab.Visitor, error) {
	var zero T
	*s.out = append(*s.out, zero)
	return PT(&(*s.out)[len(*s.out)-1]), nil
}

// _uMatSeq / _sMatSeq / _f32MatSeq / _f64MatSeq / _boolMatSeq collect the rows of
// a matrix (array whose elements are native arrays); each row arrives widened.
type _uMatSeq[T ~uint8 | ~uint16 | ~uint32 | ~uint64] struct {
	_visitorBase
	out *[][]T
}

func (s *_uMatSeq[T]) UnsignedArray(_ sofab.ID, v []uint64) error {
	*s.out = append(*s.out, _narrowU[T](v))
	return nil
}

type _sMatSeq[T ~int8 | ~int16 | ~int32 | ~int64] struct {
	_visitorBase
	out *[][]T
}

func (s *_sMatSeq[T]) SignedArray(_ sofab.ID, v []int64) error {
	*s.out = append(*s.out, _narrowS[T](v))
	return nil
}

type _f32MatSeq struct {
	_visitorBase
	out *[][]float32
}

func (s *_f32MatSeq) Float32Array(_ sofab.ID, v []float32) error {
	*s.out = append(*s.out, v)
	return nil
}

type _f64MatSeq struct {
	_visitorBase
	out *[][]float64
}

func (s *_f64MatSeq) Float64Array(_ sofab.ID, v []float64) error {
	*s.out = append(*s.out, v)
	return nil
}

type _boolMatSeq struct {
	_visitorBase
	out *[][]bool
}

func (s *_boolMatSeq) UnsignedArray(_ sofab.ID, v []uint64) error {
	row := make([]bool, len(v))
	for i, x := range v {
		row[i] = x != 0
	}
	*s.out = append(*s.out, row)
	return nil
}

// _seqSeq collects an array whose elements are themselves wrapper-sequence arrays:
// each element opens a sequence collected into a fresh inner slice by mk.
type _seqSeq[T any] struct {
	_visitorBase
	out *[][]T
	mk  func(*[]T) sofab.Visitor
}

func (s *_seqSeq[T]) BeginSequence(_ sofab.ID) (sofab.Visitor, error) {
	*s.out = append(*s.out, nil)
	return s.mk(&(*s.out)[len(*s.out)-1]), nil
}
