package kotlin

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// projectFiles scaffolds a Gradle project with a canonical-JSON encode/decode
// harness over corelib-kotlin-mp.
//
// The generated MESSAGE sources are plain `commonMain` Kotlin -- stdlib plus
// `sofab`, no JVM API -- so they drop into a multiplatform source set unchanged.
// The project around them is a JVM one, because a harness needs a `main`, a
// process exit code and a stdin: the scaffolding is where the platform gets
// picked, never the code that encodes.
//
// JSON is parsed by hand rather than with a library so a u64 above 2^53 stays
// exact and the project has no dependency the corelib does not.
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any, dir string) []generator.File {
	return []generator.File{
		{Path: "settings.gradle.kts", Content: []byte(g.settingsGradle())},
		{Path: "build.gradle.kts", Content: []byte(g.buildGradle())},
		{Path: dir + "Json.kt", Content: g.jsonHelper(s)},
		{Path: dir + "Main.kt", Content: g.mainHarness(s)},
		{Path: "README.md", Content: []byte("# Generated SofaBuffers Kotlin project\n\n" +
			"`@generated by sofabgen`. Build and run the harness:\n\n" +
			"```sh\n./gradlew installDist\nbuild/install/harness/bin/harness encode <message> < in.json\n```\n\n" +
			"The sources under `src/main/kotlin` are plain `commonMain` Kotlin (stdlib +\n" +
			"`sofab` only), so they can be moved into a Kotlin Multiplatform source set\n" +
			"as they are; only this project scaffolding is JVM-specific.\n")},
	}
}

func (g *gen) settingsGradle() string {
	return `// @generated by sofabgen
rootProject.name = "harness"

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        // mavenLocal first so a conformance run resolves the corelib build under
        // test rather than a published release.
        mavenLocal()
        mavenCentral()
    }
}
`
}

func (g *gen) buildGradle() string {
	return `// @generated by sofabgen
plugins {
    kotlin("jvm") version "2.4.10"
    application
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.sofabuffers:corelib-kotlin-mp:" + (findProperty("sofab.version") ?: "0.1.0"))
}

kotlin {
    jvmToolchain((findProperty("sofab.jdk") as String? ?: "21").toInt())
}

application {
    mainClass.set("` + g.pkg + `.MainKt")
}
`
}

// benchSinkField names one cheap integer scalar of m, folded into the bench loop
// so the decode cannot be elided. It runs inside the measured loop, so it must
// stay cheap -- rendering JSON there would be counted as decode cost.
func benchSinkField(m *ir.Message) *ir.Field {
	for _, f := range m.Fields {
		switch f.Kind {
		case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64,
			ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
			return f
		}
	}
	return nil
}

// emitBench emits the `bench <workload> <reps>` entry point (tests/bench,
// ARCHITECTURE §15).
//
// The JVM JIT-compiles the hot path at runtime, so there is no native symbol to
// --toggle-collect on. This is the `subtract` method: tests/bench runs the same
// workload at two rep counts and subtracts the totals,
//
//	Ir/op = ( Ir(R2) - Ir(R1) ) / ( R2 - R1 )
//
// which cancels JVM startup, class loading, JIT compilation and setup exactly.
//
// That only holds if the two runs differ in NOTHING but the rep count, which
// needs both halves of the contract:
//   - here: a FIXED warmup, independent of reps, so the hot methods reach their
//     final tier BEFORE the measured loop and every measured op runs at steady
//     cost;
//   - in tests/bench/lang/kotlin.sh: -XX:-TieredCompilation (one tier, no mid-run
//     transition), -XX:+UseEpsilonGC with a fixed heap (no GC at all), and
//     -XX:hashCode=2 (identity hashes are otherwise seeded per run).
func (g *gen) emitBench(f *kfile, s *ir.Schema) {
	f.line("// Fixed warmup ops per run, independent of `reps`, so it cancels in the")
	f.line("// subtraction while leaving the measured ops at steady, fully-JITted cost.")
	f.line("private val WARMUP: Int = (System.getProperty(\"sofab.warmup\") ?: \"5000\").toInt()")
	f.line("private var benchSink: Long = 0")
	f.blank()
	for _, m := range s.Messages {
		mt := exported(m.Name)
		low := strings.ToLower(m.Name)
		sink := benchSinkField(m)
		f.line("private fun benchOp%s(enc: Boolean, obj: %s, wire: ByteArray) {", mt, mt)
		f.line("    if (enc) {")
		f.line("        benchSink = benchSink xor obj.encode().size.toLong()")
		f.line("    } else {")
		if sink != nil {
			f.line("        benchSink = benchSink xor %s.decode(wire).%s.toLong()", mt, ktIdent(sink.Name))
		} else {
			f.line("        benchSink = benchSink xor %s.decode(wire).hashCode().toLong()", mt)
		}
		f.line("    }")
		f.line("}")
		f.blank()
		_ = low
	}
	f.line("private fun benchMain(w: String, reps: Int, input: ByteArray): Int {")
	for _, m := range s.Messages {
		mt := exported(m.Name)
		low := strings.ToLower(m.Name)
		f.line("    if (w == \"encode_%s\" || w == \"decode_%s\") {", low, low)
		f.line("        val obj = %s()", mt)
		f.line("        Json.from(JsonValue.parse(input.decodeToString()).obj(), obj)")
		f.line("        val wire = obj.encode()   // setup: the decode input")
		f.line("        val enc = w == \"encode_%s\"", low)
		f.line("        for (i in 0 until WARMUP) benchOp%s(enc, obj, wire)", mt)
		f.line("        for (i in 0 until reps) benchOp%s(enc, obj, wire)", mt)
		f.line("        System.err.println(\"sink=\" + benchSink + \" bytes=\" + wire.size)")
		f.line("        val hx = StringBuilder()")
		f.line("        for (b in wire) hx.append(\"0123456789abcdef\"[(b.toInt() shr 4) and 0xF]).append(\"0123456789abcdef\"[b.toInt() and 0xF])")
		f.line("        System.err.println(\"wire_hex=\" + hx)")
		f.line("        return 0")
		f.line("    }")
	}
	f.line("    System.err.println(\"unknown workload: \" + w)")
	f.line("    return 2")
	f.line("}")
	f.blank()
}

func (g *gen) mainHarness(s *ir.Schema) []byte {
	f := &kfile{}
	g.header(f)
	g.emitBench(f, s)
	f.line("public fun main(args: Array<String>) {")
	f.line("    val mode = if (args.isNotEmpty()) args[0] else \"\"")
	f.line("    val name = if (args.size > 1) args[1] else %s", ktStringLit(defaultMessage(s)))
	f.line("    val input = System.`in`.readBytes()")
	f.line("    // `bench <workload> <reps>` takes a workload, not a message name.")
	f.line("    if (mode == \"bench\") {")
	f.line("        kotlin.system.exitProcess(benchMain(name, if (args.size > 2) args[2].toInt() else 1000, input))")
	f.line("    }")
	f.line("    when (name) {")
	for _, m := range s.Messages {
		mt := exported(m.Name)
		f.line("        %s -> {", ktStringLit(m.Name))
		f.line("            when (mode) {")
		f.line("                \"encode\" -> {")
		f.line("                    val obj = %s()", mt)
		f.line("                    Json.from(JsonValue.parse(input.decodeToString()).obj(), obj)")
		f.line("                    System.out.write(obj.encode())")
		f.line("                }")
		f.line("                \"decode\" -> {")
		f.line("                    val obj = %s.decode(input)", mt)
		f.line("                    val sb = StringBuilder(); Json.to(obj, sb)")
		f.line("                    System.out.write(sb.toString().encodeToByteArray()); System.out.write('\\n'.code)")
		f.line("                }")
		f.line("                \"stream\" -> {")
		f.line("                    // Both streaming halves, against the one-shot pair as the oracle.")
		f.line("                    //")
		f.line("                    // OUT: a ONE-BYTE window with a flush sink. The corelib splits every")
		f.line("                    // atomic unit, so any buffer at or above MIN_OUTPUT_BUFFER must produce")
		f.line("                    // output byte-identical to the one-shot path -- which is the property")
		f.line("                    // that makes a message larger than RAM encodable at all, and the one a")
		f.line("                    // generated serialize can break by holding something back itself.")
		f.line("                    //")
		f.line("                    // IN: those same bytes fed ONE AT A TIME. Decoder state has to survive")
		f.line("                    // a boundary at every single byte offset, so the JSON printed here is")
		f.line("                    // compared against the `decode` mode's by the conformance runner.")
		f.line("                    val obj = %s()", mt)
		f.line("                    Json.from(JsonValue.parse(input.decodeToString()).obj(), obj)")
		f.line("                    val oneShot = obj.encode()")
		f.line("                    val acc = Sbuf.Acc()")
		f.line("                    val os = OStream(ByteArray(1), 0, FlushSink { data, off, len -> acc.write(data, off, len) })")
		f.line("                    obj.encodeTo(os)")
		f.line("                    val streamed = acc.toByteArray()")
		f.line("                    if (!oneShot.contentEquals(streamed)) {")
		f.line("                        System.err.println(\"stream: a 1-byte output buffer changed the bytes\")")
		f.line("                        kotlin.system.exitProcess(2)")
		f.line("                    }")
		f.line("                    val dec = %s.decoder()", mt)
		f.line("                    for (b in streamed) dec.feed(byteArrayOf(b))")
		f.line("                    val back = dec.finish()")
		f.line("                    val sb = StringBuilder(); Json.to(back, sb)")
		f.line("                    System.out.write(sb.toString().encodeToByteArray()); System.out.write('\\n'.code)")
		f.line("                }")
		f.line("                \"trydecode\" -> {")
		f.line("                    val obj = %s()", mt)
		f.line("                    val st = %s.tryDecode(input, obj)", mt)
		f.line("                    System.out.write((st.name + \"\\n\").encodeToByteArray())")
		f.line("                    val sb = StringBuilder(); Json.to(obj, sb)")
		f.line("                    System.out.write(sb.toString().encodeToByteArray()); System.out.write('\\n'.code)")
		f.line("                }")
		f.line("                else -> { System.err.println(\"unknown mode\"); kotlin.system.exitProcess(2) }")
		f.line("            }")
		f.line("        }")
	}
	f.line("        else -> { System.err.println(\"unknown message\"); kotlin.system.exitProcess(2) }")
	f.line("    }")
	f.line("    System.out.flush()")
	f.line("}")
	return f.bytes()
}

// ---------------------------------------------------------------------------
// The canonical-JSON harness
// ---------------------------------------------------------------------------

// jsonHelper emits Json.kt: to/from canonical JSON for every generated object,
// plus a tiny hand-written JSON reader.
//
// The reader exists so the project depends on nothing but the corelib, and so a
// `u64` above 2^53 stays exact: a number is kept as its literal TEXT and parsed
// at the field's declared width, which a double-based parser cannot do.
func (g *gen) jsonHelper(s *ir.Schema) []byte {
	f := &kfile{}
	g.header(f)
	f.line("%s", jsonReader)
	f.blank()
	f.line("internal object Json {")

	emitted := map[string]bool{}
	for _, m := range s.Messages {
		for _, key := range g.reachable(m) {
			nt := s.Named[key]
			if (nt.Category == ir.CatStruct || nt.Category == ir.CatUnion) && !emitted[key] {
				emitted[key] = true
				g.emitJSONFns(f, g.typeName(key), nt.Fields)
			}
		}
		g.emitJSONFns(f, exported(m.Name), m.Fields)
	}

	f.line("    internal fun str(b: StringBuilder, s: String) {")
	f.line("        b.append('\"')")
	f.line("        for (c in s) {")
	f.line("            when {")
	f.line("                c == '\"' || c == '\\\\' -> b.append('\\\\').append(c)")
	f.line("                c == '\\n' -> b.append(\"\\\\n\")")
	f.line("                c == '\\t' -> b.append(\"\\\\t\")")
	f.line("                c.code < 0x20 -> b.append(\"\\\\u\").append(c.code.toString(16).padStart(4, '0'))")
	f.line("                else -> b.append(c)")
	f.line("            }")
	f.line("        }")
	f.line("        b.append('\"')")
	f.line("    }")
	f.line("    internal fun bytes(b: StringBuilder, a: ByteArray) {")
	f.line("        b.append('[')")
	f.line("        for (i in a.indices) { if (i > 0) b.append(','); b.append(a[i].toInt() and 0xFF) }")
	f.line("        b.append(']')")
	f.line("    }")
	f.line("    internal fun toBytes(a: List<JsonValue>): ByteArray {")
	f.line("        val r = ByteArray(a.size)")
	f.line("        for (i in a.indices) r[i] = a[i].num().toInt().toByte()")
	f.line("        return r")
	f.line("    }")
	f.line("}")
	return f.bytes()
}

func (g *gen) emitJSONFns(f *kfile, typeName string, fields []*ir.Field) {
	// to
	f.line("    internal fun to(o: %s, b: StringBuilder) {", typeName)
	f.line("        b.append('{')")
	for i, fld := range fields {
		if i > 0 {
			f.line("        b.append(',')")
		}
		f.line("        b.append(%s)", ktStringLit("\""+fld.Name+"\":"))
		g.emitTo(f, fld)
	}
	f.line("        b.append('}')")
	f.line("    }")
	// from
	f.line("    internal fun from(j: Map<String, JsonValue>, o: %s) {", typeName)
	f.line("        var e: JsonValue?")
	for _, fld := range fields {
		f.line("        e = j[%s]", ktStringLit(fld.Name))
		f.line("        if (e != null && !e.isNull) {")
		g.emitFrom(f, fld)
		f.line("        }")
	}
	if len(fields) == 0 {
		f.line("        // no fields")
	}
	f.line("    }")
}

func (g *gen) emitTo(f *kfile, fld *ir.Field) {
	acc := "o." + ktIdent(fld.Name)
	switch fld.Kind {
	case ir.KindString:
		f.line("        Json.str(b, %s)", acc)
	case ir.KindBlob:
		f.line("        Json.bytes(b, %s)", acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("        to(%s, b)", acc)
	case ir.KindArray:
		g.jsonToArray(f, "        ", acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
	default:
		f.line("        b.append(%s)", acc)
	}
}

// jsonToArray writes val as a JSON array. struct/union elements recurse via
// to(); nested arrays recurse; everything else prints as its own value, which
// for the unsigned widths is already the VALUE (the member holds a UByte, not a
// widened byte).
func (g *gen) jsonToArray(f *kfile, ind, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	el := fmt.Sprintf("%s[%s]", val, iv)
	f.line("%sb.append('[')", ind)
	f.line("%sfor (%s in %s.indices) {", ind, iv, val)
	f.line("%s    if (%s > 0) b.append(',')", ind, iv)
	switch elem {
	case ir.KindString:
		f.line("%s    Json.str(b, %s)", ind, el)
	case ir.KindBlob:
		f.line("%s    Json.bytes(b, %s)", ind, el)
	case ir.KindStruct, ir.KindUnion:
		f.line("%s    to(%s, b)", ind, el)
	case ir.KindArray:
		g.jsonToArray(f, ind+"    ", el, items.Elem, items.ElemRef, items.ElemItems, depth+1)
	default:
		f.line("%s    b.append(%s)", ind, el)
	}
	f.line("%s}", ind)
	f.line("%sb.append(']')", ind)
}

func (g *gen) emitFrom(f *kfile, fld *ir.Field) {
	acc := "o." + ktIdent(fld.Name)
	switch fld.Kind {
	case ir.KindString:
		f.line("            %s = e.str()", acc)
	case ir.KindBlob:
		f.line("            %s = Json.toBytes(e.arr())", acc)
	case ir.KindBool:
		f.line("            %s = e.bool()", acc)
	case ir.KindFP32:
		f.line("            %s = e.num().toFloat()", acc)
	case ir.KindFP64:
		f.line("            %s = e.num()", acc)
	case ir.KindStruct, ir.KindUnion:
		f.line("            from(e.obj(), %s)", acc)
	case ir.KindArray:
		g.jsonFromArray(f, "            ", acc, "e.arr()", fld.Elem, fld.ElemRef, fld.ElemItems, 0)
	default:
		f.line("            %s = %s", acc, jsonIntRead(fld.Kind, "e"))
	}
}

// jsonIntRead parses an integer element at the member's declared width. The
// literal TEXT is what is parsed, never a double, so a u64 above 2^53 survives.
func jsonIntRead(k ir.Kind, v string) string {
	switch k {
	case ir.KindU8:
		return v + ".uint().toUByte()"
	case ir.KindU16:
		return v + ".uint().toUShort()"
	case ir.KindU32:
		return v + ".uint().toUInt()"
	case ir.KindU64, ir.KindBitfield:
		return v + ".uint()"
	case ir.KindI8:
		return v + ".int().toByte()"
	case ir.KindI16:
		return v + ".int().toShort()"
	case ir.KindI32, ir.KindEnum:
		return v + ".int().toInt()"
	case ir.KindI64:
		return v + ".int()"
	}
	return v + ".int()"
}

// jsonFromArray rebuilds target from the JSON array src, mirroring jsonToArray.
func (g *gen) jsonFromArray(f *kfile, ind, target, src string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	av := fmt.Sprintf("_a%d", depth)
	kv := fmt.Sprintf("_k%d", depth)
	f.line("%sval %s = %s", ind, av, src)
	if nativeArrayElem(elem) {
		arrType := primArrayType(elem)
		f.line("%s%s = %s(%s.size)", ind, target, arrType, av)
		var rhs string
		switch elem {
		case ir.KindBool:
			rhs = av + "[" + kv + "].bool()"
		case ir.KindFP32:
			rhs = av + "[" + kv + "].num().toFloat()"
		case ir.KindFP64:
			rhs = av + "[" + kv + "].num()"
		default:
			rhs = jsonIntRead(elem, av+"["+kv+"]")
		}
		f.line("%sfor (%s in %s.indices) %s[%s] = %s", ind, kv, av, target, kv, rhs)
		return
	}
	ev := fmt.Sprintf("_e%d", depth)
	f.line("%s%s.clear()", ind, target)
	f.line("%sfor (%s in %s) {", ind, ev, av)
	switch elem {
	case ir.KindString:
		f.line("%s    %s.add(%s.str())", ind, target, ev)
	case ir.KindBlob:
		f.line("%s    %s.add(Json.toBytes(%s.arr()))", ind, target, ev)
	case ir.KindStruct, ir.KindUnion:
		vv := fmt.Sprintf("_v%d", depth)
		f.line("%s    val %s = %s()", ind, vv, g.typeName(ref.Key))
		f.line("%s    from(%s.obj(), %s)", ind, ev, vv)
		f.line("%s    %s.add(%s)", ind, target, vv)
	case ir.KindArray:
		vv := fmt.Sprintf("_v%d", depth)
		f.line("%s    var %s: %s = %s", ind, vv, g.ktArrayType(items.Elem, items.ElemRef, items.ElemItems), g.emptyArrayInit(items.Elem, items.ElemRef, items.ElemItems))
		g.jsonFromArray(f, ind+"    ", vv, ev+".arr()", items.Elem, items.ElemRef, items.ElemItems, depth+1)
		f.line("%s    %s.add(%s)", ind, target, vv)
	}
	f.line("%s}", ind)
}

// emptyArrayInit is the fresh, empty container a nested JSON row is built into.
func (g *gen) emptyArrayInit(elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem) string {
	if nativeArrayElem(elem) {
		return emptyArrayExpr(primArrayType(elem))
	}
	return "mutableListOf()"
}

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

// jsonReader is the hand-written JSON value model the harness parses into.
//
// A NUMBER is kept as its literal text: canonical JSON carries a `u64` as a
// number, and every double-based parser in reach rounds 18446744073709551615 to
// 2^64. Parsing the text at the field's declared width is the only way the
// round-trip stays exact, and the vectors check exactly that.
const jsonReader = `internal class JsonValue private constructor(
    private val kind: Int,
    private val text: String = "",
    private val items: List<JsonValue> = emptyList(),
    private val members: Map<String, JsonValue> = emptyMap(),
) {
    internal val isNull: Boolean get() = kind == NULL

    internal fun str(): String = text
    internal fun num(): Double = when (text) {
        "Infinity", "inf" -> Double.POSITIVE_INFINITY
        "-Infinity", "-inf" -> Double.NEGATIVE_INFINITY
        "NaN", "nan" -> Double.NaN
        else -> text.toDouble()
    }
    internal fun int(): Long = text.toLong()
    internal fun uint(): ULong = text.toULong()
    internal fun bool(): Boolean = text == "true"
    internal fun arr(): List<JsonValue> = items
    internal fun obj(): Map<String, JsonValue> = members

    internal companion object {
        private const val NULL = 0
        private const val LIT = 1
        private const val STR = 2
        private const val ARR = 3
        private const val OBJ = 4

        internal fun parse(s: String): JsonValue {
            val p = P(s)
            p.ws()
            val v = p.value()
            p.ws()
            return v
        }
    }

    private class P(val s: String) {
        var i = 0
        fun ws() { while (i < s.length && s[i].isWhitespace()) i++ }
        fun value(): JsonValue {
            ws()
            return when (s[i]) {
                '{' -> obj()
                '[' -> arr()
                '"' -> JsonValue(STR, str())
                else -> lit()
            }
        }
        fun obj(): JsonValue {
            val m = LinkedHashMap<String, JsonValue>()
            i++ // {
            ws()
            if (s[i] == '}') { i++; return JsonValue(OBJ, members = m) }
            while (true) {
                ws()
                val k = str()
                ws(); i++ // :
                m[k] = value()
                ws()
                if (s[i] == ',') { i++; continue }
                i++ // }
                break
            }
            return JsonValue(OBJ, members = m)
        }
        fun arr(): JsonValue {
            val l = ArrayList<JsonValue>()
            i++ // [
            ws()
            if (s[i] == ']') { i++; return JsonValue(ARR, items = l) }
            while (true) {
                l.add(value())
                ws()
                if (s[i] == ',') { i++; continue }
                i++ // ]
                break
            }
            return JsonValue(ARR, items = l)
        }
        fun str(): String {
            val b = StringBuilder()
            i++ // "
            while (s[i] != '"') {
                if (s[i] == '\\') {
                    i++
                    when (s[i]) {
                        'n' -> b.append('\n')
                        't' -> b.append('\t')
                        'r' -> b.append('\r')
                        'b' -> b.append('\b')
                        'f' -> b.append('\u000C')
                        'u' -> { b.append(s.substring(i + 1, i + 5).toInt(16).toChar()); i += 4 }
                        else -> b.append(s[i])
                    }
                } else {
                    b.append(s[i])
                }
                i++
            }
            i++ // "
            return b.toString()
        }
        fun lit(): JsonValue {
            val start = i
            while (i < s.length && s[i] !in ",]} \t\r\n") i++
            val t = s.substring(start, i)
            return if (t == "null") JsonValue(NULL, t) else JsonValue(LIT, t)
        }
    }
}`
