package kotlin

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/analysis"
	"github.com/sofa-buffers/generator/internal/model"
	"github.com/sofa-buffers/generator/internal/naming"
	"github.com/sofa-buffers/generator/internal/parser"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/kotlin/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every name on the Kotlin list, sorted.
func reservedNames() []string {
	var names []string
	for _, set := range []map[string]bool{ktHardKeywords, ktReservedMembers, ktQualifiers, unionReserved} {
		for n := range set {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	return names
}

// outerNames is every name on ktOuterNames, sorted.
func outerNames() []string {
	var names []string
	for n := range ktOuterNames {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// splitFoldTwins keeps the first name of every fold and returns the rest apart:
// `Decoder` and `decoder` are both on the member list, and names in one scope
// must differ in more than case (ARCHITECTURE §8, "Naming"), so the second of
// such a pair goes to a message of its own, m2.
func splitFoldTwins(names []string) (first, twins []int) {
	seen := map[string]bool{}
	for i, n := range names {
		if seen[naming.Fold(n)] {
			twins = append(twins, i)
			continue
		}
		seen[naming.Fold(n)] = true
		first = append(first, i)
	}
	return first, twins
}

// reservedYAML is a schema that uses every reserved member name as a field of a
// message, of a nested struct, and as an option of a union, plus the one path
// clash a decoder frame name can hit: inner.inner2 beside a field inner_inner2.
// Next to them sit the member pairs the JVM or the class scope used to refuse
// (`isOpen` and `open` share setOpen, `getX` beside `x`, an option `A_ID`
// beside `a`'s A_ID, `hasFoo` beside `foo`'s hasFoo()). Every name on
// ktOuterNames is a type: every other one a message, the rest $defs structs
// that message `outer` uses. Names are quoted: `true`, `false` and `null` are
// YAML scalars.
func reservedYAML(names, outer []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/kotlin/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/kotlin -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field must compile warning-free and round-trip,\n")
	b.WriteString("# and every reserved type name as a message or a $defs type must compile.\n")
	first, twins := splitFoldTwins(names)
	var fields, fields2 strings.Builder
	var opts []string
	for _, i := range first {
		fmt.Fprintf(&fields, "      %q: { id: %d, type: u8 }\n", names[i], i)
		opts = append(opts, fmt.Sprintf("%q: { id: %d, type: u8 }", names[i], i))
	}
	for _, i := range twins {
		fmt.Fprintf(&fields2, "      %q: { id: %d, type: u8 }\n", names[i], i)
	}
	var defs, msgs, uses strings.Builder
	for i, n := range outer {
		if i%2 == 1 {
			fmt.Fprintf(&defs, "    %s: { x: { id: 0, type: u8 } }\n", n)
			fmt.Fprintf(&uses, "      t%d: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/%s' } }\n", i, i, n)
			continue
		}
		fmt.Fprintf(&msgs, "  %s: { payload: { x: { id: 0, type: u8 } } }\n", n)
	}
	k := len(names)
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
%smessages:
  m:
    payload:
%s      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      u:            { id: %d, type: union, oneof: { %s } }
      open:         { id: %d, type: u8 }
      isOpen:       { id: %d, type: u8 }
      getX:         { id: %d, type: u8 }
      x:            { id: %d, type: u8 }
      u2:           { id: %d, type: union, oneof: { a: { id: 0, type: u8 }, A_ID: { id: 1, type: u8 }, foo: { id: 2, type: u8 }, hasFoo: { id: 3, type: u8 }, open: { id: 4, type: u8 }, isOpen: { id: 5, type: u8 } } }
  m2:
    payload:
%s  outer:
    payload:
%s%s`, fields.String(), k, defs.String(), fields.String(), k, k+1, k+2, strings.Join(opts, ", "),
		k+3, k+4, k+5, k+6, k+7, fields2.String(), uses.String(), msgs.String())
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field, nested one,
// both sides of the path clash, the accessor pairs, and the last option of each
// union at a non-default value, each under its schema name.
func reservedJSON(names []string) string {
	top := map[string]any{}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	first, _ := splitFoldTwins(names)
	for _, i := range first {
		top[names[i]] = i + 1
		inner[names[i]] = i + 2
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{names[first[len(first)-1]]: 9}
	top["open"], top["isOpen"], top["getX"], top["x"] = 11, 12, 13, 14
	top["u2"] = map[string]any{"isOpen": 15}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite builds that file warning-free and
// round-trips it (tests/conformance/kotlin/run.sh), so a name added to
// reserved.go is covered once the file is regenerated -- and this test fails
// until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := reservedNames()
	for path, want := range map[string]string{
		"../../tests/conformance/kotlin/reserved.yaml": reservedYAML(names, outerNames()),
		"../../tests/conformance/kotlin/reserved.json": reservedJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// TestReservedNamesAreEscaped: a hard keyword is a backticked property, a
// declaration clash is `name_`, and a union-only member is a property as it is --
// wherever the schema declares it.
func TestReservedNamesAreEscaped(t *testing.T) {
	names := reservedNames()
	src := reservedYAML(names, outerNames())
	inM2 := src[strings.Index(src, "\n  m2:\n"):strings.Index(src, "\n  outer:\n")]
	var all strings.Builder
	for _, c := range genFromYAML(t, src, map[string]any{}) {
		all.WriteString(c)
	}
	for _, n := range names {
		want := ktIdent(n)
		re := regexp.MustCompile(`(?m)^    public var ` + regexp.QuoteMeta(want) + `: UByte = `)
		wantN := 2 // m and Inner
		if strings.Contains(inM2, fmt.Sprintf("%q:", n)) {
			wantN = 1 // m2 only
		}
		if got := len(re.FindAllString(all.String(), -1)); got != wantN {
			t.Errorf("field %q is the property %s in %d classes, want %d", n, want, got, wantN)
		}
	}
}

// TestFieldNamesAreNeverRefused: no valid schema is refused for its member
// names (ARCHITECTURE §8). `getX` beside `x` was, though they give getGetX and
// getX. `isOpen` beside `open` does share the JVM setter setOpen, and the `is`
// property's setter is renamed for it -- only there: `isOpen` alone keeps its
// JVM name. The same holds for union options.
func TestFieldNamesAreNeverRefused(t *testing.T) {
	const rename = "@set:kotlin.jvm.JvmName(\"setIsOpen__\")\n    public var isOpen: UByte"
	for _, c := range []struct {
		names  []string
		rename bool
	}{
		{[]string{"getX", "x"}, false},
		{[]string{"isOpen", "open"}, true},
		{[]string{"isOpen", "Open"}, true},
		{[]string{"isOpen"}, false},
		{[]string{"isOpen", "getOpen", "setOpen_x"}, false},
	} {
		var fields, opts []string
		for i, n := range c.names {
			fields = append(fields, fmt.Sprintf("      %s: { id: %d, type: u8 }", n, i))
			opts = append(opts, fmt.Sprintf("%s: { id: %d, type: u8 }", n, i))
		}
		src := "version: 1\nmessages:\n  m:\n    payload:\n" + strings.Join(fields, "\n") + "\n" +
			"  n:\n    payload:\n      u: { id: 0, type: union, oneof: { " + strings.Join(opts, ", ") + " } }\n"
		out := genFromYAML(t, src, map[string]any{})
		for _, f := range []string{"M.kt", "N_U.kt"} {
			if got := strings.Contains(out["src/main/kotlin/message/"+f], rename); got != c.rename {
				t.Errorf("%v in %s: setter renamed = %v, want %v", c.names, f, got, c.rename)
			}
		}
	}
}

// TestFrameNamesAreDistinct: decoder frames are named by the schema path joined
// with `_` and looked up by name, so the path a.b and a field a_b must be two
// frames -- sharing one, the decoder stored the field a_b into a.b.
func TestFrameNamesAreDistinct(t *testing.T) {
	src := "version: 1\n$defs:\n  struct:\n    B: { x: { id: 0, type: u8 } }\n    A: { b: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/B' } } }\n" +
		"messages:\n  m:\n    payload:\n      a: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/A' } }\n      a_b: { id: 1, type: struct, fields: { $ref: '#/$defs/struct/B' } }\n"
	doc, err := parser.Parse([]byte(src), "f.yaml")
	if err != nil {
		t.Fatal(err)
	}
	s, err := model.Build(doc)
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.Analyze(s); err != nil {
		t.Fatal(err)
	}
	seen := map[string]bool{}
	for _, fr := range (&gen{schema: s}).frames(s.Messages[0]) {
		if seen[fr.loc] {
			t.Errorf("two decoder frames are both named %s", fr.loc)
		}
		seen[fr.loc] = true
	}
	if !seen["Root_a_b"] || !seen["Root_a__b"] {
		t.Errorf("want frames Root_a_b and Root_a__b, got %v", seen)
	}
}

var (
	ktBlank = regexp.MustCompile(`(?s)/\*.*?\*/|//[^\n]*|"""(?:.|\n)*?"""|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'`)
	ktClass = regexp.MustCompile(`(?m)^(?:public )?(?:data |open )?class \w+[^{\n]*\{`)
	ktDecl  = regexp.MustCompile(`\b(fun|val|var|class|object|interface)\s+(?:<[^>]*>\s*)?` + "`?" + `(\w+)`)
	ktQual  = regexp.MustCompile(`(?:^|[^\w.])([A-Za-z_]\w*)\.[A-Za-z_]`)
	ktOptID = regexp.MustCompile(`^[A-Z0-9_]+_ID$|^(has|mutable)[A-Z]`)
	// An annotation names a TYPE, which no property shadows.
	ktAnnot = regexp.MustCompile(`@(?:\w+:)?[\w.]+`)
)

// ktScope walks the public top-level class of one generated file and returns the
// declarations at class level or inside its companion object, as "<kind> <name>"
// (kind "companion" for the latter), and the upper-case qualifiers its body uses.
func ktScope(src string) (decls, quals []string) {
	src = ktBlank.ReplaceAllString(src, `""`)
	src = ktAnnot.ReplaceAllString(src, "")
	loc := ktClass.FindStringIndex(src)
	if loc == nil {
		return nil, nil
	}
	depth, compDepth := 1, 0
	lines := strings.Split(src[loc[1]:], "\n")
	var body strings.Builder
	for _, line := range lines {
		if depth == 0 {
			break
		}
		lineDepth := depth
		if lineDepth == 1 && strings.Contains(line, "companion object") {
			compDepth = 2
		}
		for _, d := range ktDecl.FindAllStringSubmatch(line, -1) {
			switch {
			case lineDepth == 1 && !strings.Contains(line, "companion object"):
				decls = append(decls, d[1]+" "+d[2])
			case compDepth != 0 && lineDepth == compDepth:
				decls = append(decls, "companion "+d[2])
			}
		}
		for _, c := range line {
			switch c {
			case '{':
				depth++
			case '}':
				depth--
				if compDepth != 0 && depth < compDepth {
					compDepth = 0
				}
			}
		}
		body.WriteString(line + "\n")
	}
	for _, m := range ktQual.FindAllStringSubmatch(body.String(), -1) {
		if n := m[1]; n[0] >= 'A' && n[0] <= 'Z' || n == "kotlin" || n == "java" {
			quals = append(quals, n)
		}
	}
	return decls, quals
}

// TestKotlinNamesInScope is the drift guard for ktReservedMembers and
// ktQualifiers: over the corpus, realworld set and example, every member a
// public generated class or its companion declares and every name its body uses
// as an expression qualifier must be on the list (union-derived names and
// `_`-prefixed ones aside, which the union derives from distinct option names or
// no schema name spells).
// A backend that starts writing `Math.max(...)` or declares another member fails
// here until the name is reserved.
func TestKotlinNamesInScope(t *testing.T) {
	defs, _ := filepath.Glob("../../tests/matrix/corpus/defs/*.yaml")
	rw, _ := filepath.Glob("../../examples/messages/realworld/*.yaml")
	defs = append(append(defs, rw...), "../../examples/messages/example.yaml")
	for _, def := range defs {
		// A class-level `var` is a schema property unless its name is not one:
		// those are the generated vars the list must hold (a union's `which`).
		doc, err := parser.Load(def)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := doc.Resolve(); err != nil {
			t.Fatal(err)
		}
		s, err := model.Build(doc)
		if err != nil {
			t.Fatal(err)
		}
		props := map[string]bool{}
		for _, m := range s.Messages {
			for _, f := range m.Fields {
				props[strings.Trim(ktIdent(f.Name), "`")] = true
			}
		}
		for _, nt := range s.Named {
			for _, f := range nt.Fields {
				props[strings.Trim(ktIdent(f.Name), "`")] = true
				props[strings.Trim(unionOptProp(f.Name), "`")] = true
			}
		}
		for path, content := range genFromFile(t, def, map[string]any{"emit": "project"}) {
			if !strings.HasSuffix(path, ".kt") || strings.HasSuffix(path, "/_Main.kt") {
				continue
			}
			decls, quals := ktScope(content)
			for _, d := range decls {
				kind, n, _ := strings.Cut(d, " ")
				if kind == "var" && props[n] {
					continue
				}
				if strings.HasPrefix(n, "_") || ktOptID.MatchString(n) || ktReservedMembers[n] || unionReserved[n] {
					continue
				}
				t.Errorf("%s (%s): member %s is not on ktReservedMembers", path, filepath.Base(def), n)
			}
			for _, n := range quals {
				if !ktQualifiers[n] {
					t.Errorf("%s (%s): qualifier %s is not on ktQualifiers", path, filepath.Base(def), n)
				}
			}
		}
	}
}

var (
	// ktUsedType is an upper-case identifier the code names unqualified: not
	// after a `.` (a member or a qualified name), a word character or a backtick.
	ktUsedType = regexp.MustCompile("(?:^|[^\\w.`])([A-Z]\\w*)")
	// ktTopDecl is a namespace-level declaration: one at column 0.
	ktTopDecl = regexp.MustCompile(`(?m)^(?:(?:public|internal|private)\s+)?(?:class|object|interface|fun|val|var)\s+(\w+)`)
	// ktNestedType is a class or object nested in another (indented).
	ktNestedType = regexp.MustCompile(`(?m)^[ \t]+(?:(?:public|internal|private)\s+)?(?:class|object)\s+(\w+)`)
)

// ktGenerations is every generation the outer-name guards sweep: the corpus,
// the realworld set, the example, the shared name-collision schema and this
// backend's own collision schema -- in project mode, so the harness is swept
// too.
func ktGenerations(t *testing.T) map[string]map[string]string {
	t.Helper()
	defs, _ := filepath.Glob("../../tests/matrix/corpus/defs/*.yaml")
	rw, _ := filepath.Glob("../../examples/messages/realworld/*.yaml")
	defs = append(append(defs, rw...), "../../examples/messages/example.yaml",
		"../../tests/conformance/lib/names.yaml", "../../tests/conformance/kotlin/reserved.yaml")
	out := map[string]map[string]string{}
	for _, def := range defs {
		out[def] = genFromFile(t, def, map[string]any{"emit": "project"})
	}
	return out
}

// TestKotlinOuterNames is the drift guard for ktOuterNames: every upper-case
// name a generated file uses unqualified that the generated package does not
// declare itself -- a corelib name, a Kotlin default import -- must be on the
// list, or a message of that name would shadow it throughout the package. So
// must every nested class or object a generated class declares (its name hides
// a type of the same name inside the class) and the implicit `Companion`.
// Conversely every entry must still be one of those, so the list does not
// escape names nothing uses.
func TestKotlinOuterNames(t *testing.T) {
	needed := map[string]bool{}
	for def, files := range ktGenerations(t) {
		declared := map[string]bool{}
		for _, c := range files {
			c = ktBlank.ReplaceAllString(c, `""`)
			for _, m := range ktDecl.FindAllStringSubmatch(c, -1) {
				declared[m[2]] = true
			}
		}
		for path, c := range files {
			if !strings.HasSuffix(path, ".kt") {
				continue
			}
			c = ktBlank.ReplaceAllString(c, `""`)
			for _, m := range ktNestedType.FindAllStringSubmatch(c, -1) {
				if !strings.HasPrefix(m[1], "_") {
					needed[m[1]] = true
					if _, ok := ktOuterNames[m[1]]; !ok {
						t.Errorf("%s (%s): nested type %s is not on ktOuterNames", path, filepath.Base(def), m[1])
					}
				}
			}
			if strings.Contains(c, "companion object") {
				needed["Companion"] = true
			}
			for _, m := range ktUsedType.FindAllStringSubmatch(c, -1) {
				n := m[1]
				if declared[n] {
					continue
				}
				needed[n] = true
				if _, ok := ktOuterNames[n]; !ok {
					t.Errorf("%s (%s): %s is used unqualified but not on ktOuterNames", path, filepath.Base(def), n)
				}
			}
		}
	}
	for n := range ktOuterNames {
		if !needed[n] {
			t.Errorf("ktOuterNames holds %s, which no generated file needs", n)
		}
	}
}

// TestKotlinNamesSchemaDeclaresOnce generates the shared name-collision schema
// (tests/conformance/lib/names.yaml, ARCHITECTURE §8) and checks, without a
// toolchain, what kotlinc would otherwise be the first to see: every
// namespace-level declaration of the package appears exactly once, each type
// in the file named after it, no type takes a name on ktOuterNames, and no two
// files share a path once case is folded. The conformance suite builds the
// same schema against the real corelib.
func TestKotlinNamesSchemaDeclaresOnce(t *testing.T) {
	for _, mode := range []string{"sources", "project"} {
		files := genFromFile(t, "../../tests/conformance/lib/names.yaml", map[string]any{"emit": mode})
		seen := map[string]string{}
		folded := map[string]string{}
		for path, c := range files {
			if prev, dup := folded[strings.ToLower(path)]; dup {
				t.Errorf("%s: %s and %s are one file on a case-insensitive filesystem", mode, prev, path)
			}
			folded[strings.ToLower(path)] = path
			if !strings.HasSuffix(path, ".kt") {
				continue
			}
			base := strings.TrimSuffix(filepath.Base(path), ".kt")
			c = ktBlank.ReplaceAllString(c, `""`)
			for _, m := range ktTopDecl.FindAllStringSubmatch(c, -1) {
				n := m[1]
				if prev, dup := seen[n]; dup {
					t.Errorf("%s: %s is declared in both %s and %s", mode, n, prev, path)
				}
				seen[n] = path
				if _, ok := ktOuterNames[n]; ok {
					t.Errorf("%s: %s declares %s, a name the package uses from outside", mode, path, n)
				}
				if n[0] >= 'A' && n[0] <= 'Z' && n != base {
					t.Errorf("%s: %s declares the type %s -- a type lives in the file of its own name", mode, path, n)
				}
			}
		}
		// Spot-check the channels (ARCHITECTURE §8, "Naming").
		for _, want := range []string{
			"M", "M_A", "MA", "M_Decoder", "MDecoder", "M_Arr", "M_ArrElem",
			"Shape__DefaultPt", "Shape__DefaultNum", "ShapeDefault_Pt", "ShapeDefaultPt",
			"A_BC", "AB_C", "Point", "StructPoint", "Decoder_", "Companion_", "String_", "Seq_",
			"_M__Visitor", "_Decoder__Visitor", "Json", "JsonValue", "Main",
		} {
			if _, ok := seen[want]; !ok {
				t.Errorf("%s: no namespace-level declaration %s", mode, want)
			}
		}
	}
}
