// Package zig is the Zig backend (corelib-zig, the max-speed port): structs
// with schema defaults in the type declaration, marshal() over OStream, and a
// flat-visitor decode. The corelib's visitor is comptime duck typing
// (sequenceBegin/sequenceEnd events, no child visitors), so decode is a
// (location, id) state machine with a location stack -- the same shape as the
// Rust backend, monomorphized with zero dispatch overhead.
//
// The generated code follows the corelib's speed contract: encode() streams
// through a caller-owned scratch buffer into a growable list via the flush
// sink; decode() is zero-copy for strings and blobs (the decoded message
// borrows those bytes from the input buffer) and allocates array storage from
// the caller's allocator -- pass an arena and free everything at once.
package zig

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for Zig.
type Backend struct{}

func (*Backend) Lang() string { return "zig" }

// Generate emits src/message.zig; project mode adds build.zig + build.zig.zon
// and a JSON encode/decode harness (src/main.zig).
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	g := &gen{
		schema:  s,
		banner:  cfgString(cfg, "tool_banner", "sofabgen"),
		license: generator.LicenseID(cfg),
	}
	files := []generator.File{{Path: "src/message.zig", Content: g.module(s)}}
	if cfgString(cfg, "emit", "sources") == "project" {
		files = append(files, g.projectFiles(s)...)
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	banner  string
	license string // SPDX id, "" to omit the header line
}

type zfile struct{ b strings.Builder }

func (f *zfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *zfile) blank()        { f.b.WriteByte('\n') }
func (f *zfile) bytes() []byte { return []byte(f.b.String()) }

// emitDoc writes a Zig doc comment (`///`, one line per line of text) at the
// given indent. Empty text emits nothing, so it never leaves a dangling `///`.
func (f *zfile) emitDoc(indent, text string) {
	if text == "" {
		return
	}
	for _, ln := range strings.Split(text, "\n") {
		f.line("%s/// %s", indent, ln)
	}
}

// fieldDoc builds a field's doc-comment text from its Description and Unit.
func fieldDoc(fld *ir.Field) string {
	switch {
	case fld.Description != "" && fld.Unit != "":
		return fld.Description + " (unit: " + fld.Unit + ")"
	case fld.Description != "":
		return fld.Description
	case fld.Unit != "":
		return "(unit: " + fld.Unit + ")"
	default:
		return ""
	}
}

func (g *gen) module(s *ir.Schema) []byte {
	f := &zfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("// SPDX-License-Identifier: %s", g.license)
	}
	f.line("//! SofaBuffers message types over the `sofab` Zig corelib (max-speed build).")
	f.line("//! decode() borrows string/blob bytes from the input buffer (zero-copy) and")
	f.line("//! allocates array storage from the caller's allocator; pass an arena and")
	f.line("//! free the whole message at once.")
	f.blank()
	f.line("const std = @import(\"std\");")
	f.line("const sofab = @import(\"sofab\");")
	f.blank()

	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfieldConsts(f, nt)
		}
	}
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitStruct(f, g.typeName(key), nt.Fields, false, "")
		}
	}
	for _, m := range s.Messages {
		g.emitStruct(f, exported(m.Name), m.Fields, true, m.Summary)
	}
	for _, m := range s.Messages {
		g.emitDecoder(f, exported(m.Name), m.Fields)
	}
	g.emitSupport(f)
	return f.bytes()
}

func (g *gen) emitEnum(f *zfile, nt *ir.NamedType) {
	backing := enumBacking(nt)
	f.line("pub const %s = struct {", strings.ToLower(g.typeName(nt.Key)))
	for _, c := range nt.Consts {
		f.emitDoc("    ", c.Description)
		f.line("    pub const %s: %s = %d;", strings.ToUpper(c.Name), backing, c.Value)
	}
	f.line("};")
	f.blank()
}

func (g *gen) emitBitfieldConsts(f *zfile, nt *ir.NamedType) {
	backing := bitfieldBacking(nt)
	f.line("pub const %s = struct {", strings.ToLower(g.typeName(nt.Key)))
	for _, fl := range nt.Flags {
		f.emitDoc("    ", fl.Description)
		f.line("    pub const %s: %s = 1 << %d;", strings.ToUpper(fl.Name), backing, fl.Pos)
	}
	f.line("};")
	f.blank()
}

func (g *gen) emitStruct(f *zfile, name string, fields []*ir.Field, isMessage bool, summary string) {
	f.emitDoc("", summary)
	f.line("pub const %s = struct {", name)
	// Field defaults ARE the schema defaults: a plain `.{}` message carries
	// them, and sparse-canonical decode (MESSAGE_SPEC S2) reconstructs an
	// omitted field simply by leaving the default in place.
	for _, fld := range fields {
		f.emitDoc("    ", fieldDoc(fld))
		f.line("    %s: %s = %s,", zigIdent(fld.Name), g.zigType(fld), g.zigFieldDefault(fld))
	}
	f.blank()
	if isMessage {
		size, _ := g.maxSize(fields)
		f.line("    /// Upper bound on the encoded size of any value of this message.")
		f.line("    pub const MAX_SIZE: usize = %d;", size)
		f.blank()
	}

	// marshal: sparse-canonical (MESSAGE_SPEC S2) -- a leaf equal to its
	// default is omitted; a sequence is always framed.
	f.line("    /// Write this value's fields to `os` (sparse-canonical encoding).")
	f.line("    pub fn marshal(self: *const %s, os: *sofab.OStream) sofab.Error!void {", name)
	needsSelf := len(fields) > 0
	if !needsSelf {
		f.line("        _ = self;")
		f.line("        _ = os;")
	}
	for _, fld := range fields {
		g.emitMarshal(f, fld)
	}
	f.line("    }")

	if isMessage {
		f.blank()
		f.line("    /// Encode into a fresh buffer allocated from `alloc`.")
		f.line("    pub fn encode(self: *const %s, alloc: std.mem.Allocator) (sofab.Error || std.mem.Allocator.Error)![]u8 {", name)
		f.line("        var sink: _EncodeSink = .{ .alloc = alloc };")
		f.line("        var scratch: [512]u8 = undefined;")
		f.line("        var os = sofab.OStream.initFlush(&scratch, 0, &sink, _EncodeSink.push);")
		f.line("        try self.marshal(&os);")
		f.line("        _ = os.flush();")
		f.line("        if (sink.failed) return error.OutOfMemory;")
		f.line("        return sink.list.toOwnedSlice(alloc);")
		f.line("    }")
		f.blank()
		f.line("    /// Decode a complete message. Zero-copy: the result borrows string and")
		f.line("    /// blob bytes from `data` (keep it alive as long as the message); array")
		f.line("    /// storage comes from `alloc` (an arena frees everything at once).")
		f.line("    pub fn decode(alloc: std.mem.Allocator, data: []const u8) sofab.Error!%s {", name)
		f.line("        var m: %s = .{};", name)
		f.line("        var v: _dec_%s = .{ .m = &m, .alloc = alloc };", name)
		f.line("        try sofab.decode(data, &v);")
		f.line("        // A scalar array carried more elements than its schema count:")
		f.line("        // INVALID per MESSAGE_SPEC 3+7, never clamp (generator#100).")
		f.line("        if (v.inv) return error.InvalidMessage;")
		f.line("        return m;")
		f.line("    }")
	}
	f.line("};")
	f.blank()
}

func (g *gen) emitMarshal(f *zfile, fld *ir.Field) {
	acc := "self." + zigIdent(fld.Name)
	var write string
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		write = fmt.Sprintf("try os.writeUnsigned(%d, %s);", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		write = fmt.Sprintf("try os.writeSigned(%d, %s);", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("try os.writeBoolean(%d, %s);", fld.ID, acc)
	case ir.KindFP32:
		write = fmt.Sprintf("try os.writeFp32(%d, %s);", fld.ID, acc)
	case ir.KindFP64:
		write = fmt.Sprintf("try os.writeFp64(%d, %s);", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("try os.writeString(%d, %s);", fld.ID, acc)
	case ir.KindBlob:
		write = fmt.Sprintf("try os.writeBlob(%d, %s);", fld.ID, acc)
	case ir.KindStruct, ir.KindUnion:
		// A sequence is always framed; its child fields are omitted per-field
		// by the nested marshal (MESSAGE_SPEC S2). An all-default nested object
		// thus becomes an empty wrapper sequence, not a dropped field.
		f.line("        try os.writeSequenceBegin(%d);", fld.ID)
		f.line("        try %s.marshal(os);", acc)
		f.line("        try os.writeSequenceEnd();")
		return
	case ir.KindArray:
		g.emitMarshalArray(f, fld, acc)
		return
	}
	// Scalar/string/blob/enum/bitfield leaf: omit when equal to the default;
	// sparse encoding is canonical (MESSAGE_SPEC S2) and the decoder
	// reconstructs the omitted field from its default.
	f.line("        if (%s) %s", g.zigLeafNe(acc, fld), write)
}

func (g *gen) emitMarshalArray(f *zfile, fld *ir.Field, acc string) {
	// A native scalar array is a leaf field: omit it when equal to its default
	// (materialized in the field initializer), else when empty. A composite/
	// dynamic-element array is a wrapper sequence and is always framed.
	if isNativeArrayElem(fld.Elem) {
		elem := g.zigArrayElem(fld.Elem, fld.ElemRef, fld.ElemItems)
		val := acc
		if _, _, ok := g.fixedNativeArray(fld); ok {
			val = acc + "[0..]"
			if _, ok := g.zigNativeArrayParts(fld); ok {
				// Compare against the full (tail-padded) default literal.
				f.line("        if (!std.mem.eql(%s, %s, &%s)) {", elem, val, g.zigFieldDefault(fld))
			} else {
				// No schema default: the fixed array's default is all element
				// zeros (@splat has no inferable type inside eql).
				f.line("        if (!std.mem.allEqual(%s, %s, %s)) {", elem, val, zigElemZero(fld.Elem))
			}
		} else if parts, ok := g.zigNativeArrayParts(fld); ok {
			f.line("        if (!std.mem.eql(%s, %s, &.{ %s })) {", elem, val, parts)
		} else {
			f.line("        if (%s.len != 0) {", val)
		}
		g.marshalArray(f, "            ", fmt.Sprintf("%d", fld.ID), val, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
		f.line("        }")
		return
	}
	g.marshalArray(f, "        ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
}

// marshalArray writes the array val (a slice-like expression) as field idExpr.
// Numeric/enum/bitfield elements use the native array wire type (numeric/enum
// by signedness, bitfield -> unsigned); boolean lowers to a 0/1 unsigned array
// via its byte representation; string/blob/struct/union/array elements lower
// to a wrapper sequence whose child ids are the 0-based index (MESSAGE_SPEC
// S5.1). Recurses for nested arrays, depth-suffixing loop vars.
func (g *gen) marshalArray(f *zfile, ind, idExpr, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	ev := fmt.Sprintf("_e%d", depth)
	switch elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		// bitfield backing is an unsigned int, so it writes directly.
		f.line("%stry os.writeArrayUnsigned(%s, %s);", ind, idExpr, val)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		// enum backing is a signed int, so it writes directly.
		f.line("%stry os.writeArraySigned(%s, %s);", ind, idExpr, val)
	case ir.KindBool:
		// bool has no array wire type; it lowers to a 0/1 unsigned array. A
		// Zig bool is one byte holding exactly 0 or 1, so the slice's byte
		// view is already the element list -- no temporary, no allocator.
		f.line("%stry os.writeArrayUnsigned(%s, std.mem.sliceAsBytes(%s));", ind, idExpr, val)
	case ir.KindFP32:
		f.line("%stry os.writeArrayFp32(%s, %s);", ind, idExpr, val)
	case ir.KindFP64:
		f.line("%stry os.writeArrayFp64(%s, %s);", ind, idExpr, val)
	case ir.KindString:
		// A string element is a leaf: omit it when equal to the element
		// default (empty), leaving an id gap the decoder restores.
		f.line("%stry os.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%sfor (%s, 0..) |%s, %s| {", ind, val, ev, iv)
		f.line("%s    if (%s.len != 0) try os.writeString(@intCast(%s), %s);", ind, ev, iv, ev)
		f.line("%s}", ind)
		f.line("%stry os.writeSequenceEnd();", ind)
	case ir.KindBlob:
		f.line("%stry os.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%sfor (%s, 0..) |%s, %s| {", ind, val, ev, iv)
		f.line("%s    if (%s.len != 0) try os.writeBlob(@intCast(%s), %s);", ind, ev, iv, ev)
		f.line("%s}", ind)
		f.line("%stry os.writeSequenceEnd();", ind)
	case ir.KindStruct, ir.KindUnion:
		f.line("%stry os.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%sfor (%s, 0..) |*%s, %s| {", ind, val, ev, iv)
		f.line("%s    try os.writeSequenceBegin(@intCast(%s));", ind, iv)
		f.line("%s    try %s.marshal(os);", ind, ev)
		f.line("%s    try os.writeSequenceEnd();", ind)
		f.line("%s}", ind)
		f.line("%stry os.writeSequenceEnd();", ind)
	case ir.KindArray:
		f.line("%stry os.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%sfor (%s, 0..) |%s, %s| {", ind, val, ev, iv)
		g.marshalArray(f, ind+"    ", fmt.Sprintf("@intCast(%s)", iv), ev, items.Elem, items.ElemRef, items.ElemItems, depth+1)
		f.line("%s}", ind)
		f.line("%stry os.writeSequenceEnd();", ind)
	}
}

// emitSupport writes the module-level helpers shared by every message: the
// encode flush sink and the small generic decode stores. Zig analyzes private
// declarations lazily, so helpers a given schema never references cost
// nothing.
func (g *gen) emitSupport(f *zfile) {
	f.line("// --- shared encode/decode support -------------------------------------------")
	f.blank()
	f.line("/// Flush sink behind encode(): drains the OStream scratch buffer into a")
	f.line("/// growable byte list.")
	f.line("const _EncodeSink = struct {")
	f.line("    alloc: std.mem.Allocator,")
	f.line("    list: std.ArrayList(u8) = .empty,")
	f.line("    failed: bool = false,")
	f.line("    fn push(ctx: ?*anyopaque, data: []const u8) void {")
	f.line("        const self: *_EncodeSink = @ptrCast(@alignCast(ctx.?));")
	f.line("        self.list.appendSlice(self.alloc, data) catch {")
	f.line("            self.failed = true;")
	f.line("        };")
	f.line("    }")
	f.line("};")
	f.blank()
	f.line("/// Store the next native-array element into a dynamic (count-less) slice,")
	f.line("/// bounds-checked; the slice is pre-sized to the wire count, so the bound")
	f.line("/// only guards a failed allocation (the data is then dropped).")
	f.line("fn _put(s: anytype, i: *usize, v: std.meta.Elem(@TypeOf(s))) void {")
	f.line("    if (i.* >= s.len) return;")
	f.line("    @constCast(&s[i.*]).* = v;")
	f.line("    i.* += 1;")
	f.line("}")
	f.blank()
	f.line("/// Store the next native-array element into a fixed [N]T destination. An")
	f.line("/// element past the schema capacity N flags the message malformed: a wire")
	f.line("/// count above the schema count is INVALID per MESSAGE_SPEC 3+7 and must be")
	f.line("/// rejected, not clamped (generator#100).")
	f.line("fn _putc(s: anytype, i: *usize, v: std.meta.Elem(@TypeOf(s)), inv: *bool) void {")
	f.line("    if (i.* >= s.len) {")
	f.line("        inv.* = true;")
	f.line("        return;")
	f.line("    }")
	f.line("    @constCast(&s[i.*]).* = v;")
	f.line("    i.* += 1;")
	f.line("}")
	f.blank()
	f.line("/// Mutable pointer to the last element of a decode-allocated slice.")
	f.line("fn _last(s: anytype) *std.meta.Elem(@TypeOf(s)) {")
	f.line("    return @constCast(&s[s.len - 1]);")
	f.line("}")
	f.blank()
	f.line("/// Grow a decode-owned slice to n elements, filling new slots with `fill`.")
	f.line("/// Returns false when the allocation fails (the caller then drops the data).")
	f.line("fn _grow(comptime T: type, a: std.mem.Allocator, s: *[]const T, n: usize, fill: T) bool {")
	f.line("    if (s.*.len >= n) return true;")
	f.line("    const new = a.alloc(T, n) catch return false;")
	f.line("    @memcpy(new[0..s.*.len], s.*);")
	f.line("    @memset(new[s.*.len..], fill);")
	f.line("    s.* = new;")
	f.line("    return true;")
	f.line("}")
	f.blank()
	f.line("/// Allocate a zeroed native-array destination of exactly `n` elements (the")
	f.line("/// wire count); on allocation failure the array decodes as empty.")
	f.line("fn _allocN(comptime T: type, a: std.mem.Allocator, n: usize) []const T {")
	f.line("    const s = a.alloc(T, n) catch return &.{};")
	f.line("    @memset(s, std.mem.zeroes(T));")
	f.line("    return s;")
	f.line("}")
	f.blank()
	f.line("/// Place a wrapper-array string/blob element at its wire id (= array index),")
	f.line("/// growing the destination and filling id gaps left by omitted default")
	f.line("/// elements (MESSAGE_SPEC S2/S5.1).")
	f.line("fn _setElem(comptime T: type, a: std.mem.Allocator, s: *[]const T, id: usize, fill: T, v: T) void {")
	f.line("    if (!_grow(T, a, s, id + 1, fill)) return;")
	f.line("    @constCast(&s.*[id]).* = v;")
	f.line("}")
}
