package zig

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/zig/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every name on the Zig list, sorted.
func reservedNames() []string {
	seen := map[string]bool{}
	var names []string
	for _, set := range []map[string]bool{zigKeywords, zigDecls, unionDecls} {
		for n := range set {
			if !seen[n] { // serialize/isDefault are on both declaration lists
				seen[n] = true
				names = append(names, n)
			}
		}
	}
	sort.Strings(names)
	return names
}

// reservedYAML is a schema that uses every reserved name as a field of a message,
// of a nested struct, and as an option of a union. It also carries the one path
// clash a _Loc tag can hit: the path inner.inner2 beside a field inner_inner2.
func reservedYAML(names []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/zig/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/zig -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field must build and round-trip.\n")
	var fields strings.Builder
	opts := make([]string, len(names))
	for i, n := range names {
		fmt.Fprintf(&fields, "      %s: { id: %d, type: u8 }\n", n, i)
		opts[i] = fmt.Sprintf("%s: { id: %d, type: u8 }", n, i)
	}
	k := len(names)
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
messages:
  m:
    payload:
%s      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      u:            { id: %d, type: union, oneof: { %s } }
`, fields.String(), k, fields.String(), k, k+1, k+2, strings.Join(opts, ", "))
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field, nested one,
// both sides of the path clash and the last union option at a non-default value,
// each under its schema name.
func reservedJSON(names []string) string {
	top := map[string]any{}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	for i, n := range names {
		top[n] = i + 1
		inner[n] = i + 2
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{names[len(names)-1]: 9}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite builds that file and round-trips it
// (tests/conformance/zig/run.sh), so a name added to reserved.go is covered once
// the file is regenerated -- and this test fails until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := reservedNames()
	for path, want := range map[string]string{
		"../../tests/conformance/zig/reserved.yaml": reservedYAML(names),
		"../../tests/conformance/zig/reserved.json": reservedJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// reservedModule generates src/message.zig for the collision schema.
func reservedModule(t *testing.T) string {
	t.Helper()
	files, err := (&Backend{}).Generate(buildSchema(t, reservedYAML(reservedNames())), map[string]any{})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	for _, f := range files {
		if strings.HasSuffix(f.Path, "message.zig") {
			return string(f.Content)
		}
	}
	t.Fatal("no message.zig")
	return ""
}

// TestReservedNamesAreEscaped: a keyword field is the quoted identifier
// @"name", a declaration name is `name_`, and a union-only declaration name is a
// struct field as it is.
func TestReservedNamesAreEscaped(t *testing.T) {
	out := reservedModule(t)
	for _, n := range reservedNames() {
		want := zigIdent(n)
		if !regexp.MustCompile(`(?m)^    ` + regexp.QuoteMeta(want) + `: u8 = 0,$`).MatchString(out) {
			t.Errorf("field %q is not the member %s", n, want)
		}
	}
}

// TestLocTagsAreDistinct: the _Loc tags spell the schema path joined by `_`, so
// the path inner.inner2 and a field inner_inner2 must not give one tag twice.
func TestLocTagsAreDistinct(t *testing.T) {
	out := reservedModule(t)
	body := out[strings.Index(out, "const _Loc = enum {"):]
	body = body[:strings.Index(body, "};")]
	seen := map[string]bool{}
	for _, v := range regexp.MustCompile(`(?m)^\s+(\w+),`).FindAllStringSubmatch(body, -1) {
		if seen[v[1]] {
			t.Errorf("_Loc tag %s is defined twice", v[1])
		}
		seen[v[1]] = true
	}
	for _, want := range []string{"root_inner_inner2", "root_inner__inner2"} {
		if !seen[want] {
			t.Errorf("no _Loc tag %s in:\n%s", want, body)
		}
	}
}

// TestFieldNameCollision: two fields that give one member (`encode` is mangled
// to `encode_`) and two enum constants or flags that give one upper-cased
// constant are a generation error naming both, not a duplicate member zig
// reports far from the schema.
func TestFieldNameCollision(t *testing.T) {
	for _, src := range []string{
		"version: 1\nmessages:\n  m:\n    payload:\n      encode: { id: 0, type: u8 }\n      encode_: { id: 1, type: u8 }\n",
		"version: 1\nmessages:\n  m:\n    payload:\n      e: { id: 0, type: enum, enum: { a: 0, A: 1 } }\n",
		"version: 1\n$defs:\n  bitfield:\n    F: { x: { pos: 0 }, X: { pos: 1 } }\nmessages:\n  m:\n    payload:\n      f: { id: 0, type: bitfield, bits: { $ref: '#/$defs/bitfield/F' } }\n",
		// a type named after a file-scope declaration: message, and inline struct
		"version: 1\nmessages:\n  decode_error:\n    payload:\n      x: { id: 0, type: u8 }\n",
		"version: 1\nmessages:\n  decode:\n    payload:\n      error: { id: 0, type: struct, fields: { x: { id: 0, type: u8 } } }\n",
	} {
		_, err := (&Backend{}).Generate(buildSchema(t, src), map[string]any{})
		if err == nil || !(strings.Contains(err.Error(), "both generate") || strings.Contains(err.Error(), "already declares")) {
			t.Errorf("want a collision error for:\n%s\ngot %v", src, err)
		}
	}
}
