package zig

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/naming"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/zig/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every name on the Zig list, sorted.
func reservedNames() []string {
	seen := map[string]bool{}
	var names []string
	for _, set := range []map[string]bool{zigKeywords, zigDecls, unionDecls} {
		for n := range set {
			if !seen[n] { // serialize/isDefault are on both declaration lists
				seen[n] = true
				names = append(names, n)
			}
		}
	}
	sort.Strings(names)
	return names
}

// splitFolds splits names into the ones whose fold is new and the rest: the
// validator refuses two names of one scope that share a fold (`Decoder` beside
// `decoder`), so the twins go into a scope of their own.
func splitFolds(names []string) (first, twins []string) {
	seen := map[string]bool{}
	for _, n := range names {
		if seen[naming.Fold(n)] {
			twins = append(twins, n)
			continue
		}
		seen[naming.Fold(n)] = true
		first = append(first, n)
	}
	return first, twins
}

// unionClash are the options of a union whose derived members (`<opt>_id`,
// `<opt>Mut`) other options spell: they take the trailing `_` of a declaration
// clash instead of failing generation. `B` has the accessor `bMut`.
var unionClash = []string{"a", "a_id", "aMut", "B", "bMut"}

// reservedYAML is a schema that uses every reserved name as a field of a message,
// of a nested struct, and as an option of a union -- a name whose fold another
// already has (`Decoder` beside `decoder`) in a second struct and union, the
// validator's second naming rule. It carries the one path clash a _Loc tag can
// hit (the path inner.inner2 beside a field inner_inner2), a union whose options
// spell each other's derived members, and every type-level name on the list
// (zigTypeReserved) as a type: `Decoder` and `DecodeError` as messages, and
// MAX_SIZE / MAX_SIZE_LIMIT as the inline paths MAX.SIZE and MAX.SIZE.LIMIT.
func reservedYAML(names []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/zig/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/zig -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field must build and round-trip.\n")
	first, twins := splitFolds(names)
	block := func(list []string) (fields, opts string) {
		var fb strings.Builder
		os := make([]string, len(list))
		for i, n := range list {
			fmt.Fprintf(&fb, "      %s: { id: %d, type: u8 }\n", n, i)
			os[i] = fmt.Sprintf("%s: { id: %d, type: u8 }", n, i)
		}
		return fb.String(), strings.Join(os, ", ")
	}
	fields, opts := block(first)
	twinFields, twinOpts := block(twins)
	_, clashOpts := block(unionClash)
	k := len(first)
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
    Twin:
%smessages:
  m:
    payload:
%s      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      u:            { id: %d, type: union, oneof: { %s } }
      twin:         { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Twin' } }
      u2:           { id: %d, type: union, oneof: { %s } }
      u3:           { id: %d, type: union, oneof: { %s } }
  Decoder:
    payload:
      x: { id: 0, type: u8 }
  DecodeError:
    payload:
      x: { id: 0, type: u8 }
  MAX:
    payload:
      SIZE: { id: 0, type: struct, fields: { x: { id: 0, type: u8 }, LIMIT: { id: 1, type: struct, fields: { x: { id: 0, type: u8 } } } } }
`, fields, k, twinFields, fields, k, k+1, k+2, opts, k+3, k+4, twinOpts, k+5, clashOpts)
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field, nested one,
// both sides of the path clash and the last option of each union at a
// non-default value, each under its schema name.
func reservedJSON(names []string) string {
	first, twins := splitFolds(names)
	top := map[string]any{}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	for i, n := range first {
		top[n] = i + 1
		inner[n] = i + 2
	}
	twin := map[string]any{}
	for i, n := range twins {
		twin[n] = i + 3
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{first[len(first)-1]: 9}
	top["twin"] = twin
	top["u2"] = map[string]any{twins[len(twins)-1]: 8}
	top["u3"] = map[string]any{unionClash[len(unionClash)-1]: 7}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite builds that file and round-trips it
// (tests/conformance/zig/run.sh), so a name added to reserved.go is covered once
// the file is regenerated -- and this test fails until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := reservedNames()
	for path, want := range map[string]string{
		"../../tests/conformance/zig/reserved.yaml": reservedYAML(names),
		"../../tests/conformance/zig/reserved.json": reservedJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// reservedModule generates src/message.zig for the collision schema.
func reservedModule(t *testing.T) string {
	t.Helper()
	files, err := (&Backend{}).Generate(buildSchema(t, reservedYAML(reservedNames())), map[string]any{})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	for _, f := range files {
		if strings.HasSuffix(f.Path, "message.zig") {
			return string(f.Content)
		}
	}
	t.Fatal("no message.zig")
	return ""
}

// TestReservedNamesAreEscaped: a keyword field is the quoted identifier
// @"name", a declaration name is `name_`, and a union-only declaration name is a
// struct field as it is.
func TestReservedNamesAreEscaped(t *testing.T) {
	out := reservedModule(t)
	for _, n := range reservedNames() {
		want := zigIdent(n)
		if !regexp.MustCompile(`(?m)^    ` + regexp.QuoteMeta(want) + `: u8 = 0,$`).MatchString(out) {
			t.Errorf("field %q is not the member %s", n, want)
		}
	}
	// A type on the type-level list is declared with the escape; its roles and
	// its private visitor are built from the unescaped identifier.
	for _, want := range []string{
		"pub const Decoder_ = struct {",
		"pub const DecodeError_ = struct {",
		"pub const MAX_SIZE_ = struct {",
		"pub const MAX_SIZE_LIMIT_ = struct {",
		"const _Decoder__Visitor = struct {",
		"const _DecodeError__Visitor = struct {",
		"SIZE: MAX_SIZE_ = .{},",
		"LIMIT: MAX_SIZE_LIMIT_ = .{},",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q", want)
		}
	}
	// Options that spell another option's derived member take the trailing `_`.
	u3 := section(t, out, "pub const M_U3 = union(enum) {")
	for _, want := range []string{
		"    a: u8,", "    a_id_: u8,", "    aMut_: u8,", "    B: u8,", "    bMut_: u8,",
		"pub const a_id: sofab.Id = 0;", "pub const a_id_id: sofab.Id = 1;",
		"pub fn aMut(self: *M_U3) *u8 {", "pub fn aMutMut(self: *M_U3) *u8 {",
		"pub fn bMut(self: *M_U3) *u8 {", "pub fn bMutMut(self: *M_U3) *u8 {",
	} {
		if !strings.Contains(u3, want) {
			t.Errorf("union u3: missing %q in:\n%s", want, u3)
		}
	}
}

// TestLocTagsAreDistinct: the _Loc tags spell the schema path joined by `_`, so
// the path inner.inner2 and a field inner_inner2 must not give one tag twice.
func TestLocTagsAreDistinct(t *testing.T) {
	out := reservedModule(t)
	body := out[strings.Index(out, "const _M__Visitor = struct {"):]
	body = body[strings.Index(body, "const _Loc = enum {"):]
	body = body[:strings.Index(body, "};")]
	seen := map[string]bool{}
	for _, v := range regexp.MustCompile(`(?m)^\s+(\w+),`).FindAllStringSubmatch(body, -1) {
		if seen[v[1]] {
			t.Errorf("_Loc tag %s is defined twice", v[1])
		}
		seen[v[1]] = true
	}
	for _, want := range []string{"root_inner_inner2", "root_inner__inner2"} {
		if !seen[want] {
			t.Errorf("no _Loc tag %s in:\n%s", want, body)
		}
	}
}

// TestNoNameRefusal: what used to fail generation as a name clash generates now
// (ARCHITECTURE §8, "Naming"). A field `encode_` or an enum constant beside its
// upper-case twin is refused by the validator instead; a type named after a
// file-scope declaration takes the escape.
func TestNoNameRefusal(t *testing.T) {
	for src, want := range map[string]string{
		"version: 1\nmessages:\n  decode_error:\n    payload:\n      x: { id: 0, type: u8 }\n":                                       "pub const DecodeError_ = struct {",
		"version: 1\nmessages:\n  decode:\n    payload:\n      error: { id: 0, type: struct, fields: { x: { id: 0, type: u8 } } }\n": "@\"error\": Decode_Error = .{},",
		"version: 1\nmessages:\n  decoder:\n    payload:\n      x: { id: 0, type: u8 }\n":                                            "pub fn decoder(out: *Decoder_, alloc: std.mem.Allocator) Decoder {",
	} {
		files, err := generateYAML(t, src, map[string]any{})
		if err != nil {
			t.Errorf("generate:\n%s\n%v", src, err)
			continue
		}
		if out := string(files[0].Content); !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
}
