package csharp

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/analysis"
	"github.com/sofa-buffers/generator/internal/ir"
	"github.com/sofa-buffers/generator/internal/model"
	"github.com/sofa-buffers/generator/internal/parser"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/csharp/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every member-level name on the C# list, sorted.
func reservedNames() []string {
	var names []string
	for _, set := range []map[string]bool{csKeywords, csMembers, csObjectMembers, unionFixed} {
		for n := range set {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	return names
}

// unlistedNames are names a class body uses that are deliberately NOT on the
// list, because the body reaches them `global::`-qualified: as fields they must
// stay bare and still build.
var unlistedNames = []string{"Array", "DecodeStatus", "List", "OStream", "Seq", "System", "global", "sofab"}

// fieldNames is every name reserved.yaml uses as a field: the list and the
// unlisted names, sorted.
func fieldNames() []string {
	names := append(reservedNames(), unlistedNames...)
	sort.Strings(names)
	return names
}

// typeNames is every name reserved.yaml uses as a MESSAGE, for the type level:
// every csTypeReserved name, and every member a message class declares, which a
// message named like it must escape (CS0542). Each is spelled as the schema name
// its TypeIdent is.
func typeNames() []string {
	set := map[string]bool{}
	for n := range csTypeReserved {
		set[n] = true
	}
	for n := range csMembers {
		set[n] = true
	}
	var names []string
	for n := range set {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// reservedYAML is a schema that uses every reserved name as a field of a
// message, of a nested struct, and as an option of a union, plus the one path
// clash a visitor location constant can hit (inner.inner2 beside a field
// inner_inner2). At the type level it adds a message per typeNames entry, a
// message `self_named` holding a field `SelfNamed`, a message `Encode` holding a
// field `Encode` (the member escape and the type escape at once), a message
// `is` with an inline `default` (Is_Default, not the method IsDefault), and a
// $defs union `which` -- named like a member of its own class -- whose options
// probe the derived union members (`a`'s Id_A/Has_A/Mutable_A beside options
// `a_id`, `has_a`, `mutable_a`, `id_a`).
func reservedYAML(names []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/csharp/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/csharp -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field, and every type-level\n")
	b.WriteString("# name as a message, must build warning-free; message m must round-trip.\n")
	var fields strings.Builder
	var opts []string
	for i, n := range names {
		fmt.Fprintf(&fields, "      %q: { id: %d, type: u8 }\n", n, i)
		opts = append(opts, fmt.Sprintf("%q: { id: %d, type: u8 }", n, i))
	}
	k := len(names)
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
  union:
    which:
      a: { id: 0, type: struct, fields: { x: { id: 0, type: u8 } } }
      a_id: { id: 1, type: u8 }
      has_a: { id: 2, type: u8 }
      mutable_a: { id: 3, type: u8 }
      id_a: { id: 4, type: u8 }
messages:
  m:
    payload:
%s      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      u:            { id: %d, type: union, oneof: { %s } }
      w:            { id: %d, type: union, oneof: { $ref: '#/$defs/union/which' } }
`, fields.String(), k, fields.String(), k, k+1, k+2, strings.Join(opts, ", "), k+3)
	for _, n := range typeNames() {
		if n == "Encode" {
			continue
		}
		fmt.Fprintf(&b, "  %s: { payload: { x: { id: 0, type: u8 } } }\n", n)
	}
	b.WriteString("  Encode: { payload: { Encode: { id: 0, type: u16 } } }\n")
	b.WriteString("  self_named: { payload: { SelfNamed: { id: 0, type: u16 } } }\n")
	b.WriteString("  is: { payload: { default: { id: 0, type: struct, fields: { x: { id: 0, type: u8 } } } } }\n")
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field, nested one,
// both sides of the path clash and a union option at a non-default value, each
// under its schema name.
func reservedJSON(names []string) string {
	top := map[string]any{}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	for i, n := range names {
		top[n] = i + 1
		inner[n] = i + 2
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{names[len(names)-1]: 9}
	top["w"] = map[string]any{"has_a": 7}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite builds that file warning-free and
// round-trips it (tests/conformance/csharp/run.sh), so a name added to
// reserved.go is covered once the file is regenerated -- and this test fails
// until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := fieldNames()
	for path, want := range map[string]string{
		"../../tests/conformance/csharp/reserved.yaml": reservedYAML(names),
		"../../tests/conformance/csharp/reserved.json": reservedJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// schemaOf runs parse->IR over an inline schema, stopping short of generation.
func schemaOf(t *testing.T, src string) *ir.Schema {
	t.Helper()
	doc, err := parser.Parse([]byte(src), "r.yaml")
	if err != nil {
		t.Fatal(err)
	}
	resolved, err := doc.Resolve()
	if err != nil {
	}
	if errs := parser.Validate(resolved); len(errs) > 0 {
		t.Fatalf("schema does not validate: %v", errs)
	}
	s, err := model.Build(doc)
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.Analyze(s); err != nil {
		t.Fatal(err)
	}
	return s
}

// TestReservedNamesAreEscaped: a keyword is the verbatim identifier `@name`, a
// declaration clash is `name_`, a union-only member and a name the body reaches
// `global::`-qualified are fields as they are -- in the message and in the
// nested struct.
func TestReservedNamesAreEscaped(t *testing.T) {
	names := fieldNames()
	files, err := (&Backend{}).Generate(schemaOf(t, reservedYAML(names)), map[string]any{})
	if err != nil {
		t.Fatal(err)
	}
	out := string(files[0].Content)
	for _, n := range names {
		want := csIdent(n)
		if got := len(regexp.MustCompile(`(?m)^    public byte `+regexp.QuoteMeta(want)+`( = 0)?;$`).FindAllString(out, -1)); got != 2 {
			t.Errorf("field %q is the field %s in %d of the 2 classes", n, want, got)
		}
		// A mangled field keeps the schema name as its JSON key.
		attr := fmt.Sprintf("    [global::System.Text.Json.Serialization.JsonPropertyName(%q)]\n    public byte %s", n, want)
		if csRenamed(n) && strings.Count(out, attr) != 2 {
			t.Errorf("field %q (%s) does not carry its JSON name in both classes", n, want)
		}
	}
	for _, n := range unlistedNames {
		if csIdent(n) != n {
			t.Errorf("%q is reached global::-qualified and must stay a bare field, got %s", n, csIdent(n))
		}
	}
}

// TestTypeNamesEscape: a type named like a member of its own class (CS0542) or
// like a name the generated code reaches unqualified takes the trailing `_`;
// the private visitor keeps the unescaped name; nothing is refused.
func TestTypeNamesEscape(t *testing.T) {
	files, err := (&Backend{}).Generate(schemaOf(t, reservedYAML(fieldNames())), map[string]any{"emit": "project"})
	if err != nil {
		t.Fatal(err)
	}
	out := string(files[0].Content)
	for _, decl := range []string{
		"public sealed class Decoder_ {",          // csTypeReserved, and a member of its own class
		"public sealed class MaxSize_ {",          // a member of its own class
		"public sealed class Encode__ {",          // member Encode, and its field Encode is Encode_
		"public sealed class SelfNamed_ {",        // its field SelfNamed
		"public sealed class Is {",                // no clash: its inline struct is Is_Default
		"public sealed class Is_Default {",        // not the method IsDefault
		"public sealed class Which_ {",            // a union named like its member Which
		"public sealed class Reset_ {",            // on csMembers
		"internal sealed class _Encode__Visitor ", // derived from the unescaped name
	} {
		if !strings.Contains(out, decl) {
			t.Errorf("missing %q", decl)
		}
	}
	// The union's derived members split back into word and option.
	for _, m := range []string{
		"public const int Id_A = 0;", "public const int Id_AId = 1;", "public const int Id_IdA = 4;",
		"public bool Has_A =>", "public bool Has_HasA =>", "Mutable_A() {",
		"public byte AId {", "public byte HasA {", "public byte MutableA {", "public byte IdA {",
	} {
		if !strings.Contains(out, m) {
			t.Errorf("union Which_: missing %q", m)
		}
	}
	// The harness names the generated types through the namespace only.
	var prog string
	for _, f := range files {
		if f.Path == "Program.cs" {
			prog = string(f.Content)
		}
	}
	if strings.Contains(prog, "using Message;") || !strings.Contains(prog, "global::Message.Encode__.Decode(") {
		t.Errorf("Program.cs must reach the generated types as global::Message.<T>")
	}
}

// TestLocationConstantsAreDistinct: the visitor's location constants spell the
// schema path joined with `_`, so the path a.b and a field a_b must not give one
// constant twice (CS0102).
func TestLocationConstantsAreDistinct(t *testing.T) {
	src := "version: 1\n$defs:\n  struct:\n    B: { x: { id: 0, type: u8 } }\n    A: { b: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/B' } } }\n" +
		"messages:\n  m:\n    payload:\n      a: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/A' } }\n      a_b: { id: 1, type: struct, fields: { $ref: '#/$defs/struct/B' } }\n"
	files, err := (&Backend{}).Generate(schemaOf(t, src), map[string]any{})
	if err != nil {
		t.Fatal(err)
	}
	out := string(files[0].Content)
	seen := map[string]bool{}
	for _, m := range regexp.MustCompile(`private const int (Root\w*) = `).FindAllStringSubmatch(out, -1) {
		if seen[m[1]] {
			t.Errorf("location constant %s is defined twice", m[1])
		}
		seen[m[1]] = true
	}
	if !seen["Root_a_b"] || !seen["Root_a__b"] {
		t.Errorf("want constants Root_a_b and Root_a__b, got %v", seen)
	}
}

// csDecl matches a namespace-level declaration of the generated module (or of
// the harness): a class or enum at column 0.
var csDecl = regexp.MustCompile(`(?m)^(?:\[[^\]]*\]\s*)?(?:public |internal |static |sealed )*(?:class|enum|struct|record|interface) (\w+)`)

// TestNamesSchemaDeclaresEachNameOnce generates the shared name-collision
// schema (tests/conformance/lib/names.yaml) and checks, without a toolchain,
// that every namespace-level declaration of Message.cs and of Program.cs
// appears exactly once, that no generated type is spelled like a harness class,
// and that the old spellings are gone.
func TestNamesSchemaDeclaresEachNameOnce(t *testing.T) {
	doc, err := parser.Load("../../tests/conformance/lib/names.yaml")
	if err != nil {
		t.Fatal(err)
	}
	resolved, err := doc.Resolve()
	if err != nil {
	}
	if errs := parser.Validate(resolved); len(errs) > 0 {
		t.Fatalf("names.yaml does not validate: %v", errs)
	}
	s, err := model.Build(doc)
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.Analyze(s); err != nil {
		t.Fatal(err)
	}
	files, err := (&Backend{}).Generate(s, map[string]any{"emit": "project"})
	if err != nil {
		t.Fatalf("names.yaml must generate: %v", err)
	}
	declared := map[string]int{}
	for _, f := range files {
		if !strings.HasSuffix(f.Path, ".cs") {
			continue
		}
		for _, m := range csDecl.FindAllStringSubmatch(string(f.Content), -1) {
			declared[m[1]]++
		}
	}
	for n, c := range declared {
		if c != 1 {
			t.Errorf("%s is declared %d times at namespace level", n, c)
		}
	}
	// One type per message and named type, plus a visitor per message.
	if want := len(s.Named) + 2*len(s.Messages); len(declared) < want {
		t.Errorf("%d namespace-level declarations, want at least %d", len(declared), want)
	}
	for _, n := range []string{
		"M", "M_A", "MA", "M_Decoder", "MDecoder", "_M__Visitor", "M_Visitor", "MVisitor",
		"M_New", "NewM", "M_Arr", "M_ArrElem", "M_U", "M_U_Default", "A_BC", "AB_C",
		"Point", "StructPoint", "Shape__DefaultNum", "Shape__DefaultPt", "Shape_Pt",
		"ShapeDefault", "ShapeDefault_Pt", "ShapeDefaultPt", "Color", "ColorRed",
		"Flags", "FlagsOn", "Decoder_", "MaxSize_", "Serialize_", "Message", "Program",
		"OStream", "System", "Array", "_Program", "_ByteArrayConverter",
		"_Shape__DefaultPt__JsonConverter", "_M_U__JsonConverter",
	} {
		if declared[n] != 1 {
			t.Errorf("want %s declared once, got %d", n, declared[n])
		}
	}
	if strings.Contains(string(files[0].Content), "\nusing ") {
		t.Errorf("Message.cs must import nothing: every outer name is global::-qualified")
	}
}

var (
	csBlank  = regexp.MustCompile(`(?s)/\*.*?\*/|//[^\n]*|@"(?:[^"]|"")*"|\$?"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)'`)
	csClass  = regexp.MustCompile(`(?m)^public (?:sealed |partial |static )*class (\w+)[^{\n]*\{`)
	csMember = regexp.MustCompile(`^\s*(?:\[[^\]]*\]\s*)*(?:(?:public|private|internal|protected|static|readonly|const|override|sealed|partial|virtual|new|unsafe)\s+)+(?:(?:class|struct|enum|record)\s+)?(?:[\w<>\[\],.:?]+\s+)?(\w+)\s*(?:\(|=>|=|;|\{)`)
	csNested = regexp.MustCompile(`^\s*(?:(?:public|private|internal|protected|static|sealed|partial)\s+)*(?:class|struct|enum|record|interface)\s+(\w+)`)
	csQual   = regexp.MustCompile(`(?:^|[^\w.:])([A-Za-z_]\w*)\.[A-Za-z_]`)
	csDerive = regexp.MustCompile(`^(Has|Mutable|Id)_[A-Z]`)
)

// csScope walks every public top-level class of one generated file and returns
// the members each declares at its own level, the nested types among them, and
// the upper-case qualifiers its body uses.
func csScope(src string) (members, nested, quals []string) {
	src = csBlank.ReplaceAllString(src, `""`)
	for _, loc := range csClass.FindAllStringIndex(src, -1) {
		depth := 1
		var body strings.Builder
		for _, line := range strings.Split(src[loc[1]:], "\n") {
			if depth == 0 {
				break
			}
			if depth == 1 {
				if m := csMember.FindStringSubmatch(line); m != nil {
					members = append(members, m[1])
				}
				if m := csNested.FindStringSubmatch(line); m != nil {
					nested = append(nested, m[1])
				}
			}
			depth += strings.Count(line, "{") - strings.Count(line, "}")
			body.WriteString(line + "\n")
		}
		for _, m := range csQual.FindAllStringSubmatch(body.String(), -1) {
			if n := m[1]; n[0] >= 'A' && n[0] <= 'Z' {
				quals = append(quals, n)
			}
		}
	}
	return members, nested, quals
}

// TestCSharpNamesInScope is the drift guard for both levels of the list: over
// the corpus, realworld set and example,
//   - every member a public generated class declares that is not a schema field
//     (or a union's derived Has_/Mutable_/Id_ member, or a `_` name no schema
//     spells) must be on csMembers/unionFixed;
//   - every nested type one declares must be on csTypeReserved: inside that
//     class its simple name wins over a namespace-level type;
//   - a class body may use no upper-case name as an expression qualifier: an
//     outer name is `global::`-qualified, which no field or type can shadow, and
//     Message.cs imports nothing.
func TestCSharpNamesInScope(t *testing.T) {
	defs, _ := filepath.Glob("../../tests/matrix/corpus/defs/*.yaml")
	rw, _ := filepath.Glob("../../examples/messages/realworld/*.yaml")
	defs = append(append(defs, rw...), "../../examples/messages/example.yaml", "../../tests/conformance/lib/names.yaml")
	for _, def := range defs {
		doc, err := parser.Load(def)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := doc.Resolve(); err != nil {
			t.Fatal(err)
		}
		s, err := model.Build(doc)
		if err != nil {
			t.Fatal(err)
		}
		if err := analysis.Analyze(s); err != nil {
			t.Fatal(err)
		}
		fields := map[string]bool{}
		for _, m := range s.Messages {
			for _, f := range m.Fields {
				fields[strings.TrimPrefix(csIdent(f.Name), "@")] = true
			}
		}
		for _, nt := range s.Named {
			for _, f := range nt.Fields {
				fields[strings.TrimPrefix(csIdent(f.Name), "@")] = true
				if nt.Category == ir.CatUnion {
					fields[unionOptProp(f)] = true
				}
			}
		}
		files, err := (&Backend{}).Generate(s, map[string]any{})
		if err != nil {
			t.Fatalf("%s: %v", def, err)
		}
		src := string(files[0].Content)
		if strings.Contains(src, "\nusing ") {
			t.Errorf("%s: Message.cs has a using directive", filepath.Base(def))
		}
		members, nested, quals := csScope(src)
		for _, n := range members {
			if fields[n] || strings.HasPrefix(n, "_") || csDerive.MatchString(n) || csReserved(n) || unionFixed[n] {
				continue
			}
			t.Errorf("%s: member %s is not on csMembers", filepath.Base(def), n)
		}
		for _, n := range nested {
			if csTypeReserved[n] == "" {
				t.Errorf("%s: nested type %s is not on csTypeReserved", filepath.Base(def), n)
			}
		}
		for _, n := range quals {
			t.Errorf("%s: %s is used unqualified in front of a dot; write it global::-qualified", filepath.Base(def), n)
		}
	}
}
