/*!
 * @file scalars_sofab.h
 * @brief SofaBuffers generated types for "Scalars" - DO NOT EDIT.
 *
 * @generated by sofabgen. Regenerate instead of editing; manual changes are lost.
 */

#ifndef MESSAGE_SCALARS__H
#define MESSAGE_SCALARS__H

#include <stdint.h>
#include <stddef.h>
#include "sofab/sofab.h"
#include "sofab/object.h"

/* --- API-version guard: this code was generated against C API v1 --- */
#if SOFAB_API_VERSION != 1
# error "SofaBuffers: generated against C API v1, but the linked corelib reports a different SOFAB_API_VERSION. Regenerate or update the corelib."
#endif

/* --- capability guards: a feature-stripped corelib fails loudly --- */
#if defined(SOFAB_DISABLE_FIXLEN_SUPPORT)
# error "SofaBuffers: message Scalars uses fixed-length fields (string/blob/fp), but the corelib was built with SOFAB_DISABLE_FIXLEN_SUPPORT."
#endif
#if defined(SOFAB_DISABLE_FP64_SUPPORT)
# error "SofaBuffers: message Scalars uses fp64/double, but the corelib was built with SOFAB_DISABLE_FP64_SUPPORT."
#endif
#if defined(SOFAB_DISABLE_ARRAY_SUPPORT)
# error "SofaBuffers: message Scalars uses numeric arrays, but the corelib was built with SOFAB_DISABLE_ARRAY_SUPPORT."
#endif
#if defined(SOFAB_DISABLE_INT64_SUPPORT)
# error "SofaBuffers: message Scalars uses 64-bit integers, but the corelib was built with SOFAB_DISABLE_INT64_SUPPORT."
#endif

/* --- value-width guard: field ids must fit the corelib's id ceiling --- */
#if 8 > SOFAB_ID_MAX
# error "SofaBuffers: field ids in Scalars exceed SOFAB_ID_MAX for this value width (see SOFAB_DISABLE_INT64_SUPPORT)."
#endif

typedef struct {
    uint64_t u64max;
    int64_t i64min;
    double f64;
    /**
     * Schema bound: count 4 is a capacity; flags__len carries the length -- elements set without it encode an EMPTY array; encode clamps flags__len to at most 4. Over 4 on the wire is INVALID.
     */
    uint8_t flags__len; uint8_t flags[4];
    float f32;
    uint8_t u8min;
    uint8_t u8max;
    int8_t i8min;
    uint8_t flag;
} message_Scalars_t;

/*! Worst-case serialized size of Scalars (every field present, all maxlen/count). */
#define MESSAGE_SCALARS__MAX_SIZE 55

/*! Initialize a Scalars with its schema defaults (non-default fields zeroed). */
void message_Scalars__init(message_Scalars_t *msg);
/*! Encode msg into buf[buflen]; *used receives the byte count. Returns sofab_ret_t. */
sofab_ret_t message_Scalars__encode(const message_Scalars_t *msg, uint8_t *buf, size_t buflen, size_t *used);
/*! Decode buf[len] into msg (call message_Scalars__init first to apply defaults). Returns sofab_ret_t. */
sofab_ret_t message_Scalars__decode(message_Scalars_t *msg, const uint8_t *buf, size_t len);

/*! Object descriptor for Scalars, for use with the sofab_object_* API directly. */
extern const sofab_object_descr_t message_Scalars__descr;

/*!
 * Encode msg into a stream the caller owns. With a flush callback on that
 * stream the message may exceed its buffer: the buffer is drained as it
 * fills, so what bounds memory is the buffer, not the message. The caller
 * flushes the tail with sofab_ostream_flush().
 */
sofab_ret_t message_Scalars__encode_to(sofab_ostream_t *os, const message_Scalars_t *msg);

/*!
 * Incremental decoder: hold one and feed the message as bytes arrive,
 * instead of buffering it whole first.
 *
 * The wire format has no end marker at the top level -- a message ends
 * where its bytes end -- so a feed cannot report that the MESSAGE is
 * complete, only that the bytes handed in ended on a field boundary
 * (SOFAB_RET_OK) or mid-field (SOFAB_RET_INCOMPLETE). Neither is a failure
 * mid-stream; the caller's own framing decides when the input is over, and
 * the last verdict says whether it ended half-read.
 */
typedef struct {
    sofab_istream_t is;
    sofab_object_decoder_t dec[1];
} message_Scalars__decoder_t;

/*! Bind a decoder to msg. Call message_Scalars__init on msg first to apply defaults. */
void message_Scalars__decoder_init(message_Scalars__decoder_t *d, message_Scalars_t *msg);

/*! Feed the next chunk. See message_Scalars__decoder_t for what the return value means. */
sofab_ret_t message_Scalars__decoder_feed(message_Scalars__decoder_t *d, const void *buf, size_t len);

#endif /* MESSAGE_SCALARS__H */
