/*!
 * @file scalars_sofab.c
 * @brief SofaBuffers generated types for "Scalars" - DO NOT EDIT.
 *
 * @generated by sofabgen. Regenerate instead of editing; manual changes are lost.
 */

#include "scalars_sofab.h"

#include <string.h>

static const sofab_object_descr_field_t _message_Scalars__fields[] = {
    SOFAB_OBJECT_FIELD(0, message_Scalars_t, u8min, SOFAB_OBJECT_FIELDTYPE_UNSIGNED),
    SOFAB_OBJECT_FIELD(1, message_Scalars_t, u8max, SOFAB_OBJECT_FIELDTYPE_UNSIGNED),
    SOFAB_OBJECT_FIELD(2, message_Scalars_t, u64max, SOFAB_OBJECT_FIELDTYPE_UNSIGNED),
    SOFAB_OBJECT_FIELD(3, message_Scalars_t, i8min, SOFAB_OBJECT_FIELDTYPE_SIGNED),
    SOFAB_OBJECT_FIELD(4, message_Scalars_t, i64min, SOFAB_OBJECT_FIELDTYPE_SIGNED),
    SOFAB_OBJECT_FIELD(5, message_Scalars_t, f32, SOFAB_OBJECT_FIELDTYPE_FP32),
    SOFAB_OBJECT_FIELD(6, message_Scalars_t, f64, SOFAB_OBJECT_FIELDTYPE_FP64),
    SOFAB_OBJECT_FIELD(7, message_Scalars_t, flag, SOFAB_OBJECT_FIELDTYPE_BOOLEAN),
    SOFAB_OBJECT_FIELD_ARRAY_SIZED(8, message_Scalars_t, flags, flags__len, SOFAB_OBJECT_FIELDTYPE_ARRAY_BOOLEAN),
};
static const message_Scalars_t _message_Scalars__defaults = {
    .u8max = 255,
    .u64max = 18446744073709551615ULL,
    .i8min = -128,
    .i64min = (-9223372036854775807LL - 1),
    .f32 = 3.14f,
    .f64 = -2.5,
    .flag = 1,
};
const sofab_object_descr_t message_Scalars__descr = SOFAB_OBJECT_DESCR_WITH_DEFAULTS(_message_Scalars__fields, 9, NULL, 0, &_message_Scalars__defaults);

void message_Scalars__init(message_Scalars_t *msg) {
    memset(msg, 0, sizeof(*msg));
    sofab_object_init(&message_Scalars__descr, msg);
}

sofab_ret_t message_Scalars__encode(const message_Scalars_t *msg, uint8_t *buf, size_t buflen, size_t *used) {
    sofab_ostream_t ctx;
    sofab_ret_t ret;
    sofab_ostream_init(&ctx, buf, buflen, 0, NULL, NULL);
    ret = sofab_object_encode(&ctx, &message_Scalars__descr, msg);
    if (used) { *used = sofab_ostream_flush(&ctx); }
    return ret;
}

sofab_ret_t message_Scalars__encode_to(sofab_ostream_t *os, const message_Scalars_t *msg) {
    return sofab_object_encode(os, &message_Scalars__descr, msg);
}

void message_Scalars__decoder_init(message_Scalars__decoder_t *d, message_Scalars_t *msg) {
    memset(d->dec, 0, sizeof(d->dec));
    d->dec[0].info = &message_Scalars__descr;
    d->dec[0].dst = (uint8_t *)msg;
    d->dec[0].depth = (uint8_t)(sizeof(d->dec) / sizeof(d->dec[0]) - 1);
    sofab_istream_init(&d->is, sofab_object_field_cb, (void *)&d->dec[0]);
}

sofab_ret_t message_Scalars__decoder_feed(message_Scalars__decoder_t *d, const void *buf, size_t len) {
    return sofab_istream_feed(&d->is, buf, len);
}

sofab_ret_t message_Scalars__decode(message_Scalars_t *msg, const uint8_t *buf, size_t len) {
    message_Scalars__decoder_t d;
    message_Scalars__decoder_init(&d, msg);
    return message_Scalars__decoder_feed(&d, buf, len);
}
