package c

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// projectFiles scaffolds a buildable C root project around the generated
// message sources (PLAN §9.1): build manifests, devcontainer wiring, the
// IR-driven encode/decode JSON harness, and a runnable README/script.
func (g *gen) projectFiles(s *ir.Schema) []generator.File {
	return []generator.File{
		{Path: "Makefile", Content: []byte(g.makefile())},
		{Path: "CMakeLists.txt", Content: []byte(g.cmake())},
		{Path: ".devcontainer/devcontainer.json", Content: []byte(devcontainer)},
		{Path: "harness/main.c", Content: g.harness(s)},
		{Path: "README.md", Content: []byte(g.readme(s))},
		{Path: "run.sh", Content: []byte(runScript)},
	}
}

func (g *gen) makefile() string {
	return `# @generated by sofabgen - builds the encode/decode harness against corelib-c-cpp.
# Point SOFAB_C_CORELIB at a corelib-c-cpp checkout.
SOFAB_C_CORELIB ?= /opt/corelib-c-cpp
CC ?= cc
# The C standard is kept separate from CFLAGS so it is always applied even if a
# caller overrides CFLAGS. The generated code targets C99.
CSTD ?= -std=c99
CFLAGS ?= -Wall -Wextra
INCLUDES := -Igenerated -I$(SOFAB_C_CORELIB)/src/include -I$(SOFAB_C_CORELIB)/test/shared
CORE := $(SOFAB_C_CORELIB)/src/object.c $(SOFAB_C_CORELIB)/src/ostream.c $(SOFAB_C_CORELIB)/src/istream.c
JSON := $(SOFAB_C_CORELIB)/test/shared/sofab_test_json.c
GEN  := $(wildcard generated/*.c)

harness/harness: harness/main.c $(GEN) $(CORE) $(JSON)
	$(CC) $(CSTD) $(CFLAGS) $(INCLUDES) $^ -o $@

.PHONY: clean
clean:
	rm -f harness/harness
`
}

func (g *gen) cmake() string {
	return `# @generated by sofabgen
cmake_minimum_required(VERSION 3.16)
project(sofabuffers_generated C)
set(CMAKE_C_STANDARD 99)

if(NOT DEFINED SOFAB_C_CORELIB)
  set(SOFAB_C_CORELIB $ENV{SOFAB_C_CORELIB})
endif()
if(NOT SOFAB_C_CORELIB)
  message(FATAL_ERROR "set SOFAB_C_CORELIB to a corelib-c-cpp checkout")
endif()

file(GLOB GEN_SRC generated/*.c)
add_executable(harness
  harness/main.c ${GEN_SRC}
  ${SOFAB_C_CORELIB}/src/object.c
  ${SOFAB_C_CORELIB}/src/ostream.c
  ${SOFAB_C_CORELIB}/src/istream.c
  ${SOFAB_C_CORELIB}/test/shared/sofab_test_json.c)
target_include_directories(harness PRIVATE
  generated ${SOFAB_C_CORELIB}/src/include ${SOFAB_C_CORELIB}/test/shared)
`
}

const devcontainer = `{
  "// @generated by sofabgen": "reuses corelib-c-cpp's toolchain (Ubuntu 24.04 + gcc + cmake)",
  "name": "sofabuffers-generated-c",
  "build": { "dockerfile": "../../corelib-c-cpp/.devcontainer/Dockerfile" },
  "postCreateCommand": "cmake -S . -B build -DSOFAB_C_CORELIB=/opt/corelib-c-cpp && cmake --build build"
}
`

const runScript = `#!/usr/bin/env sh
# @generated by sofabgen - build + a JSON encode->decode round-trip smoke test.
set -eu
: "${SOFAB_C_CORELIB:?set SOFAB_C_CORELIB to a corelib-c-cpp checkout}"
make
echo "built harness/harness"
`

func (g *gen) readme(s *ir.Schema) string {
	var b strings.Builder
	b.WriteString("# Generated SofaBuffers C project\n\n")
	b.WriteString("`@generated by sofabgen`. Builds an encode/decode harness against `corelib-c-cpp`.\n\n")
	b.WriteString("## Build\n\n```sh\nmake SOFAB_C_CORELIB=/path/to/corelib-c-cpp\n```\n\n")
	b.WriteString("## Harness CLI\n\n")
	b.WriteString("```sh\n# encode: canonical JSON on stdin -> serialized bytes on stdout\n")
	b.WriteString("echo '{...}' | harness/harness encode [Message]\n")
	b.WriteString("# decode: serialized bytes on stdin -> canonical JSON on stdout\n")
	b.WriteString("harness/harness decode [Message] < bytes.bin\n```\n\n")
	b.WriteString("Messages: ")
	for i, m := range s.Messages {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString("`" + m.Name + "`")
	}
	b.WriteString("\n")
	return b.String()
}

// ---- harness (IR-driven encode/decode JSON CLI) -------------------------

func (g *gen) harness(s *ir.Schema) []byte {
	h := &cfile{}
	h.banner(g.banner, g.license, "main.c", "encode/decode harness")
	h.line("#include <stdio.h>")
	h.line("#include <stdlib.h>")
	h.line("#include <string.h>")
	h.line(`#include "sofab_test_json.h"`)
	for _, m := range s.Messages {
		h.line(`#include "%s.h"`, strings.ToLower(m.Name))
	}
	h.blank()
	h.line("%s", jsonPrelude)
	h.blank()

	// Forward-declare every json function so callers precede definitions
	// regardless of emission order (a struct may use a type defined later).
	h.line("/* forward declarations */")
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			ct := g.cType("named/"+key, nt.Name)
			h.line("static void %s_to_json(const %s *o, FILE *out);", g.jsonFn(key), ct)
			h.line("static void %s_from_json(const sofab_json_t *j, %s *o);", g.jsonFn(key), ct)
		}
	}
	h.blank()

	// Emit to_json/from_json for every struct/union named type, then messages.
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitToJSON(h, g.cType("named/"+key, nt.Name), g.jsonFn(key), nt.Fields)
			g.emitFromJSON(h, g.cType("named/"+key, nt.Name), g.jsonFn(key), nt.Fields)
		}
	}
	for _, m := range s.Messages {
		ct := g.cType("message/"+m.Name, m.Name)
		g.emitToJSON(h, ct, g.jsonFnName(m.Name), m.Fields)
		g.emitFromJSON(h, ct, g.jsonFnName(m.Name), m.Fields)
	}

	g.emitMain(h, s)
	return h.bytes()
}

func (g *gen) jsonFn(key string) string   { return g.prefix + sanitizeKey(key) }
func (g *gen) jsonFnName(n string) string { return g.prefix + sanitizeKey(n) }

func (g *gen) emitToJSON(h *cfile, cType, fn string, fields []*ir.Field) {
	h.line("static void %s_to_json(const %s *o, FILE *out) {", fn, cType)
	h.line(`    fputc('{', out);`)
	for i, f := range fields {
		if i > 0 {
			h.line(`    fputc(',', out);`)
		}
		h.line(`    fprintf(out, "\"%s\":");`, f.Name)
		g.fieldToJSON(h, f)
	}
	h.line(`    fputc('}', out);`)
	h.line("}")
	h.blank()
}

func (g *gen) fieldToJSON(h *cfile, f *ir.Field) {
	acc := "o->" + f.Name
	switch f.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		h.line(`    fprintf(out, "%%llu", (unsigned long long)%s);`, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		h.line(`    fprintf(out, "%%lld", (long long)%s);`, acc)
	case ir.KindBool:
		h.line(`    fputs(%s ? "true" : "false", out);`, acc)
	case ir.KindFP32, ir.KindFP64:
		h.line(`    fprintf(out, "%%.17g", (double)%s);`, acc)
	case ir.KindString:
		h.line(`    json_str(out, %s);`, acc)
	case ir.KindBlob:
		h.line(`    json_bytes(out, %s, sizeof(%s));`, acc, acc)
	case ir.KindStruct, ir.KindUnion:
		h.line(`    %s_to_json(&%s, out);`, g.jsonFn(f.Ref.Key), acc)
	case ir.KindArray:
		g.arrayToJSON(h, f, acc)
	}
}

func (g *gen) arrayToJSON(h *cfile, f *ir.Field, acc string) {
	g.arrayValueToJSON(h, specOfField(f), acc, "    ", 0)
}

// arrayValueToJSON emits the JSON for one array value. Native numeric/enum/
// boolean/bitfield elements are read from acc[_iN]; string/blob/struct/union and
// nested-array elements live in the holder's acc.items[_iN] slot. Recurses for
// nested arrays, depth-suffixing the loop variable.
func (g *gen) arrayValueToJSON(h *cfile, spec arraySpec, acc, ind string, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	h.line(`%sfputc('[', out);`, ind)
	h.line("%sfor (int %s = 0; %s < %d; %s++) {", ind, iv, iv, spec.count, iv)
	h.line(`%s    if (%s) fputc(',', out);`, ind, iv)
	elem := fmt.Sprintf("%s[%s]", acc, iv)     // native element access
	slot := fmt.Sprintf("%s.items[%s]", acc, iv) // holder element access
	switch spec.elem {
	case ir.KindFP32, ir.KindFP64:
		h.line(`%s    fprintf(out, "%%.17g", (double)%s);`, ind, elem)
	case ir.KindBool:
		h.line(`%s    fputs(%s ? "true" : "false", out);`, ind, elem)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		h.line(`%s    fprintf(out, "%%lld", (long long)%s);`, ind, elem)
	case ir.KindString:
		h.line(`%s    json_str(out, %s);`, ind, slot)
	case ir.KindBlob:
		h.line(`%s    json_bytes(out, %s, sizeof(%s));`, ind, slot, slot)
	case ir.KindStruct, ir.KindUnion:
		h.line(`%s    %s_to_json(&%s, out);`, ind, g.jsonFn(spec.ref.Key), slot)
	case ir.KindArray:
		g.arrayValueToJSON(h, specOfItems(spec.items), slot, ind+"    ", depth+1)
	default: // unsigned numeric, bitfield
		h.line(`%s    fprintf(out, "%%llu", (unsigned long long)%s);`, ind, elem)
	}
	h.line("%s}", ind)
	h.line(`%sfputc(']', out);`, ind)
}

func (g *gen) emitFromJSON(h *cfile, cType, fn string, fields []*ir.Field) {
	h.line("static void %s_from_json(const sofab_json_t *j, %s *o) {", fn, cType)
	h.line("    const sofab_json_t *c;")
	h.line("    (void)c;")
	for _, f := range fields {
		g.fieldFromJSON(h, f)
	}
	h.line("}")
	h.blank()
}

func (g *gen) fieldFromJSON(h *cfile, f *ir.Field) {
	acc := "o->" + f.Name
	h.line(`    c = sofab_json_get(j, "%s");`, f.Name)
	h.line("    if (c) {")
	switch f.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		h.line("        %s = (%s)sofab_json_u64(c);", acc, scalarCType(f))
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		h.line("        %s = (%s)sofab_json_i64(c);", acc, scalarCType(f))
	case ir.KindBool:
		h.line("        %s = (uint8_t)sofab_json_bool(c);", acc)
	case ir.KindFP32:
		h.line("        %s = (float)sofab_json_double(c);", acc)
	case ir.KindFP64:
		h.line("        %s = (double)sofab_json_double(c);", acc)
	case ir.KindString:
		h.line("        json_to_str(c, %s, sizeof(%s));", acc, acc)
	case ir.KindBlob:
		h.line("        json_to_bytes(c, %s, sizeof(%s));", acc, acc)
	case ir.KindStruct, ir.KindUnion:
		h.line("        %s_from_json(c, &%s);", g.jsonFn(f.Ref.Key), acc)
	case ir.KindArray:
		g.arrayFromJSON(h, f, acc)
	}
	h.line("    }")
}

func (g *gen) arrayFromJSON(h *cfile, f *ir.Field, acc string) {
	g.arrayValueFromJSON(h, specOfField(f), acc, "c", "        ", 0)
}

// arrayValueFromJSON parses one array value from the JSON node jnode. Mirrors
// arrayValueToJSON: native elements land in acc[_iN], holder elements in
// acc.items[_iN]. Recurses for nested arrays.
func (g *gen) arrayValueFromJSON(h *cfile, spec arraySpec, acc, jnode, ind string, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	ev := fmt.Sprintf("_e%d", depth)
	h.line("%sfor (size_t %s = 0; %s < sofab_json_array_size(%s) && %s < %d; %s++) {", ind, iv, iv, jnode, iv, spec.count, iv)
	h.line("%s    const sofab_json_t *%s = sofab_json_array_at(%s, %s);", ind, ev, jnode, iv)
	elem := fmt.Sprintf("%s[%s]", acc, iv)
	slot := fmt.Sprintf("%s.items[%s]", acc, iv)
	switch spec.elem {
	case ir.KindFP32:
		h.line("%s    %s = (float)sofab_json_double(%s);", ind, elem, ev)
	case ir.KindFP64:
		h.line("%s    %s = (double)sofab_json_double(%s);", ind, elem, ev)
	case ir.KindBool:
		h.line("%s    %s = (uint8_t)sofab_json_bool(%s);", ind, elem, ev)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		h.line("%s    %s = (%s)sofab_json_i64(%s);", ind, elem, g.arrayElemCType(spec.elem, spec.ref), ev)
	case ir.KindString:
		h.line("%s    json_to_str(%s, %s, sizeof(%s));", ind, ev, slot, slot)
	case ir.KindBlob:
		h.line("%s    json_to_bytes(%s, %s, sizeof(%s));", ind, ev, slot, slot)
	case ir.KindStruct, ir.KindUnion:
		h.line("%s    %s_from_json(%s, &%s);", ind, g.jsonFn(spec.ref.Key), ev, slot)
	case ir.KindArray:
		g.arrayValueFromJSON(h, specOfItems(spec.items), slot, ev, ind+"    ", depth+1)
	default: // unsigned numeric, bitfield
		h.line("%s    %s = (%s)sofab_json_u64(%s);", ind, elem, g.arrayElemCType(spec.elem, spec.ref), ev)
	}
	h.line("%s}", ind)
}

func (g *gen) emitMain(h *cfile, s *ir.Schema) {
	h.line("int main(int argc, char **argv) {")
	h.line("    if (argc < 2) { fprintf(stderr, \"usage: %%s <encode|decode> [Message]\\n\", argv[0]); return 2; }")
	h.line("    const char *mode = argv[1];")
	h.line(`    const char *msg = argc > 2 ? argv[2] : %q;`, s.Messages[0].Name)
	h.line("    (void)msg;")
	h.blank()
	h.line("    /* read all of stdin */")
	h.line("    size_t cap = 65536, len = 0; unsigned char *in = malloc(cap);")
	h.line("    for (;;) { if (len == cap) { cap *= 2; in = realloc(in, cap); }")
	h.line("        size_t n = fread(in + len, 1, cap - len, stdin); len += n; if (n == 0) break; }")
	h.blank()
	for i, m := range s.Messages {
		ct := g.cType("message/"+m.Name, m.Name)
		fn := g.jsonFnName(m.Name)
		pfx := g.prefix + strings.ToLower(m.Name)
		cond := fmt.Sprintf("strcmp(msg, %q) == 0", m.Name)
		kw := "if"
		if i > 0 {
			kw = "else if"
		}
		h.line("    %s (%s) {", kw, cond)
		h.line("        %s obj; %s_init(&obj);", ct, pfx)
		h.line(`        if (strcmp(mode, "encode") == 0) {`)
		h.line("            char err[128];")
		h.line("            sofab_json_t *root = sofab_json_parse((const char *)in, len, err, sizeof(err));")
		h.line(`            if (!root) { fprintf(stderr, "json: %%s\n", err); return 1; }`)
		h.line("            %s_from_json(root, &obj);", fn)
		h.line("            sofab_json_free(root);")
		h.line("            unsigned char out[%s];", strings.ToUpper(g.prefix+m.Name+"_MAX_SIZE"))
		h.line("            size_t used = 0;")
		h.line("            if (%s_encode(&obj, out, sizeof(out), &used) != SOFAB_RET_OK) return 1;", pfx)
		h.line("            fwrite(out, 1, used, stdout);")
		h.line(`        } else if (strcmp(mode, "decode") == 0) {`)
		h.line("            if (%s_decode(&obj, in, len) != SOFAB_RET_OK) return 1;", pfx)
		h.line("            %s_to_json(&obj, stdout);", fn)
		h.line("            fputc('\\n', stdout);")
		h.line(`        } else { fprintf(stderr, "unknown mode\n"); return 2; }`)
		h.line("    }")
	}
	h.line("    else { fprintf(stderr, \"unknown message\\n\"); return 2; }")
	h.line("    free(in);")
	h.line("    return 0;")
	h.line("}")
}

// scalarCType returns the C type of a scalar/enum/bitfield field (for casts).
func scalarCType(f *ir.Field) string {
	switch f.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64:
		return uintC(f.Kind)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		return intC(f.Kind)
	case ir.KindEnum:
		return enumC(f.Ref.Target)
	case ir.KindBitfield:
		return bitfieldC(f.Ref.Target)
	}
	return "long long"
}

// jsonPrelude is the small, dependency-free JSON output + helper block shared by
// the generated harness (the reader comes from corelib's sofab_test_json).
const jsonPrelude = `static void json_str(FILE *out, const char *s) {
    fputc('"', out);
    for (; *s; s++) {
        unsigned char c = (unsigned char)*s;
        if (c == '"' || c == '\\') { fputc('\\', out); fputc(c, out); }
        else if (c == '\n') fputs("\\n", out);
        else if (c == '\t') fputs("\\t", out);
        else if (c == '\r') fputs("\\r", out);
        else if (c < 0x20) fprintf(out, "\\u%04x", c);
        else fputc(c, out);
    }
    fputc('"', out);
}
static void json_bytes(FILE *out, const unsigned char *b, size_t n) {
    fputc('[', out);
    for (size_t i = 0; i < n; i++) { if (i) fputc(',', out); fprintf(out, "%u", b[i]); }
    fputc(']', out);
}
static void json_to_str(const sofab_json_t *c, char *dst, size_t cap) {
    size_t L = 0; const char *s = sofab_json_string(c, &L);
    if (!s) { dst[0] = 0; return; }
    if (L >= cap) L = cap - 1;
    memcpy(dst, s, L); dst[L] = 0;
}
static void json_to_bytes(const sofab_json_t *c, unsigned char *dst, size_t cap) {
    size_t n = sofab_json_array_size(c);
    for (size_t i = 0; i < n && i < cap; i++) dst[i] = (unsigned char)sofab_json_u64(sofab_json_array_at(c, i));
}`
