// Package rust is the Rust backend (PLAN §6.2, embedded/no_std-capable): structs
// with marshal() over OStream and a flat-visitor decode. The corelib's Visitor
// is flat (sequence_begin/end events, no child visitors), so decode is a
// (location, id) state machine with a location stack — every assignment targets
// self.m.<path> directly, which keeps the borrow checker happy.
//
// The `corelib` config key selects the Rust corelib: "rs-no-std" (default,
// corelib-rs-no-std — #![no_std], heap-free, Cargo features to drop unused wire
// types; the generated crate enables only the features the schema needs and a
// require!() guard asserts them) or "rs" (corelib-rs — std, high-throughput,
// every wire type always compiled in, so no features and no require! guard).
// Both expose the same sofab:: interface and produce identical wire bytes.
package rust

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for Rust.
type Backend struct{}

func (*Backend) Lang() string { return "rust" }

// Generate emits src/message.rs; project mode adds Cargo.toml + a serde-json
// harness.
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	g := &gen{schema: s, banner: cfgString(cfg, "tool_banner", "sofabgen"), license: generator.LicenseID(cfg), corelib: cfgString(cfg, "corelib", "rs")}
	files := []generator.File{{Path: "src/message.rs", Content: g.module(s)}}
	if cfgString(cfg, "emit", "sources") == "project" {
		files = append(files, g.projectFiles(s, cfg)...)
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	banner  string
	license string // SPDX id, "" to omit the header line
	// corelib selects the Rust corelib: "rs" (default, corelib-rs — std,
	// high-throughput, every wire type always compiled in, no feature flags and no
	// require! capability guard) or "rs-no-std" (corelib-rs-no-std — #![no_std],
	// heap-free, Cargo feature flags to shrink the binary).
	corelib string
}

// std reports whether the std corelib-rs is selected (vs corelib-rs-no-std).
func (g *gen) std() bool { return g.corelib != "rs-no-std" }

type rfile struct{ b strings.Builder }

func (f *rfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *rfile) blank()        { f.b.WriteByte('\n') }
func (f *rfile) bytes() []byte { return []byte(f.b.String()) }

func (g *gen) module(s *ir.Schema) []byte {
	f := &rfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("// SPDX-License-Identifier: %s", g.license)
	}
	f.line("#![allow(dead_code, unused_variables, unused_imports, non_camel_case_types, clippy::all)]")
	// ArrayKind is only referenced by the per-message decoder's array_begin (and
	// only when the schema has a scalar array); it is gated behind the no-std
	// `array` feature, so it is imported there on demand, not crate-wide.
	f.line("use sofab::{OStream, IStream, Visitor, Id, Unsigned, Signed};")
	f.line("use serde::{Serialize, Deserialize};")
	f.blank()
	// capability guard for the whole crate. corelib-rs-no-std gates wire types
	// behind Cargo features and exposes require!() to assert them; corelib-rs
	// (std) always compiles every wire type in and has no such macro.
	if !g.std() {
		caps := g.capabilities(s)
		if len(caps) > 0 {
			f.line("sofab::require!(%s);", strings.Join(caps, ", "))
			f.blank()
		}
	}

	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfieldConsts(f, nt)
		}
	}
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitStruct(f, g.typeName(key), nt.Fields, false, "")
		}
	}
	for _, m := range s.Messages {
		g.emitStruct(f, exported(m.Name), m.Fields, true, m.Summary)
	}
	return f.bytes()
}

func (g *gen) emitEnum(f *rfile, nt *ir.NamedType) {
	f.line("pub mod %s {", strings.ToLower(g.typeName(nt.Key)))
	for _, c := range nt.Consts {
		f.line("    pub const %s: %s = %d;", strings.ToUpper(c.Name), enumBacking(nt), c.Value)
	}
	f.line("}")
	f.blank()
}

func (g *gen) emitBitfieldConsts(f *rfile, nt *ir.NamedType) {
	f.line("pub mod %s {", strings.ToLower(g.typeName(nt.Key)))
	for _, fl := range nt.Flags {
		f.line("    pub const %s: %s = 1 << %d;", strings.ToUpper(fl.Name), bitfieldBacking(nt), fl.Pos)
	}
	f.line("}")
	f.blank()
}

// emitDoc writes a rustdoc `///` comment (one line per line of text) at the
// given indent. Empty text emits nothing, so it never leaves a dangling `///`.
func (f *rfile) emitDoc(indent, text string) {
	if text == "" {
		return
	}
	for _, ln := range strings.Split(text, "\n") {
		f.line("%s/// %s", indent, ln)
	}
}

// fieldDoc builds a field's rustdoc text from its Description and Unit.
func fieldDoc(fld *ir.Field) string {
	switch {
	case fld.Description != "" && fld.Unit != "":
		return fld.Description + " (unit: " + fld.Unit + ")"
	case fld.Description != "":
		return fld.Description
	case fld.Unit != "":
		return "(unit: " + fld.Unit + ")"
	default:
		return ""
	}
}

func (g *gen) emitStruct(f *rfile, name string, fields []*ir.Field, isMessage bool, summary string) {
	// rustdoc summary attaches to the struct that immediately follows.
	f.emitDoc("", summary)
	// Encoding is sparse-canonical (MESSAGE_SPEC S2): a field equal to its default
	// is omitted, so decode must reconstruct schema defaults. A manual Default impl
	// carries them (native scalar arrays and blobs materialize their default too),
	// so derive(Default) type-zeros are never correct here.
	f.line("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
	f.line("#[serde(default)]")
	f.line("pub struct %s {", name)
	for _, fld := range fields {
		// rustdoc attaches to the item that follows, so the doc must precede
		// any #[serde(rename = ...)] attribute and the field itself.
		f.emitDoc("    ", fieldDoc(fld))
		if rustNeedsRename(fld.Name) {
			f.line("    #[serde(rename = %q)]", fld.Name)
		}
		f.line("    pub %s: %s,", rustIdent(fld.Name), g.rustType(fld))
	}
	f.line("}")
	f.blank()
	f.line("impl Default for %s {", name)
	f.line("    fn default() -> Self {")
	f.line("        Self {")
	for _, fld := range fields {
		f.line("            %s: %s,", rustIdent(fld.Name), g.rustFieldDefault(fld))
	}
	f.line("        }")
	f.line("    }")
	f.line("}")
	f.blank()

	f.line("impl %s {", name)
	if isMessage {
		size, _ := g.maxSize(fields)
		f.line("    pub const MAX_SIZE: usize = %d;", size)
	}
	// marshal
	f.line("    pub fn marshal(&self, os: &mut OStream) {")
	for _, fld := range fields {
		g.emitMarshal(f, fld)
	}
	f.line("    }")

	if isMessage {
		f.line("    pub fn encode(&self) -> Vec<u8> {")
		f.line("        let mut buf = vec![0u8; Self::MAX_SIZE];")
		f.line("        let used = { let mut os = OStream::new(&mut buf); self.marshal(&mut os); os.bytes_used() };")
		f.line("        buf.truncate(used);")
		f.line("        buf")
		f.line("    }")
		f.line("    pub fn decode(data: &[u8]) -> Self {")
		f.line("        %s_dec::decode(data)", strings.ToLower(name))
		f.line("    }")
	}
	f.line("}")
	f.blank()

	if isMessage {
		g.emitVisitor(f, name, fields)
	}
}

func (g *gen) emitMarshal(f *rfile, fld *ir.Field) {
	acc := "self." + rustIdent(fld.Name)
	var write string
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		write = fmt.Sprintf("let _ = os.write_unsigned(%d, %s as Unsigned);", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		write = fmt.Sprintf("let _ = os.write_signed(%d, %s as Signed);", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("let _ = os.write_boolean(%d, %s);", fld.ID, acc)
	case ir.KindFP32:
		write = fmt.Sprintf("let _ = os.write_fp32(%d, %s);", fld.ID, acc)
	case ir.KindFP64:
		write = fmt.Sprintf("let _ = os.write_fp64(%d, %s);", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("let _ = os.write_str(%d, &%s);", fld.ID, acc)
	case ir.KindBlob:
		// blob is a leaf: omit when equal to its default (value-equal; empty if
		// none).
		if lit, ok := g.rustBlobLiteral(fld); ok {
			f.line("        if %s != %s { let _ = os.write_blob(%d, &%s); }", acc, lit, fld.ID, acc)
		} else {
			f.line("        if !%s.is_empty() { let _ = os.write_blob(%d, &%s); }", acc, fld.ID, acc)
		}
		return
	case ir.KindStruct, ir.KindUnion:
		// A sequence is always framed; its child fields are omitted per-field by
		// the nested marshal (MESSAGE_SPEC S2). An all-default nested object thus
		// becomes an empty wrapper sequence, not a dropped field.
		f.line("        let _ = os.write_sequence_begin(%d); %s.marshal(os); let _ = os.write_sequence_end();", fld.ID, acc)
		return
	case ir.KindArray:
		g.emitMarshalArray(f, fld, acc)
		return
	}
	// Scalar/string/enum/bitfield leaf: always omit when equal to the default;
	// sparse encoding is canonical (MESSAGE_SPEC S2) and the decoder reconstructs
	// the omitted field from its default.
	f.line("        if %s != %s { %s }", acc, g.rustCompare(fld), write)
}

func (g *gen) emitMarshalArray(f *rfile, fld *ir.Field, acc string) {
	// A native scalar array is a leaf field: omit it when equal to its default
	// (materialized in Default), else when empty. A composite/dynamic-element
	// array is a wrapper sequence and is always framed (never whole-omitted).
	if isNativeArrayElem(fld.Elem) {
		if _, _, ok := g.fixedNativeArray(fld); ok {
			// Fixed `[elem; N]` is never "empty"; omit when equal to its default
			// (mirrors the C++ backend's `!= std::array{}`).
			f.line("        if %s != %s {", acc, g.rustFieldDefault(fld))
		} else if lit, ok := g.rustNativeArrayLiteral(fld); ok {
			f.line("        if %s != %s {", acc, lit)
		} else {
			f.line("        if !%s.is_empty() {", acc)
		}
		g.marshalArray(f, "            ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
		f.line("        }")
		return
	}
	g.marshalArray(f, "        ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
}

// marshalArray writes the array val as field idExpr. Numeric/enum/bitfield
// elements use the native array wire type (numeric/enum by signedness, bitfield
// -> unsigned); boolean lowers to a 0/1 unsigned array; string/blob/struct/union/
// array elements lower to a wrapper sequence whose child ids are the 0-based
// index (per MESSAGE_SPEC). Recurses for nested arrays, depth-suffixing loop vars
// to avoid collisions.
func (g *gen) marshalArray(f *rfile, ind, idExpr, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	iv := fmt.Sprintf("_i%d", depth)
	ev := fmt.Sprintf("_e%d", depth)
	tv := fmt.Sprintf("_t%d", depth)
	switch elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		// bitfield backing is an unsigned int (UnsignedElem), so it writes directly.
		f.line("%slet _ = os.write_array_unsigned(%s, &%s);", ind, idExpr, val)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		// enum backing is a signed int (SignedElem), so it writes directly.
		f.line("%slet _ = os.write_array_signed(%s, &%s);", ind, idExpr, val)
	case ir.KindBool:
		// bool is not an array element type; lower to a 0/1 unsigned array.
		f.line("%s{ let %s: Vec<u8> = %s.iter().map(|_v| *_v as u8).collect(); let _ = os.write_array_unsigned(%s, &%s); }", ind, tv, val, idExpr, tv)
	case ir.KindFP32:
		f.line("%slet _ = os.write_array_fp32(%s, &%s);", ind, idExpr, val)
	case ir.KindFP64:
		f.line("%slet _ = os.write_array_fp64(%s, &%s);", ind, idExpr, val)
	case ir.KindString:
		f.line("%slet _ = os.write_sequence_begin(%s);", ind, idExpr)
		f.line("%sfor (%s, %s) in %s.iter().enumerate() { let _ = os.write_str(%s as Id, %s); }", ind, iv, ev, val, iv, ev)
		f.line("%slet _ = os.write_sequence_end();", ind)
	case ir.KindBlob:
		f.line("%slet _ = os.write_sequence_begin(%s);", ind, idExpr)
		f.line("%sfor (%s, %s) in %s.iter().enumerate() { let _ = os.write_blob(%s as Id, %s); }", ind, iv, ev, val, iv, ev)
		f.line("%slet _ = os.write_sequence_end();", ind)
	case ir.KindStruct, ir.KindUnion:
		f.line("%slet _ = os.write_sequence_begin(%s);", ind, idExpr)
		f.line("%sfor (%s, %s) in %s.iter().enumerate() {", ind, iv, ev, val)
		f.line("%s    let _ = os.write_sequence_begin(%s as Id); %s.marshal(os); let _ = os.write_sequence_end();", ind, iv, ev)
		f.line("%s}", ind)
		f.line("%slet _ = os.write_sequence_end();", ind)
	case ir.KindArray:
		f.line("%slet _ = os.write_sequence_begin(%s);", ind, idExpr)
		f.line("%sfor (%s, %s) in %s.iter().enumerate() {", ind, iv, ev, val)
		g.marshalArray(f, ind+"    ", fmt.Sprintf("%s as Id", iv), ev, items.Elem, items.ElemRef, items.ElemItems, depth+1)
		f.line("%s}", ind)
		f.line("%slet _ = os.write_sequence_end();", ind)
	}
}
