package rust

import (
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

// emitBench emits the Callgrind workload entry points (tests/bench, ARCHITECTURE
// §15). Each run_<workload> performs EXACTLY ONE op and is #[inline(never)] +
// #[no_mangle], so
//
//	valgrind --tool=callgrind --collect-atstart=no --toggle-collect=run_<workload>
//
// collects that single op and nothing else — process start, JSON parsing and the
// decode input's pre-encode all happen in bench_main, before collection is toggled
// on. Same shape as corelib-rs-no-std/benches/bench.rs.
//
// black_box keeps the op from being elided or const-folded. inline(never) is on the
// wrapper only, so encode/try_decode and the corelib still inline into it — that
// inlining is the cost being measured.
func (g *gen) emitBench(f *rfile, s *ir.Schema) {
	for _, m := range s.Messages {
		mt := exported(m.Name)
		low := strings.ToLower(m.Name)
		// Returns the byte count, not the buffer: encode()'s type differs by profile
		// (Vec<u8> with corelib rs, heapless::Vec<u8, MAX_SIZE> with rs-no-std), and
		// usize is the same in both. black_box(&out) keeps the buffer live so the
		// encode cannot be reduced to just its length. bench_main re-encodes outside
		// the collected region for the sink/hex.
		f.line("#[inline(never)]")
		f.line("#[no_mangle]")
		f.line("pub fn run_encode_%s(obj: &%s) -> usize {", low, mt)
		f.line("    let out = black_box(obj).encode();")
		f.line("    black_box(&out);")
		f.line("    out.len()")
		f.line("}")
		f.blank()
		f.line("#[inline(never)]")
		f.line("#[no_mangle]")
		f.line("pub fn run_decode_%s(wire: &[u8]) -> %s {", low, mt)
		f.line("    black_box(%s::try_decode(black_box(wire)).expect(\"decode\"))", mt)
		f.line("}")
		f.blank()
	}

	f.line("// bench_main runs one op of <workload>. Everything here is setup and")
	f.line("// observation; only the run_* call is collected.")
	f.line("fn bench_main(w: &str, input: &[u8]) -> i32 {")
	for _, m := range s.Messages {
		mt := exported(m.Name)
		low := strings.ToLower(m.Name)
		f.line("    if w == \"encode_%s\" || w == \"decode_%s\" {", low, low)
		f.line("        let obj: %s = serde_json::from_slice(input).expect(\"json\");", mt)
		f.line("        let wire = obj.encode(); // setup: the decode input (not collected)")
		f.line("        let mut sink: u64 = 0;")
		f.line("        if w == \"encode_%s\" {", low)
		f.line("            sink = sink.wrapping_add(run_encode_%s(&obj) as u64);", low)
		f.line("        } else {")
		f.line("            let out = run_decode_%s(&wire);", low)
		f.line("            sink = sink.wrapping_add(serde_json::to_vec(&out).map(|v| v.len() as u64).unwrap_or(0));")
		f.line("        }")
		f.line("        eprintln!(\"sink={} BYTES={}\", sink, wire.len());")
		f.line("        let hex: String = wire.iter().map(|b| format!(\"{:02x}\", b)).collect();")
		f.line("        eprintln!(\"wire_hex={}\", hex);")
		f.line("        return 0;")
		f.line("    }")
	}
	f.line("    eprintln!(\"unknown workload: {}\", w);")
	f.line("    2")
	f.line("}")
	f.blank()
}

// projectFiles scaffolds a buildable Cargo binary with a serde-json encode/decode
// harness over the selected Rust corelib: corelib-rs-no-std with only the wire
// types the schema needs (default), or the always-on std corelib-rs.
func (g *gen) projectFiles(s *ir.Schema, cfg map[string]any) []generator.File {
	files := []generator.File{
		{Path: "Cargo.toml", Content: []byte(g.cargoToml(s))},
		{Path: "src/main.rs", Content: g.harness(s)},
		{Path: "README.md", Content: []byte(rustReadme)},
	}
	if g.noStd {
		// The no_std profile ships a lib crate root that carries the crate-level
		// #![no_std] (a bin cannot be no_std on a hosted target — it needs a panic
		// handler); the harness is a separate std bin over that lib.
		files = append(files, generator.File{Path: "src/lib.rs", Content: g.libRoot(s)})
	}
	return files
}

// libRoot is the crate root for the no_std profile: it applies #![no_std] (unless
// the `std` feature, which the harness needs, is on) and re-exports the message
// module. `extern crate alloc` is pulled only when allow_dynamic put an alloc
// container in the generated types.
func (g *gen) libRoot(s *ir.Schema) []byte {
	f := &rfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("// SPDX-License-Identifier: %s", g.license)
	}
	f.line("#![cfg_attr(not(feature = \"std\"), no_std)]")
	if g.usesAlloc(s) {
		f.line("extern crate alloc;")
	}
	f.line("mod message;")
	f.line("pub use message::*;")
	return f.bytes()
}

const rustReadme = "# Generated SofaBuffers Rust crate\n\n" +
	"`@generated by sofabgen`. Encode/decode harness over a Rust corelib -\n" +
	"`corelib-rs-no-std` (default) or `corelib-rs` (`corelib: rs`).\n\n" +
	"```sh\n# set the sofab path in Cargo.toml, then:\n" +
	"echo '{...}' | cargo run -- encode <Message>\n" +
	"cargo run -- decode <Message> < bytes.bin\n```\n"

func (g *gen) cargoToml(s *ir.Schema) string {
	// corelib-rs (std) has no Cargo features — every wire type is always compiled
	// in and the value type is always 64-bit. Its crate is published as the
	// package "sofa-buffers-corelib" (importable as `sofab`).
	dep := `sofab = { package = "sofa-buffers-corelib", path = "${SOFAB_RS_CORELIB}" }`
	if !g.std() {
		// corelib-rs-no-std: turn every feature off and re-enable exactly the wire
		// types this schema uses, so the footprint matches the messages (the point
		// of the no_std build). require!() in the module asserts the same set.
		feats := ""
		if caps := g.capabilities(s); len(caps) > 0 {
			quoted := make([]string, len(caps))
			for i, c := range caps {
				quoted[i] = `"` + c + `"`
			}
			feats = ", features = [" + strings.Join(quoted, ", ") + "]"
		}
		dep = `sofab = { package = "sofa-buffers-corelib-no-std", path = "${SOFAB_RS_CORELIB}", default-features = false` + feats + ` }`
	}
	if g.noStd {
		// Heap-free profile: a lib crate (the firmware artifact, buildable as
		// #![no_std] via `--no-default-features`) plus a std harness bin gated on the
		// `std` feature. serde is optional, pulled by `std` for the JSON harness.
		return `# @generated by sofabgen
[package]
name = "sofabuffers-generated"
version = "0.0.0"
edition = "2021"

[lib]
name = "sofabuffers_generated"
path = "src/lib.rs"

[[bin]]
name = "harness"
path = "src/main.rs"
required-features = ["std"]

[dependencies]
` + dep + `
heapless = { version = "0.8", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[features]
default = ["std"]
# std pulls serde + serde_json so the JSON harness builds; a bare-metal consumer
# uses --no-default-features for a genuinely #![no_std], heap-free lib.
std = ["serde", "dep:serde_json"]
serde = ["dep:serde", "heapless/serde"]
`
	}
	return `# @generated by sofabgen
[package]
name = "sofabuffers-generated"
version = "0.0.0"
edition = "2021"

[dependencies]
` + dep + `
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "harness"
path = "src/main.rs"
`
}

func (g *gen) harness(s *ir.Schema) []byte {
	f := &rfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.noStd {
		// The message module is the crate's lib (src/lib.rs); this std harness bin
		// (built only with the `std` feature) consumes it as a dependency.
		f.line("use sofabuffers_generated::*;")
	} else {
		f.line("mod message;")
		f.line("use message::*;")
	}
	f.line("use std::io::{Read, Write};")
	f.line("use std::hint::black_box;")
	f.blank()
	g.emitBench(f, s)
	f.line("fn main() {")
	f.line("    let args: Vec<String> = std::env::args().collect();")
	f.line("    let mode = args.get(1).map(|s| s.as_str()).unwrap_or(\"\");")
	f.line("    let name = args.get(2).map(|s| s.as_str()).unwrap_or(%q);", defaultMessage(s))
	f.line("    let mut input = Vec::new();")
	f.line("    std::io::stdin().read_to_end(&mut input).unwrap();")
	f.line("    // `bench <workload>` takes a workload, not a message name.")
	f.line("    if mode == \"bench\" {")
	f.line("        std::process::exit(bench_main(args.get(2).map(|s| s.as_str()).unwrap_or(\"\"), &input));")
	f.line("    }")
	f.line("    match name {")
	for _, m := range s.Messages {
		mt := exported(m.Name)
		f.line("        %q => {", m.Name)
		f.line("            if mode == \"encode\" {")
		f.line("                let obj: %s = serde_json::from_slice(&input).expect(\"json\");", mt)
		f.line("                std::io::stdout().write_all(&obj.encode()).unwrap();")
		f.line("            } else if mode == \"decode\" {")
		// try_decode, not the best-effort decode: the harness must surface the
		// accept/reject verdict (a malformed input exits non-zero) so the
		// conformance run can assert rejects, e.g. over-count arrays (#100).
		f.line("                let obj = match %s::try_decode(&input) {", mt)
		f.line("                    Ok(o) => o,")
		f.line("                    Err(e) => { eprintln!(\"decode error: {:?}\", e); std::process::exit(1); }")
		f.line("                };")
		f.line("                println!(\"{}\", serde_json::to_string(&obj).unwrap());")
		f.line("            } else { eprintln!(\"unknown mode\"); std::process::exit(2); }")
		f.line("        }")
	}
	f.line("        _ => { eprintln!(\"unknown message\"); std::process::exit(2); }")
	f.line("    }")
	f.line("}")
	return f.bytes()
}

func defaultMessage(s *ir.Schema) string {
	if len(s.Messages) > 0 {
		return s.Messages[0].Name
	}
	return ""
}

var _ = ir.KindU8
