package rust

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/sofa-buffers/generator/internal/analysis"
	"github.com/sofa-buffers/generator/internal/ir"
	"github.com/sofa-buffers/generator/internal/model"
	"github.com/sofa-buffers/generator/internal/naming"
	"github.com/sofa-buffers/generator/internal/parser"
)

// schemaOf runs parse->validate->IR over an inline schema, stopping short of
// generation so a test can see the generator's own error.
func schemaOf(t *testing.T, src string) *ir.Schema {
	t.Helper()
	doc, err := parser.Parse([]byte(src), "inline.yaml")
	if err != nil {
		t.Fatal(err)
	}
	resolved, _ := doc.Resolve()
	if errs := parser.Validate(resolved); errs != nil {
		t.Fatalf("invalid: %v", errs)
	}
	s, err := model.Build(doc)
	if err != nil {
		t.Fatal(err)
	}
	if err := analysis.Analyze(s); err != nil {
		t.Fatal(err)
	}
	return s
}

var update = flag.Bool("update", false, "rewrite tests/conformance/rust/reserved.{yaml,json} from the reserved-name list")

// reservedNames is every name on the Rust list, sorted.
func reservedNames() []string {
	seen := map[string]bool{}
	var names []string
	for _, set := range []map[string]bool{rustKeywords, rustNonRaw, unionReserved} {
		for n := range set {
			if !seen[n] { // `crate` is on both keyword lists
				seen[n] = true
				names = append(names, n)
			}
		}
	}
	sort.Strings(names)
	return names
}

// foldSplit splits the list into the names a scope can hold together and their
// case twins (`Self` beside `self`): two names of one scope may not share a
// fold (the naming rules), so the twins go to a scope of their own.
func foldSplit(names []string) (first, twins []string) {
	seen := map[string]bool{}
	for _, n := range names {
		if f := naming.Fold(n); seen[f] {
			twins = append(twins, n)
		} else {
			seen[f] = true
			first = append(first, n)
		}
	}
	return first, twins
}

// snakeOf is a schema name whose type identifier is the given Pascal name:
// DecodeError -> decode_error.
func snakeOf(pascal string) string {
	var b strings.Builder
	for i, c := range pascal {
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			c += 'a' - 'A'
		}
		b.WriteRune(c)
	}
	return b.String()
}

// typeReservedNames is every type identifier on rustTypeReserved, sorted.
func typeReservedNames() []string {
	var out []string
	for n := range rustTypeReserved {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}

// reservedYAML is a schema that uses every reserved member name as a field of a
// message, of a nested struct, and as an option of a union; a case twin (`Self`
// beside `self`) sits in an inline struct `twins` of its own. The union also
// holds the pairs whose DERIVED members share a shape -- `x` beside `x_mut`, `a`
// beside `A_ID`, `borrow` beside `borrow_mut`, `deref` beside `deref_mut` --
// which the member spelling keeps apart. It carries the one path clash a _Loc
// variant can hit (the path inner.inner2 beside a field inner_inner2), and every
// type-level reserved name (rustTypeReserved) as a message.
func reservedYAML(names []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/rust/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/rust -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field must build clippy-clean and round-trip.\n")
	first, twins := foldSplit(names)
	var fields, twinFields strings.Builder
	var opts []string
	for i, n := range first {
		fmt.Fprintf(&fields, "      %s: { id: %d, type: u8 }\n", n, i)
		opts = append(opts, fmt.Sprintf("%s: { id: %d, type: u8 }", n, i))
	}
	for i, n := range twins {
		fmt.Fprintf(&twinFields, "          %s: { id: %d, type: u8 }\n", n, i)
	}
	k := len(first)
	for i, n := range []string{"deref", "x", "x_mut", "a", "A_ID"} {
		opts = append(opts, fmt.Sprintf("%s: { id: %d, type: u8 }", n, k+4+i))
	}
	var msgs strings.Builder
	for _, n := range typeReservedNames() {
		fmt.Fprintf(&msgs, "  %s: { payload: { x: { id: 0, type: u8 } } }\n", snakeOf(n))
	}
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
messages:
  m:
    payload:
%s      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      u:            { id: %d, type: union, oneof: { %s } }
      twins:
        id: %d
        type: struct
        fields:
%s%s`, fields.String(), k, fields.String(), k, k+1, k+2, strings.Join(opts, ", "), k+3, twinFields.String(), msgs.String())
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field, nested one,
// case twin, both sides of the path clash and the last union option at a
// non-default value, each under its schema name.
func reservedJSON(names []string) string {
	first, twins := foldSplit(names)
	top := map[string]any{}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	for i, n := range first {
		top[n] = i + 1
		inner[n] = i + 2
	}
	tw := map[string]any{}
	for i, n := range twins {
		tw[n] = i + 3
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{"A_ID": 9}
	top["twins"] = tw
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite builds that file on every profile,
// clippy-clean, and round-trips it (tests/conformance/rust/run.sh), so a name
// added to reserved.go is covered once the file is regenerated -- and this test
// fails until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := reservedNames()
	for path, want := range map[string]string{
		"../../tests/conformance/rust/reserved.yaml": reservedYAML(names),
		"../../tests/conformance/rust/reserved.json": reservedJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// TestReservedNamesAreEscaped: a keyword field is the raw identifier `r#name`,
// one of the four keywords that refuse it is `name_` with a serde rename, and any
// other name on the list (a union member) is the field as it is.
func TestReservedNamesAreEscaped(t *testing.T) {
	names := reservedNames()
	out := moduleFromYAML(t, reservedYAML(names), nil)
	for _, n := range names {
		if !regexp.MustCompile(`(?m)^    pub ` + regexp.QuoteMeta(rustIdent(n)) + `: u8,$`).MatchString(out) {
			t.Errorf("field %q is not the member %s", n, rustIdent(n))
		}
	}
	for _, n := range []string{"self", "Self", "crate", "super"} {
		if !strings.Contains(out, fmt.Sprintf(`#[serde(rename = %q)]`, n)) {
			t.Errorf("field %q lost its JSON name: no serde rename", n)
		}
	}
	// `Self` is mangled to `Self_`, which is not snake_case: the struct carries
	// the allow, or a -D warnings build refuses it.
	if !strings.Contains(out, "#[allow(non_snake_case)] // spelled as the schema names it\npub struct M {") {
		t.Error("struct M has a non-snake_case field but no #[allow(non_snake_case)]")
	}
	// Every type-level reserved name, as a message, takes the escape.
	for _, n := range typeReservedNames() {
		if !strings.Contains(out, "pub struct "+n+"_ {") {
			t.Errorf("message %s is not escaped to %s_", snakeOf(n), n)
		}
	}
}

// TestNonSnakeAllow follows rustc's is_snake_case: upper case or a `__` inside
// the name needs the allow; leading/trailing underscores do not.
func TestNonSnakeAllow(t *testing.T) {
	for ident, want := range map[string]bool{
		"abc": false, "a_b": false, "a_": false, "self_": false,
		"Foo": true, "Self_": true, "a__b": true, "legacyId": true,
	} {
		if got := nonSnakeAllow(ident) != ""; got != want {
			t.Errorf("nonSnakeAllow(%q) = %v, want %v", ident, got, want)
		}
	}
}

// TestMembersAreDistinct: the member spellings keep apart every pair the
// naming rules still admit -- a field `self` is `self_`, which no schema name
// is; enum constants and flags upper-case names whose folds differ, so their
// upper-case spellings differ too. Nothing is refused.
func TestMembersAreDistinct(t *testing.T) {
	out := moduleFromYAML(t, "version: 1\nmessages:\n  m:\n    payload:\n"+
		"      self: { id: 0, type: u8 }\n      self_x: { id: 1, type: u8 }\n"+
		"      e: { id: 2, type: enum, enum: { a_b: 0, abc: 1 } }\n", nil)
	for _, want := range []string{"pub self_: u8,", "pub self_x: u8,", "pub const A_B: i8 = 0;", "pub const ABC: i8 = 1;"} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q", want)
		}
	}
}

// TestLocVariantsAreDistinct: the _Loc variants spell the schema path joined by
// `_`, so the path inner.inner2 and a field inner_inner2 must not give one
// variant twice (error[E0428], with the generator exiting 0).
func TestLocVariantsAreDistinct(t *testing.T) {
	out := moduleFromYAML(t, reservedYAML(reservedNames()), nil)
	body := out[strings.Index(out, "mod _M__Decode {"):]
	body = body[strings.Index(body, "enum _Loc {"):]
	body = body[:strings.Index(body, "}")]
	seen := map[string]bool{}
	for _, v := range regexp.MustCompile(`(?m)^\s+(\w+),$`).FindAllStringSubmatch(body, -1) {
		if seen[v[1]] {
			t.Errorf("_Loc variant %s is defined twice", v[1])
		}
		seen[v[1]] = true
	}
	for _, want := range []string{"Root_inner_inner2", "Root_inner__inner2"} {
		if !seen[want] {
			t.Errorf("no _Loc variant %s in:\n%s", want, body)
		}
	}
}
