// Package typescript is the TypeScript throughput backend (PLAN §6.4): it emits
// one class per object with marshal(OStream) and a visitor-based decode against
// corelib-ts (@sofa-buffers/corelib). 64-bit fields use bigint.
package typescript

import (
	"fmt"
	"strings"

	"github.com/sofa-buffers/generator/internal/generator"
	"github.com/sofa-buffers/generator/internal/ir"
)

func init() { generator.Register(&Backend{}) }

// Backend implements generator.Backend for TypeScript.
type Backend struct{}

func (*Backend) Lang() string { return "typescript" }

const corelibPkg = "@sofa-buffers/corelib"

// Generate emits a single messages.ts module; project mode adds a harness +
// package.json + tsconfig.
func (*Backend) Generate(s *ir.Schema, cfg map[string]any) ([]generator.File, error) {
	g := &gen{schema: s, banner: cfgString(cfg, "tool_banner", "sofabgen"), license: generator.LicenseID(cfg), omit: cfgBool(cfg, "omit_defaults")}
	files := []generator.File{{Path: "messages.ts", Content: g.module(s)}}
	if cfgString(cfg, "emit", "sources") == "project" {
		files = append(files, g.projectFiles(s, cfg)...)
	}
	return files, nil
}

type gen struct {
	schema  *ir.Schema
	banner  string
	license string // SPDX id, "" to omit the header line
	omit    bool
}

type tsfile struct{ b strings.Builder }

func (f *tsfile) line(format string, args ...any) {
	fmt.Fprintf(&f.b, format, args...)
	f.b.WriteByte('\n')
}
func (f *tsfile) blank()        { f.b.WriteByte('\n') }
func (f *tsfile) bytes() []byte { return []byte(f.b.String()) }

func (g *gen) module(s *ir.Schema) []byte {
	f := &tsfile{}
	f.line("// Code generated by %s; DO NOT EDIT.", g.banner)
	if g.license != "" {
		f.line("// SPDX-License-Identifier: %s", g.license)
	}
	f.line("import { OStream, decode, type Visitor } from %q;", corelibPkg)
	f.blank()
	f.line("%s", tsPrelude)
	f.blank()

	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		switch nt.Category {
		case ir.CatEnum:
			g.emitEnum(f, nt)
		case ir.CatBitfield:
			g.emitBitfield(f, nt)
		}
	}
	for _, key := range s.NamedOrder {
		nt := s.Named[key]
		if nt.Category == ir.CatStruct || nt.Category == ir.CatUnion {
			g.emitClass(f, g.typeName(key), nt.Summary, nt.Fields)
		}
	}
	for _, m := range s.Messages {
		g.emitClass(f, exported(m.Name), m.Summary, m.Fields)
	}
	return f.bytes()
}

func (g *gen) emitEnum(f *tsfile, nt *ir.NamedType) {
	f.line("export enum %s {", g.typeName(nt.Key))
	for _, c := range nt.Consts {
		f.line("  %s = %d,", exported(c.Name), c.Value)
	}
	f.line("}")
	f.blank()
}

func (g *gen) emitBitfield(f *tsfile, nt *ir.NamedType) {
	f.line("export enum %s {", g.typeName(nt.Key))
	for _, fl := range nt.Flags {
		f.line("  %s = %d,", exported(fl.Name), uint64(1)<<uint(fl.Pos))
	}
	f.line("}")
	f.blank()
}

func (g *gen) emitClass(f *tsfile, name, summary string, fields []*ir.Field) {
	f.emitDoc("", summary)
	f.line("export class %s {", name)
	for _, fld := range fields {
		f.emitDoc("  ", fieldDoc(fld))
		f.line("  %s: %s = %s;", fld.Name, g.tsType(fld), g.tsDefault(fld))
	}
	f.blank()

	// marshal
	f.line("  marshal(os: OStream): void {")
	for _, fld := range fields {
		g.emitMarshal(f, fld)
	}
	f.line("  }")
	f.blank()

	// JSON
	g.emitJSON(f, name, fields)

	// visitor + decode
	g.emitVisitor(f, name, fields)
	f.line("}")
	f.blank()
}

func (g *gen) emitMarshal(f *tsfile, fld *ir.Field) {
	acc := "this." + fld.Name
	var write string
	switch fld.Kind {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64, ir.KindBitfield:
		write = fmt.Sprintf("os.writeUnsigned(%d, %s);", fld.ID, acc)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64, ir.KindEnum:
		write = fmt.Sprintf("os.writeSigned(%d, %s);", fld.ID, acc)
	case ir.KindBool:
		write = fmt.Sprintf("os.writeBoolean(%d, %s);", fld.ID, acc)
	case ir.KindFP32:
		write = fmt.Sprintf("os.writeFp32(%d, %s);", fld.ID, acc)
	case ir.KindFP64:
		write = fmt.Sprintf("os.writeFp64(%d, %s);", fld.ID, acc)
	case ir.KindString:
		write = fmt.Sprintf("os.writeString(%d, %s);", fld.ID, acc)
	case ir.KindBlob:
		f.line("    os.writeBlob(%d, %s);", fld.ID, acc)
		return
	case ir.KindStruct, ir.KindUnion:
		f.line("    os.writeSequenceBegin(%d);", fld.ID)
		f.line("    %s.marshal(os);", acc)
		f.line("    os.writeSequenceEnd();")
		return
	case ir.KindArray:
		g.emitMarshalArray(f, fld, acc)
		return
	}
	if g.omit {
		f.line("    if (%s !== %s) {", acc, g.tsDefault(fld))
		f.line("      %s", write)
		f.line("    }")
	} else {
		f.line("    %s", write)
	}
}

func (g *gen) emitMarshalArray(f *tsfile, fld *ir.Field, acc string) {
	g.marshalArray(f, "    ", fmt.Sprintf("%d", fld.ID), acc, fld.Elem, fld.ElemRef, fld.ElemItems, 0)
}

// marshalArray writes the array `val` as field `idExpr`. Numeric/enum/boolean/
// bitfield elements use the native array wire type (enum->signed, bool/bitfield->
// unsigned); string/blob/struct/union/array elements lower to a wrapper sequence
// whose child ids are the 0-based index (per MESSAGE_SPEC). Recurses for nested
// arrays.
func (g *gen) marshalArray(f *tsfile, ind, idExpr, val string, elem ir.Kind, ref *ir.TypeRef, items *ir.ArrayElem, depth int) {
	ev := fmt.Sprintf("_e%d", depth)
	iv := fmt.Sprintf("_i%d", depth)
	switch elem {
	case ir.KindU8, ir.KindU16, ir.KindU32, ir.KindU64:
		f.line("%sos.writeUnsignedArray(%s, %s);", ind, idExpr, val)
	case ir.KindI8, ir.KindI16, ir.KindI32, ir.KindI64:
		f.line("%sos.writeSignedArray(%s, %s);", ind, idExpr, val)
	case ir.KindEnum:
		f.line("%sos.writeSignedArray(%s, %s);", ind, idExpr, val)
	case ir.KindBool:
		f.line("%sos.writeUnsignedArray(%s, %s.map((%s) => (%s ? 1 : 0)));", ind, idExpr, val, ev, ev)
	case ir.KindBitfield:
		f.line("%sos.writeUnsignedArray(%s, %s);", ind, idExpr, val)
	case ir.KindFP32:
		f.line("%sos.writeFp32Array(%s, %s);", ind, idExpr, val)
	case ir.KindFP64:
		f.line("%sos.writeFp64Array(%s, %s);", ind, idExpr, val)
	case ir.KindString:
		f.line("%sos.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%s%s.forEach((%s, %s) => os.writeString(%s, %s));", ind, val, ev, iv, iv, ev)
		f.line("%sos.writeSequenceEnd();", ind)
	case ir.KindBlob:
		f.line("%sos.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%s%s.forEach((%s, %s) => os.writeBlob(%s, %s));", ind, val, ev, iv, iv, ev)
		f.line("%sos.writeSequenceEnd();", ind)
	case ir.KindStruct, ir.KindUnion:
		f.line("%sos.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%s%s.forEach((%s, %s) => {", ind, val, ev, iv)
		f.line("%s  os.writeSequenceBegin(%s);", ind, iv)
		f.line("%s  %s.marshal(os);", ind, ev)
		f.line("%s  os.writeSequenceEnd();", ind)
		f.line("%s});", ind)
		f.line("%sos.writeSequenceEnd();", ind)
	case ir.KindArray:
		f.line("%sos.writeSequenceBegin(%s);", ind, idExpr)
		f.line("%s%s.forEach((%s, %s) => {", ind, val, ev, iv)
		g.marshalArray(f, ind+"  ", iv, ev, items.Elem, items.ElemRef, items.ElemItems, depth+1)
		f.line("%s});", ind)
		f.line("%sos.writeSequenceEnd();", ind)
	}
}
