package typescript

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite tests/conformance/typescript/reserved{.yaml,.json,_absent.json} from the reserved-name list")

// reservedNames is every name on the list, sorted.
func reservedNames() []string {
	var names []string
	for _, set := range []map[string]bool{tsClassBody, tsMembers, tsObjectMembers, unionReserved} {
		for n := range set {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	return names
}

// reservedTypeNames is every name on the type-level list a TypeIdent can spell
// (it starts upper-case), sorted: the corelib imports and the globals. The fixed
// module constants take a path of their own (reservedYAML).
func reservedTypeNames() []string {
	var names []string
	for _, n := range corelibNames {
		if n[0] >= 'A' && n[0] <= 'Z' {
			names = append(names, n)
		}
	}
	for n := range tsGlobals {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// reservedYAML is a schema that uses every reserved name as a field of a message,
// of a nested struct, and as an option of a union. An fp32 field gives the
// message a raw-bytes companion too, beside a field spelled like it, and the
// union has options its derived has<Opt>/raw-bytes members land on. Every
// type-level name is a message of its own, and the path MAX.DYN.* spells the
// module's receiver-limit constants, which the unbounded leaves below it make
// the module declare.
func reservedYAML(names []string) string {
	var b strings.Builder
	b.WriteString("# Generated by TestReservedSchemaFile from generators/typescript/reserved.go;\n")
	b.WriteString("# do not edit. Regenerate: go test ./generators/typescript -run TestReservedSchemaFile -update\n")
	b.WriteString("# The collision test: every reserved name as a field must typecheck and round-trip.\n")
	var fields strings.Builder
	opts := make([]string, len(names))
	for i, n := range names {
		fmt.Fprintf(&fields, "      %s: { id: %d, type: u8 }\n", n, i)
		opts[i] = fmt.Sprintf("%s: { id: %d, type: u8 }", n, i)
	}
	k := len(names)
	// Options with a derived member's shape beside the options whose members
	// they would spell (TestTSUnionMembersAreShapeBased), and a string option, so
	// the union declares its private release method beside an option `leave`.
	for i, o := range []string{
		"x: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }",
		"hasX: { id: %d, type: u8 }", "mutableX: { id: %d, type: u8 }", "xFp32Raw: { id: %d, type: u8 }",
		"own_property: { id: %d, type: u8 }", "g: { id: %d, type: fp32 }", "gFp32Raw: { id: %d, type: u8 }",
		"has: { id: %d, type: fp32 }", "fp32_raw: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }",
		"leave: { id: %d, type: u8 }", "s: { id: %d, type: string, maxlen: 4 }",
	} {
		opts = append(opts, fmt.Sprintf(o, k+i))
	}
	fmt.Fprintf(&b, `version: 1
$defs:
  struct:
    Inner2:
      x: { id: 0, type: u8 }
    Inner:
%s      inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
messages:
  m:
    payload:
%s      f:            { id: %d, type: fp32 }
      inner:        { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner' } }
      u:            { id: %d, type: union, oneof: { %s } }
      inner_inner2: { id: %d, type: struct, fields: { $ref: '#/$defs/struct/Inner2' } }
      fFp32Raw:     { id: %d, type: u8 }
  MAX:
    payload:
      DYN:
        id: 0
        type: struct
        fields:
          ARRAY: { id: 0, type: struct, fields: { COUNT: { id: 0, type: struct, fields: { a: { id: 0, type: array, items: { type: u8 } } } } } }
          STRING: { id: 1, type: struct, fields: { LEN: { id: 0, type: struct, fields: { s: { id: 0, type: string } } } } }
          BLOB: { id: 2, type: struct, fields: { LEN: { id: 0, type: struct, fields: { b: { id: 0, type: blob } } } } }
`, fields.String(), k, fields.String(), k, k+1, k+2, strings.Join(opts, ", "), k+3, k+4)
	for _, n := range reservedTypeNames() {
		fmt.Fprintf(&b, "  %s: { payload: { x: { id: 0, type: u8 } } }\n", n)
	}
	return b.String()
}

// reservedJSON is the harness input for m: every reserved field, nested one and
// the last union option at a non-default value, each under its schema name.
func reservedJSON(names []string) string {
	top := map[string]any{"f": 1.5, "fFp32Raw": 3}
	inner := map[string]any{"inner2": map[string]any{"x": 5}}
	for i, n := range names {
		top[n] = i + 1
		inner[n] = i + 2
	}
	top["inner"] = inner
	top["inner_inner2"] = map[string]any{"x": 6}
	top["u"] = map[string]any{names[len(names)-1]: 9}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// reservedAbsentJSON is the harness input for m with every reserved key ABSENT:
// a key Object.prototype has (constructor, toString, ...) must not read as
// present. Only the union, at its first option, and a nested struct carry a
// value, so their fromJSON runs over an object without those keys too.
func reservedAbsentJSON(names []string) string {
	top := map[string]any{
		"u":     map[string]any{names[0]: 7},
		"inner": map[string]any{"inner2": map[string]any{"x": 1}},
	}
	b, _ := json.MarshalIndent(top, "", "  ")
	return string(b) + "\n"
}

// TestReservedSchemaFile keeps the checked-in collision schema and its input in
// step with the list: the conformance suite typechecks and round-trips that file
// (tests/conformance/typescript/run.sh), so a name added to reserved.go is
// covered the moment the file is regenerated -- and this test fails until it is.
func TestReservedSchemaFile(t *testing.T) {
	names := reservedNames()
	for path, want := range map[string]string{
		"../../tests/conformance/typescript/reserved.yaml":        reservedYAML(names),
		"../../tests/conformance/typescript/reserved.json":        reservedJSON(names),
		"../../tests/conformance/typescript/reserved_absent.json": reservedAbsentJSON(names),
	} {
		if *update {
			if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
				t.Fatal(err)
			}
			continue
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != want {
			t.Errorf("%s is out of step with the reserved-name list; regenerate with -update", path)
		}
	}
}

// TestReservedNamesAreMangled: every name on the list comes out with a trailing
// underscore as a class member -- except the members only a union has, which a
// struct member keeps -- and the JSON key keeps the schema name.
func TestReservedNamesAreMangled(t *testing.T) {
	names := reservedNames()
	out := genTSWith(t, reservedYAML(names), map[string]any{})
	for _, n := range names {
		want := n + "_"
		if unionReserved[n] {
			want = n
		}
		if !regexp.MustCompile(`(?m)^  ` + regexp.QuoteMeta(want) + `: number = 0;$`).MatchString(out) {
			t.Errorf("field %q is not the member %s", n, want)
		}
		if !strings.Contains(out, fmt.Sprintf("%q: ", n)) {
			t.Errorf("JSON key %q is gone", n)
		}
	}
}

// TestScopeConstantsAreDistinct: the decoder's scope constants spell the schema
// path joined with `_` below a per-type root, so the path a.b and a field a_b
// must not declare one constant twice ("Cannot redeclare block-scoped
// variable").
func TestScopeConstantsAreDistinct(t *testing.T) {
	src := "version: 1\n$defs:\n  struct:\n    B: { x: { id: 0, type: u8 } }\n    A: { b: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/B' } } }\n" +
		"messages:\n  m:\n    payload:\n      a: { id: 0, type: struct, fields: { $ref: '#/$defs/struct/A' } }\n      a_b: { id: 1, type: struct, fields: { $ref: '#/$defs/struct/B' } }\n"
	out := genTSWith(t, src, map[string]any{})
	seen := map[string]bool{}
	for _, m := range regexp.MustCompile(`(?m)^const (_\w+__Loc\w*) = `).FindAllStringSubmatch(out, -1) {
		if seen[m[1]] {
			t.Errorf("scope constant %s is declared twice", m[1])
		}
		seen[m[1]] = true
	}
	if !seen["_M__Loc_a_b"] || !seen["_M__Loc_a__b"] {
		t.Errorf("want _M__Loc_a_b and _M__Loc_a__b, got %v", seen)
	}
}

// moduleDecl matches every module-level declaration of an emitted .ts file.
var moduleDecl = regexp.MustCompile(`(?m)^(?:export )?(?:class|enum|type|const|let|function|interface) ([A-Za-z_$][\w$]*)`)

// TestNamesSchemaDeclaresEachNameOnce generates the shared name-collision schema
// (tests/conformance/lib/names.yaml, ARCHITECTURE §8 "Naming") and requires every
// module-level declaration of message.ts and harness.ts to appear exactly once,
// in every int64 mode -- the guarantee the conformance suite checks with tsc,
// checked here without a toolchain. It also pins the spelling of each channel.
func TestNamesSchemaDeclaresEachNameOnce(t *testing.T) {
	s := schemaFile(t, "../../tests/conformance/lib/names.yaml")
	for _, mode := range []string{"bigint", "long", "number"} {
		files, err := (&Backend{}).Generate(s, map[string]any{"emit": "project", "int64": mode})
		if err != nil {
			t.Fatalf("%s: names.yaml must generate: %v", mode, err)
		}
		for _, f := range files {
			if !strings.HasSuffix(f.Path, ".ts") {
				continue
			}
			seen := map[string]int{}
			for _, m := range moduleDecl.FindAllStringSubmatch(string(f.Content), -1) {
				seen[m[1]]++
			}
			for n, c := range seen {
				if c > 1 {
					t.Errorf("%s %s: %s is declared %d times", mode, f.Path, n, c)
				}
			}
			if f.Path != "message.ts" {
				continue
			}
			for _, want := range []string{
				"Point", "M_A", "MA", "M_Decoder", "M__Decoder", "MDecoder", "M_Visitor", "M_Visitor__Array",
				"M_New", "NewM", "M_Arr", "M_ArrElem", "A_BC", "AB_C", "Point",
				"Shape__DefaultNum", "Shape__DefaultPt", "Shape_Pt", "ShapeDefault_Pt", "ShapeDefaultPt",
				"Color", "Color__Array", "ColorRed", "Flags", "FlagsOn",
				// escaped: a corelib import, a global, one of both
				"OStream_", "Visitor_", "Long_", "Uint8Array_", "Record_", "Number_", "Object_", "String",
				// not escaped: nothing in the module reaches these unqualified
				"Math", "Seq", "Decoder",
				// privates
				"_M__Visitor", "_M__Loc", "_M__Loc_a", "_M_Arr__Make",
			} {
				if seen[want] != 1 {
					t.Errorf("%s: want exactly one declaration of %s, got %d", mode, want, seen[want])
				}
			}
		}
	}
}

// TestTSGlobalsListed is the drift test for tsGlobals: over the corpus, the
// realworld set, the example and the names schema, in every int64 mode, every
// upper-case identifier the emitted module reaches unqualified must be one it
// declares itself, a corelib import, or on tsGlobals -- otherwise a message of
// that name would shadow it. The reverse holds too: a listed global the module
// never uses would only escape a type for nothing.
func TestTSGlobalsListed(t *testing.T) {
	defs, _ := filepath.Glob("../../tests/matrix/corpus/defs/*.yaml")
	rw, _ := filepath.Glob("../../examples/messages/realworld/*.yaml")
	defs = append(append(defs, rw...), "../../examples/messages/example.yaml", "../../tests/conformance/lib/names.yaml")
	strLit := regexp.MustCompile(`"(?:[^"\\]|\\.)*"|` + "`(?:[^`\\\\]|\\\\.)*`")
	ident := regexp.MustCompile(`[A-Za-z_$][\w$]*`)
	// A member declaration inside a class, enum or `as const` object: the name is
	// the class's own, not a reference.
	member := regexp.MustCompile(`(?m)^\s+(?:static |readonly |private |get |set )*([A-Za-z_$][\w$]*)\s*(?:[:=(?]|$)`)
	corelib := map[string]bool{}
	for _, n := range corelibNames {
		corelib[n] = true
	}
	used := map[string]bool{}
	for _, def := range defs {
		s := schemaFile(t, def)
		for _, mode := range []string{"bigint", "long", "number"} {
			files, err := (&Backend{}).Generate(s, map[string]any{"int64": mode})
			if err != nil {
				t.Fatalf("%s %s: %v", def, mode, err)
			}
			src := codeOnly(string(files[0].Content))
			own := map[string]bool{}
			for _, m := range moduleDecl.FindAllStringSubmatch(src, -1) {
				own[m[1]] = true
			}
			for _, m := range member.FindAllStringSubmatch(src, -1) {
				own[m[1]] = true
			}
			code := strLit.ReplaceAllString(src, `""`)
			for _, loc := range ident.FindAllStringIndex(code, -1) {
				n := code[loc[0]:loc[1]]
				if n[0] < 'A' || n[0] > 'Z' || own[n] || corelib[n] {
					continue
				}
				if loc[0] > 0 && code[loc[0]-1] == '.' {
					continue // a property, not a reference
				}
				used[n] = true
				if !tsGlobals[n] {
					t.Errorf("%s (%s): message.ts reaches %s unqualified, which is not on tsGlobals", def, mode, n)
				}
			}
		}
	}
	for n := range tsGlobals {
		if !used[n] {
			t.Errorf("tsGlobals lists %s, which no generated module uses", n)
		}
	}
}
