// Code generated by sofabgen; DO NOT EDIT.
//! SofaBuffers message types over the `sofab` Zig corelib (max-speed build).
//! decode() borrows string/blob bytes from the input buffer (zero-copy) and
//! allocates array storage from the caller's allocator; pass an arena and
//! free the whole message at once.

const std = @import("std");
const sofab = @import("sofab");

/// Error set of the one-shot decode() wrappers: the corelib baseline plus
/// IncompleteMessage. The corelib reports INCOMPLETE as a
/// non-error decode Status -- the caller owns end-of-input -- and for a
/// one-shot decode over a whole buffer, end-of-input is here: a trailing
/// .incomplete means the message was truncated. Kept distinct from
/// error.InvalidMessage so INCOMPLETE and INVALID never collapse.
pub const DecodeError = sofab.Error || error{IncompleteMessage};

pub const Scalars = struct {
    u8min: u8 = 0,
    u8max: u8 = 255,
    u64max: u64 = 18446744073709551615,
    i8min: i8 = -128,
    i64min: i64 = -9223372036854775808,
    f32: f32 = 3.14,
    f64: f64 = -2.5,
    flag: bool = true,

    /// Worst-case encoded size of this message, derived from the schema.
    pub const MAX_SIZE: usize = 49;

    /// Write this value's fields to `os` (sparse-canonical encoding).
    pub fn marshal(self: *const Scalars, os: *sofab.OStream) sofab.Error!void {
        if (self.u8min != 0) try os.writeUnsigned(0, self.u8min);
        if (self.u8max != 255) try os.writeUnsigned(1, self.u8max);
        if (self.u64max != 18446744073709551615) try os.writeUnsigned(2, self.u64max);
        if (self.i8min != -128) try os.writeSigned(3, self.i8min);
        if (self.i64min != -9223372036854775808) try os.writeSigned(4, self.i64min);
        if (self.f32 != 3.14) try os.writeFp32(5, self.f32);
        if (self.f64 != -2.5) try os.writeFp64(6, self.f64);
        if (self.flag != true) try os.writeBoolean(7, self.flag);
    }

    /// True when every field equals its declared default, compared per field
    /// and recursively -- i.e. when marshal would write no child at all (S2).
    pub fn isDefault(self: *const Scalars) bool {
        if (self.u8min != 0) return false;
        if (self.u8max != 255) return false;
        if (self.u64max != 18446744073709551615) return false;
        if (self.i8min != -128) return false;
        if (self.i64min != -9223372036854775808) return false;
        if (self.f32 != 3.14) return false;
        if (self.f64 != -2.5) return false;
        if (self.flag != true) return false;
        return true;
    }

    /// Encode into a fresh buffer allocated from `alloc`.
    pub fn encode(self: *const Scalars, alloc: std.mem.Allocator) (sofab.Error || std.mem.Allocator.Error)![]u8 {
        var sink: _EncodeSink = .{ .alloc = alloc };
        var scratch: [512]u8 = undefined;
        var os = sofab.OStream.initFlush(&scratch, 0, &sink, _EncodeSink.push);
        try self.marshal(&os);
        _ = os.flush();
        if (sink.failed) return error.OutOfMemory;
        return sink.list.toOwnedSlice(alloc);
    }

    /// Decode a complete message. Zero-copy: the result borrows string and
    /// blob bytes from `data` (keep it alive as long as the message); array
    /// storage comes from `alloc` (an arena frees everything at once).
    /// Truncated input (the corelib's .incomplete decode Status) fails with
    /// error.IncompleteMessage; malformed input with error.InvalidMessage.
    pub fn decode(alloc: std.mem.Allocator, data: []const u8) DecodeError!Scalars {
        var m: Scalars = .{};
        var v: _dec_Scalars = .{ .m = &m, .alloc = alloc };
        const st = try sofab.decode(data, &v);
        // A scalar array over its schema count, or a wrapper-array element
        // id at/beyond the schema count: an index above the schema capacity
        // is invalid and is rejected, never clamped.
        if (v.inv) return error.InvalidMessage;
        // The bytes end inside a field or an open sequence: INCOMPLETE.
        // This wrapper decodes a whole buffer, so a trailing .incomplete
        // is a truncated message.
        if (st == .incomplete) return error.IncompleteMessage;
        return m;
    }
};

/// Flat-visitor decoder for Scalars: a (location, id) state machine over the
/// corelib's streaming callbacks, with a bounded location stack.
const _dec_Scalars = struct {
    m: *Scalars,
    alloc: std.mem.Allocator,
    cur: _Loc = .root,
    inv: bool = false, // a scalar array over its schema count, or a wrapper element id >= count -> INVALID
    askip: usize = 0, // elements left to discard from a wire-type-contradictory array

    const _Loc = enum {
        root,
        dead, // a per-element allocation failed; ignore the subtree
    };

    pub fn unsigned(self: *_dec_Scalars, id: sofab.Id, value: sofab.Unsigned) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                0 => self.m.u8min = @truncate(value),
                1 => self.m.u8max = @truncate(value),
                2 => self.m.u64max = value,
                7 => self.m.flag = value != 0,
                else => {},
            },
            else => {},
        }
    }

    pub fn signed(self: *_dec_Scalars, id: sofab.Id, value: sofab.Signed) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                3 => self.m.i8min = @truncate(value),
                4 => self.m.i64min = value,
                else => {},
            },
            else => {},
        }
    }

    pub fn fp32(self: *_dec_Scalars, id: sofab.Id, value: f32) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                5 => self.m.f32 = value,
                else => {},
            },
            else => {},
        }
    }

    pub fn fp64(self: *_dec_Scalars, id: sofab.Id, value: f64) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                6 => self.m.f64 = value,
                else => {},
            },
            else => {},
        }
    }

    pub fn arrayBegin(self: *_dec_Scalars, _: sofab.Id, kind: sofab.ArrayKind, count: usize) void {
        self.askip = switch (kind) {
            .unsigned, .signed => switch (self.cur) {
                else => count,
            },
            .fixlen => switch (self.cur) {
                else => count,
            },
        };
    }
};

// --- shared encode/decode support -------------------------------------------

/// Flush sink behind encode(): drains the OStream scratch buffer into a
/// growable byte list.
const _EncodeSink = struct {
    alloc: std.mem.Allocator,
    list: std.ArrayList(u8) = .empty,
    failed: bool = false,
    fn push(ctx: ?*anyopaque, data: []const u8) void {
        const self: *_EncodeSink = @ptrCast(@alignCast(ctx.?));
        self.list.appendSlice(self.alloc, data) catch {
            self.failed = true;
        };
    }
};

/// Mutable pointer to element `i` of a decode-allocated wrapper array.
///
/// The element id IS the array index (S5.1), so sequenceBegin
/// grows the destination to id + 1 -- default-filling the gaps left by omitted
/// elements -- records the id, and every child store then lands HERE, at that
/// index. Appending instead would shorten the array by the size of any interior
/// id gap, and would decode a REOPENED element id as a second element instead of
/// merging into the first (S7.4). It is the object-element twin of what
/// sofab.arrays.setElem does for a string/blob element.
///
/// Gaps are ordinary here: an interior element equal to the element default is
/// omitted by a conformant encoder (S2), and only the LAST element is guaranteed
/// present -- which is what makes the decoded length, highest present id + 1,
/// exact.
fn _at(s: anytype, i: usize) *std.meta.Elem(@TypeOf(s)) {
    return @constCast(&s[i]);
}

/// Storage for a `count: N` native array: N elements of inline capacity plus
/// the length.
///
/// `count` is a CAPACITY, never a length (S3): the field carries
/// 0..N elements and the wire count M IS the length, so a bare `[N]T` -- which
/// can only ever BE N long -- cannot represent the value. This can, without
/// giving up the inline storage that keeps a bounded array allocation-free on
/// both encode and decode.
///
/// The value is `items[0..len]`; `items[len..]` is spare capacity and never
/// reaches the wire. `.{}` is the EMPTY array -- which is what a fresh count:N
/// array is: N is a bound, not a content.
pub fn FixedArray(comptime T: type, comptime N: usize) type {
    return struct {
        const Self = @This();

        /// The schema `count`: the most elements this field may carry.
        pub const capacity: usize = N;

        items: [N]T = std.mem.zeroes([N]T),
        len: usize = 0,

        /// The array's value: exactly the elements the wire carries.
        pub fn slice(self: *const Self) []const T {
            return self.items[0..self.len];
        }

        /// Replace the value with `vals`, truncated to the capacity N.
        pub fn set(self: *Self, vals: []const T) void {
            const n = @min(vals.len, N);
            @memcpy(self.items[0..n], vals[0..n]);
            self.len = n;
        }

        /// A value holding `vals` (truncated to N) -- the literal form.
        pub fn init(vals: []const T) Self {
            var s: Self = .{};
            s.set(vals);
            return s;
        }
    };
}

/// Native-array destination of exactly the announced wire count.
fn _allocN(comptime T: type, a: std.mem.Allocator, n: usize) []const T {
    return sofab.arrays.allocN(T, a, n);
}
