// Code generated by sofabgen; DO NOT EDIT.
//! SofaBuffers message types over the `sofab` Zig corelib (max-speed build).
//! decode() borrows string/blob bytes from the input buffer (zero-copy) and
//! allocates array storage from the caller's allocator; pass an arena and
//! free the whole message at once.

const std = @import("std");
const sofab = @import("sofab");

/// Error set of the one-shot decode() wrappers: the corelib baseline plus
/// IncompleteMessage. The corelib reports INCOMPLETE as a
/// non-error decode Status -- the caller owns end-of-input -- and for a
/// one-shot decode over a whole buffer, end-of-input is here: a trailing
/// .incomplete means the message was truncated. Kept distinct from
/// error.InvalidMessage so INCOMPLETE and INVALID never collapse.
pub const DecodeError = sofab.Error || error{IncompleteMessage};

pub const Scalars = struct {
    u8min: u8 = 0,
    u8max: u8 = 255,
    u64max: u64 = 18446744073709551615,
    i8min: i8 = -128,
    i64min: i64 = -9223372036854775808,
    f32: f32 = 3.14,
    f64: f64 = -2.5,
    flag: bool = true,

    /// Worst-case encoded size of this message, derived from the schema.
    pub const MAX_SIZE: usize = 49;

    /// Write this value's fields to `os` (sparse-canonical encoding).
    pub fn marshal(self: *const Scalars, os: *sofab.OStream) sofab.Error!void {
        if (self.u8min != 0) try os.writeUnsigned(0, self.u8min);
        if (self.u8max != 255) try os.writeUnsigned(1, self.u8max);
        if (self.u64max != 18446744073709551615) try os.writeUnsigned(2, self.u64max);
        if (self.i8min != -128) try os.writeSigned(3, self.i8min);
        if (self.i64min != -9223372036854775808) try os.writeSigned(4, self.i64min);
        if (self.f32 != 3.14) try os.writeFp32(5, self.f32);
        if (self.f64 != -2.5) try os.writeFp64(6, self.f64);
        if (self.flag != true) try os.writeBoolean(7, self.flag);
    }

    /// Encode into a fresh buffer allocated from `alloc`.
    pub fn encode(self: *const Scalars, alloc: std.mem.Allocator) (sofab.Error || std.mem.Allocator.Error)![]u8 {
        var sink: _EncodeSink = .{ .alloc = alloc };
        var scratch: [512]u8 = undefined;
        var os = sofab.OStream.initFlush(&scratch, 0, &sink, _EncodeSink.push);
        try self.marshal(&os);
        _ = os.flush();
        if (sink.failed) return error.OutOfMemory;
        return sink.list.toOwnedSlice(alloc);
    }

    /// Decode a complete message. Zero-copy: the result borrows string and
    /// blob bytes from `data` (keep it alive as long as the message); array
    /// storage comes from `alloc` (an arena frees everything at once).
    /// Truncated input (the corelib's .incomplete decode Status) fails with
    /// error.IncompleteMessage; malformed input with error.InvalidMessage.
    pub fn decode(alloc: std.mem.Allocator, data: []const u8) DecodeError!Scalars {
        var m: Scalars = .{};
        var v: _dec_Scalars = .{ .m = &m, .alloc = alloc };
        const st = try sofab.decode(data, &v);
        // A scalar array over its schema count, or a wrapper-array element
        // id at/beyond the schema count: an index above the schema capacity
        // is invalid and is rejected, never clamped.
        if (v.inv) return error.InvalidMessage;
        // The bytes end inside a field or an open sequence: INCOMPLETE.
        // This wrapper decodes a whole buffer, so a trailing .incomplete
        // is a truncated message.
        if (st == .incomplete) return error.IncompleteMessage;
        return m;
    }
};

/// Flat-visitor decoder for Scalars: a (location, id) state machine over the
/// corelib's streaming callbacks, with a bounded location stack.
const _dec_Scalars = struct {
    m: *Scalars,
    alloc: std.mem.Allocator,
    cur: _Loc = .root,
    inv: bool = false, // a scalar array over its schema count, or a wrapper element id >= count -> INVALID
    askip: usize = 0, // elements left to discard from a wire-type-contradictory array

    const _Loc = enum {
        root,
        dead, // a per-element allocation failed; ignore the subtree
    };

    pub fn unsigned(self: *_dec_Scalars, id: sofab.Id, value: sofab.Unsigned) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                0 => self.m.u8min = @truncate(value),
                1 => self.m.u8max = @truncate(value),
                2 => self.m.u64max = value,
                7 => self.m.flag = value != 0,
                else => {},
            },
            else => {},
        }
    }

    pub fn signed(self: *_dec_Scalars, id: sofab.Id, value: sofab.Signed) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                3 => self.m.i8min = @truncate(value),
                4 => self.m.i64min = value,
                else => {},
            },
            else => {},
        }
    }

    pub fn fp32(self: *_dec_Scalars, id: sofab.Id, value: f32) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                5 => self.m.f32 = value,
                else => {},
            },
            else => {},
        }
    }

    pub fn fp64(self: *_dec_Scalars, id: sofab.Id, value: f64) void {
        if (self.askip > 0) { self.askip -= 1; return; }
        switch (self.cur) {
            .root => switch (id) {
                6 => self.m.f64 = value,
                else => {},
            },
            else => {},
        }
    }

    pub fn arrayBegin(self: *_dec_Scalars, _: sofab.Id, kind: sofab.ArrayKind, count: usize) void {
        self.askip = switch (kind) {
            .unsigned, .signed => switch (self.cur) {
                else => count,
            },
            .fixlen => switch (self.cur) {
                else => count,
            },
        };
    }
};

// --- shared encode/decode support -------------------------------------------

/// Flush sink behind encode(): drains the OStream scratch buffer into a
/// growable byte list.
const _EncodeSink = struct {
    alloc: std.mem.Allocator,
    list: std.ArrayList(u8) = .empty,
    failed: bool = false,
    fn push(ctx: ?*anyopaque, data: []const u8) void {
        const self: *_EncodeSink = @ptrCast(@alignCast(ctx.?));
        self.list.appendSlice(self.alloc, data) catch {
            self.failed = true;
        };
    }
};

/// Native-array destination of exactly the announced wire count.
fn _allocN(comptime T: type, a: std.mem.Allocator, n: usize) []const T {
    return sofab.arrays.allocN(T, a, n);
}
