// Code generated by sofabgen; DO NOT EDIT.
package message;
import org.sofabuffers.sofab.*;
import java.io.IOException;
import java.util.*;

public class Scalars {
    public long u8min = 0L;
    public long u8max = 255L;
    public long u64max = Long.parseUnsignedLong("18446744073709551615");
    public long i8min = -128L;
    public long i64min = -9223372036854775808L;
    public float f32 = 3.14f;
    public double f64 = -2.5;
    public boolean flag = true;

    public void marshal(OStream os) throws IOException {
        if (this.u8min != 0L) { os.writeUnsigned(0, this.u8min); }
        if (this.u8max != 255L) { os.writeUnsigned(1, this.u8max); }
        if (this.u64max != Long.parseUnsignedLong("18446744073709551615")) { os.writeUnsigned(2, this.u64max); }
        if (this.i8min != -128L) { os.writeSigned(3, this.i8min); }
        if (this.i64min != -9223372036854775808L) { os.writeSigned(4, this.i64min); }
        if (this.f32 != 3.14f) { os.writeFp32(5, this.f32); }
        if (this.f64 != -2.5) { os.writeFp64(6, this.f64); }
        if (this.flag != true) { os.writeBoolean(7, this.flag); }
    }
    public static final int MAX_SIZE = 82;
    // Per-thread scratch buffer: encode() marshals into it and returns an
    // exact-size copy, so the worst-case buffer is not re-allocated (and
    // zeroed) on every call. Do not call encode() reentrantly from a
    // marshal() override on the same thread.
    private static final ThreadLocal<byte[]> ENC_BUF =
        ThreadLocal.withInitial(() -> new byte[MAX_SIZE]);
    public byte[] encode() {
        try {
            byte[] buf = ENC_BUF.get();
            OStream os = new OStream(buf);
            marshal(os);
            return Arrays.copyOf(buf, os.bytesUsed());
        } catch (IOException e) { throw new RuntimeException(e); }
    }
    public static Scalars decode(byte[] data) {
        Scalars m = new Scalars();
        try { new IStream().feed(data, new ScalarsVisitor(m)); }
        catch (Exception e) { throw new RuntimeException(e); }
        return m;
    }
    public static DecodeStatus tryDecode(byte[] data, Scalars out) throws SofabException {
        IStream is = new IStream();
        is.feed(data, new ScalarsVisitor(out));
        return is.status();
    }
}

class ScalarsVisitor implements Visitor {
    private final Scalars m;
    private int cur = 0;
    private int ai = 0;                 // index into the primitive array currently being filled
    private int[] stk = new int[16];    // sequence scope stack (unboxed, was ArrayDeque<Integer>)
    private int sp = 0;
    private java.io.ByteArrayOutputStream acc; // lazy: only split string/blob payloads need it
    ScalarsVisitor(Scalars msg) { m = msg; }

    public void unsigned(int id, long value) {
        switch (cur) {
        case 0: switch (id) {
            case 0: m.u8min = value; break;
            case 1: m.u8max = value; break;
            case 2: m.u64max = value; break;
            case 7: m.flag = value != 0; break;
        } break;
        }
    }
    public void signed(int id, long value) {
        switch (cur) {
        case 0: switch (id) {
            case 3: m.i8min = value; break;
            case 4: m.i64min = value; break;
        } break;
        }
    }
    public void fp32(int id, float value) {
        switch (cur) {
        case 0: switch (id) {
            case 5: m.f32 = value; break;
        } break;
        }
    }
    public void fp64(int id, double value) {
        switch (cur) {
        case 0: switch (id) {
            case 6: m.f64 = value; break;
        } break;
        }
    }
    public void string(int id, int total, int offset, byte[] data, int chunkOffset, int chunkLength) {
        String _s;
        if (offset == 0 && chunkLength >= total) {
            _s = new String(data, chunkOffset, total, java.nio.charset.StandardCharsets.UTF_8);
        } else {
            if (acc == null) acc = new java.io.ByteArrayOutputStream();
            acc.write(data, chunkOffset, chunkLength);
            if (acc.size() < total) return;
            _s = new String(acc.toByteArray(), java.nio.charset.StandardCharsets.UTF_8);
            acc.reset();
        }
        switch (cur) {
        }
    }
    public void blob(int id, int total, int offset, byte[] data, int chunkOffset, int chunkLength) {
        byte[] _b;
        if (offset == 0 && chunkLength >= total) {
            _b = java.util.Arrays.copyOfRange(data, chunkOffset, chunkOffset + total);
        } else {
            if (acc == null) acc = new java.io.ByteArrayOutputStream();
            acc.write(data, chunkOffset, chunkLength);
            if (acc.size() < total) return;
            _b = acc.toByteArray();
            acc.reset();
        }
        switch (cur) {
        }
    }
    public void arrayBegin(int id, ArrayKind kind, int count) {
        ai = 0;
        switch (cur) {
        }
    }
    public void sequenceBegin(int id) {
        if (sp == stk.length) stk = java.util.Arrays.copyOf(stk, sp * 2);
        stk[sp++] = cur;
        switch (cur) {
        }
    }
    public void sequenceEnd() { cur = sp > 0 ? stk[--sp] : 0; }
}

